### ISSUE TITLE
Maximum limit auto save

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#10]
Could you make the max limit auto save differentiate by session (every time I close and open firefox again) or if that's not possible by day so for example if I set the max to 3 I can have 3 autosaves per session/day instead of all the autosaves being from x minutes ago?

**Comment by sienori** [comment]
I hope I can deal with it too. Please wait a while.

**Comment by rnc** [comment]
@sienori @rayman89 I see in the settings for 1.5.0 "Save session regularly" and "Save session when closed" so does this mean that a person can have a limit of autosaves and it will also have a separate limit for closing firefox? What happens for the latter preference if there are multiple windows  ?

**Comment by sienori** [comment]
@rnc 
It is saved every time the window is closed.
Limits are separate for save regulaly and save when closed.

rayman89's suggestion may not be necessary because save session when closed was added after this issue was build.

**Comment by rnc** [comment]
@sienori  Ok thanks!

**Comment by rayman89** [comment]
Yes this got outdated I'll close it if that's ok.
