### ISSUE TITLE
Saved Session hasn't drag-n-drop 😒

### ISSUE THREAD

**Issue by rediffusion** [sienori/Tab-Session-Manager#1000]
When I add a new window to the current Session it's always first. Session hasn't drag-n-drop for Windows and tabs.

---

![TSM_session](https://user-images.githubusercontent.com/30071027/169025828-b0fbbd9b-b944-48d3-a47c-90c1bbf6d720.png)

## Platform information
* Platform (OS): FireFox
* Version of browser: 100.0.2
* Version of Tab Session Manager: 6.12.0

With Sincere Appreciation ( ͡~ ͜ʖ ͡°)

**Comment by sienori** [comment]
There are no plans to support reordering of windows.
