### ISSUE TITLE
Uses large amounts of memory resulting in crash on in-built previous session restore

### ISSUE THREAD

**Issue by Adamfmc** [sienori/Tab-Session-Manager#101]
I run sessions with very large numbers of tabs open (500-600+).

I've identified that with this extension active, my Firefox crashes whenever I try to Restore Previous Session. It will open all the tabs, hang, and then I can watch in Task Manager as the amount of memory in use increases over the course of ten seconds to the maximum and the application crashes to desktop.

Since discovering that it is Tab Session Manager that is the problem, I'm now starting Firefox, disabling the add-on, Restore Previous Session (which then happens instantly), and then re-enabling the add-on. This is annoying and it would be good if there could be a fix for this huge memory usage.

**Comment by nevion** [comment]
adding me too, I usually run out of memory on my 32GiB of ram desktop - somewhere after 15GiB while furiously hitting the GC button in about:memory.

**Comment by sienori** [comment]
I fixed it.
It's included in the next version.
50ed045

**Comment by aaaxx** [comment]
I got here from [Firefox bug report 1422436](https://bugzilla.mozilla.org/show_bug.cgi?id=1422436). The same problem happens to me in version 4.1.0.

Could you check if the code has been broken by refactoring since v1.7.0? If not, something else must be causing it, and the issue should be reopened.

**Comment by sienori** [comment]
I fixed the problem that increased memory usage when restoring session or closing a large number of tabs. 90390af
