### ISSUE TITLE
Incorrect numbering of exported session❗

### ISSUE THREAD

**Issue by rediffusion** [sienori/Tab-Session-Manager#1010]
## Short description

 I go to options > Session > Session export
...and I see this "26 Сессии - 2022-05-21 22-38-32.json". Maybe it's because I have also `Tracking [4]` and it's cause some problems with saving❓

![tbs](https://user-images.githubusercontent.com/30071027/169666968-cdb2088d-50bd-4311-8edc-15ad2cd5e1fb.png)

## Platform information
* Platform (OS): FireFox
* Version of browser: 100.0.2
* Version of Tab Session Manager: 6.12.0

**Comment by sienori** [comment]
Exported sessions include internal temp sessions, so the number of sessions will be different.
