### ISSUE TITLE
"Add Tab"(s) functionality is missing in menu

### ISSUE THREAD

**Issue by quentintdv** [sienori/Tab-Session-Manager#1015]
It's not possible to add single tabs to any given session. There would be two traits to further improve this feature:

- add not only one, but all selected tabs
- add to a specific window in the session

**Comment by rediffusion** [comment]
@quentintdv 

`It's not possible to add single tabs to any given session.`
Move the cursor to the window then MouseRightClick the context menu will pop up.

`add to a specific window in the session`
Already has.

**Comment by rediffusion** [comment]
FYI:
A similar issue is [here](https://github.com/sienori/Tab-Session-Manager/issues/1007).

**Comment by sienori** [comment]
The ability to add the current tab to a window already exists.
![image](https://user-images.githubusercontent.com/29514424/189946528-ab9702ff-3f09-4ad9-b1a3-9d5beaa820cb.png)
