### ISSUE TITLE
TSM suspected of causing Firefox to stop working correctly

### ISSUE THREAD

**Issue by MrTheV** [sienori/Tab-Session-Manager#1019]
## Short description
FF 100.0-101.0 with TSM: 
The tabs are not able to contact any site after a random period of correct usage
Network is stalled, as well as any interaction in the pages
Changing tabs work (clicking on another tab)
FF CPU usage is higher that usual
Add-ons cannot be disabled but very rarely (after a lot of tries)

## Steps to reproduce

1. Start browser with clean profile (Refreshed Firefox)
2. Install Tab Session Manager (and some other extensions / add-ons, including privacy related extensions Ghostery, AdBlockPlus, µBlockOrigin, and Everhour time tricking extension)
3. Browse for some time
4. All tabs are stalled
5. 6. Disable TSM (you must try several times before it is actually disabled)
7. Tabs that were stalled are now working

I can't be 100% sure this is related to TSM, but I did not have the issue after I removed it
I tried to disable all my add-ons one after the other and when disabling TSM, everything went well

## Expected result
FF should be responsive and work

## Platform information
* Platform (OS): Windows 10 x64
* Version of browser: Firefox 100.0 - 101.0
* Version of Tab Session Manager: Latest

**Comment by sienori** [comment]
I cannot reproduce the problem.
