### ISSUE TITLE
Lost all my tabsession history, several times.

### ISSUE THREAD

**Issue by linuxguy123** [sienori/Tab-Session-Manager#1021]
## Short description

All the tab sessions I'd saved are gone.  This has happened a few times, recently.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Save tabSessions

## Expected result

Should see saved tab sessions in TabSession Manager.

## Actual result

All previous saved sessions are gone.

## Platform information
* Platform (OS):  Fedora 35 Workstation
* Version of browser: Firefox, various.  Latest is 100.0.2-1
* Version of Tab Session Manager: 6.12.0

## Additional context

I've been using Tab Session Manager for years.   This is the first major problem I've had with it.  It is a great "add-on".

**Comment by linuxguy123** [comment]
I've still got this problem.  Fortunately I saved my sessions by exporting them.  I tried importing my sessions but they don't display to be used.

**Comment by sienori** [comment]
Sorry for the inconvenience.
Follow the article below to reset IndexedDB and get it ready to save sessions.
After that, import the exported sessions.
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
