### ISSUE TITLE
Delete Sessions - In CLOUD

### ISSUE THREAD

**Issue by merlin555** [sienori/Tab-Session-Manager#1023]
Hi,

Does anyone know how I delete the "Session" in the cloud (Google Drive) in Tab Session Manager,
without having to open a new Google account?

I always have to manually delete all saved tabs and pages (in TSM)
and then at the end press the Sync button at Tab Session Manager.
This takes a lot of time if you want to delete up to 1000 entries.

Thanks !

Greetings..

 Merlin

**Comment by aviv926** [comment]
In Google Drive settings you can remove the saved sync data

**Log in to Google Drive and click on the gear**
![image](https://user-images.githubusercontent.com/51673860/175791158-5700814b-6c8c-4c40-90bc-42f84ff6dd3b.png)

**Then click Settings**
![image](https://user-images.githubusercontent.com/51673860/175791171-f4a4e012-0225-4f2c-a06e-9d110c74ca75.png)

**Then on Manage Apps**
![image](https://user-images.githubusercontent.com/51673860/175791177-1ade3b42-5a04-4a05-847c-e90f33d85e37.png)

**Then remove the saved data of the extension**
![image](https://user-images.githubusercontent.com/51673860/175791145-225fa1df-f160-465c-ace0-adbddde41e45.png)

**Comment by merlin555** [comment]
Hi aviv926,

Thank you thank you !
I somehow never came across it, even if it's easy.
I am happy.
Great.

Greetings..

 Merlin
