### ISSUE TITLE
Problem with Tracked sessions and the name/colors of Tab Groups

### ISSUE THREAD

**Issue by zaran64** [sienori/Tab-Session-Manager#1027]
## Short description
When a tracking session is established, tab group names and colors are not saved correctly.

## Steps to reproduce
1. Save a session with tab groups and activate the "Track window changes"
3. Close the session.
4. Open the session
5. The first time all is ok
6. Close the session
7. Open the session
8. The groups names and colors are lost (partially or totally).

## Expected result
![1](https://user-images.githubusercontent.com/83920577/174343886-0d273a87-6da1-4bfd-a037-329b97eba933.jpg)

## Actual result
![4](https://user-images.githubusercontent.com/83920577/174344150-cd67df5d-1907-4f0b-a030-0778b1287762.jpg)

## Platform information
* Platform (OS): Windows 10 version 21H1 (compilation 19043.1766)
* Version of browser: Microsoft Edge Versión 102.0.1245.39 (Compilación oficial) (64 bits)
* Version of Tab Session Manager: 6.12.0

## Additional context
I have installed the "Save Tab Groups for Tab Session Manager" (last version: 1.0.2).
Another screenshots:
-Create session with tracking:
![2](https://user-images.githubusercontent.com/83920577/174345009-b9016770-b509-4f80-8cef-8a19f83db706.jpg)
-The first time is ok:
![3](https://user-images.githubusercontent.com/83920577/174345271-8d7214ba-1100-42be-97ad-da563596664f.jpg)
Thank you!

**Comment by sienori** [comment]
Additional extension `Save Tab Groups for Tab Session Manager` are required to save tab group colors.
