### ISSUE TITLE
Unable to open some sessions.

### ISSUE THREAD

**Issue by wynxel** [sienori/Tab-Session-Manager#1028]
## Short description

Some sessions can not be opened (restored). Clicking either on open button in list of all sessions or on open button in detail view, or on window name in session detail view. Individual tabs can be opened (not much useful, just observed that). 

## Steps to reproduce

Random bug. Approximately half of my sessions are not restorable. 
I observed one thing:
I have google drive session backup enabled. When session is not restorable in chrome, I can restore it in firefox, then remove this session from manager (from firefox, chrome, then sync), save session again (still opened in firefox...), sync and then I can restore it  in chrome. The same tabs...

## Expected result

Click on open will restore session.

## Actual result

Nothing happens. 
Would add log, but could not find it's location. 

## Platform information
* Platform (OS): linux ubuntu LTS 22.04
* Version of browser: chrome
* Version of Tab Session Manager: 6.12.0

**Comment by jimmyjudas** [comment]
I have the same problem on Windows:
* Platform (OS): Windows 11 Home 21H2
* Version of browser: Chrome v104.0.5112.102 (Official Build) (64-bit)
* Version of Tab Session Manager: 6.12.0

From the console in the debugger:
`background.js:2 Uncaught (in promise) {message: 'Invalid value for bounds. Bounds must be at least 50% within visible screen space.'}`

If I then deselect the 'Restore windows position' option in settings, the session opens just fine.

**Comment by sienori** [comment]
This problem was fixed by @Drincann! https://github.com/sienori/Tab-Session-Manager/pull/1058
