### ISSUE TITLE
performance issues, half hour+ to restore sessions

### ISSUE THREAD

**Issue by nevion** [sienori/Tab-Session-Manager#103]
Similiar to #101, I use this plugin on firefox on 64-bit linux.  I've noticed that with several hundred tabs open, to restore a session is very slow, taking something like an 20-30 minutes to complete watching these tabs open one by one and take quite some time to load (even with lazy loading).

Firefox will have the cpu pegged at 100-140% (multicore, multithread)

Currently on 58b9

**Comment by lapineige** [comment]
I experience the same issue, ~1000 tabs took more than 30 min to load, with CPU usage at 100%, high memory usage (more than 10GB), and some bugs when I interacted with the tabs (if I click on one of them, most of the time the restoration is lost).

64 bit Linux too.

(btw thanks a lot for this addon)

**Comment by sienori** [comment]
Reduced the load in ver1.7.0.
Try it.

**Comment by lapineige** [comment]
It seems to be faster, indeed. I see tabs loaded every second.
But it's already taking more than 5 min to restore.

But even in offline mode (to reduce load) it takes way too much memory (not finished yet (~50%), I did a garbage collect, and it's 5GB of RAM, twice the memory usage I had before closing Firefox (with 1300 tabs loaded, and online mode - so way more content).

**Comment by acertain** [comment]
In the old session manager and when you use FF's built-in "restore previous session," the tabs are all created with their titles and icons, but the pages aren't actually loaded until you visit them. This means that as soon as the foreground page loads, there was no more activity until you actually switch to a different tab. And then just that tab loads. Makes start-up much quicker and doesn't chew up all those resources. Given current behavior I'll stick with the built-in restore, even though it doesn't restore my tree-tab structure.

**Comment by lapineige** [comment]
But session manager implements lazy loading, isn't it ?

**Comment by acertain** [comment]
Good point. I guess this is simply a bug in Tab Session Manager. I have "Lazy Loading" selected, but it still greedily loads every tab on restore.

**Comment by acertain** [comment]
I take everything back. It looks like it's restoring the tabs because they go through the FF "loading" icon, but I guess it's just converting the bookmark to a non-loaded page. Sorry for my confusion.

**Comment by sienori** [comment]
Lazy loading option loads the favicon of the page.
I might add a setting that does not load favicon (but it will be hard to use).

It takes time to restore the session because it opens the tab one by one.
it is a specification to correspond to Tree Style Tab.
I plan to fix it in the future. #52 
Also, currently it turns a little faster when the TST option is off. (tab open interval: 150ms- > 0ms)

**Comment by lapineige** [comment]
> It takes time to restore the session because it opens the tab one by one.
it is a specification to correspond to Tree Style Tab.

Ok, thanks for the information :)

> Also, currently it turns a little faster when the TST option is off. (tab open interval: 150ms- > 0ms)

But it's off in my case.

> I plan to fix it in the future. #52

Cool, good news :)

**Comment by sienori** [comment]
In ver 3.2.0, I speeded up session restoration!
When the TST support option is disabled, all tabs open at once.
Also, multiple windows are restored simultaneously.

**Comment by lapineige** [comment]
Thanks for your work, I'll test it again 🙂

**Comment by lapineige** [comment]
Ok I tested it, with 12 windows and roughly 500 tabs.
It doesn't success. It took way too much memory (it might be the same problem as #249), I had to stop it (above 10GB RAM usage), almost froze with very high CPU usage.

I was able to restore the session by restoring one window by one window. This way, each windows took a few seconds (and just ~1sec for small number of tabs). (In total, it takes a few minutes)

I did another test with ~100 tabs in one window, it took ~2sec (which is very ok).


So it seems faster than before, but it's still not really usable with lots of tabs.

**Comment by irvinm** [comment]
Not sure if this will help or not, but when I need to restore a large session (800-900 tabs w\TST support enabled), I slow the restore pace to about 2-3 per second (using active tab loading, not "Tab Lazy Loading") and then use another add-on (Auto Tab Discard) which I configure to call the native Firefox command tab.discard() after 5 seconds to hibernate the tab.  So basically, I can restore 120-180 tabs per minute and my memory never gets too crazy as the tabs are discarded shortly after they are created.  

As a side note, I see that Firefox is going to be adding the ability to create tabs in the "discarded" state in the near future and if that is incorporated into this add-on, much of this will go away.

https://bugzilla.mozilla.org/show_bug.cgi?id=1378647

**Comment by irvinm** [comment]
On a coincidence, I needed to restore one of my sessions today and I decided to try it a little differently this time.  I enabled "Tab Lazy Loading", left of Tree Style Tab compatibility and used a delay of 350 ms.  I opened my existing session (833 tabs) in one window and used TSM to restore an older version of that same session in a new window.  

The total restore time was 7 minutes 25 seconds for creating 833 tabs (total of 1666 tabs in 2 windows) and the memory used never went above 3.5GB.  Overall, this is great for me and I could probably shorten the time somewhat by reducing the delay, but I value my tree structures and I remember if the number was too low, the tab creation process wouldn't maintain the original hierarchy all the time. 

I let Firefox maintain my sessions between restarts, so I only need to do this infrequently, so waiting 7 minutes for a fully functional backup of my sessions is perfect for me.

**Comment by sienori** [comment]
I fixed the problem that increased memory usage when restoring session or closing a large number of tabs. 90390af
Also, I added option to use "discarded" property for lazy loading. 45719c3
Enabling this option will improve performance when opening tabs.
