### ISSUE TITLE
Session tracking not working 

### ISSUE THREAD

**Issue by typhoon71** [sienori/Tab-Session-Manager#1030]
## Short description
Tracking session stops

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. create 3 sessions, anable tracking on all of them
4. close and reopen browser
5. change session

## Expected result
the active session should be tracked, always

## Actual result
Session tracking stops working afeter a while (ie: I add 2 tabs, but even after minutes they aren't added to the current session; the traking dot becames greyed out, like unactive sessions, not becoming red as active ones.

## Platform information
* Platform (OS): Windows 7 sp1 fully updated / same issue on windows10 fully updated 
* Version of browser: Firefox Dev Edition
* Version of Tab Session Manager: 6.12.0

## Additional context
I'm using vertical tabs reloaded extension; in Tab Session Manager its support checkbox for it is clicked

**Comment by sienori** [comment]
I cannot reproduce the problem.
