### ISSUE TITLE
Version 1.6.1 freezes my system

### ISSUE THREAD

**Issue by saucefrog** [sienori/Tab-Session-Manager#104]
While this add-on is deactivated, Firefox 57 works well. As soon as I activate it, it only takes a few seconds and the browser hangs for minutes. Often it freezes my whole system as well, I can't move the mouse cursor anymore or click on anything. RAM usage of Firefox goes up from 1GB to 4GB (my maximum). I currently have about 700 tabs open, seems that Tab Session Manager can't handle that much.

**Comment by sienori** [comment]
I fixed it.
It's included in the next version.
https://github.com/sienori/Tab-Session-Manager/commit/50ed045d306d5242cbc8a521e336c4f86770299f
