### ISSUE TITLE
Doesn't show any currently open tabs. What is there to manage?  This is no manager. This is bullshit.

### ISSUE THREAD

**Issue by StacktraceException** [sienori/Tab-Session-Manager#1040]
## Short description
Doesn't show any currently open tabs. What is there to manage?  This is no manager. This is bullshit.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Damn it
4. 

## Expected result
manage tabs, sessions just like Session buddy or better

## Actual result
Doesn't show any currently open tabs. What is there to manage?  This is no manager. This is bullshit.

## Platform information
* Platform (OS): 
* Version of browser:  firefox and chrome
* Version of Tab Session Manager: latest

## Additional context
Maybe add a warning that this isn't actually what its (misleading) name says. It's wrong to mislead people.

**Comment by dexeonify** [comment]
It would be nicer of you to file a proper feature request instead of accusing the extension as "misleading" just because it lacks a feature you desire from a Chrome extension. :)

**Comment by StacktraceException** [comment]
"Just because?" Wtf ?    why don't you admit that the name is misleading
and that the so called manager doesn't manage anything
?  Lots of chrome extensions have this basic functionality , "just one " ?
omg
śr., 24 sie 2022, 10:59 użytkownik dexeonify ***@***.***>
napisał:

**Comment by dexeonify** [comment]
It manages sessions, and it does exactly what it name suggests. Why does it have to manage open tabs? Doesn't all browsers come with a tab bar? I don't understand. Anyways, that still doesn't change the fact that you could have asked for the feature nicely. 🙂

**Comment by IzualYang** [comment]
I've been using SessionBuddy for a long time. But I think it's SessionBuddy who is misleading. Sometimes i deleted tabs from a session, then realized i was closing actual tabs, instead of editing a replica of current session.

**Comment by sienori** [comment]
The display of currently open tabs, like Session Buddy, is outside the scope of TSM.
