### ISSUE TITLE
Cannot import existing Firefox session

### ISSUE THREAD

**Issue by sorin-costea** [sienori/Tab-Session-Manager#105]
Since a while Firefox saves the session data in .jsonlz4 format - so nothing can be loaded after install.

**Comment by sienori** [comment]
Currently, importing sessions corresponds to only Tab Session Manager and Session Manager.

**Comment by Ynjxsjmh** [comment]
[Firefox Bookmark Backup Reader/Decompressor](https://www.jeffersonscher.com/ffu/bookbackreader.html) can convert `.jsonlz4` format to `.json` format. 

Dragging the .jsonlz4 file to the input box, it shows `appears to be/contain valid JSON`. However, after converted and use `Tab-Session-Manager` to import that json file, it shows `Read failed`

And using the other button on that site like `Check/Repare JSON` or `Export HTML` button, it will pop up `Unable to parse JSON: TypeError: Cannot read property 'length' of undefined`

**Comment by WolfganP** [comment]
Similar case happened for me today. Browser crashed, and on restart the Sessions' list was empty. Troubleshooting it vs a working session in another profile, I saw that there's no recovery.bak, or other backup files, other than the lz4 compressed versions.
It will be wonderful if TSM can import those lz4 files as well for manual recovery in case something major happens.
