### ISSUE TITLE
Support for Tree Style Tabs "Colorize Tabs" Extension 

### ISSUE THREAD

**Issue by kings2u** [sienori/Tab-Session-Manager#1055]
I would love it if in addition to supporting Tree Style Tabs, Tab Session Manager also supported restoring the color of tabs assigned by the [Tree Style Tabs "Colorize Tabs" Extension ](https://addons.mozilla.org/en-US/firefox/addon/tst-colorize-tabs/). It is a major part of my workflow.

PS I just made a donation. Keep up the great work!

**Comment by sienori** [comment]
Sorry, integration with other extensions is technically difficult.
