### ISSUE TITLE
Restoring overlapping order of windows 

### ISSUE THREAD

**Issue by timdug** [sienori/Tab-Session-Manager#1056]
## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. create 6 different windows with multiple tabs open.
4. Saved profile and save for registered for startup. 
5. Close chrome
6. Reopen chrome

Result
1. 1 Of the saved windows does not save to the set location. It saves behind one of the other saved windows. 

## Platform information
* Platform (OS): win 10 and win 11
* Version of browser: 104.0.5112.102
* Version of Tab Session Manager:  6.12.0

**Comment by sienori** [comment]
Sorry, restoring overlapping order of windows is not supported.
