### ISSUE TITLE
bug: tab session is not opened as expected

### ISSUE THREAD

**Issue by Drincann** [sienori/Tab-Session-Manager#1057]
## Short description

I tried to open the history tab session by clicking as usual, but nothing happens, the window is not opened.(I also used Save Tab Groups for Tab Session Manager)
But there are some tab session that do open, and I don't see any inherent connection between them.

## Steps to reproduce

- Move the window so that the visible area of the window is below 50%.
- Use the TabSessionManager to save the window as a session.
- Double click the session, and nothing happens.

Like the following:

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/53897259/189791738-05a5444d-20fc-4031-a58d-520e2a516171.png">

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/53897259/189791815-e0b200c1-b6a2-48ea-9465-6b13415af4a2.png">

## Expected result

The tab session is opened.

## Actual result

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/53897259/189646282-6e450b4c-57ca-4155-b508-e5bee5d74d9b.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/53897259/189647656-eec54ad6-bdb5-4db0-9cbd-93e7b57c8157.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/53897259/189649727-c3d387c1-98d9-441c-83ac-d09668bae380.png">

I can confirm that it is a problem in this line.

How can I see the unuglify code in devtools and maybe I can troubleshoot the problem myself?

## Platform information
* Platform (OS): macOS Big Sur `11.6.7`
* Version of browser: chrome: `105.0.5195.102 (x86_64)`
* Version of Tab Session Manager: `6.12.0`
* Version of Save Tab Groups for Tab Session Manager `1.0.2`
## Additional context

nothing

**Comment by Drincann** [comment]
https://source.chromium.org/chromium/chromium/src/+/d51682b36adc22496f45a8111358a8bb30914534

I think the problem here is that the window is not properly positioned and sized, causing the create call to fail. 

Maybe we can catch this error and try to open the window again in some safe mode (e.g. width: 800, height: 600, left: 0, top: 0).

**Comment by Drincann** [comment]
fixed here #1058

**Comment by sienori** [comment]
Thank you for your report and PR!
