### ISSUE TITLE
Local HTML files won't open Automatically

### ISSUE THREAD

**Issue by Obscure2020** [sienori/Tab-Session-Manager#1062]
## Short description
I'm a Computer Science student who loves Java. For easy access, I have downloaded a local offline copy of the whole JDK 18 JavaDoc. Often I leave pages from this collection open in Firefox, and I have noticed that when Tab Session Manager tries to reopen these files when restoring a session, it doesn't work for some reason.

## Steps to reproduce

1. Open any local html file.
![image](https://user-images.githubusercontent.com/69320464/190212911-ea643809-9d1e-440d-8707-39a8d8cd7d6e.png)
2. Close the window.
3. Ask Tab Session Manager to reopen the window.
![image](https://user-images.githubusercontent.com/69320464/190213047-2bc658f7-728d-44b7-9667-d99c7f74136e.png)

## Expected result
Firefox can open local html files. Tab Session Manager should have no issue opening them either.

## Actual result
![image](https://user-images.githubusercontent.com/69320464/190213222-92b58f1a-3e0d-4bfa-b6bb-d051de3bc99f.png)

This result seems especially silly to me, because if I click `Copy URL` and then paste the result into the URL bar, the page immediately loads just fine.

## Platform information
* Platform (OS): Windows 10 Home 21H2 19044.2006
* Version of browser: 104.0.2 (64-bit)
* Version of Tab Session Manager: 6.12.0

**Comment by sienori** [comment]
See https://github.com/sienori/Tab-Session-Manager/issues/931#issuecomment-1229373777
