### ISSUE TITLE
[Bug!] Firefox 105.0 & 150.1 doesn't work. Crash on start; Open a new Window; and no reaction with manual selection.

### ISSUE THREAD

**Issue by kaitokid187** [sienori/Tab-Session-Manager#1066]
## Short description
first of all, my english is not very good, so i use DeepL.com translater (from German).

At today's startup, Firefox crashed completely right after restoring the last session. Only after more than 20x restarts did Firefox start at all, but then only with the default page.

then wanted to restore the session manually but the app no longer worked to the extent that a restore a tab session, is not possible. There was no response possible in any session. Only editing the session was possible.

Even resetting the app and the backup restore, caused after restarting Firefox exactly the same error.

Only by disabling the tap session app, Firefox ran normally again at every start.

I also completely reset Firefox and then set it up again. 

If it was due to a Firefox update error. But the error was there again after setup.
However, if I only install firefox with the tab session manager, the app works a few times until the error reappears. Mostly when 2xwindows and more are restored.

I also tried using v.6.11 for testing purposes, but even under that the error was back.

Please fix

Translated with www.DeepL.com/Translator (free version)

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager 6.12.1
3. Instell all other Addons
4. Activate the restore last session on starting browser
5. Close firefox
6. start firefox

## Steps to reproduce 2
1. Start browser with clean profile
2. Install Tab Session Manager 6.12.1
3. Activate the restore last session on starting browser
4. Close firefox
5. start firefox
6. step 4 and 5 repeat

## Steps to reproduce 3
1. Start browser with clean profile
2. Install Tab Session Manager older version 6.11.0
3. Activate the restore last session on starting browser
4. Close firefox
5. start firefox
6. step 4 and 5 repeat

## Expected result
Open many windows and tabs than TabSessionManager store it when close firefox

## Platform information
* Platform (OS): Windows 10
* Version of browser: Firefox 105.0 (64bit) & 105.1 (64bit)
* Version of Tab Session Manager: 6.12,1 & 6.12.0 & 6.11

**Comment by v3ritas1989** [comment]
I am also not able to open new windows that were stored in Tab session manager anymore since a few days. My moz version 105.0.1. Both "open" buttons do not work when clicking. though I can open a single stored link in a new tab

**Comment by hnorri** [comment]
having same issue firefox version 107.0.1

**Comment by docjochim** [comment]
look at the answers and solutions at [#1082](https://github.com/sienori/Tab-Session-Manager/issues/1082#issue-1389946202)

**Comment by kaitokid187** [comment]
> look at the answers and solutions at [#1082](https://github.com/sienori/Tab-Session-Manager/issues/1082#issue-1389946202)

Thankyou

I changed my FF 105.0.1 homepage FROM [www.google.com](http://www.google.com/) TO https://www.google.com/

It´s Working

**Comment by hdygma** [comment]
I added https:// to my home page under FF settings like kaitikid187 suggested and this was the fix.
FF v108.0.2 + tab session mgr v6.12.1
Hope this helps

**Comment by kaitokid187** [comment]
thank you. thats fixit
