### ISSUE TITLE
TSM does not work with Firefox version 105.0

### ISSUE THREAD

**Issue by mugetsu21** [sienori/Tab-Session-Manager#1070]
## Short description
When Firefox updated today i tried to open my saved session from yesterday but it will not open.  Clicking the open icon like usual does nothing.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Click the TSM icon and select session i want to open. 
4. Click the open icon

## Expected result

I expect my previous session to open.

## Actual result

Nothing happens and sessions do not open.
[tsmissue.txt](https://github.com/sienori/Tab-Session-Manager/files/9620941/tsmissue.txt)

## Platform information
* Platform (OS): Windows 10 64 bit
* Version of browser: 105.0
* Version of Tab Session Manager: 6.12.1

**Comment by ChevyCam** [comment]
I'm experiencing the same issue with 6.12.1 and FireFox 105.0.  Please see attached for the console output with debug option turned on from TSM.  Looks like there are a few exceptions being thrown.
[console-export-2022-9-21_19-23-44.txt](https://github.com/sienori/Tab-Session-Manager/files/9620987/console-export-2022-9-21_19-23-44.txt)

**Comment by LordEkimus** [comment]
Can confirm the same as above.

No longer able to Open tabs correctly after 6.12.1 update in FF 105.0.1 but can still Save.

Can still Delete new and old saved sessions.

**Comment by Tmk969** [comment]
Can confirm this too. Can't restore session, only window tabs in current window.

**Comment by hdmtb** [comment]
Same issues for me TSM 6.12.1 / FF 105.0.1.  Additional behavior - on browser startup, session registered with Startup tag opens first of three browser windows with two saved tabs, but does not open other two startup session windows.

**Comment by sienori** [comment]
Does the problem occur in TSM version 6.12.0?
https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/versions/

**Comment by mugetsu21** [comment]
This problem does still occur on TSM version 6.12.0 just downloaded old version from the link and installed it and still same issue. @sienori

**Comment by sienori** [comment]
I'm researching this issue and can't reproduce it...
Does the problem occur in[ Firefox 106.0beta](https://www.mozilla.org/en-US/firefox/106.0beta/releasenotes/) or [Firefox Nightly 107.0a1](https://www.mozilla.org/en-US/firefox/107.0a1/releasenotes/)?

**Comment by mugetsu21** [comment]
@sienori So it works in the beta and in nightly but still not in the current 105.0 version of firefox.

**Comment by docjochim** [comment]
@mugetsu21
in my firefox I figured out a correlation to the startup-page: If I change the startup-page from firefox-standard to a user-defined page e.g. 'www.google.de', FF exactly and reproducibly shows the described behaviour.

Did you also have a modified startup-page in your 105.0 whereas the beta or nightly are configured out of the box using the original firefox-standard startup-page?

I'd be interested in your results, if your problem was the same.

(sorry for my bad english, but school is already a long time ago...)

**Comment by docjochim** [comment]
changing custom startup-page from www.google.de to http://www.google.de also works  (see [here](https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264412811))

**Comment by mugetsu21** [comment]
@sienori @docjochim i think that might be the issue cause last night when i installed both the beta and nightly both worked but today after setting the home page and new windows setting to google in the beta version i can no longer open my saved sessions while in nightly where i have not done so still works.

**Comment by Kurotaku-sama** [comment]
> changing custom startup-page from [www.google.de](http://www.google.de) to http://www.google.de also works (see [here](https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264412811))

I changed my start page after I read this and it works now thx

**Comment by LordEkimus** [comment]
My FF 105.0.1 was user defined but adding http:// has fixed the issue also. How bizarre.

**Comment by sienori** [comment]
See: https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264412811
