### ISSUE TITLE
Open previous session on startup not working in Windows 11, version 22H2

### ISSUE THREAD

**Issue by Zafaron** [sienori/Tab-Session-Manager#1073]
## Short description
After updating to Windows 11 22H2 restore previous session on startup not working.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Open some tabs
4. Restart Firefox

## Expected result
Expected previous session to be restored.

## Actual result
Firefox shuts down as prior to 22H2 update, but does not start again on its own  The next time the user
 manually starts Firefox it also shuts down, attempting to restore session, but does not start.  Starting in 
debug mode is necessary to disable Tab Session Manager and change from 'Restore Previous Session'.

No crash log exists as Tab Session Manager simply fails to start Firefox in order to restore the previous
session.  Manually restoring session still works as expected.

## Platform information
* Platform (OS): Windows 11, Version 22H2
* Version of browser: 105.0.1
* Version of Tab Session Manager: Version 6.12.1

## Additional context
 Maybe permission problem with Firefox trying to restart itself?  Possible to restore the session automatically without
 restarting Firefox?

**Comment by BoydyBoydy** [comment]
I get this as well.

I am also unable to manually open the previous session from the double window 'open' icon.

Not sure if this was the same issue, since the previous session couldn't open or that there might be a separate issue here.

**Comment by sienori** [comment]
Does the problem occur in TSM version 6.12.0?
https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/versions/

**Comment by Zafaron** [comment]
Yes, the issue also happens in TSM version 6.12.0.  Manually opening session does still work but not automatically restoring session.

**Comment by BoydyBoydy** [comment]
Just to confirm that my issue is fixed.

I had downgraded the version at the suggested 6.12.0 (and previous versions) and the opening of the saved session worked.
Overnight the version had been updated automatically to the current version 6.12.1 and now seems to allow for the same functionality to work as before. (Opening the saved session on starting Firefox as well as manually opening the saved session)

Possibly, at least for me, it could have been an installation error during the Windows Update and downgrading (or even just installing the version again) would allow for the correct update to happen.

Obviously this is not the best case, but it might help other people to fix the issue in future.

**Comment by sienori** [comment]
I'm researching this issue and can't reproduce it...
Does the problem occur in[ Firefox 106.0beta](https://www.mozilla.org/en-US/firefox/106.0beta/releasenotes/) or [Firefox Nightly 107.0a1](https://www.mozilla.org/en-US/firefox/107.0a1/releasenotes/)?

**Comment by sienori** [comment]
See: https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264412811
