### ISSUE TITLE
TSM Causes Firefox 105.0.1 to crash upon startup

### ISSUE THREAD

**Issue by trumpy81** [sienori/Tab-Session-Manager#1076]
## Short description
When attempting to start Firefox, Firefox will immediately shutdown if Tab Session Manager is set to 'Open previous session'

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Set Tab Session Manager to 'Open Previous Session'
4. Close Firefox
5. Restart Firefox and watch it shutdown seconds later

## Expected result
I expect Firefox to startup and remain running as it previously did prior to 105.0.1 being installed.

Current workaround is to set Tab Session Manager to 'Do nothing' at startup.

## Platform information
* Platform (OS): Windows 11 Pro
* Version of browser: 105.0.1
* Version of Tab Session Manager: 6.12.1

Sorry, I am not able to capture any logs.

**Comment by trumpy81** [comment]
I installed 6.12.0 and had the same issue.

Had a real time of it trying to prevent auto update to 6.12.1, but got there in the end.

Also, importing settings has not worked for quite sometime. The settings appear to export OK (.json is populated), but they do not import correctly. Not a big issue since I rarely use it, but thought I would mention it.

I have attached my exported settings so that you may see how things are configured. 
[TabSessionManager_Settings.zip](https://github.com/sienori/Tab-Session-Manager/files/9658116/TabSessionManager_Settings.zip)

Do note, that if I set the `Start Up` settings to `Open Previous Session`, then Firefox will crash as soon as you attempt to open it.

The only way to open Firefox in that case is to go to:
C:\Users\USER NAME\AppData\Roaming\Mozilla\Firefox\Profiles\PROFILE NAME\extensions

And delete the Tab-Session-Manager@sienori.xpi package.

After Firefox restarts, you then reinstall Tab Session Manager.

**Comment by sienori** [comment]
I'm researching this issue and can't reproduce it...
Does the problem occur in[ Firefox 106.0beta](https://www.mozilla.org/en-US/firefox/106.0beta/releasenotes/) or [Firefox Nightly 107.0a1](https://www.mozilla.org/en-US/firefox/107.0a1/releasenotes/)?

**Comment by trumpy81** [comment]
I opened a Windows 11 Pro VM, installed the 106 Beta and had the same issue. If `Open Previous Session` is enabled, then when you attempt to reopen Firefox, Firefox immediately shuts down. If it matters, I also have Popup set to `Open in current window`.

Interestingly, when I updated Firefox to the 106 Beta, Tab Session Manager was NOT synced, all my other add-ons were synced. I had to download TSM and install it manually.

I then installed the 107 Nightly (separate install from the 106 Beta) and had the same issue. If `Open Previous Session` is enabled, then when you attempt to reopen Firefox, Firefox immediately shuts down.

This time, TSM was synced along with all my other add-ons.

Deleting the Tab-Session-Manager@sienori.xpi package is the only way to get Firefox to restart in both cases.

I made a screen capture showing what happens. Note: I had TSM installed previous to my capture, so that is why TSM is already configured after I reinstall it.

Hopefully, you can download the video here:
https://drive.google.com/file/d/1W8an0pTJyn9nP90rgS_F21nBNjaj3p_B/view?usp=sharing

**Comment by sienori** [comment]
See: https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264412811

**Comment by trumpy81** [comment]
I tried the suggested fix and by golly it worked :)

Thanks for the feedback.
