### ISSUE TITLE
Don't steal tab focus on update

### ISSUE THREAD

**Issue by JukePlz** [sienori/Tab-Session-Manager#108]
Addon restart-less updates mean Tab Session Manager can take away tab focus when the user is busy with something else, because of the forced Information/settings window that pops up when a new version is downloaded. This is painful and will do things like closing youtube videos the user is watching if Tab Session Manager happens to update while doing so, and the only workaround is to disable automatic updates for the addon (which is bad)

Sugested fix:

- Open the information in a new tab, but don't switch to it, and make sure it doesn't do things like closing fullscreen videos playing in other tabs.
- Add a checkbox to stop showing the information window on new updates to the addon options.

**Comment by sienori** [comment]
I will try to open it in the background.

This is the necessary process to initialize the settings.
Addon reads the elements on the options page and adds new settings.

**Comment by MadscientistCC** [comment]
I would like to second this request. In particular:
> Add a checkbox to stop showing the information window on new updates to the addon options.

**Comment by sienori** [comment]
I Implemented it.
https://github.com/sienori/Tab-Session-Manager/commit/58ee555ba39c29986bdb5f69dd5f4c6015074adf
