### ISSUE TITLE
Feature enhancement

### ISSUE THREAD

**Issue by crssi** [sienori/Tab-Session-Manager#109]
Is there a way to add feature?
I have in mind the same what addon [URLs List](https://addons.mozilla.org/en-US/firefox/addon/urls-list/) offers.

There are two reasons why:
1. To have both functionalities in one.
2. URLs List has a problem when using together with [Close Unused Blank Tabs](https://addons.mozilla.org/en-US/firefox/addon/close-unused-blank-tabs/), where your addon doesn't suffer.

**Comment by tbertels** [comment]
This doesn't seem to have anything to do with session saving.
It would probably be better to fix URLs List or create a new extension.

**Comment by crssi** [comment]
Fair enough.

Thank you
Cheers
