### ISSUE TITLE
v1.1.1: Containers are not saved/restored

### ISSUE THREAD

**Issue by DilectableBananaButterfly** [sienori/Tab-Session-Manager#11]
Tab containers state is not saved or restored such that when a session is restored, all tabs open in the default container rather than the ones they were in during the session. Security issues not withstanding, this would be an extreme annoyance as users have to re-open those tabs in the proper containers.

**Comment by sienori** [comment]
Supported in ver1.3.2

**Comment by reallyuniquename** [comment]
@sienori Is it actually supported for native containers? Latest Firefox has its own native containers support and it seems TSM doesn't save nor restore those tabs correctly. They are getting openned in the default container.
