### ISSUE TITLE
can't load session from session manager .session file

### ISSUE THREAD

**Issue by jblb** [sienori/Tab-Session-Manager#110]
Hi,
I try to load session fron my session manager backup file .session whith TSM but it fail !
here is what i do:
- i import my session file
- opening TSM with icon on tools bar show me my session (whith corect nb of windows and tabs)
- clicking on open just open me a new window with TSM extention tab but not my saved session...

afer that my saved session disappear from tool bar popup

**Comment by iffling** [comment]
I have the same problem.  I exported my sessions via Session Manager (originally out of Tab Mix Plus) to .session files.  I then import them via TSM, and they have the right number of tabs and such.  But when I expand the entry in TSM's pull down, all the tabs are just duplicates of the last tab of the set.  And, when I actually choose that session, it doesn't even open the listed tab, just a TSM page.

**Comment by kamidev** [comment]
Exactly the same problem here. I am using version 1.7.1

**Comment by ooofest** [comment]
I believe we're talking about the same issue here: 
https://github.com/sienori/Tab-Session-Manager/issues/78

I uploaded a sample Session Manager session for potential debugging of this situation.

**Comment by sienori** [comment]
I fixed it in version 1.8.0.
https://github.com/sienori/Tab-Session-Manager/commit/c566d11e31c1f91b490d4aaf7a0dc52986668e93
