### ISSUE TITLE
Edit saved sessions and remove saved pages

### ISSUE THREAD

**Issue by alterechtschreibung** [sienori/Tab-Session-Manager#112]
Please add a button to deselect pages from saved sessions. Often you don't want to restore all saved tabs. Thus it would be great to modify saved sessions and save the cleaned version (by overwriting or alternatively as new session with a different name.

**Comment by sienori** [comment]
I implemented the function to delete window or tab on saved session. https://github.com/sienori/Tab-Session-Manager/commit/12b592a45d171e6684116457b08d034791328073
![delete](https://user-images.githubusercontent.com/29514424/38173294-d2e441f0-35f6-11e8-9bda-eebe6f40f7d4.png)

**Comment by alterechtschreibung** [comment]
Thank you. That's a good start. To improve it, please see: 
https://github.com/sienori/Tab-Session-Manager/issues/229
