### ISSUE TITLE
Tab Session Manager does not import Sessions that were stored in an External Files on my C: Drive.

### ISSUE THREAD

**Issue by RALandkamer-GitHub** [sienori/Tab-Session-Manager#116]
In the original Session Manager created by Michael Kraft, there was an option to save all Session Manager definitions in an external file on the user's C: Drive.  Also, one could specify the name of this external file.

I read too many horror stories of Session Manager definitions being wiped out when Firefox and/or their computer crashed, and their Session Manager definitions were stored in the default Firefox location.  Consequently, I stored all of my Session Manager definitions in the above referred to external file, which I could always go back to without having any Session Manager definitions destroyed.

My testing indicates indicates that Tab Sessions Manager by Sienori does not open or load any Session Manager definitions from this external file.  I do not know if the name of this external file is available when any Sessions are initially loaded. 

Does Tab Sessions Manager by Sienori have any plans to load and use all Session Manager definitionss that were saved in an external file by Michael Kraft's previous version of Session Manager?  If so, when will this feature become available?  Also, I would like to be able to continue keeping all of my Session Manager definitions in an external file on my C: Drive.

Richard A. Landkamer

**Comment by RALandkamer-GitHub** [comment]
Clarification from the author:  This Subject should have been:  "Tab Session Manager does not import Sessions that were stored in an External File on my C: Drive", since  I had only 1 external file.

Richard A. Landkamer

**Comment by RALandkamer-GitHub** [comment]
How do you drag and drop an external file that is currently over 90 Meg with a single user defined name that I made up called "Mozilla Session Manager Files".  

I originally began using Michael Kraft's  Session Manager about 5 years ago back in 2012.  At that time I began organizing my Windows by subject matter, after which I could add and drop Windows dynamically within a Session.  By now most links to Windows with Tabs over 2 years old are probably obsolete, and could be deleted.

Michael Kraft states the following about his version of Session Manager:

"Unfortunately do to limitations in the the provided APIs in Firefox 57, Session Manager cannot be implemented as a WebExtension add-on and will not work in Firefox 57 or higher. My only recommendation is to either not update to Firefox 57, use the Firefox ESR build or use a forked version of Firefox that does not remove support for add-ons such as CyberFox or Waterfox."

Tab Session Manager by Sienori totally ignores the existence my above external file named "Mozilla Session Manager Files".  Does Sienori ever intend to support an external file like I use?

I started using this external file option that was offered by Michael Kraft when I read other people's horror stories about losing all of their SESSION definitions when either Mozilla Firefox and/or their computers crashed.  By using an external file, I never lost any of my SESSION Definitions. 

Richard A. Landkamer

**Comment by RALandkamer-GitHub** [comment]
I believe that Issue #121 named "Support "Window Sessions" is directly related to my Issue.  The author of Issue #121 accurately described one of the main features of how I previously used Michael Kraft's Session Mamager, regardless of whether the author of Issue #121 stored his/her Session Definitions in an external file like I did.

Richard A. Landkamer

**Comment by sienori** [comment]
It seems to be the same problem as #78.
I will fix it.

**Comment by sienori** [comment]
I fixeed it probably.
Please try it in version1.8.0.
c566d11

**Comment by RALandkamer-GitHub** [comment]
Hi sienori,

Something has changed in the list of Extensions for Firefox v57.0.2.  I 
no longer see your Tab Session Manager in the list of Firefox v57.0.2 
Extensions, which is how I got to your Tab Session Manager before.

Are they finally fixing the "spam infestation problem", which is 
described on the web page at 
https://www.ghacks.net/2017/12/13/mozillas-extensions-store-has-a-spam-infestation/ 
?

I will check back later.

Richard A. Landkamer
