### ISSUE TITLE
Not load Save sessions Windows 7 64bit Firefox Quantum

### ISSUE THREAD

**Issue by youtubedownloads** [sienori/Tab-Session-Manager#117]
Will not respond and load 8 windows 113 Tabs in Firefox

* Clicking open in the menu does not do anything? (Able to Delete)

Is this Add-on non-functional with the new update today? @ Wed Dec 13

Contact @ thisisstipid008@gmail.com

**Comment by sienori** [comment]
It is fixed in the current version.
