### ISSUE TITLE
Auto save session with a name.

### ISSUE THREAD

**Issue by loggerhead** [sienori/Tab-Session-Manager#120]
It is hard to distinguish which session is which when session auto save is turn on. If the plugin can auto create a name (e.g. the first tab title of the session) when the session is saved, it would be helpful to reduce this situation.

**Comment by sienori** [comment]
I added the option. 
The title of the open tab is used as the auto save name.
https://github.com/sienori/Tab-Session-Manager/commit/12d3cf803033e6eafa7f9ca8f84ee6214448859b
