### ISSUE TITLE
Project Dead? Needs Contributors / Admins?

### ISSUE THREAD

**Issue by Swivelgames** [sienori/Tab-Session-Manager#1207]
Any plans to update this project? Do you need additional collaborators?

Outside of updating the `backers.md` file, this project hasn't been [updated in 9 months](https://github.com/sienori/Tab-Session-Manager/commit/c319f6b9205b9fdf71ccae873c360c0e6aae75e0). But, more importantly, there hasn't been any responses to Issues or PRs since [then](https://github.com/sienori/Tab-Session-Manager/issues/1082#issuecomment-1264212699) either.

If you need assistance, I'm sure there are plenty of us users that would be more than happy to contribute!

**Comment by sienori** [comment]
Sorry for the infrequency of maintenance due to my busy work schedule. I am willing to continue maintenance.

**Comment by Swivelgames** [comment]
I think the frustration comes from seeing the `backers.md` file updated frequently, while PRs and Issues are ignored. It paints a bad image, given that the maintainer is receiving donations specifically to maintain the project, but the project is being neglected.

Thank you for the update!
