### ISSUE TITLE
Support "Window Sessions"

### ISSUE THREAD

**Issue by ElhemEnohpi** [sienori/Tab-Session-Manager#121]
Michael Kraft's legacy Session Manager addon supported "Window Sessions". That means, that you can save and restore each window separately, each with a different name. You can open and close any window at any time, in any combination. It's just like working with standard word processing or spreadsheet documents. There's also an autosave.

For me, it's one of the most useful things ever in Firefox, and once you start using it, you won't know how anyone can use a browser without it, or why the browser doesn't work that way by default.

Please support this in Tab Session Manager! Thanks.

**Comment by wbt** [comment]
Duplicate of #30?

**Comment by ElhemEnohpi** [comment]
This would not require any new API from Mozilla, as far as I can tell.
I suppose it is probably a duplicate of issue 30, so I'll close it.
