### ISSUE TITLE
Restores only one window of the saved session

### ISSUE THREAD

**Issue by TheLastChosenOne** [sienori/Tab-Session-Manager#122]
Ich habe mehrere gespeicherte Sessions mit jeweils 3-4 Fenster und insgesamt oft über 40 Tabs (Firefox-ESR unter Debian Stable (Stretch), Version 52.5.2 64bit). Wenn ich auf "Öffnen" bei einer gespeicherten Sitzung klicke, wird nur ein Fenster statt alle 4 gespeicherten wiederhergestellt.
Die Option "Unterstützung von baumstrukturierte Tabs" wurde auch deaktiviert, jedoch selbes Problem.
Wenn der Haken bei der Option "Sitzung im neuen Fenster öffnen" gesetzt ist, passiert beim Klick auf "Öffnen" nichts - auch nicht  nach mehreren Minuten.

In English:
I'm using Firefox-ESR 52.5.2 on Debian Stretch. In the AddOn options, i disabled the first one which will replace the current Tabs with the one from the saved Session. With this option enabled, the Session Manager won't do anything when restoring a saved session.
The last option "Support of tree structured tabs" is disabled cause I'm using an older version of Firefox than v57.
When I'm trying to restore a saved session with 40 Tabs in 4 Firefox windows, the AddOn will restore just the first window. The other 3 saved ones won't be restored.

**Comment by sienori** [comment]
I think that this problem is solved in the latest version.
