### ISSUE TITLE
Don't work with Kiwi on android : Failed to save session.

### ISSUE THREAD

**Issue by mikhoul** [sienori/Tab-Session-Manager#1221]
## Short description
Don't work with Kiwi on android : Failed to save session.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Click on the save button
4. The error "Failed to save session." appears. 

## Expected result

Should save the session
## Actual result

![image](https://github.com/sienori/Tab-Session-Manager/assets/5678673/97549ebe-6c4e-4edd-be49-06fe3782d226)

## Platform information
* Platform (OS):   Android 11
* Version of browser:  Latest Kiwi
* Version of Tab Session Manager:  6.12.1

**Comment by KaKi87** [comment]
Unfortunately, maintainer has already refused to support mobile browser multiple times without explanation, see #837 & #1037 for Kiwi, #261 & #984 for Firefox. :/

**Comment by mikhoul** [comment]
Sad but I tested Tabs Backup & Restore on Kiwi and with 1 windows it work: https://chrome.google.com/webstore/detail/tabs-backup-restore/dehocbglhkaogiljpihicakmlockmlgd

**Comment by KaKi87** [comment]
That one's not FLOSS though.

**Comment by sienori** [comment]
Sorry, Tab Session Manager does not support android.
