### ISSUE TITLE
Is Tab Session Manager dead?

### ISSUE THREAD

**Issue by YousufSSyed** [sienori/Tab-Session-Manager#1224]
I've noticed that the app hasn't gotten any meaningful updates since September and there are lots of unaddressed bug reports on GitHub. Personally I've had some issues with the extension myself like a bunch of tabs missing when restoring sessions: https://github.com/sienori/Tab-Session-Manager/issues/1223. I've had issues like this for years and am seriously looking at alternative extensions.

**Comment by sienori** [comment]
Sorry for the late reply due to my busy work schedule. I am willing to continue maintenance.
