### ISSUE TITLE
Unable to  Google Sync / Not Syncing

### ISSUE THREAD

**Issue by ftodd1** [sienori/Tab-Session-Manager#1225]
Running FF esr 102.
About 1 week ago sessions unsynced starting building up.  Even when manually telling it sync now.  Logged out and back on to google.  Config shows logon properly.
Suggestions?
Todd

**Comment by devanteweary** [comment]
Kind of the same issue here.
Hasn't been syncing for months and when I go to authorize TSM, it gets to the point where Google says "Tab Session Manager wants access to your Google Account." and I click continue and it tells me Something went wrong
Sorry, something went wrong there. Try again.".

I just can't even login to my Google account using TSM.

**Comment by kesu1** [comment]
I have ~500 sessions saved, but when I try to sync with another browser I regularly use, it's stuck at downloading ~100 sessions. Where are the sessions stored exactly in your Google storage?

**Comment by sienori** [comment]
Try reset Google Drive. See https://github.com/sienori/Tab-Session-Manager/discussions/552
