### ISSUE TITLE
Tab list preview not showing if a website asks for htaccess login

### ISSUE THREAD

**Issue by saucefrog** [sienori/Tab-Session-Manager#124]
In my hundreds of tabs, I have a website that asks for an .htaccess login. During everyday use of Firefox, it's not a problem as the website is deep down in my tabs and not loaded. But if I open the Tab Session Manager (TSM) window, then click on a session to preview the list of tabs, the TSM window closes and I'm shown the .htaccess login of that specific website.

So instead of just showing the list, it loads or activates all the websites and if one has an .htacess login, it switches to it.

**Comment by sienori** [comment]
Could you tell me the URL of the problem website?
