### ISSUE TITLE
List of sessions mostly "0 windows - 0 tabs" 

### ISSUE THREAD

**Issue by tornado103** [sienori/Tab-Session-Manager#125]
Is it because I don't save history?
I've noticed that 95% of my saved sessions have nothing :(

It's by far my favorite session manager, so I'd like to get it figured out

**Comment by tornado103** [comment]
When I try to save a session, it's saving as 0 windows 0 tabs

**Comment by sienori** [comment]
Please tell me your firefox version.
In firefox57 and Tab Session Manager ver1.8.0, It will not happen.

**Comment by tornado103** [comment]
Hello Sienori, 
The PC I was using has crashed, 
but I have transferred the files to my WIndows 10 laptop where Tab Session Manager has always worked.

I figured it out! 
On the crashed PC I was using "private" firefox and did not check the box in options for "Save Private Window"

Problem solved. Thank you for a great Add-on/Extension
