### ISSUE TITLE
Support overwriting user sessions

### ISSUE THREAD

**Issue by ivandardi** [sienori/Tab-Session-Manager#127]
It would be really practical to have a way to overwrite a user-saved session with the current tabs.

Right now if I want to "overwrite" a user-saved session, I have to delete the old one and create a new one with the same name.

My proposal is that next to the `Open Delete` options of user-saved sessions there be an `Overwrite` option that creates a new session with the same name and with the current tabs and deletes the old one, effectively overwriting it.

**Comment by sienori** [comment]
I am planning to implement it.

**Comment by sienori** [comment]
I added the menu item to replace with current session. https://github.com/sienori/Tab-Session-Manager/commit/94f2dfc1f789563a5158bfe450331ed0e15492ac  #149
![replace](https://user-images.githubusercontent.com/29514424/38174082-c859a192-3602-11e8-9d6f-88ffea524fb6.png)

**Comment by ivandardi** [comment]
Thank you so much!
