### ISSUE TITLE
import/export session

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#13]
could you add the feature to import export sessions so we can port the sessions to an other profile/pc?

**Comment by sienori** [comment]
It is difficult to implement.
Because the webextensitons API does not yet correspond.
Sorry.

**Comment by rayman89** [comment]
Dont worry. I hope in the feature is possible. Thank you.

**Comment by sienori** [comment]
If you want to migrate the session, copy the following files.
[profile folder]\browser-extension-data\Tab-Session-Manager@sienori\storage.js
(you can open profile folder from about:support)

**Comment by rayman89** [comment]
Thank you. You could make the addon save a copy of that on desired fodler and import to replace the file and then ask the user to reload coulndt you?

**Comment by sienori** [comment]
Please do the work with the browser closed.

**Comment by rayman89** [comment]
I'm saying that the thing you told me could be used as an export/import feature making the addon do the same thing for you (idk if WE are capable of that or at least to copy the storage.js to the desktop and then tell the user what to do with it. Just an idea.)

**Comment by sienori** [comment]
I implemented import/export function. #40
