### ISSUE TITLE
"Dont' expand collapsed tree" option doesn't work

### ISSUE THREAD

**Issue by ildar** [sienori/Tab-Session-Manager#133]
And behaves quite strangely: Ctrl+PgDown from collapsed parent expands it and stay on the parent tab.

**Comment by sienori** [comment]
Is this an issue for the Tree Style Tab?
This is Tab Session Manager’s repository.

**Comment by ildar** [comment]
Woops, sorry. Indeed, the issue's true address should be
https://github.com/piroor/treestyletab/issues/1583
