### ISSUE TITLE
Cannot export.

### ISSUE THREAD

**Issue by freemedom** [sienori/Tab-Session-Manager#1334]
## Short description
chrome-extension://iaiomicjabeggjcfkbimgmglanimpnae/options/index.html#sessions
![image](https://github.com/sienori/Tab-Session-Manager/assets/57294686/c815496a-e130-4268-9734-dd8af49378fb)

![image](https://github.com/sienori/Tab-Session-Manager/assets/57294686/160dec76-e0f5-41c4-aaf8-7832eabdde0b)

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. 
4. 

## Platform information
* Platform (OS): Windows
* Version of browser: Google Chrome 114.0.5735.199
* Version of Tab Session Manager: [Version 7.0.0]

**Comment by freemedom** [comment]
type: "application/json"
  })) : (0 == await t().runtime.**getContexts**({
      contextTypes: ["OFFSCREEN_DOCUMENT"],
      documentUrls: [t().runtime.getURL("offscreen/index.html")]
  }) && await t().offscreen.createDocument({
      url: "offscreen/index.html",
      reasons: ["BLOBS"],
      justification: "Use URL.createObjectURL"
  }),

**Comment by sienori** [comment]
Please use the latest version of Chrome.
The `chrome.runtime.getContexts` used for export is only available in Chrome 116 or later.

**Comment by freemedom** [comment]
because of some troublesome compatibility reason, i don't want to upgrade the chrome version, so i find a method to manually export indexeddb.
https://dfahlander.medium.com/export-indexeddb-from-a-web-app-using-devtools-62c55a8996a1
