### ISSUE TITLE
Unable to see or access the SAVE button and custom name fields 

### ISSUE THREAD

**Issue by Art5** [sienori/Tab-Session-Manager#1336]
When using TSM in Firefox on a windows 11 laptop with a 1920x1080 display and Custom Scale set to 200, the bottom of the TSM Save window is cut off, making it impossible to manually save a session.

There appears to be no way to drag this window up, and there are no visible scrollbars.

As a moderately visually impaired user, it would be greatly appreciated if you could either move the SAVE button and name field to the top of the window, allow the window to be moved/resized, and/or add scroll bars.

thank you for your consideration.

**Comment by sienori** [comment]
You can change the popup size from the settings page.
![image](https://github.com/sienori/Tab-Session-Manager/assets/29514424/cfd3acf2-7bb0-426a-9b7d-5088c29f20cc)

You can also open the session list in a tab.
![image](https://github.com/sienori/Tab-Session-Manager/assets/29514424/6343452f-7c20-4e62-9c67-8221018b18bc)

**Comment by Art5** [comment]
Brilliant! Thank you - for both thinking of this in your design and explaining it to me.
