### ISSUE TITLE
Well done, Tab Session Manager v7.0.0! 

### ISSUE THREAD

**Issue by TeaganXXX** [sienori/Tab-Session-Manager#1343]
Well done, Tab Session Manager v7.0.0!  You've successfully turned Mozilla Firefox v126.0.1 (64bit) into the world's most efficient opening-and-closing browser simulator.   Who needs a functioning browser anyway, right?  Who knew one little extension could bring so much excitement to our browsing experience?  Maybe a heads-up from the developer wouldn't have hurt, you know, before leaving us stranded in Browser Limbo.  But hey, who needs smooth browsing when you've got suspense? 🙄 #ThanksButNoThanks  

  . . . Seriously, I've never encountered anything quite like this before, especially with it dragging on for so long.

**Comment by sienori** [comment]
Sorry for the inconvenience. I have already fixed this issue and uploaded version 7.0.1 to the Add-on Store. https://github.com/sienori/Tab-Session-Manager/issues/1333#issuecomment-2150428455 Please wait a few days until it is published in the Add-on Store.

**Comment by TeaganXXX** [comment]
> Sorry for the inconvenience. I have already fixed this issue and uploaded version 7.0.1 to the Add-on Store. [#1333 (comment)](https://github.com/sienori/Tab-Session-Manager/issues/1333#issuecomment-2150428455) Please wait a few days until it is published in the Add-on Store.

@sienori   It's all good 👍🏼, I do appreciate what you do and the extensions (add-ons) you make available.  I've been using several of your extensions for a while now, and they are fantastic, and I rely on them daily.  Please don't take my sarcasm too seriously.
