### ISSUE TITLE
Firefox quits at startup if unfocused with TSM installed

### ISSUE THREAD

**Issue by OsmiumBalloon** [sienori/Tab-Session-Manager#135]
Tab Session Manager 1.8.0 (2017 December 19)
Firefox 57.0.2 (32-bit)
Debian Linux 7.11
Kernel Linux3.2.0-4-686-pae #1 SMP Debian 3.2.93-1 i686 GNU/Linux
X.Org X Server 1.12.4
Window manager = fvwm 2.5.30
Focus follows mouse

If I start Firefox, and don't focus the window immediately, Firefox quits within a second or two.  If I focus the window as soon as it appears, everything is fine, and after a few seconds, I can defocus/refocus without issue.  Only happens when Tab Session Manager is enabled.

I don't get a crash reporter dialog, and if I start Firefox from an xterm, I don't see any error messages, which makes me suspect this isn't a Firefox core crash, but rather something like "TSM is trying to restore an empty session, and accidentally closes everything".

Any suggestions on how to debug?

(Edit #1, 2017DEC27: Added version of TSM.  That would help.)

**Comment by sienori** [comment]
I wonder if the option to restore session at startup is the cause.
Try turning off the option to restore session at startup.
Also, please tell me what happens to the last autosave session (window was closed) when problems occur.

**Comment by justcsdr** [comment]
I tried it with the "restore session at startup" disabled and it didn't quit if unfocused.

**Comment by justcsdr** [comment]
After updating to v3.1.2 on FF 6.0.1 the browser doesn't quit any more if unfocused.

**Comment by sienori** [comment]
Thanks for the report.
This issue seems to have been solved.

**Comment by justcsdr** [comment]
Unfortunately this bug returned.

**Comment by sienori** [comment]
@justcsdr 
Please tell me the detailed steps to reproduce the problem.

**Comment by justcsdr** [comment]
I am not doing anything special. Just starting FF and focus other window. As you can see from the screenshots I have (in this case) 18 tabs open.

The session isn't crushing because TSM is saving the new (no tabs loaded) session. It happens even with an empty session if "Restore session on startup" is selected.

![settings1](https://user-images.githubusercontent.com/8593662/42878755-e7ade9ac-8a96-11e8-8e0a-405b53470270.png)
![settings2](https://user-images.githubusercontent.com/8593662/42878756-e808e91a-8a96-11e8-8360-10cf91d7f414.png)
![settings3](https://user-images.githubusercontent.com/8593662/42878760-e8beb416-8a96-11e8-8be4-ee990a395d80.png)

**Comment by sienori** [comment]
Hmm, I can not reproduce the problem...

## Steps I tried
1.  Create a new profile for firefox and install TSM
2.  Set the TSM settings according to your screenshot
3.  Open google.com in a new tab
4.  Close firefox
5.  Start firefox and click on another window

## Expected result
Firefox closes like a bug report

## Actual result
Firefox is opened normally and the previous session is restored

## Platform information
Windows10 64bit
Firefox 61.0.1 (64bit)
RAM 24GB
Tab Session Manager 3.2.0

It may be affected by other add-ons and Firefox settings.
Does the problem occur even with the new profile?
Also, please tell me about your environment (OS, memory etc).

**Comment by sienori** [comment]
Does the problem occur 100%?
I can not understand the cause...

**Comment by justcsdr** [comment]
Yes. Every time I start FF.
For the moment I'll use FF built-in session restore and let TMS do the session backup.
