### ISSUE TITLE
Lost all sessions

### ISSUE THREAD

**Issue by toodeeptofind** [sienori/Tab-Session-Manager#136]
I recently had a BSOD and restarted the laptop. When I open the firefox, all I see is blank and there are no saved sessions in tab session manager which I have been using since the upgrade to FF 57. Is there a way to restore all the tabs as there were more than 100 tabs and it is cumbersome to search in history.

What I have done till now(just a beginner)?
- profile_name>Tab-Session-Manager@sienori>storage.js has current tabs but storage.js.corrupt is empty when opened by sublime
- profile_name>sessionstore-backups has files but all they provide is bunch of 1s and 0s only.

**Comment by AerialView** [comment]
I have v 57 of Firefox. I can no longer access old sessions.
I have a bunch of (.session) files, but importing a session in session manager -> import sessions does nothing... I can see that there is information in these files. How can I restore all the tabs from one of these files? 
Your assistance is greatly appreciated.

**Comment by mwld** [comment]
I'm in the exact same situation. Lost all my sessions due to a BSOD. I've got backups of my Firefox profile folder. How can I restore the sessions?

**Comment by irvinm** [comment]
I had the exact same problem (BSOD & problems after restarting).  

Because all of the information is stored in a single file, if that file get corrupted \ replaced, you will lose everything.  I ended up writing a batch file that is run thru task scheduler to backup my storage.js and append the date and time to the filename while only keeping 10 copies.

The only way I got around losing everything that day was to use Firefox's history and selected everything from the day it happened [As I had used Tab Session Manager that day to restore a session] to load each page in separate tabs.  Once loaded, I spent hours trimming it down to the tabs I originally had in my session.  I decided I didn't want to go thru that again and went the backup route.

**Comment by sienori** [comment]
The problem of session file corruption has been reported by several people.
I think that it probably happens when Firefox or the PC is terminated while writing to the session file.
In order to deal with this problem, I'm planning to implement the function to backup sessions to the cloud.

**Comment by toodeeptofind** [comment]
@sienori I think that will solve lots of problems and be better for people like me who uses more than one laptop.

Hoping to see this feature soon

**Comment by mwld** [comment]
The file in question I was looking for is: {Firefox Profile Folder}\browser-extension-data\Tab-Session-Manager@sienori\storage.js. I was able to restore it from a backup of my user data.

@sienori A backup would be nice. But I think it does not need to be saved to some server. It would be enough to have copies made of storage.js on a cyclic basis and an option to restore them from plugin settings. For example: one copy from the last hour, one from the day before, one from one week ago etc.

**Comment by sienori** [comment]
@mwld That is the simplest solution but because of the specification of WebExtensions, it is impossible to create the file in local storage.

**Comment by aaaxx** [comment]
Here's a crazy idea: Is it possible to dump the json data into a bookmarklet? Then we could just let Firefox Sync take care of it.

**Comment by sienori** [comment]
I implemented the function to save the backup.
I thought that I could not save the file without user interaction, but it was a misunderstanding.
The save destination is only Firefox default download directory.
https://github.com/sienori/Tab-Session-Manager/commit/96e76b0d8c79ed0fe08af974e03fcdf0a72bfcfa

**Comment by Mister-Bill** [comment]
I just got this wonderful window when I reopened Firefox. None of my windows reopened. What a great program this is.

Restore Session
about:sessionrestore
This page can not be opened by Tab Session Manager.

**Comment by AlexanderESmith** [comment]
If corruption can destroy the entire library of sessions, maybe it would be a better idea to not rely on a single file to store them? Maybe alternate between several files?

If you can't recover your sessions after a critical failure, the addon is useless.

**Comment by Babbo-at** [comment]
Agreed ... unfortunately: just opened FF, right now, and all my sessions are lost (without any crash of any program, all on a very stable Win 10 pro system).

Total frustration.
