### ISSUE TITLE
Unable to restore "New Tab" 

### ISSUE THREAD

**Issue by CrashNBurn71** [sienori/Tab-Session-Manager#139]
While not a game-breaker, it could possibly indicate a deeper bug - or just be a quirk. 
"
New Tab | about:newtab
This page can not be opened by Tab Session Manager.
"

**Comment by gro-gg** [comment]
The same occurs when trying to restore a tab with local file URL:

file:///tmp/index.html

**Comment by sienori** [comment]
I changed to open the about:newtab pgae.
https://github.com/sienori/Tab-Session-Manager/commit/375c0ffcf6829b6ff424422f8eb37022cb82a3f5

@gro-gg It is impossible to open a local file because of specification of Web Extensions.
