### ISSUE TITLE
Incorrect URL is restored when fast switching the replaced tab

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#141]
WHen a session is restored the url chanes to moz extension something I noticed tht if I want to make the addon load the page properly ahd switch focus to those tabs sometimes the addon will load an other page so for example lets say i have a google page and a youtube page sometimes it will load 2 google pages or 2 youtube pages duplicated so you have to check the duplicates to see what was the actual webpage.

This happened to me when I was changing tabs quickly after restoring a session.

**Comment by mr-brunes** [comment]
I have noticed this also with some tabs, with no apparent method of recovering the tab.

The URL displayed is something like:
moz-extension://9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html?state=redirect&title=Store%20-%20Midland%20Audio%20Xchange%2C%20West%20Midlands&url=https%3A//www.devialet.com/en-gb/store-retail/midland-audio-xchange_west-midlands&favIconUrl=https%3A//www.devialet.com/media/favicon/default/devialet-favicon-32.png

**Comment by sienori** [comment]
I fixed the problem that the replacement page can not be replaced.
https://github.com/sienori/Tab-Session-Manager/commit/ca58887f225c8152de08aca48974f26962b77cfd

**Comment by rayman89** [comment]
@sienori The issue that I opened was not the same mr-brunes mentioned. The issue I experienced was when trying to make those pages load fast (clicking on one after an other quickly) the mox-extension url would redirect to an incorrect url  so for example if I had tabs 1 2 3 and urls A B C it would make A1 A2 C3 instead of properly loading A1 B2 C3.

**Comment by sienori** [comment]
I recognized the problem and fixed it.
https://github.com/sienori/Tab-Session-Manager/commit/871eb9c5a4b505ac2f81bf93e722be78ff880cd0
