### ISSUE TITLE
Search feature for saved session access.

### ISSUE THREAD

**Issue by JW78** [sienori/Tab-Session-Manager#142]
Would be nice to be able to quickly find a particular saved session by name, even date without scrolling through the list...

**Comment by sienori** [comment]
I will implement a function to search by session name and tab title.

**Comment by JW78** [comment]
Hello,

That would make the add-on more user friendly.

Thank you

On 05/01/2018 11:38, sienori wrote:

I will implement a function to search by session name and tab title.

**Comment by letsprogress** [comment]
The current version (3.1.2) of sienori "Tab Session Manager" add-on has been working quite reliably--but I really need the SEARCH function.

sienori committed to adding this enhancement ("I will implement a function to search by session name and tab title.", https://github.com/sienori/Tab-Session-Manager/issues/142#issuecomment-355511924), but I haven't seen it yet.

**How soon are we likely to get this ESSENTIAL search function enhancement?**

Kudo's to sienori for this indispensable FF quantum add-on!

**Comment by sienori** [comment]
I implemented the search function. https://github.com/sienori/Tab-Session-Manager/commit/56571eda5efad4d84fb646bf191f38423a163cc9
![search](https://user-images.githubusercontent.com/29514424/46585666-79b7a980-caae-11e8-8a4c-70e1dff8fc0c.png)
Thank you for waiting!
