### ISSUE TITLE
replacing old session with new one

### ISSUE THREAD

**Issue by alfredoivan** [sienori/Tab-Session-Manager#149]
Hi.
It would be great if there is an item in the contextual menu, for when you expand a session's menu, which says: replace session with current session

![enh](https://user-images.githubusercontent.com/5880102/34740849-8d324d14-f55f-11e7-8a34-931fced7d97d.png)

Right now, what works is deleting it and creating a new one with the same name.

**Comment by mwld** [comment]
That would be a great feature, indeed!

**Comment by cheebase** [comment]
Add another useful option: replacing the current session (all windows) with another previously saved session (all windows).

![image](https://user-images.githubusercontent.com/36238398/35938909-908cd914-0c18-11e8-8a0c-7dd76bd9b85e.png)

**Comment by mwld** [comment]
@cheebase Think I might not understand. Sounds like "Open in current window". Anyways, it would be great to open a separate feature request for a feature that has nothing in common with the requested "Replace with current session".

**Comment by cheebase** [comment]
Will do...

**Comment by sienori** [comment]
I added the menu item to replace with current session. https://github.com/sienori/Tab-Session-Manager/commit/94f2dfc1f789563a5158bfe450331ed0e15492ac
![replace](https://user-images.githubusercontent.com/29514424/38174082-c859a192-3602-11e8-9d6f-88ffea524fb6.png)

**Comment by alfredoivan** [comment]
again thanks for your great work @sienori
