### ISSUE TITLE
Restoring sessions doesn't work--only opens blank window

### ISSUE THREAD

**Issue by camartinez1229** [sienori/Tab-Session-Manager#15]
I'm using Firefox 56 on Windows 7. Whenever I select a session to try to restore, all I get is a blank window with no tabs. I have to manually click on each listed tab in the list to open everything I need. This is suboptimal behavior. I definitely appreciate your effort in making this extension, especially since the old Session Manager plugin hasn't seen an update yet and has been misbehaving for me lately. However, I hope this issue gets fixed soon. It's not very useful if I can't properly restore my sessions automatically.

**Comment by camartinez1229** [comment]
Looks like restoring sessions does work in Firefox 57. I just started testing the 57 beta today. However, the addon tries to load all the tabs at the same time. Is there a way to adjust it so it loads all the tabs except whichever one is selected first, in a pending state? Dealing with dozens of tabs is otherwise a hassle.

**Comment by sienori** [comment]
In FF56, it is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting.
As for the problem that all tabs are read simultaneously, I can not deal with it because there is no API.

**Comment by sienori** [comment]
It may have been due to a bug.
Improved with Version 1.3.3.
#16

**Comment by camartinez1229** [comment]
Thanks for the replies. I've given 1.3.3 a try in both FF56 and 57, but I've seen no difference. When I try to load a session, all the tabs get loaded. It's impractical when I'm dealing with 50+ tabs, as I usually do. I appreciate your efforts, though. I'm still keeping your addon installed since it does work for me as a fallback when Firefox's native session restore fails me.

**Comment by sienori** [comment]
About lazy loading tabs, see the following issues.
#18

**Comment by grahamperrin** [comment]
> … [turn off "Supports Tree Style Tab(Firefox57++)"](https://github.com/sienori/Tab-Session-Manager/issues/15#issuecomment-338489029) …

Thanks, I tried that. 

From this morning's [post 32](https://discourse.mozilla.org/t/-/13310/32?u=grahamperrin) under _Concern about WebExtensions exclusive strategy from add-on authors and users - Mozillians - Mozilla Discourse_: 

> (for me) repeatedly, consistently, fails to restore anything with Firefox 56.0.2.

More specifically, I have exactly what's described in the title here: 

> ## … only opens blank window

@sienori would you like to reopen this issue? 

Or prefer a new issue for a different bug with the same symptom?

Please advise – thanks. 

(I'm in no rush; prepared to continue with 56.x until maybe August 2018.)

**Comment by sienori** [comment]
Sorry, I misread it.
I will reopen this issue.

**Comment by grahamperrin** [comment]
Thanks. 

An early thought. My sessions are large – at the time of writing: 1,405 tabs (no more than forty-six loaded) – so I read this issue #15 alongside a more recent issue: 

- [Not all tabs opened when restoring a large session · Issue #22 · sienori/Tab-Session-Manager](
https://github.com/sienori/Tab-Session-Manager/issues/22)

**Comment by grahamperrin** [comment]
Reproducing symptoms of the issue: 

- https://www.youtube.com/watch?v=x2njDHYQzbc (unlisted)
- Tab Session Manager 1.5.0
- Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT
- session data imported from a Session Manager file.

**Comment by grahamperrin** [comment]
https://youtu.be/sQMGKq8EVp0 (unlisted), at 03:15 on the timeline I disabled [QuoteTab](https://addons.mozilla.org/addon/dayquote/), also known as _New Tab with Quotes_, which seemed to work around the issue. 

Defocusing from QuoteTab: I wonder whether this issue will be reproducible with some other types of extension that modify new tab behaviours. 

----

Parts of that long screen recording relate to another Tab Session Manager issue.

**Comment by grahamperrin** [comment]
>  … [no tabs are restored. The "Open" link apparently does nothing. I am using Firefox 57 on Fedora 27, with the Tab Session Manager version 1.5.0. Is this a separate issue?](https://github.com/sienori/Tab-Session-Manager/issues/22#issuecomment-346015671) 

Probably separate; probably this issue #15. 

> How can I collect information to help debug this?

@laggarcia please: 

1. visit `about:support`
2. Copy raw data to clipboard
3. visit https://pastebin.mozilla.org/
4. paste the data, allow retention for maybe one month
5. let us have the link to the pasted data. 

Thanks

**Comment by laggarcia** [comment]
@grahamperrin, I was able to work around my issue after reading this and related issues opened here. My problem was that one of my tabs was about:sessionrestore. After handly modifying the storage.js file and substituting about:sessionrestore to a valid URL I was able to restore all my tabs (with the exception of the about:sessionrestore one, of course). Thanks for pointing me to these other issues.

**Comment by sienori** [comment]
@grahamperrin @laggarcia 
Thank you for the report.
Processing stops on about:xxx or moz-extension://xxx is a known problem.
I will fix it soon by replacing the page.
#6

**Comment by sienori** [comment]
I added a function to replace a page that can not be restored. 789c4d4
#16

**Comment by Sopheus** [comment]
sdfsfsdf
