### ISSUE TITLE
if page url begins with moz-extension://, it should not be replaced for lazy loading

### ISSUE THREAD

**Issue by bin-y** [sienori/Tab-Session-Manager#154]
some tab group extension and this extension it self do this for lazy loading, but if session is saved when a lazy loading page is not loaded, that page will be replaced again and again, and I have to trigger onfocus many times to load correct page.

**Comment by sienori** [comment]
Could you please tell me in detail what kind of problems will happen?
When saving a lazy loading page that is not loaded, that URL will be treated as the original URL.
It is not replaced again and again.
https://github.com/sienori/Tab-Session-Manager/blob/337be7b74ae142d5ca3dd83f442ab30ca2ce7634/Tab-Session-Manager/background.js#L262-L265

If you use Tab Suspender, there is a problem that original URL are not restored.
https://github.com/sienori/Tab-Session-Manager/issues/132
But I think that this is a Tab Suspender's problem.

**Comment by bin-y** [comment]
This issue is similar to #132 , but it happens with Simple Tab Groups extension, which is doing lazy loading too.
I think this is a problem on both side, maybe both of you should consider the 'moz-extension' idea , that will solve the problem.
@sienori  @Drive4ik

**Comment by sienori** [comment]
I made it impossible to access the lazy loading page from the back button. It work in FF 57 or later. https://github.com/sienori/Tab-Session-Manager/commit/03b7c874b57a45874b36c3ba753ece16a9045f1a
This change solved the problem of Tab Suspender.

**Comment by Drive4ik** [comment]
I fix create lazy load tabs with "moz-extension" urls
https://github.com/Drive4ik/simple-tab-groups/issues/113
