### ISSUE TITLE
Similar WebExtensions

### ISSUE THREAD

**Issue by davidhedlund** [sienori/Tab-Session-Manager#155]
These add-ons can be used if Tab Session Manager temporary breaks:
* [MySessions](https://addons.mozilla.org/en-US/firefox/addon/my-sessions/)
* [SaveTabs](https://addons.mozilla.org/en-US/firefox/addon/savetabs/)
* [Tab Saver](https://addons.mozilla.org/en-US/firefox/addon/vyrtsev-tab-saver/)
* [Tab Sessions](https://addons.mozilla.org/en-US/firefox/addon/tab-sessions/)
* [Tab manager](https://addons.mozilla.org/en-US/firefox/addon/tab_manager/)

Perhaps it's worth mention that somewhere else too?

**Comment by ranran1** [comment]
Thanks for the headsup while sienori continues his hard work on Tab Session Manager.  Which of these seem to work the best with FF58+ and TreeStyle Tab?

**Comment by Myer** [comment]
There's also this one: [MySessions](https://addons.mozilla.org/en-US/firefox/addon/my-sessions/)

**Comment by ranran1** [comment]
Thanks for the alternative.  I've now upgraded to FF58 and been using sienori's Tab Manager for over a week now, and apart from one time where the session wouldn't load (which I think was due to TreeStyle Tab), it has been working flawlessly for me.  So, I am good with this! :)

**Comment by davidhedlund** [comment]
@Myer 
> There's also this one: MySessions
Added to the list. Thanks.

**Comment by RobertAb1** [comment]
https://www.reddit.com/r/firefox/comments/7t6hmx/extensions_in_firefox_59/dvxabix/

**Comment by davidhedlund** [comment]
Ok, I think we have enough WebExtensions at this point. People will find this issue when the search for issues with the word "Similar". Thank all of you.
