### ISSUE TITLE
[Feature] Allow turning off Delete confirmation

### ISSUE THREAD

**Issue by squigglezworth** [sienori/Tab-Session-Manager#156]
I often have to remove a bunch of automatically saved sessions at a time, with no need to be confirmed every time. It'd be great to have a setting to toggle that confirmation

**Comment by sienori** [comment]
I changed the behavior when deleting a session. https://github.com/sienori/Tab-Session-Manager/commit/672c59c719128527e31cfb3136f2411eaf69a424

When you click the Delete button, the session will be deleted and "This session has been deleted" is displayed.
If you want to cancel the deletion, click the Restore button.

![restore](https://user-images.githubusercontent.com/29514424/38176098-82c1c8f0-3623-11e8-864f-452f431c6209.png)

**Comment by squigglezworth** [comment]
:+1: 
Thank you very much.
