### ISSUE TITLE
Wrong parsing of Session Manager's .session file

### ISSUE THREAD

**Issue by aaaxx** [sienori/Tab-Session-Manager#158]
This is a pretty significant issue.

You seem to be importing tab URLs only from the first object of every `"entries"` array.

The problem is that an `"entries"` array holds the entire history stack of a tab, and the `"index"` key then tells you which of the objects under `"entries"` holds the `"url"` of the last viewed page (numbering starts at 1, not 0). The objects before that one are the Back Button history, and the objects after are the Forward Button history.

So practically all tabs end up showing the wrong page right now.

Here's an example:

```json
"tabs": [
  {
    "entries": [
      {
        "url": "https://clicking-back-button-2x-takes-you-here",
        "..."
      },
      {
        "url": "https://clicking-back-button-1x-takes-you-here",
        "..."
      },
      {
        "url": "https://page-being-viewed-when-session-was-saved",  // 3rd object from beginning
        "..."
      },
      {
        "url": "https://clicking-forward-button-1x-takes-you-here",
        "..."
      },
      {
        "url": "https://clicking-forward-button-2x-takes-you-here",
        "..."
      }
    ],
    "..."
    "index": 3,  // position of the object with last active url; counting starts at 1, not 0
    "..."
  }
]
```

**Comment by sienori** [comment]
I fix it.
Thanks for your advise.
https://github.com/sienori/Tab-Session-Manager/commit/ca8c6432563652c96c15335c967c7b36f0c6a473

**Comment by 1RonRock** [comment]
That's great! Will there soon be an update that I can download to fix this? You guys are way over my knowledge level. But I am having this issue.

**Comment by sienori** [comment]
@1RonRock I am planning to update within a few days.

**Comment by 1RonRock** [comment]
Very good. I did not mean to be rude, I very much like TSM. Thank you.
