### ISSUE TITLE
Compatibility with Reader View (about:reader?url=)

### ISSUE THREAD

**Issue by hdf** [sienori/Tab-Session-Manager#159]
Currently it does not load pages that were in Reader View when the session was saved. Extracting the original URL is also difficult, as it was encoded. I'm guessing the problem is multiple layers of URL encoding maybe?

**Comment by hdf** [comment]
After digging in to it a bit, turns out, it's a security thing. `about:reader` is a privileged URL because [it may not be prepared to handle arbitrary user input](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456#c17), so we need to detect if the URL contains `about:reader`, and than use `openInReaderMode` setting in [`browser.tabs.create`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) when redirecting (after removing the `about:reader?url=` part from the URL).

**Comment by hdf** [comment]
Unfortunately you can't open an extension page in Reader View, and `browser.tabs.update` does not have an `openInReaderMode` property, so best we can do is load the original page, and the user will have to go to Reader View manually. Which is still an improvement over no functional page loading at all.

**Comment by hdf** [comment]
Turns out, my original suspicion was correct as well. There was one extra layer of encoding, but `about:reader?url=` needed to be stripped as well. (Also, seems modifying `property.url` is a bad idea.)

**Comment by sienori** [comment]
Thanks.
Based on your pull request, I improved to open tab in leader view.
https://github.com/sienori/Tab-Session-Manager/commit/74895944ec6e375f9258c6c78eb6d5a7bdc3d2bd
https://github.com/sienori/Tab-Session-Manager/commit/d9afd101071e94185dc46e8c33590b87cff55120

**Comment by hdf** [comment]
Thanks, works wonderfully! My approach was to just fix my particular usage scenario with minimal code changes, have not even considered other configuration paths. :P
You even got it to switch to reader mode after the page is loaded. :) (I haven't noticed the existence of `browser.tabs.toggleReaderMode`. :P )
