### ISSUE TITLE
Not all windows are restored

### ISSUE THREAD

**Issue by hirvinen** [sienori/Tab-Session-Manager#16]
I had a session with two windows containing 168 tabs. Opening restores only one of them. I tried several prior saves as well, and all of the ones I have tried only open one of the windows. Using 1.3.2 on Fx Quantum 57.0b10 (64-bit) on Windows.

Then I tried to restore one of those sessions after one window was restored. That resulted in the same window being opened again. Apparently something else went wrong as well, because after that, any attempt to restore one of those sessions resulted in Fx relatively quickly hogging memory until I ran out of it.

Is there a way to export those session saves so that I could manually try to save those tabs?

**Comment by hirvinen** [comment]
Also, is there a way to mark those sessions as being user saved so that they won't be overwritten due to limit of autosaved session count?

**Comment by sienori** [comment]
I solved the problem that multiple windows did not open.
Include in ver1.3.3.
Thank you for reporting.

To save the session manually, please copy the following file.
[profile folder]\browser-extension-data\Tab-Session-Manager@sienori\storage.js
(you can open profile folder from about:support)

I will add the function to mark the automatically saved session as a user.

**Comment by grahamperrin** [comment]
@hirvinen also please consider: 

- [Not all tabs opened when restoring a large session · Issue #22 · sienori/Tab-Session-Manager](https://github.com/sienori/Tab-Session-Manager/issues/22)

**Comment by hirvinen** [comment]
Hi!

Failed to restore window number two just now. However, I have a hypothesis about the cause, which I wanted to share, even though I don't have time to test it right now. The first tab in that second window was about:memory, and I noticed that I can't open it from the "session preview" link, unlike other tabs. Maybe the restoration process chokes on that, which is why none of the second windows tabs were opened for me, only a blank second window?

@grahamperrin : Did your session restore fail at a point where there was a window with a special url?

**Comment by laggarcia** [comment]
I had the same issue that @hirvinen is describing above, but with about:sessionrestore tab. As my first tab was about:sessionrestore, no tabs were being restored from my saved session. After I modified about:sessionrestore to a valid URL in the storage.js file I was able to restore my session (with the exception of the about:sessionrestore tab, of course).

**Comment by sienori** [comment]
I added a function to replace a page that can not be restored. 789c4d4
Thank you for the report.

**Comment by sienori** [comment]
Also, I implemented lazy loading.
This greatly reduces memory usage.
https://github.com/sienori/Tab-Session-Manager/commit/501461d4ffd69fec7320b8c2da815f99970aa9b1
