### ISSUE TITLE
super slow startup

### ISSUE THREAD

**Issue by GianniGi** [sienori/Tab-Session-Manager#161]
I have about 200 tabs open, if I select the firefox option 
> "load tabs from last time"

the startup has no delay, it is as fast as an empty session, but when I select the option to load the tabs from last time in the addon options

 > Restore previous session at startup
 > When Firefox starts up, restore the session that was closed the last time.

it's very slow, and takes over a minute, when it doesn't crash.

firefox 58.01 on ubuntu 17.10

**Comment by kevinkk525** [comment]
That happens even if I use the "Restore last session" from Firefox itself. With 8 Windows and 375 tabs restoring the last session is only randomly working. The RAM usage rises until 100%, then firefox crashes. Restoring without Tab-Session-Manager is done within seconds without any noticeable spike in RAM usage.
With a few less tabs, restoring the last session works reliably but also has the high RAM rise (but falls back to "normal" after everything is loaded correctly) but it takes over a minute to do so.

Firefox 58.0.2 on Windows 10

**Comment by sienori** [comment]
I plan to add an option to speed up tab opening. #52

**Comment by GianniGi** [comment]
wonderful, thanks

**Comment by Adamfmc** [comment]
I don't know if the issue in this thread is related, but the bug I originally posted about here:

[](https://github.com/sienori/Tab-Session-Manager/issues/101)

appears to have been reintroduced.  I have around 879 tabs open, and I am once again having to disable Tab Session Manager before I use Firefox's Restore Previous Session option, or it will freeze.

**Comment by sienori** [comment]
In [ver 3.2.0](https://github.com/sienori/Tab-Session-Manager/releases/tag/3.2.0), I speeded up session restoration!
When the TST support option is disabled, all tabs open at once.
Also, multiple windows are restored simultaneously.
