### ISSUE TITLE
Tabs with moz-extension don't reload

### ISSUE THREAD

**Issue by Verequus** [sienori/Tab-Session-Manager#162]
If I reload the tab before the normal reload after adding the focus happens, I end up with the moz-extension URL, but no longer can reload the page to return to the actual URL. This also happens if I bookmark the unloaded tabs. I can't trigger a manual reload of the original page. If I'm lucky I can actually copy the original URL, but it would be better if I could click on the text like a real link.

**Comment by hdf** [comment]
If you switch to a different tab, than back, than it will work as it should.

**Comment by Verequus** [comment]
That works only for the non-bookmarked ones.

**Comment by hdf** [comment]
Even if I bookmark the moz-extension: URL, it still works the same way. Switch away to a different tab, than back, that will start the page reload, and will redirect to the actual page.

Relevant bit:
https://github.com/sienori/Tab-Session-Manager/blob/b4fa436a14ca0779649292a79a284072f23c1a98/Tab-Session-Manager/background/replace.js#L44-L56

**Comment by Verequus** [comment]
For whatever reason, it doesn't work like that for me here in this instance.

**Comment by Verequus** [comment]
A general remark on spelling: It's "parameter". I know that the misspelling is tempting, but 'a' and 'e' have parity.

**Comment by sienori** [comment]
If you have bookmarked `moz-extension:` page in the past, it may be that the add-on ID has changed.
Please open the delayed loading page again and compare it with the URL of the bookmarked page.
If the character string in **bold** has changed, this add-on can not deal with it.
moz-extension://**54bd5c9c-8031-4410-84dd-da9e0348a\*\*\***/replaced/replaced.html?...

Also, I am ashamed of misspelling...
I added a spelling checker extension to my editor :p

**Comment by Verequus** [comment]
The addon id is indeed different. Since this could happen again, the solution is change the URL even for delayed loading, even if the page isn't actually loaded. Not sure if there is a flag which says "This tab hasn't been loaded yet". Also, is there any solution to deal with this? Would exporting the bookmarks as file and manually replacing the addon id with the current value work, when you reimport the bookmarks?

**Comment by sienori** [comment]
If you replace url to the current correct add-on ID, it should work normally.
Also, the URL of the original page is included in the URL parameter.
```
moz-extension://54bd5c9c-8031-4410-84dd-da9e0348a***/replaced/replaced.html
?state=redirect
&title=Google
&url=https%3A//www.google.co.jp/
&favIconUrl=https%3A//www.google.co.jp/images/branding/product/ico/googleg_lodp.ico
```

I suggest you not to bookmark this page.
There is a possibility that it can not be used due to future specification change.

**Comment by Verequus** [comment]
I didn't intend to bookmark the page like that. I opened a session with lazy loading and bookmarked my windows as backup. I didn't notice that the tabs would have to be reloaded completely at first. So saying "Don't bookmark it like this." is true, but not overly helpful, because the trap is still there.

**Comment by sienori** [comment]
It will be difficult to change the URL only when bookmarking a replace page.
Thanks for your understanding.
