### ISSUE TITLE
Please stop randomly open your options/options.html#information tab, thanks!

### ISSUE THREAD

**Issue by COLABORATI** [sienori/Tab-Session-Manager#165]
Much too often I see that 
moz-extension://5975e788-8926-4c68-bd34-38430d85952b/options/options.html#information
opening, that is annoying. Please give only information when user asked for it, thanks.

**Comment by rnc** [comment]
I actually quite like it in that it is a good indication the addon has been updated and it could display what changed ..... although I would like a direct link to the appropriate changelog.

**Comment by sienori** [comment]
I changed it so as not to display it when updating the browser.
https://github.com/sienori/Tab-Session-Manager/blob/22d3f06bb1503b9ce4c4b664bd240d8b0c206c62/Tab-Session-Manager/background/background.js#L32-L33

Also I added a link for version information.
![default](https://user-images.githubusercontent.com/29514424/37569069-8afc87a2-2b20-11e8-935a-8872b8a604cc.PNG)

**Comment by decadent** [comment]
@hdf Could the extension initialize the database lazily when it's first used? At the very least, it could confidently use the default settings until they are overridden manually, and store these defaults in the background script.

I like the extension but I don't quite feel the need to know about its updates every time.

**Comment by hdf** [comment]
So that the options page doesn't get loaded at all would be problematic, but maybe it could close itself if it was called with the updated parameter? Maybe this behavior could depend on a setting? The relevant bit is here:
https://github.com/sienori/Tab-Session-Manager/blob/d23c63d48b122c0ec2502dfd836cdd89f6544483/Tab-Session-Manager/options/ui.js#L104

**Comment by decadent** [comment]
> So that the options page doesn't get loaded at all would be problematic

Why is that?

**Comment by sienori** [comment]
I added that option. ecdbc71
