### ISSUE TITLE
FF58 + TSM 2.0 -> Import Function broken.

### ISSUE THREAD

**Issue by ranran1** [sienori/Tab-Session-Manager#167]
System: Windows 10 / Portable FF58  with 3 extensions (Adblock, TSM 2.0, Tree Style Tabs).

Last week I manually copy-pasted ~40 tabs into FF58.  I then used the 'Export' function in TSM to export a .json session file.  Today, I opened FF58, no tabs.  I attempted to open the saved .json file (~1.1Kb in size) and TSM states, "Session Imported"  However, *no* tabs load.

Just now, I opened 3 tabs and then exported the session.  I closed the tabs, then attempted to import the session.  TSM thinks there are 24 tabs in the session and fails to load!!!

Where does TSM store it's session data when FF closes?

**Comment by sienori** [comment]
The import function ignores duplicate sessions.
That is, if the same session as the imported session already exists, that session will be ignored.

Please make sure whether the session is imported correctly in this way:
1. Export session A from session list menu
2. Delete session A
3. Import session A

**Comment by ranran1** [comment]
Nope, nothing imports.  Attached is a 1 tab session file (Google.com).  It won't import.

[Tab Session Manager - 2018-02-05 09-47-05.zip](https://github.com/sienori/Tab-Session-Manager/files/1695565/Tab.Session.Manager.-.2018-02-05.09-47-05.zip)

**Comment by sienori** [comment]
How did you export this session?
Internal tags in this session are "winClose" and "temp".
Sessions tagged with temp are hidden.
This is used when autosave at window was closed is enabled.
The temp tagged session is saved every time the tab is updated.
When the window is closed, the temp tag is removed and appears in the session list.

Therefore, users do not need to see temp tagged sessions or import them.
If you really want to import this session, open it with a text editor and delete the temp tag.

**Comment by ranran1** [comment]
Thanks for responding. 
Steps I took:
1. Open FF58
2. type 'google.com' in the address bar
3. Go to Tools ->Addons -> TSM -> Options -> Sessions -> Export -> Save
4. Make sure 'Restore' upon FF start is not checked.
5. Close FF58.
7. Go to Tools ->Addons -> TSM -> Options -> Sessions -> Import-> Load Session
8. Receive 'Session Loaded' message, but no tab loaded.

Is this the wrong way to save sessions?

**Comment by sienori** [comment]
Do you notice the add-on button on the toolbar?
If the add-on button is not displayed, it can be displayed from the customization of the Firefox menu.
![1](https://user-images.githubusercontent.com/29514424/35813735-b1c54b58-0ad7-11e8-9fca-8eaf7e13e04f.png)

**Comment by ranran1** [comment]
No, I didn't notice the icons.  Where are those sessions stored?  How can I open up a session that I exported as described earlier to my desktop?  Can I copy the exported session to a folder that TSM would find?
