### ISSUE TITLE
Missing dates

### ISSUE THREAD

**Issue by cheebase** [sienori/Tab-Session-Manager#169]
When a wider width is selected the popup box is enlarged to the right and off the browser. It is now invisible. Could it span the other direction so control items remain visible?
Also, in the previous incarnation, it was possible to restore individual windows as opposed to the entire session. Can we have this feature?
The latest version seem to drop the first window in favour of the last open window (this appears twice now). This needs to be fixed...
Thanks!

**Comment by sienori** [comment]
>The latest version seem to drop the first window in favour of the last open window (this appears twice now). This needs to be fixed...

I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/a7fcb44bba1b0b9949d4fdf4d87063ea374472fe

**Comment by sienori** [comment]
>Also, in the previous incarnation, it was possible to restore individual windows as opposed to the entire session. Can we have this feature?

If there is new information on this function, I will report on https://github.com/sienori/Tab-Session-Manager/issues/55.
