### ISSUE TITLE
Tree style tab tree state not preserved

### ISSUE THREAD

**Issue by hirvinen** [sienori/Tab-Session-Manager#17]
Restoring session does not, at least reliably, preserve tree style tab tree state. Using 1.3.2 on Fx Quantum 57.0b10 (64-bit) on Windows.

**Comment by sienori** [comment]
If you replaced the parent-child relationship of tabs, It is impossible to restore completely.
This is due to the specification of TST.
#7 
https://github.com/piroor/treestyletab/issues/1475

**Comment by sienori** [comment]
However, stability little improved in version 1.3.3.

**Comment by irvinm** [comment]
Try disabling the "auto-group tabs opened within" feature in TST and see if that solves your problem.

My session restores are very consistent now.  (See my issue:  https://github.com/sienori/Tab-Session-Manager/issues/20)

**Comment by sienori** [comment]
I fixed the problem that could not be restored in some cases.
https://github.com/sienori/Tab-Session-Manager/commit/fecc84996188b552b92b00683c3ebbb9873a0f76
