### ISSUE TITLE
On replacing current session with a previously saved session

### ISSUE THREAD

**Issue by cheebase** [sienori/Tab-Session-Manager#170]
Today I noticed that one of the previously open 14 windows did not load at all after reboot and firefox launch. Noting that single window of a session containing many windows can not be selected from a saved session, I figured, by opening a (or any) previous session will replace the entire currently loaded session. Not so. It appended the 13 window current session with the 14 window previously saved session, resulting in 27 windows.
The contextual menu lists several options, neither seems to indicate swapping entire sessions cleanly.
Therefore, may I suggest an additional menu item dealing with entire sessions to complement the existing line-up: 
![image](https://user-images.githubusercontent.com/36238398/35944581-f07bc120-0c2a-11e8-891f-3ae3f7719588.png)

Of course, in the ideal world, any window from any session could be individually opened to form a new session or appended to the current session...

**Comment by sienori** [comment]
Such behavior is possible with "Open in current window".
In version 2.0.0, there was a bug that "Open in current window" does not work properly. 
Therefore, I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/a7fcb44bba1b0b9949d4fdf4d87063ea374472fe
