### ISSUE TITLE
large memory leak

### ISSUE THREAD

**Issue by ertyz** [sienori/Tab-Session-Manager#171]
TSM v2.0
Mozilla Firefox 58.0.2 (64-bit)
Windows 10 x64 v1709

On new tab open TSM start to eat memory.

Firefox without TSM 1 empty tab (334 MB): https://goo.gl/9QeHzm
Firefox without TSM 5 empty tabs (361 MB): https://goo.gl/hGGzAX
Firefox with TSM 1 empty tab (481 MB): https://goo.gl/EcEaH7
Firefox with TSM 5 empty tabs (935 MB): https://goo.gl/KcD3oS
Firefox with TSM 11 empty tabs (**1820** MB): https://goo.gl/pMxNE7

And when I just open new empty tabs browser lagged and use 10-25% cpu resources.
After I done "Minimize memory usage" procedure from "about:memory", memory usage return to normal (10 tabs = 382 MB): https://goo.gl/sMBi4W

here is memory dumps before and after memory clean: https://goo.gl/S48hCz
memory diff screenshot: https://goo.gl/vMMCuZ

**Comment by hdf** [comment]
I don't seem to be able to reproduce this. Perhaps interference from a different extension? Does the problem persist, if you disable all other extensions?
Also your "empty tab" page is a bit strange, why no Firefox logo in the top left corner, and Options button in the top right?

**Comment by ertyz** [comment]
> I don't seem to be able to reproduce this. Perhaps interference from a different extension? Does the problem persist, if you disable all other extensions?

Ok. I'll try. Just the show up only when TSM enabled, and not show when disabled.

> Also your "empty tab" page is a bit strange, why no Firefox logo in the top left corner, and Options button in the top right?

about:blank is my "new page". It is save my memory from 50 MB per 'empty' tab to 5 MB.

**Comment by sienori** [comment]
I tested it with a new profile that installed TSM only.
I don't seem to be able to reproduce this.

TSM v2.0
Mozilla Firefox 58.0.2 (64-bit)
 Windows 10 x64 v1709

without TSM 1 empty tab(188MB) https://i.imgur.com/jXW1qyC.png
without TSM 10 empty tabs(336MB) https://i.imgur.com/QN08rob.png
without TSM 30 empty tabs(550MB) https://i.imgur.com/8aGpSUo.png

with TSM 1 empty tab(192MB ) https://i.imgur.com/sccMNdN.png
with TSM 10 empty tabs(363MB) https://i.imgur.com/AC2OZNI.png
with TSM 30 empty tabs(697MB) https://i.imgur.com/93GUfZe.png

**Comment by sienori** [comment]
It seems to happen when there are a lot of sessions and automatic saving(when window was closed) is enabled.
I will consider whether it can reduce the load of automatic saving.
Thanks.

**Comment by yashchandak** [comment]
similar issue faced. I had around 80 tabs in the last session and auto-save feature was enabled. Everytime I used to start firefox, it took up entire 8GB of my Ram and froze the system. Simple work-around was to 1. start firefox in safe mode, 2. export the last session, 3. Delete all sessions, 4. Import the saved session.
Thanks for the useful add-on. Hope the bug gets fixed soon :)

**Comment by sienori** [comment]
Tab Session Manager saves sessions in [storage system](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage).
However, this storage system is not suitable for storing large amounts of data.
The problem of increasing memory usage is caused by the storage system.

In order to solve this problem, I will implement it using IndexedDB in the future.
(IndexedDB is a system suitable for storing large amounts of data)

**Comment by hethhhhh** [comment]
same problem here. solved after deleting storage.js (lost all sessions of course..)

**Comment by sienori** [comment]
Replacement with IndexedDB is complete! https://github.com/sienori/Tab-Session-Manager/commit/22d3f06bb1503b9ce4c4b664bd240d8b0c206c62
Memory usage will be greatly improved.
