### ISSUE TITLE
Import a link list

### ISSUE THREAD

**Issue by aaaxx** [sienori/Tab-Session-Manager#172]
Could you add support for pasting a simple list of links to import, optionally with page titles? It would make things easier for testing purposes and when importing tabs from a non-Firefox browser, because there are plenty of add-ons for every browser that can copy the list of open tabs.

I think a space character could be used as the separator between the url and title (tab character should probably also work).

For example:

![import link list mockup](https://user-images.githubusercontent.com/6186480/36035713-01a9ec2c-0db8-11e8-9f31-2c0f1e6b2c9d.png)

**Comment by sienori** [comment]
Please tell me examples of addons that can be output in this format.

**Comment by aaaxx** [comment]
Firefox:

- [Copy All Tabs](https://addons.mozilla.org/en-GB/firefox/addon/copy-all-tabs/)
- [URLs List](https://addons.mozilla.org/en-GB/firefox/addon/urls-list/)
- [tabs2txt](https://addons.mozilla.org/en-US/firefox/addon/tabs2txt/)

Chrome:

- [tabs2txt](https://chrome.google.com/webstore/detail/tabs2txt/jaobckfgmoejmffgmlllfohadijkicgf)
- [Bulk URL Opener](https://chrome.google.com/webstore/detail/bulk-url-opener/kgnfciolbjojfdbbelbdbhhocjmhenep)
- [Save my Tabs](https://chrome.google.com/webstore/detail/save-my-tabs/djadfifncobffjpicnkiegahdiobpaap)
- [Tab-Snap](https://chrome.google.com/webstore/detail/tab-snap/ajjloplcjllkammemhenacfjcccockde)

**Comment by sienori** [comment]
Thanks.
I added the function Import URL list. https://github.com/sienori/Tab-Session-Manager/commit/fd93fad2b9590dac2b1117d9273bee7cb8ea3846
