### ISSUE TITLE
[feature suggestion] schedule export

### ISSUE THREAD

**Issue by joubertredrat** [sienori/Tab-Session-Manager#173]
Hi guys,
Yesterday I lost all my profile data after fucking Firefox corrupt my data and force upgrade (I disabled all upgrade options)
I was very angry about this because I lost my tabs with my research.

Anyway, I accepted that I lost everything, I updated Firefox and I installed this plugin in place of the session manager and I liked a lot.

But I'm afraid if firefox fuck me again corrupting my profile data and I don't want to lose my open tabs again.

I saw that this plugin have option to export tabs, I liked a lot, export to json and I was happy. But I think that can be even better if you can schedule to export automatic to outside profile data folder.

What you think guys? Thanks

**Comment by sienori** [comment]
I just implemented that feature yesterday.
Save the backup when Firefox starts up to Firefox download folder.
You can also set the upper limit of the backup file.
https://github.com/sienori/Tab-Session-Manager/commit/96e76b0d8c79ed0fe08af974e03fcdf0a72bfcfa
