### ISSUE TITLE
Empty list and Save backup

### ISSUE THREAD

**Issue by rddim** [sienori/Tab-Session-Manager#177]
When the session list is empty and `Save backup` option is enabled it create a file name `0Sessions - 2018-02-11 16-32-00.json` which contain only `[]` in it.

**Comment by sienori** [comment]
I changed not to create a backup when the session list is empty.
https://github.com/sienori/Tab-Session-Manager/commit/6e74ccd5b64e6d0fb24b10e342d8bd8e817b6a6a
