### ISSUE TITLE
[Feature] Custom filename format for Backup files

### ISSUE THREAD

**Issue by rddim** [sienori/Tab-Session-Manager#178]
Could you add please option for custom filenames for backuped files. At now they are `1Sessions - 2018-02-11 16-35-23.json` and the leading part is the number of session. But for example I have:
```
1Sessions - 2018-02-11 16-35-23.json
2Sessions - 2018-02-11 16-36-38.json
3Sessions - 2018-02-11 16-38-01.json
10Sessions - 2018-02-11 16-23-38.json
```
As you can see the 1,2, and 3 sessions files are created **after** the 10 sessions file. I would like to use the date and time as leading part. Something similar like the `Date format` will be good, but with option to add string for the number of sessions of course.

**P.S.** `1Sessions - 2018-02-11 16-35-23.json` could be `1 Sessions - 2018-02-11 16-35-23.json` (add white space) and in some languages with lower letter `s` > `1 sessions - 2018-02-11 16-35-23.json`

**Comment by hdf** [comment]
If I may interject. I don't think, having the file name lead with the date is a good idea. Currently you can sort by how many sessions are in the file, or just sort by file date. But if you put the date first, than you can only sort by date.

I do think, that a seconds based resolution is however slightly naive. True, it's an edge case, but it is probably not impossible for two backups to try to have the same name. I would also add a CRC32 hash of the file contents to the file name.

A space between the number and the word Sessions would however probably be nice.

**Comment by sienori** [comment]
I changed the name of backup file. https://github.com/sienori/Tab-Session-Manager/commit/af496335492dcf8fe94c0ddcb500c4db2501f0c2
```
2018-02-12 17-59-18 (1 session).json
2018-02-12 17-59-28 (2 sessions).json
2018-02-12 17-59-40 (3 sessions).json
2018-02-12 17-59-40 (3 sessions)(1).json
```

@hdf Even if you save it in the same second, the file will not be overwritten because of the following option.
https://github.com/sienori/Tab-Session-Manager/blob/af496335492dcf8fe94c0ddcb500c4db2501f0c2/Tab-Session-Manager/background/import.js#L51
