### ISSUE TITLE
Pinned tabs, perhaps 'normal' tabs are re-ordered when I start up

### ISSUE THREAD

**Issue by ultrablue** [sienori/Tab-Session-Manager#179]
Hi:

When I start FF, my previous session is restored. However, the order of tabs has changed. I see this happening for sure with pinned tabs, and it appears to be happening with normal tabs, as well.

Do you have any insight on what's causing this or how to prevent it?

Thank you!
Greg

**Comment by sienori** [comment]
It is not reproduced in the new profile where TSM only is installed.
Is not it due to other add-ons or settings?

**Comment by ultrablue** [comment]
Hi:

A dang. I thought I had only one tab-related extension, but it turns out that I have another installed (Tab Open/Close Control 0.0.3). I should have checked before I created an Issue, sorry about that.

I've emailed the developer of that extension as well as removed it, which seems to have fixed the problem.

Thanks for your time!
Greg
