### ISSUE TITLE
Thanks - donated!

### ISSUE THREAD

**Issue by ranran1** [sienori/Tab-Session-Manager#180]
Hi Sienori,

Just wanted to thank you again for all your work on this add-in.  It's working well for me, so I put my money where my mouth is.  Wasn't sure where else to send a note to say thank you, so I apologize if this is totally the wrong place!

Well done, and keep up the good work - we all appreciate it!

-Ran

**Comment by sienori** [comment]
Thank you very much!
I will keep doing my best ;)
