### ISSUE TITLE
Overwrite/Update existing session

### ISSUE THREAD

**Issue by mirkogrcic** [sienori/Tab-Session-Manager#184]
Hello, It would be great to be able to overwrite/update an existing session so there wont be a need to delete the old session after saving the new one with the same name.

**Comment by mirkogrcic** [comment]
I see that you have added an option to "Replace with current session", the problem with it for me is that it saves all windows, maybe you can add a menu option below it for "Replace with current window"?

**Comment by mrwensveen** [comment]
I extensively (indeed, exclusively) use the "Save only current windows" feature. I always have 1 window with miscellaneous stuff (slashdot, news and whatnot) and 1 window for the project I work on, which are saved as sessions. That way I can switch projects easily. However, when updating (replacing) the session for the project I'm working on I need to delete the window with the misc. stuff from the session every time.

A "Replace with current window" feature would be super useful for this kind of workflow.

**Comment by sienori** [comment]
Thanks to the wonderful work of @mrwensveen, I added "Replace with current window" option! 877cb5de18874af9aac2cba4200635e96475012f

**Comment by mirkogrcic** [comment]
Thank you @mrwensveen
