### ISSUE TITLE
Session details not shown - Authentication to apps.collabera.com required

### ISSUE THREAD

**Issue by allentiak** [sienori/Tab-Session-Manager#185]
When I click on a saved session details, I get an Alert box with the following text:

"Authentication required
http://apps.collabera.com is requesting your username and password. WARNING: Your password will not be sent to the website you are currently visiting!"

How to reproduce:
- Click on the Tab Session Manager icon
- Click on the lower part of each session (where there is the number of windows and tabs involved).
- The Alert box will appear.

**Comment by Verequus** [comment]
I tried to reproduce but it doesn't happen for me. Do you maybe have a tab which accesses http://apps.collabera.com?

**Comment by allentiak** [comment]
No, I don't have any need to connect to that server.
I have just tried opening a saved session again, having only one open tab,
with gmail.

Same result: as soon as I click on the session details to see which windows
and tabs contains, I get the alert box...

Maybe is it that some of my other extensions conflicts with this one?

Here's the list:
- Disconnect
- Firefox Lightbeam
- Firefox Multi-Account Containers
- GNOME Shell intergration
- Mailvelope
- NoScript
- Sasa Key
- Tab Session Manager
-  uBlock Origin

**Comment by sienori** [comment]
It could not be reproduced.
