### ISSUE TITLE
Restoring tabs stops when a local page is encountered

### ISSUE THREAD

**Issue by stephanmahieu** [sienori/Tab-Session-Manager#186]
When during restoring tabs a bookmark is encountered that links to a local file, for example _"file:///D:/example.html_", the process stops and the remaining tabs are not restored.

Workaround is to open the list with saved tabs and restore the remaining tabs by hand one by one. The bookmark that links to a local file can not be restored this way.

Tested with FF 58.0.2 on Win OS.

Caused probably by the fact that the WebExtension Api restricts opening privileged urls (such as file:///, chrome:, about:, etc..). Skipping these restricted urls (and possibly notifying the user) and continue restoring the remaining tabs would be a solution.

**Comment by sienori** [comment]
Are you using version 2.1.0?
The problem of processing stops was fixed in the past version.
![capture](https://user-images.githubusercontent.com/29514424/36736245-7ad19796-1c1b-11e8-8d64-e261da876b6a.PNG)

**Comment by jschmer** [comment]
Works for me just fine with Tab Session Manager Version. 2.1.1
