### ISSUE TITLE
your update 2.1 erases everything

### ISSUE THREAD

**Issue by boistordu** [sienori/Tab-Session-Manager#188]
Your update 2.1 on FF 58.0.2 did erase everything on all my vms and hosts

**Comment by sienori** [comment]
What is "vms and hosts"?

The issue of session disappearance has been reported to several people.
In order to deal with this problem, I implemented the session backup function in ver 2.1.0.

Also, please check that the category filter at the top of the session list is "All".
The hidden session will be displayed.

**Comment by boistordu** [comment]
all my windows 10 pro VMs and my hosts with windows 10 pro have the same symptoms. That was an information to say: even on fresh installed which are VMs where not much can interfere like antivirus or things like that. 
No I can confirm to you that even with all the previous session have disappeared. So I guess that somewhere in the code, the previous session was considered as corrupted and the files have been replaced or something like that.

**Comment by boistordu** [comment]
I just hope that it won't happen again in the future.

**Comment by xboydavey** [comment]
I have verson 2.1.0, it wiped out all of my saved tabs, and I don't have a category option titled 'All'.
I have:
Newest
Oldest
A-Z
Z-A

...

**Comment by sienori** [comment]
Hmm...
The disappearance of the sessions has never happened in my environment, and I can not find the bug.
In the future, I will implement it using IndexedDB for improve stability and performance.
That change may solve this problem.

From now on, please use the backup function.
Sorry for the inconvenience.

**Comment by sienori** [comment]
Replacement with IndexedDB is complete. https://github.com/sienori/Tab-Session-Manager/commit/22d3f06bb1503b9ce4c4b664bd240d8b0c206c62
Sessions will not disappear from the next version.
