### ISSUE TITLE
Browser jank in Firefox (nightly)

### ISSUE THREAD

**Issue by autonome** [sienori/Tab-Session-Manager#19]
I captured a profile that shows serious jank in Firefox when I close a tab: https://perfht.ml/2yQ7zmi

Turned out it's caused by setAutoSaveListener() in this extension.

Maybe the function is doing too much work synchronously, somewhere?

**Comment by sienori** [comment]
I will investigate. thanks.

**Comment by sienori** [comment]
I added lazy loading tab, and Invalid auto save function during session restore.
This greatly reduces memory usage.
https://github.com/sienori/Tab-Session-Manager/commit/501461d4ffd69fec7320b8c2da815f99970aa9b1
https://github.com/sienori/Tab-Session-Manager/commit/e201220b38ca38800db5bc47d84f6f353e9b0954

**Comment by sienori** [comment]
I improved it so as not to save in large quantities in a short time.
https://github.com/sienori/Tab-Session-Manager/commit/50ed045d306d5242cbc8a521e336c4f86770299f
