### ISSUE TITLE
Exported session filename doesn't inlcude the ".json" extension

### ISSUE THREAD

**Issue by aaaxx** [sienori/Tab-Session-Manager#191]
And Tab Session Manager doesn't recognize such files (says "Read failed"), so it's pretty confusing the first time you try to import a session and gets annoying in the long run.

**Comment by sienori** [comment]
The exported file contains ".json".
https://github.com/sienori/Tab-Session-Manager/blob/07eecdd3976d5ac83f680539fa9db3f1424ac579/Tab-Session-Manager/options/options.js#L279

Also, The backup file contains ".json".
https://github.com/sienori/Tab-Session-Manager/blob/07eecdd3976d5ac83f680539fa9db3f1424ac579/Tab-Session-Manager/background/import.js#L50

Windows10, Firefox 58.0.2, Tab Session Manager 2.1.0

**Comment by aaaxx** [comment]
Windows 8.1 here, the rest is the same as yours.

Automatic backup (i.e., saving to Downloads folder on startup) works fine, but manual exporting offers just the name without extension in the Save Dialogue.

![screenshot of the Save Dialogue](https://user-images.githubusercontent.com/6186480/36931577-24e47272-1eb9-11e8-94b6-f02463e1b505.png)

**Comment by sienori** [comment]
When Windows setting "[Hide extensions for known file types](http://www.thewindowsclub.com/show-file-extensions-in-windows)" is turned on, it looks like this.
![default](https://user-images.githubusercontent.com/29514424/36990673-c9b3286c-20e8-11e8-8fd6-b18d0f9a966b.PNG)
However, the file that is actually saved has an extension and can be imported normally.

What happens when you turn off that setting?

**Comment by aaaxx** [comment]
Interesting. When the setting is off, the extension is visible in the dialogue and the file is saved with the extension.
![screenshot of the Save Dialogue; JSON extension is visible in the filename field](https://user-images.githubusercontent.com/6186480/37002386-d5227438-20c9-11e8-933a-3dbe336bf666.png)

**Comment by mss999** [comment]
Hi aaaxx:
Which version of Tab Session Manager allows one to export specific, dated sessions?
I have a session that I would like to export and then put into a separate file.
Thanks

**Comment by aaaxx** [comment]
It always exports _all_ of the sessions.
