### ISSUE TITLE
"Restore previous session at startup" does not work perfectly after closing multiple windows

### ISSUE THREAD

**Issue by TonyK1321** [sienori/Tab-Session-Manager#192]
I just installed this, and set it to autosave every 240 minutes, and to save when Firefox closes.  I had my PC on all day yesterday, but no sessions were saved.  I have multiple windows open so I expect this session manager to save them all, and restore them when FF restarts up.  I have Win10-64 with FF 58.0.2-64.

Also, as a feature, I want to declare where the sessions are stored.  There currently does not appear to be that option.

**Comment by sienori** [comment]
In my environment it did not reproduce.
Procedure:
* Turn on the option ”Save the session regularly"
* Set the ”Interval (minutes)” to 0.1
* Open or close several tabs
* Open the session list and set the category filter on the top to "Auto Saved - Regularly".
* Autosave session is displayed

**Comment by TonyK1321** [comment]
I have 4 FF windows open.  Maybe that will cause the failure.

 

Tony

**Comment by sienori** [comment]
Do you mean like this problem?
* You are turning on "Restore previous session at startup"
* Close all 4 windows you are open
* Only the last one window (NOT 4 windows) is restored at the next startup

In the future, I would like to solve this problem.
<hr>

>Also, as a feature, I want to declare where the sessions are stored. There currently does not appear to be that option.

Because of the Web Extensions specification, you can not change the session storage location.

**Comment by sienori** [comment]
I fixed the problem that only one window could be restored with option of "restore previous session at startup". https://github.com/sienori/Tab-Session-Manager/commit/7fc9b90505739f89cbc720d352b091157124c3a1
