### ISSUE TITLE
Weird behaviour of the backup option

### ISSUE THREAD

**Issue by aaaxx** [sienori/Tab-Session-Manager#193]
Browser crashing will sometimes result in the "Save backup" option being disabled the next time the browser starts, the loss of all sessions, and TSM being unable to save any new sessions (automatic or manual) until the "Save backup" option is enabled again.

I don't know how to reproduce this other than trying to crash the browser repeatedly until the sessions are lost and the session "Save" button stops responding, because it doesn't happen on every crash. But once it happens, going into the options and enabling the "Save backup" option fixes it immediately.

**Comment by sienori** [comment]
I think that it is probably not an inherent problem of the backup option.
For example, other settings are also initialized, but you just do not notice.
