### ISSUE TITLE
Tab SM 21.0 : Import sessions not working, nothing happens

### ISSUE THREAD

**Issue by Question2** [sienori/Tab-Session-Manager#194]
I just updated to firefox 58.0.2 64 bit, and i had session manager save files. So i tried importing the sessions and Tab SM said that the sessions were successfully imported, but nothing else happened. Tab SM did not load the tabs or anything else from the imported session at all.

Attempting to import it multiple times just resulted in Tab SM telling it was successfully imported but otherwise, nothing.

Have included a copy of the session file here if it helps.

[backup.zip](https://github.com/sienori/Tab-Session-Manager/files/1777991/backup.zip)

**Comment by Question2** [comment]
Okay so it looks like you cannot load the sessions from the options page because there is no load function there, you have to click the tab SM icon to the right of the search bar. Very weird.

I was able to load the sessions but the way Tab SM loaded them weird. It insisted on loading every, single tab, all 892 of them, one by one. This obviously took a very long time.

And when the tabs were loaded, they were not "fully" loaded. I got a placeholder URL : moz-extension://8a2ae063-ee31-460b-9612-c009c06279ba/replaced/replaced.html?state=redirect&title=Read%20manga%20Manuke%20na%20FPS%20Player%20ga%20Isekai%20e%20Ochita%20Baai%20Ch.009.003%20-%20Read%20Online%20online%20in%20high%20quality&url=http%3A//kissmanga.com/Manga/Manuke-na-FPS-Player-ga-Isekai-e-Ochita-Baai/Ch-009-003---Read-Online%3Fid%3D406645&favIconUrl=http%3A//kissmanga.com/Content/images/favicon.ico

Which obviously is not a "real" URL so i couldnt refresh the page and have the page load. I had to manually open the link. On every, single, tab that i am attempting to restore.

The previous session manager for older fireox versions simply loaded the tab instantly when i clicked on it. Not sure if all of this (loading tabs one by one, the weird placeholder URL, etc) is intended?

**Comment by 1RonRock** [comment]
I am having the same issue. As well as the problem with the memory being used up by all of the tabs loading. Puts a hell of a strain to my computer. Often locks up for long amounts of time. Maybe 500 pages in the session, 8GB memory. No other apps running at the time, just FFox.

**Comment by Question2** [comment]
I just closed and opened firefox, and tab SM dd not load the previous session. The only sessions i can see in Tab SM are the ones that i have imported..and by default tab sm is set to save the session when i close the window. I had "auto-load the previous session" ticked but it did not do that.

**Comment by sienori** [comment]
> I was able to load the sessions but the way Tab SM loaded them was weird. It insisted on loading every, single tab, all 892 of them, one by one. This obviously took a very long time.

I plan to add an option to speed up tab opening. https://github.com/sienori/Tab-Session-Manager/issues/52

> And when the tabs were loaded, they were not "fully" loaded. I got a placeholder URL : moz-extension://8a2ae063-ee31-460b-9612-c009c06279ba/replaced/replaced.html?

In order not to display this page, please disable the lazy loading option.

> I just closed and opened firefox, and tab SM dd not load the previous session. The only sessions i can see in Tab SM are the ones that i have imported..and by default tab sm is set to save the session when i close the window. I had "auto-load the previous session" ticked but it did not do that.

It will not happen in my environment. Please let me know if you know how to reproduce.



Anyways, discuss only one problem with one issue.
