### ISSUE TITLE
Infinite memory leak on Google Sheets when storage.js reaches certain size

### ISSUE THREAD

**Issue by pmoris** [sienori/Tab-Session-Manager#202]
I discovered a memory leak that only seems to occur when opening a Google Sheets document, provided Tab Session Manager's `storage.js` database is over a specific size or contains specific content (undetermined at the moment). The memory leak can fill my system's 16GB RAM in ~10 seconds, causing heavy swapping on Linux Mint or a Firefox crash on Windows. 

## Expected Behavior
Google Sheets should not cause an unending memory leak that crashes the system.

## Current Behavior
Opening any Google Sheets document rapidly fills the system's available memory when using a `storage.js` database with a specific size/format (see below).

## Possible Solution
Starting with a fresh session database fixes the issue.

## Steps to Reproduce
1. Create a fresh Firefox profile.
2. Install Tab Session Manager.
3. Import the following exported session json file: [sessions-google.txt](https://github.com/sienori/Tab-Session-Manager/files/1808193/sessions-google.txt) (renamed to .txt to allow upload via github).
 Note that I replaced all URL, favicon and title entries with Google for the purposes of sharing this file, but the issue originally occurred with my regular session database. Moreover, it occurred on both Windows and Linux, where I have different storage files, albeit they are probably too large and messy for my own good on both systems.
4. Open any Google Sheet or create a new one.
5. RAM usage rapidly increases and keeps doing so until a system lock-up or Firefox crash.

Honestly, I'm pretty stumped! This seems like such a weird interaction between two seemingly unrelated things. Perhaps there are other websites that can cause the same issue, but so far I haven't discovered any.

Thanks in advance!

**Comment by sienori** [comment]
The memory leak is due to the storage system. 
I replaced it with IndexedDB, as a result, improved greatly.
https://github.com/sienori/Tab-Session-Manager/issues/171

Also, I discovered that the tabs.onUpdate event fires about 50 times when opening the google spreadsheet.
As a result, a large amount of auto save processing occurs.
I am planning to fix this problem.

**Comment by sienori** [comment]
I fixed this problem. https://github.com/sienori/Tab-Session-Manager/commit/e68c08cac91b03db605a8466e4e518a6995f8579

**Comment by pmoris** [comment]
Cheers, it works perfectly now on my system. Thanks a bunch!
