### ISSUE TITLE
Feature request: delete specific tabs from a saved session

### ISSUE THREAD

**Issue by syldub69** [sienori/Tab-Session-Manager#204]
I have saved many sessions of my previous profiles before migrating to Firefox 57+.
I have imported all these sessions in a unique Firefox profile (all the preceding profiles have now been deleted). 
For each one of these sessions, I have saved the session as a User session (so they all appear in the "User Saved" section of Tab Session Manager).
Now, I regularly process all my tabs from each of my old "User Saved" sessions in order to process all my previous work. I want to review all my old tabs before deleting them. To give you an idea of the quantity of tabs: I have nearly 500 tabs to process in 5 User sessions...
But this is a very very complicated process to manage, as we can't delete specific tabs from a user saved sessions.
Actually, the only solution I found is to maintain a list in Excel of all the tabs that I have already processed.
Maybe I could edit the session file directly (json file?), but I don't know where the sessions are stored. I didn't found any relevant file in the Firefox profile.

Could you please implement a [X] button on the left of each tab in a session in order to be able to remove the corresponding tab from the session?

**Comment by sienori** [comment]
I implemented the function to delete window or tab on saved session. 12b592a https://github.com/sienori/Tab-Session-Manager/issues/112
![delete](https://user-images.githubusercontent.com/29514424/38173394-e0636d18-35f8-11e8-8fbd-f007fe2ed5f7.png)
