### ISSUE TITLE
How does one save a specific session in TSM

### ISSUE THREAD

**Issue by mss999** [sienori/Tab-Session-Manager#206]
I have a saved session with specific tabs that I would like to download/export. 

I am concerned that if I update to version 2.1 it will overwrite the session--and all my other saved sessions--and I will lose everything.

Is the specific, dated session already stored in a file on my computer--Windows machine--or do I have to upgrade to another version of TSM to save the tabs from that specific session.

Thanks.

**Comment by sienori** [comment]
What is the version of TSM you are using?
If it is 1.5.0 or later, you can export all sessions.
Oeeaption page -> Sessions -> Export Sessions

Normally, sessions are rarely lost when updating.

**Comment by mss999** [comment]
Hi:

When was version 1.5 released? I first started using TSM back in late
November/early December when I upgraded to Firefox Quantum and needed a
replacement for Session Manager.

Thanks

**Comment by sienori** [comment]
It is November 18, 2017.

Please open the settings page.
![a](https://user-images.githubusercontent.com/29514424/37565549-991d5172-2aee-11e8-9f62-75aa0e96fa6f.jpg)

If version 1.5.0 or later, such a settings page opens.
![180318_02](https://user-images.githubusercontent.com/29514424/37565617-b6991abe-2aef-11e8-8fe7-09ee88339e3f.png)

![d](https://user-images.githubusercontent.com/29514424/37565640-3c9cc476-2af0-11e8-8e48-a400e983c8fe.jpg)

**Comment by mss999** [comment]
Thanks. This add-on is great. I have upgraded to version 2.1. I was using
1.3.

I exported the sessions file.

A couple of questions:
How do I open the file? What format is it in?
What is in the file? Are all the sessions in one file or can I export
separately dated files?

Thanks.

**Comment by sienori** [comment]
The file is json file.
You can import from "Import sessions" on settings page.

That file contains all the sessions.
To export individual sessions:
![180318_00](https://user-images.githubusercontent.com/29514424/37565918-4770d464-2af5-11e8-9ec8-e3c4d8f81f12.jpg)

**Comment by mss999** [comment]
Do you know how to convert .json to txt or word?

I have 2 goals:
1) Have a backup of my tabs that I can use TSM to reimport later
2) Have a version of my tabs in word or txt format that I can use manually.

Thanks for your help and for this powerful tool.

**Comment by sienori** [comment]
Please do not edit the exported file as it causes a bug.
You can read json file with Notepad etc, but readability is low.
