### ISSUE TITLE
After closing a window in a multiple window session, the session list is empty

### ISSUE THREAD

**Issue by devanes** [sienori/Tab-Session-Manager#209]
I had session going with three windows and lots of tabs. I closed one of the the windows and then the session list was suddenly empty. When restarting firefox, the list returned.

**Comment by sienori** [comment]
"After closing the window" does not reproduce for me.
Did you try opening the popup several times after becoming empty once?
Normally, the sessions should be displayed.

Known Issues:
If you open the pop-up in multiple windows at the same time, the session list will be empty.
It will be displayed when you reopen the popup.
![b](https://user-images.githubusercontent.com/29514424/37716469-fa36c7ca-2d61-11e8-8685-12de9eddaa86.PNG)

**Comment by devanes** [comment]
That is wat it looked like, except the dropdown and 'newest' were gray. That might be a theme thing though.
But I tried it multiple times and the same thing happened. I did not have the popup open in multiple windows. I might have had the settings window open. I tried reproducing it with a new (4th) window and a single tab and the issue didn't occur. With one of my tree existing windows with a lot of tabs it did. I do get the popup (from Firefox) whether I really want to close X tabs. Maybe that has something to do with it. I'll try closing my browser and creating a new window with multiple tabs now.

**Comment by devanes** [comment]
A new window with a few tabs doesn't reproduce the issue. A new window with 48 tabs does.

**Comment by sienori** [comment]
It seems that processing temporarily stopped with an exception occurred.
I think that this problem is solved in the latest version.
Sorry for my late reply.

**Comment by PackElend** [comment]
same issue here app and firefox are up to date, lost anyhting
