### ISSUE TITLE
feature request: dark theme

### ISSUE THREAD

**Issue by jar311** [sienori/Tab-Session-Manager#211]

**Comment by sienori** [comment]
I may implement a dark theme in the future.

**Comment by gsirvine** [comment]
I second this request, please make a dark theme option.  All my other addons seem to change over to dark when I run Shadowfox "https://github.com/overdodactyl/ShadowFox".  Your amazing tab addon doesn't however.  A default dark theme would be nice though.

**Comment by deathtrip** [comment]
Any decision on this? The issue is two years old already, so we are now in "the future".

**Comment by sienori** [comment]
I implemented the dark mode!
![dark mode](https://user-images.githubusercontent.com/29514424/101980998-d88b9580-3cac-11eb-9c84-e8f64a4c0d9c.png)
