### ISSUE TITLE
Version 3.0 does not save any sessions

### ISSUE THREAD

**Issue by KazeAmaru** [sienori/Tab-Session-Manager#212]
I updated to 3.0 the other day and now neither does it create regular backup sessions ( I set it to create one every five minutes ) nor does it on regular close.

I already deinstalled and reinstalled the addon ( cleaning the left-overs by hand just to be sure ). I included even private tabs to be sure but no session is created. When I check it, not even ONE session is created even if the whole browser was up for hours. So neither Auto-Save nor Save on Close

**Comment by sienori** [comment]
Is this issue the same as https://github.com/sienori/Tab-Session-Manager/issues/210 ?

**Comment by wmarchibald-ws** [comment]
Yes.

**Comment by KazeAmaru** [comment]
Well Yes and No, it was labeled Firefox bug as the profile load up does bs. However I have NO Firefox profile etc

**Comment by sienori** [comment]
As you are using Firefox, the profiles exists.
https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data
