### ISSUE TITLE
Feature request: Blacklist

### ISSUE THREAD

**Issue by Aergernis** [sienori/Tab-Session-Manager#216]
Hi,
i'd like to see a Blacklist Feature. For example: i use a addon that opens https://web.whatsapp.com/ in a Tab when Firefox is starting. If i store/restore a session this should not be stored/restored.

Hope it's clear what i mean

**Comment by sienori** [comment]
In version 5.1.0, I implemented ignore URL list option.
![image](https://user-images.githubusercontent.com/29514424/71642642-cf9af180-2cf1-11ea-8b38-eb03fa21c982.png)
