### ISSUE TITLE
User interface too wide for overflow bar

### ISSUE THREAD

**Issue by jimbobmcgee** [sienori/Tab-Session-Manager#218]
A very minor issue but, when TSM is invoked via the overflow (**>>**) menu, the right-hand side of the user interface is cut off (including access to the settings gear icon).  

This doesn't happen if the TSM icon is in the toolbar, but I *like* putting things in the overflow bar! :-)

**Comment by sienori** [comment]
It is the specification of firefox.
Please set the popup width to 348 on the setting page.

**Comment by sienori** [comment]
I have made the popup scrollable horizontally. https://github.com/sienori/Tab-Session-Manager/commit/ad7771e9ac8a5af740b6d23f50d3ac3a9bfa2b8d #778 
![image](https://user-images.githubusercontent.com/29514424/120101395-e1035a00-c180-11eb-8a09-c830adf344ff.png)
