### ISSUE TITLE
(AHAHA) Lost All my session, guys 

### ISSUE THREAD

**Issue by ANrd3243** [sienori/Tab-Session-Manager#220]
I think its very funny, update addon and lost all session in one time. I mean you advice install Version. 2.1.1 don't do anything. I lost everything. You very smart guys, Maybe can warn that the update will erase everything before updating? And even funnier is that I installed this addon before updating firefox, so as not to lose my 1000+ tabs. I read here the next thread and your advice (Well, then delete your profile and create a new one), it's just wonderful, but I do not need your application, i need my tabs.

**Comment by ANrd3243** [comment]
In general, as far as I understand our "smart guys" do not know how to work with IndexedDB, so you need to install version 2.1.1, reboot browser and install version 3.0.1. In this case, the saved sessions will appear. This solves the problem.

**Comment by sienori** [comment]
I am glad that you solved the problem.
In version 3.0.0, only when updating from version 2, the sessions is migrated.
Therefore, if IndexedDB error occurred and reset storage, you need to install 2.1.1 once.

I have released version 3.0.1 to solve this.
Version 3.0.1 will migrate old sessions at every startup.
You do not need to install version 2.1.1 once.
