### ISSUE TITLE
Restore to default settings

### ISSUE THREAD

**Issue by davidhedlund** [sienori/Tab-Session-Manager#221]
I suggest a "Restore to default settings" button in the Settings.

uBlock Origin has a "Restore to default settings..." button, it's useful if you messed up your configuration.

**Comment by sienori** [comment]
I added the option to reset all settings. https://github.com/sienori/Tab-Session-Manager/commit/7950c4908c72241e4eef36f53fd6876a7a3e9689

**Comment by davidhedlund** [comment]
@sienori Thank you very much.
