### ISSUE TITLE
saving tab reload actions

### ISSUE THREAD

**Issue by ehtron** [sienori/Tab-Session-Manager#223]
Hi ;)
is there a way to save tab reload timer
e.g. with Tab Session Manager 
I like to have this feature
regards ehtron :)

**Comment by sienori** [comment]
I can not understand "saving tab reload actions".
What do you mean?

**Comment by ehtron** [comment]
Hi :)
we use also the firefox addon
Auto Reload Tab
to set tab reload and like do have save and restore the reload times with tab session manager.
regards ehtron :)

**Comment by sienori** [comment]
Sorry, it is impossible to save the setting of Auto Reload Tab.

**Comment by ehtron** [comment]
Hi :)
not the settings... the reload timer per tab..
the crash restore from firefox save that.
regards ehtron

**Comment by sienori** [comment]
"Reload timer" is an internal value of Auto Reload Tab.
It is impossible to get/set the value with TSM.
Thanks for your understanding.

**Comment by ehtron** [comment]
Hi :)
ok,, understand.

but firefox self can restore the value via save on close and restore after crash...
