### ISSUE TITLE
When restoring session last tab doesn't open

### ISSUE THREAD

**Issue by eboye** [sienori/Tab-Session-Manager#224]
OK, so to reproduce the bug to the following:

1. On MacOS High Sierra, Firefox 60.0beta8 Dev Edition
2. Quit the Firefox (not close, quit)
3. Start Firefox (I mostly have empty session without windows)
4. When I restore (or when TSM auto restores) last one the last tab is missing, there's a new tab at the end.

**Comment by sienori** [comment]
I think that this problem is solved in the latest version.
Sorry for my late reply.
