### ISSUE TITLE
Add search function for saved tabs

### ISSUE THREAD

**Issue by gramireus** [sienori/Tab-Session-Manager#228]
It would be fantastic if I could search through the saved tab sessions for a specific tab or session.

**Comment by sienori** [comment]
I will implement the search function in the future.
duplicate: #142

**Comment by sienori** [comment]
I will implement the search function in the future.
duplicate: #142

**Comment by ThisIsABug** [comment]
I actually think this isn't a duplicate, because #142 is a feature request for searching in the title of the saved session while this one is about searching in the titles of the tabs inside a session. And as far as I know (please correct me if I just didn't find it) this feature isn't implemented.

**Comment by ElhemEnohpi** [comment]
It would be great to search for tab titles in saved sessions! Session Boss extension has this, so I'm using it. But I would prefer to use Tab Session Manager. Thanks.

**Comment by Ghos3t** [comment]
It would be very helpful if it was possible to search by the title or the URL of a tab, as many times I might remember the title of the website or it's URL but not which session I saved it under.

**Comment by sienori** [comment]
In version 6.2.0, I implemented the search function for saved tab title!
![4d5b0d7b5a66b638cd84b79113e0c6ed](https://user-images.githubusercontent.com/29514424/90147214-eb549300-ddbc-11ea-8375-07eca72620b4.gif)
Thanks!
