### ISSUE TITLE
TSM autosaves incognito tabs

### ISSUE THREAD

**Issue by aidenn** [sienori/Tab-Session-Manager#23]
I feel like this should be a big big no-no (or at least configurable).

To reproduce:

1. Launch FF57(b13) and install TSM
2. Check if autosaving is enabled
3. Open a private browsing window
4. Open something in that window
5. Wait for autosave
6. Voila - the private browsing tab is saved on the list.

Expected behaviour: TSM should not be aware of incognito tabs.

This is my only true gripe with this addon, other annoyances are pretty minor and I'd very much like to continue using TSM until a true SM contender arrives. Maybe TSM will be this contender? I wish you all the best, and I like how you cooperate with TST devs.

Cheers!

**Comment by sienori** [comment]
I will implement it in a few days.

**Comment by aidenn** [comment]
Whee, thanks!

**Comment by sienori** [comment]
I added that function.
https://github.com/sienori/Tab-Session-Manager/commit/99d06f84b0d774f44054f46e6edd29448d0ed2b2
