### ISSUE TITLE
Reorganize sessions by "custom" order?

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#231]
I would like to request the feature to move the orders of saved sessions in the menu by drag and dropping as you do with tabs. This would show as "custom" in the little box thats says the order for the sessions. Thank you a lot for the hard work @sienori

**Comment by sienori** [comment]
No, I do not implement custom oder.
It is troublesome to reconfigure the custom order when the session increases.
If you want to keep the order of sessions, sort by A - Z and number the session name.
![number](https://user-images.githubusercontent.com/29514424/39514681-e61432f4-4e32-11e8-9835-46fcb38ac13b.PNG)

**Comment by mrwensveen** [comment]
Thanks for pointing me to the ordering dropdown. It was so plainly in sight that I didn't even see it!
