### ISSUE TITLE
export individual sessions?

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#232]
Sessio Manager would just open a folder and you could copy and paste saved sessions individually. I saw that TSM handles the thing in a different way by exporting all (at the least I think so) sessons as .json file. Would it be possible to have an option to export all sessions/export session individually, to be able to chose the former option?
Thank you.

**Comment by sienori** [comment]
Hmm, I think there is no need to export all sessions individually.
Generating hundreds of files is troublesome for many people.

**Comment by WPFilmmaker** [comment]
@sienori I don't know if you understood correctly or maybe I misunderstood, what I meant was if I have 10 sessions saved, the options to export only some of them, you wrote "hundreds of files" so I think you understood exporting each tab?If I misunderstood sorry:)

**Comment by sienori** [comment]
Sorry for the misunderstanding and my late reply.
Individual export is possible from version 2.0.0.
![181029_01](https://user-images.githubusercontent.com/29514424/47619808-05f54380-db26-11e8-9c80-166429209559.png)
