### ISSUE TITLE
Older saved backups not deleting after reaching maximum

### ISSUE THREAD

**Issue by dionymnia** [sienori/Tab-Session-Manager#233]
I have enabled the option to save backups when Firefox starts up, and it's set to the default save location (Download folder\TabSessionManager - Backup).

Older backups aren't being deleted, however, once it exceeds "Maximum number of saved backups". I've set the maximum to various numbers (10, 8, 6, and 4), and I've also tried deleting the backup folder, to see if that would "reset" the counter. Regardless, the maximum isn't triggering deletion of older backups.

**Comment by sienori** [comment]
This option was not working properly.
I had removed the backup upper limit option in version 4.0.0.
It is difficult to implement it because of limitations of WebExtensions.

**Comment by sienori** [comment]
I have implemented incremental backup. https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545 #710
This allows you to manage backup sessions individually.
Only updated sessions are saved, saving storage.

![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)
