### ISSUE TITLE
This page can not be opened by Tab Session Manager

### ISSUE THREAD

**Issue by mmartarello** [sienori/Tab-Session-Manager#234]
I try to save a session (one window, two tab), url = file:///P:/V5%20Documentations/B21doc/English/online/CATIA_P3_default.htm and file:///P:/V5%20Documentations/B21doc/English/online/CATIA_P3_default.htm.

Opening session i have this message for both tab:
This page can not be opened by Tab Session Manager.

How can I solve this?

Thanks in Advance

**Comment by sienori** [comment]
That is normal behavior.
Local files can not be opened from add-ons due to restrictions on WebExtensions.

**Comment by lasergyro** [comment]
Is there a bug ticket on Mozilla we can vote on to get a workaround/lift the restriction?
