### ISSUE TITLE
Firefox & TSM startup sequence? 

### ISSUE THREAD

**Issue by 1RonRock** [sienori/Tab-Session-Manager#236]
I'm not sure if this is an issue or just the way FF & TSM work.

When I start up FF with TSM addon, the FF opens as expected with all of my saved tabs from previous. A short time after opening all tabs close and then they are reloaded again with the tab address showing the TSM address. I also have "Foxy Tab addon" with the tab counter. It shows the tabs number increase as the tabs are reloaded. 

Is this expected tab opening and closing then re-opening behavior? Or do I have an issue with my FF?

Everything works as normal after the "re-opening"

**Comment by sienori** [comment]
I can not see such a problems in my environment.
Firefox Nightly 61.0a1, TSM 3.1.0, Foxy Tab 2.11

1. Install TSM and Foxy Tab with new profile
2. Enable TSM setting "Restore previous session at startup"
3. Open 5 tabs
  Foxy Tab displays "5"
4. Exit firefox
5. Launch firefox
  TSM restores the previous 5 tabs
  Foxy Tab displays "5"
  The counter does not increase even when reloading the tab

**Comment by 1RonRock** [comment]
Maybe I was not clear about my concern. The tab counter was just part of my explanation.

When I open Firefox with TSM installed and it opens FF and all tabs as expected. Then after a short time All tabs close and are reloaded one at a time as the tab counter counts up. When the last tab is open the FF is ready to go.

**Comment by 1RonRock** [comment]
Here is a short video of my FF when I open it.

[https://drive.google.com/open?id=1rJSuiIjrGrI5siXXs1oXfu2iCEUcidqW](url)

I stopped the video before all tabs were counted. After they are counted (Lazy loading, I assume) the FF starts as expected.

**Comment by 1RonRock** [comment]
Sorry first link didn't work, this one should,

https://drive.google.com/file/d/1rJSuiIjrGrI5siXXs1oXfu2iCEUcidqW/view?usp=sharing

**Comment by 1RonRock** [comment]
Any response to my video of the way that FF opens up then downloads TSM then re-opens the session? Is this expected behavior? I have FF and TSM on two different computers and both act the same. But IDK if that is correct.
