### ISSUE TITLE
Special tabs are not restored

### ISSUE THREAD

**Issue by shelaf** [sienori/Tab-Session-Manager#24]
Special tabs like about:addons are not restored.
Special tabs are intentionally restored as new tabs, but please restore them as they are.

**Comment by sienori** [comment]
Opening about: xxx can not be done becouse the firefox specification.
It can not be restored as it is.

**Comment by shelaf** [comment]
It cannot be helped.

**Comment by grahamperrin** [comment]
[about:xxx not restored properly · Issue #6 · sienori/Tab-Session-Manager](https://github.com/sienori/Tab-Session-Manager/issues/6)
