### ISSUE TITLE
TSM not working on Firefox Nightly 61

### ISSUE THREAD

**Issue by MCKSysArgentina** [sienori/Tab-Session-Manager#241]
After updating to Nightly 61.0a1 (2018-05-01) (64-bit), TSM shows a blank list of sessions (see attachment).
Using the "Import sessions" feature doesn't solve the problem.

![tsm1](https://user-images.githubusercontent.com/10077263/39506377-819b99b8-4dae-11e8-96cd-64dc9d1c4b18.jpg)

**Comment by MichaelMFeldman** [comment]
Same, yikes! Is there at least a way to get the list of URLs in my sessions? i.e. where are they stored?

**Comment by sienori** [comment]
I installed nightly and started up with a new profile, but I can not see such a problem.
Could you please show me the debug log?

Please open about:debugging.
Check "Enable add-on debugging" at the top of the page and click on Tab Session Manager Debug.
![1](https://user-images.githubusercontent.com/29514424/37721822-dce27bae-2d6d-11e8-8516-f59ec88c9fae.PNG)
![2](https://user-images.githubusercontent.com/29514424/37721832-e06315a4-2d6d-11e8-97f5-4d27f13f8cc2.PNG)

Open the "Console" tab of the development tool and tell me the logs shown there.
If possible, it will be helpful if you can take a screenshot. 
![180322_00](https://user-images.githubusercontent.com/29514424/37721862-f5083b56-2d6d-11e8-959a-69787e350dff.png)

Thanks for your cooperation.

**Comment by Jack0fHearts** [comment]
Same problem here. Stopped working after latest Nightly build and it worked excellent before.

![sm_debug](https://user-images.githubusercontent.com/38913268/39524357-3a7e7ce4-4e08-11e8-905d-36f65d408df9.jpg)


I think that's the relevant data, please let me known if you needed any more info.

Thank you for an excellent extension!

**Comment by MCKSysArgentina** [comment]
Nightly last update: 61.0a1 (2018-05-02) (64-bit). Problem persists:

Data from about:debugging
![tsm2](https://user-images.githubusercontent.com/10077263/39528329-2aaf21be-4dfa-11e8-8f73-cf31263cffcb.jpg)

And the log

![tsm3](https://user-images.githubusercontent.com/10077263/39528342-34803b1a-4dfa-11e8-8183-37bc74f8305e.jpg)

Also, "Export" button doesn't do anything.

**Comment by MCKSysArgentina** [comment]
It's working again (on Nightly 61.0a1 (2018-05-02) (64-bit)) since the last update (Version 3.1.1).
I'm leaving this ticket open since I'm not sure if I should be the one who closes it.

**Comment by alyandon** [comment]
Working again for me as well.  Nightly 61.0a1 2018-05-03.

**Comment by MichaelMFeldman** [comment]
It's fixed!!! :) Thank you

**Comment by sienori** [comment]
I think that this is probably a temporary problem of firefox.
Reinstall or update the add-on and solve it.
