### ISSUE TITLE
TSM treats right-click as if it were left-click

### ISSUE THREAD

**Issue by craig-sanders** [sienori/Tab-Session-Manager#244]
I clicked on the TSM icon to get the dropdown session list, then tried right-clicking on the Open link of the first saved session, expecting to either get a right-click menu or nothing to happen

(Note: the mini-hamburger menu with Rename, Export, etc doesn't display until **after** you mouse over the session entry - I discovered this later, at the time I didn't even realise that there *was* a hamburger menu.)

Instead, what happened was that a) the standard firefox right-click context menu popped up and b) simultaneously, the session was opened, replacing my current session.  Fortunately, that session had been recently saved so nothing important was lost.

Similar result with the session details expander (i.e. "_X windows - Y tabs_"): right-click on that and you get the FF context menu **and** then the session details are displayed.  And for the "_+_" (Add a tag) button.  I didn't try it, but presumably right-clicking the "_Delete_" link behaves the same.

Suggested fixes:

1. Right-clicking anywhere in the TSM dropdown pops up the hamburger menu
2. Ignore right-click entirely

The first option would be great for discoverability and usability.  The second at least stops bad/unexpected things from happening.

**Comment by sienori** [comment]
In version 4, right click is ignored.
