### ISSUE TITLE
Toolbar Height limited to <= 600 pixels

### ISSUE THREAD

**Issue by craig-sanders** [sienori/Tab-Session-Manager#245]
My main monitor is 2560x1440 (and my second monitor is pivoted 1080p, so 1080 wide x 1920 high - I use this mostly for reading stuff - ebooks, PDFs, long web articles, etc).

The TSM popup is nowhere near tall enough on either of these monitors so, I tried setting Height of the TSM popup to 1000, but TSM changes any value entered above 600 to 600.

This might make sense on a 1080p display, but not on higher-resolution displays - e.g. 4K is becoming common these days, and that's 3840x2160.

Setting arbitrary limits like this doesn't serve any useful purpose or help anyone, it just adds unnecessary annoyance.

**Comment by sienori** [comment]
The width and height of the popup are limited by firefox.
High resolution displays are probably also limited to this size.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups
>It will grow to a size of **800x600 pixels** at most if that fits on the user's screen.

**Comment by RobertAb1** [comment]
@sienori 
Can you create new bug at Mozilla Bugzilla and let me know?

**Comment by RobertAb1** [comment]
I have created [Bug 1545886](https://bugzilla.mozilla.org/show_bug.cgi?id=1545886) (Increase the size of popup window for Webextensions).

**Comment by RobertAb1** [comment]
I have created [Bug 1545886](https://bugzilla.mozilla.org/show_bug.cgi?id=1545886) (Increase the size of popup window for Webextensions). 
Then, I found out that similar bug already exists and it was denied ([Bug 1404626](https://bugzilla.mozilla.org/show_bug.cgi?id=1404626)).
