### ISSUE TITLE
Part of the restored tab is saved as a new tab

### ISSUE THREAD

**Issue by shelaf** [sienori/Tab-Session-Manager#25]
Environment: firfox57 beta14 x64, Tab Session Manager 1.3.3
When do the following operation, some tabs are saved as new tab.

1. Open some urls. (ex. github issues page, google search result, firefox add-ons search result, etc.)
2. Save sessions with Tab Session Manager.
3. Restore saved sessions with Tab Session Manager.
4. Exit firefox.
5. Launch firefox again.
6. Check auto saved sessions with Tab Session Manager.
7. You can see some tabs are saved as about:blank.

**Comment by sienori** [comment]
I plan to fix it sometime soon.

**Comment by sienori** [comment]
I fixed it.
It will not happen if you close the window after all tabs have been loaded.
https://github.com/sienori/Tab-Session-Manager/commit/e201220b38ca38800db5bc47d84f6f353e9b0954

**Comment by shelaf** [comment]
Looks good to me
