### ISSUE TITLE
Sessions disappeared 

### ISSUE THREAD

**Issue by Helstar74** [sienori/Tab-Session-Manager#260]
Hello, I had the "disappearing sessions" problem today, after an automatic update (eventhough automation was disabled...), and i wish i could knew beforehand - you should have sent a warning/notification or something.
Now everything is gone and i don't know how to restore the sessions. I tried overwriting 2.1.1, deleting storage folder (of course i made a backup of it), putting again the last version, copying back the storage folder & all the combinations possible, nothing. I'm really mad now...

**Comment by sienori** [comment]
I'm really sorry for the inconvenience.

Is "automatic update" an update to firefox? Or is it TSM update?
If TSM is an update, what is the version of TSM before the update? (2.x.x, or 3.x.x)

**Comment by sienori** [comment]
Same issue: #239

**Comment by AdventureDave82** [comment]
I found the deleted sessions from the Wiki article.  Now how do I restore my old sessions?  I'm not a coder so be careful with the jargon.  Glad you found the error.

**Comment by Helstar74** [comment]
Forget them, they're gone. I don't think anybody succeeded in recovering them, once Firefox and the extension updated themselves.
Never trust 100% these add-ons ... they will pwn you before or after (like it happened with Sessions Manager previously)

**Comment by sienori** [comment]
@AdventureDave82 
I updated the wiki. https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
If you have backed up the storage folder, you can restore the session.

@Helstar74 
I am offering option for sessions backup.
If you use it, sessions stability will increase.
I am terribly sorry...

**Comment by Helstar74** [comment]
I have good news ! The "storage/default/moz-extension+++" Internal UUID copy-paste folder trick worked. Sessions are all back ! Thanks for solving the problem, i was really depressed ^^; !
