### ISSUE TITLE
Questions about bad ratings on AMO

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#267]
For a long time there's been a lot of bad ratings on AMO claiming the addon does not work or that it does not restore all the tabs and that it loses sessions. I've used this addon on and off but I dont fully commit to it due to fear. How true are this accusations? Why there is no counter measure to either inform that the problems are not related to the addon or that are due to miss use/miss information that causes this for them or why there is not a clear communication to let the users know that X update version fixed the problem?

If the addon is having issues keeping the data if possible why does the addon not force an automatic backup that is restored automatically when the original database load fails or why not use an alternate way of storing sessions in case the primary way fails if the backups are not enough/ you dont want to force them?

BTW Talking to an other dev he told me that IndexDB is local to a certain page and not at browser level. Using WebExtensions storage is guaranteed to be fine even if Firefox crashes while IndexDB or page local storage can be corrupted in such cases so wouldnt it be better to keep localstorage if using indexDB is going to further create issues with people loosing their sessions? (At this point I think stability would be key to focus on).

**Comment by sienori** [comment]
In the current version, I think that the problem of losing session is solved.
I am showing add-on improvements with version information, but older reviewers often do not update ratings.
I currently answer questions only with email and github.
It is hard to respond to all reviews, but I want to answer if I have time.

**I believe that IndexedDB is best for storing sessions.**
Local storage has capacity limitation. It is not enough to save a lot of sessions.
Also, webextensions storage sometimes breaks when firefox crashes (It's like a nightmare...).
A problem that IndexedDB can not be used depending on firefox profile has been reported, but I show a solution.
For now, the problem of lost indexedDB data has **not** been reported.

BTW I am a beginner in English. It is difficult for me to read a sentence that is too long...

**Comment by laktak** [comment]
fyi - I just installed the extension and got the indexdb error. https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error#what-is-this did not help - so I gave up.

**Comment by RobertAb1** [comment]
Do you still need this bug fixed?
https://bugzilla.mozilla.org/show_bug.cgi?id=944918

**Comment by sienori** [comment]
@laktak 
IndexedDB error occurs when the firefox setting is set not to remenber the history. https://github.com/sienori/Tab-Session-Manager/issues/281
I added a solution to the wiki. Is this solution helpful to you?
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error#firefox-setting-is-set-not-to-remenber-the-history

@RobertAb1 
I hope this bug will be fixed.

**Comment by RobertAb1** [comment]
@sienori
I have added [bug 944918](https://bugzilla.mozilla.org/show_bug.cgi?id=944918) as depended of meta-bug for session managers ([bug 1427928](https://bugzilla.mozilla.org/show_bug.cgi?id=1427928)) on Bugzilla, and to the voting list.

Do you need other bugs fixed other then on voting list?
https://www.reddit.com/r/firefox/comments/7m8nvx/can_session_manager_tab_session_manager_coexist/drslt43/
https://github.com/sienori/Tab-Session-Manager/issues/150

It will great if you could notify me by e-mail if you need other bugs fixed.

**Comment by RobertAb1** [comment]
Comment by Alan976:
https://www.reddit.com/r/firefox/comments/9c2q9m/indexeddb_broken_unknownerror_error_opening/

**Comment by RobertAb1** [comment]
@sienori

**Comment by RobertAb1** [comment]
@sienori
Finally. Bug 944918 was assigned.
See also comment made on Trello on 2018-09-04.
Seniori - you may follow this bug, so the problem with database will be solved and it will be not affecting Tab Session Manager.
