### ISSUE TITLE
Closed Twitch.tv tabs are being saved.

### ISSUE THREAD

**Issue by WhiteDragonD** [sienori/Tab-Session-Manager#268]
## Short description
I had a few twitch.tv tabs opened, closed them, saved my session, the closed tabs were exported and reopened when I restarted Firefox.

## Steps to reproduce
I can delete all my sessions in the options, close all the twitch.tv tabs, then save the window.
When I export, I can see the closed tabs in the .json file.

## Expected result
Closed tabs shouldn't be saved.

## Platform information
* Platform (OS): Windows 7
* Version of Firefox: 61.0 (64-bit)
* Version of Tab Session Manager: 3.2.0

**Comment by sienori** [comment]
It is normal behavior.
When autosave(window close) option is enabled, TSM saves hidden sessions each time the tab changes.
It is recorded in the json file, but it will not be displayed even if it is imported.
