### ISSUE TITLE
GUI context menu in sessions list is cut off

### ISSUE THREAD

**Issue by ronso0** [sienori/Tab-Session-Manager#286]
At first I was a bit puzzled that all those 'Replace' options seemed to be gone..

Can the menu position be improved?

![tab_session](https://user-images.githubusercontent.com/5934199/44433827-3f4e8780-a5a8-11e8-987e-f8ad076df57f.png)

Ubuntu Studio 18.04.1 64bit, xfce4, ff 61.0.1
Tab Session Manager 3.2.0

**Comment by sienori** [comment]
I improved the behavior of the menu.
It will be effective from the next version.
![improved menu](https://i.gyazo.com/c8747977e333c4b7d80d0233765f14e6.gif)

**Comment by ronso0** [comment]
Thanks for picking this up, it's a great improvement!
