### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by meoso** [sienori/Tab-Session-Manager#29]
I love this product; however, i just deleted wrong session-saves due to the layout.
Please move Open and Remove links inside the box, just under the session name.

Also, the list does not fill the dialog box.

Please see this image for visual explanation:
[![Screenshot_2017-11-08_09-47-48.png](https://s26.postimg.org/bxr2i7dvd/Screenshot_2017-11-08_09-47-48.png)](https://postimg.org/image/4hrsweq5x/)

Thank you very kindly.

Firefox 56.0.2
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by sienori** [comment]
Layout problems will be fixed soon.
UI changes such as open / remove will take a while.

**Comment by sienori** [comment]
I fix it.
https://github.com/sienori/Tab-Session-Manager/commit/077bcd4bd1920a8c9d93dbc9612d9cdd2e37e165
