### ISSUE TITLE
Recently Closed Tabs Reload Upon Selecting Session

### ISSUE THREAD

**Issue by invalidbeard** [sienori/Tab-Session-Manager#290]
## Short description
Recently Closed Tabs Reload Upon Selecting Session

## Steps to reproduce

1. Start Firefox with clean profile
2. Install Tab Session Manager
3. I use "Undo Tab Tab"
4. Load saved profile sessions. 
5. Tabs closed during that session reload.

**Comment by sienori** [comment]
Due to the webExtensions specification, it is impossible to edit recently closed tabs.

**Comment by invalidbeard** [comment]
Thank you for responding. Just to make sure I was clear, I am not requesting that Recently Closed Tabs be edited. The issue is that Recently Closed Tabs are loading as active tabs when selecting a session.

**Comment by sienori** [comment]
Sorry for the misunderstanding.
I will think about this issue.

**Comment by RobertAb1** [comment]
@sienori 
Can you create new bug at Mozilla Bugzilla and let me know?

**Comment by PaddlesAU** [comment]
Hi. I've been having this issue as well. I also use "Undo Close Tab" extension, but the problem occurs even if Undo Close Tab is disabled.
