### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by visualwind** [sienori/Tab-Session-Manager#291]
Hello, I forget to backup the data. After a crush, I lost all tab backups. I suggets you to save datas to bookmarks with date folders.

**Comment by sienori** [comment]
Sorry for the inconvenience.
Please see below for how to fix DB error:
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

I recommend using the **local backup option** or the **cloud sync function** in case the session is lost.
![backup](https://user-images.githubusercontent.com/29514424/78506378-07637a80-77b4-11ea-9908-a6bbe9a99c2d.png)
