### ISSUE TITLE
File Not Found after update

### ISSUE THREAD

**Issue by godlike13** [sienori/Tab-Session-Manager#297]
Seems like all my tabs are showing 'File Not Found' after the recent update on the addon.

Any idea how to fix this instead having me to manually cut-n-paste updating every tabs?

**Comment by sienori** [comment]
I interpreted as follows. is it right?
1. You were browsing after opening a session with TSM
2. The add-on was updated and some already opened pages changed to File Not Found

Does the URL of the File Not Found page start with `moz-extension://`?
Please save the current session and open it again. I think the page will load correctly.

**Comment by dajiahao** [comment]
the URL starts indeed with moz-extension://  
but restarting or save and load won't help ... only solution seems to be ugly copy&paste

**Comment by sienori** [comment]
Hmm... 
Once you install [version 3.2.0](https://addons.mozilla.org/firefox/addon/tab-session-manager/versions/?page=1#version-3.2.0), save the current session, then update to version 4.0.1 and restore it, you can load the page.

Caution:
Please **disable** the option restore last session on startup.
Do **NOT** uninstall the add-on

**Comment by r00li** [comment]
I had the same issue with 4.0.1 and this solution helped. Thanks!

**Comment by kartis56** [comment]
Same  with 4.0.1 by saving oldversion (maybe 3.2.0 ) 
Save all session at 4.0.1 and reload, when active oldversion tab, this  happend.
Such as
>  ファイルが見つかりませんでした
> moz-extension://248d1b94-46e3-4a7d-a9b3-92100916d194/replaced/replaced.html?state=redirect&title=(etc.)
Copy from &url=https://  manualy, and paste to new tab, then it restored 

Old json file date 2018/09/15 =                    "url": "http://food.ismedia.jp/category/diamond_sub26?page=2",

But New json file date 2018/09/22 =                    "url": "moz-extension://248d1b94-46e3-4a7d-a9b3-92100916d194/replaced/replaced.html?state=redirect&title=%E9%A3%9F%E3%81%AE%E7%A0%94%E7%A9%B6%E6%89%80&url=http%3A//food.ismedia.jp/subcategory/%25E6%2597%25A5%25E6%259C%25AC%25E3%2581%25A8%25E4%25B8%2596%25E7%2595%258C%25E3%2581%25AE%25E9%25A3%259F%25E4%25BA%258B%25E6%2583%2585%3Fpage%3D10&favIconUrl=http%3A//food.ismedia.jp/favicon.ico",

so unreadable.

**Comment by sienori** [comment]
@kartis56 
Please do the following steps.

0.  (In version 4.0.1, you have NotFound pages)
1.  Install version 3.2.0
2.  Save the current session
3.  Update to version 4.0.1
4.  Restore session saved in version 3.2.0

**Comment by kartis56** [comment]
Thank you for quick response, but this works not full...

>(In version 4.0.1, you have NotFound pages)
>Install version 3.2.0
>Save the current session

This saved sometimes "active TAB" only, So NEED all tabs be actived
And somtimes saved all tabs, but all inactived tabs restored as moz-extension:// 

I found about:hogehoge ( suchas about:support ) cannot resotred at ver 3.2.0 tha saved ver 3.2.0
Is this hint?

**Comment by kartis56** [comment]
At 3.2.0, need twice click to reload tab.
First loaded as moz-extension://hogehoge, Second  TSM load URL. 
maybe when second load moz-extension://hogehoge,  addon isnot called ?

**Comment by sienori** [comment]
@kartis56 
> At 3.2.0, need twice click to reload tab.

That behavior is not strange.
When the `moz-extension://` page is loaded and the tab is focused, the URL is loaded.
This problem only occurs when updating to version 4.0.0.
If you update the add-on and load all the tabs, you can use it after that without problems.
Sorry for the inconvenience. Thank you for your understanding.

**Comment by boistordu** [comment]
Wait a sec, I'm not sure I quite follow here. 
I have also this error and I'm 99% sure that those tabs were already opened when your plugin was version 4.0.0. When was release v4? Maybe of course I'm wrong because of my recollection of the timeline but I have a big doubt here. 
and so the problem occurred only between v3.9 and v4.0 ? 
what would I propose if it's possible,
Next time, there is an upgrade, I don't know if it is possible but that a script is launched to export all the session automatically and that the session are reread from those files... would that be possible?

**Comment by hackel** [comment]
I just got hit by this as well.  Hundreds of saved tabs trying to navigate to this now non-existent extension UUID.  Since the add-on automatically updated, you've really got to come up with a better upgrade solution!  I will try the downgrade, save, upgrade, restore workaround, but this is not idea.  It also makes me worried about other saved sessions I have that are not active.  There is no easy way to restore these sessions other than manually plucking the redirect URL.

**Comment by infoscoot** [comment]
I have the same issue,but i can´t install 3.2 version properly,I go to [https://addons.mozilla.org/firefox/addon/tab-session-manager/versions/?page=1#version-3.2.0](url) ,download a exe file and executing, the process finish ok but when open firefox the add-on no appears!Whats wrong?I need to recover my tabs!Thanks

**Comment by kartis56** [comment]
> This saved sometimes "active TAB" only, So NEED all tabs be actived
This re-happend at ver4.0.2 when I'm use restart addon, that is old addon.

**Comment by hackel** [comment]
@infoscoot Never install random exe files off the internet!  The only files you should be downloading from AMO are xpi files, but even that should be transparent from a user perspective.  It sounds like your issue is unrelated to this extension.

@kartis56 Also sounds unrelated to this extension.

**Comment by Stoneywood** [comment]
Pulling my hair out here hoping you can help. I have been using tab session manager for sometime now with little to no issues.

Firefox decided to crash and update a few days ago, upon restarting all of my extensions had to be restarted too and my session with over 100 tabs did not load which it normally would even after a restart.

I checked my tab session manager dropdown menu and low and behold all of my saved sessions appeared to be wiped clean.

After further digging I find two different folders with both .session files and .json files in an "old firefox data" folder.

One folder is titled "Sessions" the other is titled "sessionstore-backups"

I have .session files in the "Sessions" folder however these only date to late 2017.

I have .json files in the "sessionstore-backups" folder and they are dated up to 30th September 2018, great stuff I think, this must be my recent saved session.

When I use the import function however these files fail to read when importing, I then hit the import button regardless and a message appears "Sessions imported", great news, they must now be saved in my tab sessions manager extension but low and behold they are nowhere to be seen.

I have downgraded to version 3.2, still not able to import the .json files and still not seeing my old sessions in the dropdown menu so please if someone could shed some light as to what the heck has went on here I would greatly appreciate it, if I had a few tabs to recover I wouldn't even bother but I have at least over 100 tabs in that session I need to restore thanks in advance.

**Comment by sienori** [comment]
I fixed this problem. https://github.com/sienori/Tab-Session-Manager/commit/a2374d6d6438cea9e627f28c7b463cb0db6e9c61
Sorry for the inconvenience.

**Comment by Stoneywood** [comment]
Hey thanks for this but I still can not access my old sessions?


I have updated the extension but I still can not import the sessions I had just before the update.

________________________________

**Comment by Stoneywood** [comment]
?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sienori** [comment]
@Stoneywood 
Tab Session Manager only supports importing `.session` file of Session Manager and `.json` file of Tab Session Manager.
The `.json` file in the `sessionstore-backups` folder can not be imported.
It is the folder to save previous Firefox sessions.
This page may be helpful: https://support.mozilla.org/en-US/questions/1221836

Also, You seem to be talking about a different topic than this issue.
If you want continue this discussion, I encourage you to post a new issue.

**Comment by Stoneywood** [comment]
Can you please advise then how I can restore my session before the firefox update?



________________________________

**Comment by kartis56** [comment]
@Stoneywood
> Can you please advise then how I can restore my session before the firefox update?

Maybe you can restore from TSM autobackup or exported session file. I did it from autobackup
