### ISSUE TITLE
Inconsistent naming of files and import statements

### ISSUE THREAD

**Issue by mirkogrcic** [sienori/Tab-Session-Manager#299]
## Short description
Unable to build on Linux on EXT4 file system due to inconsistent naming of files and import statements

## Steps to reproduce

1. Clone the repo locally on an Linux OS like Fedora 28
2. Enter the "Tab-Session-Manager" directory
3. Run "npm install"
4. Run "npm run build"

## Expected result
Successful build

## Actual result
Multiple errors while building
```Module not found: Error: Can't resolve '../styles/categoryContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'```
The file is available as "CategoryContainer.scss".
Note the first letter C in category on import statement and file name

## Platform information
* Platform (OS): Fedora 28
* Version of Firefox: Not important for building
* Version of Tab Session Manager: Not important for building

## Additional context
No

## Solution
I'm considering making the changes myself and making a pull request, would it be better to make the imports first letter upper case or the files first letter lower case?
In my opinion it would be better to update the import statements (may take longer which I don't mind)

**Comment by sienori** [comment]
Thanks for the report!
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/2ce34f5b7466463a9e77f983e64ba7f38f9ffa2e

**Comment by mirkogrcic** [comment]
Its not just that file, I put the files just as an example, here is the full error list:
```
    ERROR in ./src/options/components/CategoryContainer.js
    Module not found: Error: Can't resolve '../styles/categoryContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/NameContainer.js
    Module not found: Error: Can't resolve '../styles/nameContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
    ERROR in ./src/options/components/OptionContainer.js
    Module not found: Error: Can't resolve '../styles/optionContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/SessionsArea.js
    Module not found: Error: Can't resolve '../styles/sessionsArea.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
    ERROR in ./src/options/components/CategoryContainer.js
    Module not found: Error: Can't resolve '../styles/categoryContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/NameContainer.js
    Module not found: Error: Can't resolve '../styles/nameContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
    ERROR in ./src/options/components/OptionContainer.js
    Module not found: Error: Can't resolve '../styles/optionContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/SessionsArea.js
    Module not found: Error: Can't resolve '../styles/sessionsArea.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
    ERROR in ./src/options/components/CategoryContainer.js
    Module not found: Error: Can't resolve '../styles/categoryContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/NameContainer.js
    Module not found: Error: Can't resolve '../styles/nameContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
    ERROR in ./src/options/components/OptionContainer.js
    Module not found: Error: Can't resolve '../styles/optionContainer.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/options/components'
    ERROR in ./src/popup/components/SessionsArea.js
    Module not found: Error: Can't resolve '../styles/sessionsArea.scss' in '/home/mirko/git/mirkogrcic/Tab-Session-Manager/src/popup/components'
```

**Comment by sienori** [comment]
I fixed three more files. https://github.com/sienori/Tab-Session-Manager/commit/030e5c652ff7452b92efb7e3d586af0a211c5aee

**Comment by mirkogrcic** [comment]
Build successful, thanks.
