### ISSUE TITLE
Add current window to an existing saved session?

### ISSUE THREAD

**Issue by vchang-akamai** [sienori/Tab-Session-Manager#300]
Is it possible to add the current window to an existing saved session?

I see options for replacing a saved session with current windows (or all windows), but I want to keep what's already saved, and add a new window to it.

**Comment by sienori** [comment]
I implemented the function to add current window to an existing session in version 4.4.0.

**Comment by Aezaeo** [comment]
Awesome, going to have to try it out, thanks!

**Comment by vchang-akamai** [comment]
I noticed this new feature by chance last night. It does what I was hoping for. Thanks for adding!!

**Comment by futagoza** [comment]
@sienori Shouldn't you close this now?
