### ISSUE TITLE
Feature Request: Option to not show info page on upgrade.

### ISSUE THREAD

**Issue by MadscientistCC** [sienori/Tab-Session-Manager#305]
Just a small feature request.

Can we get an option to prevent the information page from opening when the extension is upgraded.

Most addons have this option, or don't show anything, and it seems weird that Tab Session Manager always shows something when upgraded.

**Comment by sienori** [comment]
I added that option. https://github.com/sienori/Tab-Session-Manager/commit/ecdbc7118bcef103ff271a54c0e59dbe27472018

**Comment by MadscientistCC** [comment]
Much appreciated!
