### ISSUE TITLE
Makes assumptions about text color (i.e. unreadable with dark theme)

### ISSUE THREAD

**Issue by Zer0t3ch** [sienori/Tab-Session-Manager#308]
## Short description
Unreadable text. 

## Steps to reproduce

1. Start Firefox with clean profile
2. Install Tab Session Manager
3. Open Tab Session Manager

## Expected result
Readable text

## Actual result
Unreadable text
![image](https://user-images.githubusercontent.com/1359291/46359044-f4577380-c62d-11e8-8e24-ae53d83547bd.png)

## Platform information
* Platform (OS): Linux (OpenSUSE Tumbleweed)
* Version of Firefox: 61.0.2
* Version of Tab Session Manager: 4.0.2

![image](https://user-images.githubusercontent.com/1359291/46359123-28cb2f80-c62e-11e8-8021-c2abbbc4f009.png)

## Additional context
Not sure if the theme causing it is the GTK theme (Breeze Dark, IIRC) or the FF theme.

**Comment by sienori** [comment]
It seems to be due to OS theme.
I fixed this problem. Did it solve in your environment? https://github.com/sienori/Tab-Session-Manager/commit/17f247c3f573b6ec6014e952007371e2f07fb033
