### ISSUE TITLE
Restore does not work

### ISSUE THREAD

**Issue by chemag** [sienori/Tab-Session-Manager#309]
## Short description
Restore does not work. Note that the "Save" button in the TSM window does not work either (clicking on it does not do anything).

## Steps to reproduce
1. Start Firefox
2. Restore a TSM saved state
3. Wait until all the windows are open
4. Check any of the tabs of a window but the one in focus

## Expected result
The contents of the window itself.

## Actual result
A "Problem Loading Page" error with the following message:

```
File not found

Firefox can’t find the file at jar:file:///dotmozillafirefoxdirectory/extensions/Tab-Session-Manager@sienori.xpi!/replaced/replaced.html?state=redirect&title=systemd-resolved resolvconf unbound - Google Search&url=https://www.google.com/search?client=ubuntu&channel=fs&q=systemd-resolved resolvconf unbound&ie=utf-8&oe=utf-8&favIconUrl=https://www.google.com/images/branding/product/ico/googleg_lodp.ico.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```
Note that the file mentioned above does exist:

```
$ file dotmozillafirefoxdirectory/extensions/Tab-Session-Manager@sienori.xpi 
dotmozillafirefoxdirectory/extensions/Tab-Session-Manager@sienori.xpi: Zip archive data, at least v2.0 to extract
```

## Platform information
* Platform (OS): Linux Ubnutu 18.04
* Version of Firefox: Firefox Quantum 62.0 (64-bit)
* Version of Tab Session Manager: 4.0.2,

**Comment by sienori** [comment]
I fixed this problem. https://github.com/sienori/Tab-Session-Manager/issues/297 a2374d6
Sorry for the inconvenience.

**Comment by chemag** [comment]
Thanks

**Comment by chemag** [comment]
Updated to 4.1.0, and seems to be working
