### ISSUE TITLE
auto saving closed window with option set off

### ISSUE THREAD

**Issue by meoso** [sienori/Tab-Session-Manager#31]
It is auto-saving upon window close even though i turned it off.

Firefox 56.0.2
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by sienori** [comment]
I tried it in the same environment as you, but it did not happen.
Have you pressed the save setting button?
Does it happen if you restart the browser?

**Comment by meoso** [comment]
definitely pressed "save". i set max to "1" so that i'm not flooded with them.  i've restarted a million times.  not a huge problem.

[![config image](https://s26.postimg.org/3m9p46321/20171115_Selection_002.png)](https://postimg.org/image/5e2nz2met/)
[![proof image](https://s26.postimg.org/nsd731ypl/Screenshot_2017-11-15_11-25-43.png)](https://postimg.org/image/62bii0l4l/)

**Comment by mjr66** [comment]
Seeing the same behaviour here, I'm afraid.

Can't seem to see a "save settings" button anywhere, but I have the same settings as meoso and they are remembered between Firefox sessions, so maybe there's no need to manually save them by now.

**Comment by sienori** [comment]
I fix it.
The problem occurred when firefox was started with setting off.
https://github.com/sienori/Tab-Session-Manager/commit/9697e3fc322844aafc277a947bac8fcd6e4d9adf

**Comment by fnagel** [comment]
Same here. Option does not work at all.

**Comment by mjr66** [comment]
Seems to be fixed now. Thanks!
