### ISSUE TITLE
Auto save doesn't work

### ISSUE THREAD

**Issue by ItielMaN** [sienori/Tab-Session-Manager#312]
## Short description
Auto save doesn't work. Used to some time ago but not anymore.

## Steps to reproduce
I'm pretty sure this STR won't reproduce on other systems, but here goes:
1. Install Tab Session Manager
2. On TSM settings, enable all auto save options
3. Set interval to 15 & Maximum number Saved to 100000
4. (Probably optional) Uncheck "Tab lazy loading"

## Expected result
TSM will auto save sessions every 15 minutes.

## Actual result
TSM doesn't auto save at all.

## Platform information
* Platform (OS): Windows 10 x86
* Version of Firefox: 64.0a1 (updated Nightly)
* Version of Tab Session Manager: 4.0.2

## Additional context
TSM is actually able to save session when I do so manually, but since about half a year ago it will no longer auto save.
There was a time where TSM did actually autosave the session, but only for 20 times (10 regularly and 10 Window was closed).
I haven't tried TSM's auto save on a fresh profile as I believe it'd work. I'm trying to figure out what's wrong with TSM in my profile.

I didn't think screenshots or screencasts would be necessary here; if extra info is needed I'll be happy to provide it.

**Comment by Vaibhav** [comment]
I could not reproduce this

**Comment by sienori** [comment]
I can not reproduce too.
Please enable debug mode and show me the log.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

**Comment by ItielMaN** [comment]
> So, to show you an informative log for this issue, I should leave the debugger thingy open and wait until the time specified (in the interval on the TSM settings) passes, and post the log afterwards?

Assuming the answer to this is 'yes', then all I see is:
`Use of nsIFile in content process is deprecated.      NetUtil.jsm:259:12`

**Comment by ItielMaN** [comment]
Here's all my settings for TSM:

```
        Tab lazy loading  -  disabled

            Use the "discarded" property for lazy loading  -  enabled

        Save private window  -  disabled

        Restore windows position  -  enabled

        Supports Tree Style Tab  -  enabled

            Delay when tree restoration (millisecond)  -  150

        Date format  -  YYYY.MM.DD HH:mm:ss

        Save the session regularly  -  enabled

            Interval (minutes)  -  15

            Maximum number Saved  -  100000

        Save the session when window was closed  -  enabled

            Maximum number Saved  -  100000

        Save the session when exiting browser  -  enabled

            Maximum number Saved  -  10

        Use page title for auto save session name  -  enabled

        Restore previous session at startup  -  disabled

        Save backup  -  disabled

            Save location  -  TabSessionManager - Backup

        Open button behavior  -  Open in new window

        Save button behavior  -  Save all windows

        Display the search bar  -  enabled

        Display session name within one line  -  disabled

        Size

            Width  -  350

            Height  -  500

        Display option page when updating  -  enabled

        Enable debug mode  -  enabled
```

**Comment by sienori** [comment]
> Assuming the answer to this is 'yes', then all I see is:
> `Use of nsIFile in content process is deprecated. NetUtil.jsm:259:12`

Thank you for the report.
Please try the following method. Is the log displayed?
1. Set the auto save interval to `0.1` (and debug mode to enabled)
2. Restart browser
3. Show log

If possible please attach a screenshot of the debugger.

**Comment by ItielMaN** [comment]
You got it:
![default](https://user-images.githubusercontent.com/18016656/48672744-8108b300-eb42-11e8-823a-3ecf3e94f763.png)

**Comment by sienori** [comment]
Thanks.
I updated the output logs in version 4.3.1. 
Please show me the logs again.

**Comment by sienori** [comment]
Sorry, I made a mistake in the program...
I published version 4.3.2 so please show me the log again

**Comment by ItielMaN** [comment]
> Sorry, I made a mistake in the program...
> I published version 4.3.2 so please show me the log again.

No problem!
![default](https://user-images.githubusercontent.com/18016656/48675295-e28b4a80-eb5f-11e8-9b3f-4819a18551f5.png)

**Comment by sienori** [comment]
Thanks.

It seems that session data saved in past versions to be in an incorrect format for some reason.
A quick way to solve it is to reinstall Tab Session Manager.
Please **export the existing session**, delete the Tab Session Manager and install it.

**Comment by ItielMaN** [comment]
> Thanks.
> 
> It seems that session data saved in past versions to be in an incorrect format for some reason.
> A quick way to solve it is to reinstall Tab Session Manager.
> Please **export the existing session**, delete the Tab Session Manager and install it.

Not sure why I didn't try this myself before..
Thanks, look like this worked.

Well, not 100% as the interval (set to 0.1) is not really honored (session is not saved if the tabs count doesn't change [or something similar]), but this is another issue.
Now TSM at least can auto-save my session.

Thank you!

**Comment by sienori** [comment]
Good.

>Well, not 100% as the interval (set to 0.1) is not really honored (session is not saved if the tabs count doesn't change [or something similar]), but this is another issue.
Now TSM at least can auto-save my session.

Auto save is executed only when changing any tabs.

**Comment by ItielMaN** [comment]
> Auto save is executed only when changing any tabs.

changing any tabs = switching to another tab, or adding/closing tabs?

I think this ticket can be closed now.

Oh and forgot to say- you've got an awesome addon! :)
