### ISSUE TITLE
Save state of "category filter" selector dropdown

### ISSUE THREAD

**Issue by ddirks** [sienori/Tab-Session-Manager#314]
**Is your feature request related to a problem? Please describe.**
This is perhaps a small issue, but a fix would make using TSM more seamless (for me, anyway) and it seems like the necessary change might be easy and low-impact.

I have several "user defined" sessions set up to open in separate browser windows. I use these to keep groups of related tasks/sites neatly organized. I generally open each of the user defined sessions every day. To do this, I  click on the TSM icon to display the session-chooser pane, then select "User Saved" from the "category filter" dropdown (the one at the top of the TSM pane), then select one of my "user defined" sessions to restore.

**Describe the solution you'd like**
Rather than having the "category filter" dropdown default to "All," have it select the most recently used option. That is, if I select "User Saved," the next time I open the TSM pane it opens to the "User Saved" list instead of "All." This allows me to pick my predefined session with a single click. Those who prefer the current functionality can just leave the "category filter" set on "All."

As a side note, it seems like TSM behaved as I'm describing for a while (that is, remembering which "category filter" I had last selected). Buy my memory may be faulty...

**Describe alternatives you've considered**
The alternative is easy and works fine -- just taking the extra step to select "User Saved" from the dropdown. This change would just be a small quality-of-life improvement.

**Comment by sienori** [comment]
Thanks for the report!
It seems to be a bug occurred in version 4.1.0.
I fixed this issue. https://github.com/sienori/Tab-Session-Manager/commit/d0dfe3df5822a969a4b87ec949b16ab756d4b9c2

**Comment by ddirks** [comment]
Fantastic! Thanks for your quick response...
