### ISSUE TITLE
TSM with hundreds of tabs - undeterministic behaviour when restarting FF

### ISSUE THREAD

**Issue by przemolb** [sienori/Tab-Session-Manager#315]
## Short description
I am using TSM on MacOS with (currently) FF 62.*.
I usually have a few hundreds of tabs opened. When I restart FF it looks like TSM is trying to load all of them and my FF is not usable (allocating more and more memory) so I have to kill the FF. And try to restart it again. And it repeats again.
After several attempts, it finally works.
I have `Tab lazy loading` setting enabled (!) all the time.

## Platform information
* Platform (OS): MacOS High Sierra
* Version of browser: FF 60.* / 61.* / 62.*
* Version of Tab Session Manager: currently 4.1 (but the same happened with earlier releases as well)

**Comment by sienori** [comment]
Have you disabled the option to restore the previous session at startup?

**Comment by wbt** [comment]
@przemolb Have you tried it with `tab lazy loading` deselected/disabled, counterintuitive as that may be?

**Comment by wbt** [comment]
@przemolb I know it's a counterintuitive attempt strategy, but [multiple](https://github.com/sienori/Tab-Session-Manager/issues/249#issuecomment-403110728) [comments](https://github.com/sienori/Tab-Session-Manager/issues/249#issuecomment-403180820) on Issue #249 suggest that the lazy loading may not be impacting memory usage in the expected way.

**Comment by przemolb** [comment]
@sienori, @wbt that doesn't work. I mean I didn't find any difference between the two modes - both are taking ages (I am writing this using Chrome because FF is unusable).
I don't understand why when I tick the `tab lazy loading` TSM is doing anything in the background. It should start as many tabs as were saved and keep them quiet. Until I select one of them. But it doesn't work that way - I have the dots shifting from left to right and back on all tabs.
And eats up all the memory ...
I like this addon but I am always expecting the worst when I have to restart FF ...

**Comment by przemolb** [comment]
@sienori any debugging I can enable and help with investigating this issue?

**Comment by sienori** [comment]
Have you disabled Firefox option to restore the previous session?
![Firefox option](https://prod-cdn.sumo.mozilla.net/uploads/gallery/images/2018-06-07-19-34-46-e893a9.png)
It can not be used at the same time.

**Comment by przemolb** [comment]
@sienori yes I have disabled Firefox option to restore the previous session.

**Comment by hmijail** [comment]
Seeing the same problem for the last few versions of Firefox beta (right now at 64.0b3) on macOS. About 300 tabs, >50GB allocated - after which it slowly starts deallocating down to about 1 GB. It's so bad that I've gotten used to disabling TSM before trying to restore a session.
I'm using TreeStyleTabs too, which also has its own problems. Not sure if one might be affecting the other.

**Comment by przemolb** [comment]
@sienori is there any way I can enable debugging or verbose mode? 
<img width="470" alt="screen shot 2018-10-24 at 11 11 02" src="https://user-images.githubusercontent.com/5048651/47423673-8f4ef380-d77d-11e8-97fd-7b4d1c03c9a7.png">
I can see that it is eating up all memory but don't know why :-(

**Comment by przemolb** [comment]
@sienori with these settings all is working very well - FF starts very quickly and is responsive and then TSM opens all windows and tabs very quickly as well. It seems that for now, this is the right workaround to use.

**Comment by WPFilmmaker** [comment]
I don't know it is related but I never encountered any issue with TSM but since FF 63 update (on Linux), TSM makes FF slow and unresponsive...Disabling it fixes the issues. Am I the only one to have this problem?

**Comment by WPFilmmaker** [comment]
@sienori It seems that with FF 63 something changed and several users reported sluggish browser after the update (like here: https://old.reddit.com/r/firefox/comments/9riy4f/firefox_63_is_slow_at_loading_new_pages/ and here here: https://old.reddit.com/r/firefox/comments/9rtaad/with_version_630_youtube_lags_when_watching_1080p/ ).

I have no idea what changed but it seems that on linux certain addons make the browser slow.

I am using also decentraleyes and following this: https://git.synz.io/Synzvato/decentraleyes/issues/323 I disabled it and now the browser works fine without needing to change settings in TSM or disabling it.

It is very puzzling :/ do you have any idea if FF changed something which messes up with cetain addons in the 63 version?

**Comment by sienori** [comment]
@WPFilmmaker 
It does not seem to be Tab Session Manager specific problem. I do not have any idea...
If you want to continue this discussion please post a new issue.

**Comment by sienori** [comment]
@przemolb 
I fixed the memory leak problem! https://github.com/sienori/Tab-Session-Manager/commit/90390af779b9ea5c8fa19468f0a41054e93815b2
