### ISSUE TITLE
The list box does not remember last state, it selects "All" every time I click the TSM icon

### ISSUE THREAD

**Issue by mirkogrcic** [sienori/Tab-Session-Manager#316]
## Short description
The list box state for selecting "All", "User Saved"... is not preserved after closing the Tab Session Manager window

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. Click the Tab Session Manager icon
4. Click the list box and select "User Saved"
5. Close the Tab Session Manager window by click outside of it
6. Click the Tab Session Manager icon again
7. The list box selection is returned to "All"

## Expected result
"User Saved" needs to be selected, before the 4.1.0 version this worked
![image](https://user-images.githubusercontent.com/11380296/46965510-6064bd80-d0ab-11e8-84b8-3aa23bfad68d.png)

## Actual result
"All" is selected
![Image of the list box](https://user-images.githubusercontent.com/11380296/46964571-bbe17c00-d0a8-11e8-83f0-021963f2a6ae.png)

## Platform information
* Platform (OS): Fedora 28
* Version of browser: Mozilla Firefox 62.0.3 (64-bit), Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Version of Tab Session Manager: 4.1.0

## Additional context
I built the Chrome version using `npm run-script build`
The Firefox one is from the official Firefox site

**Comment by sienori** [comment]
I fixed this problem. #314

**Comment by mirkogrcic** [comment]
Thank you
