### ISSUE TITLE
all sessions gone on restart, no error message

### ISSUE THREAD

**Issue by xvazquezc** [sienori/Tab-Session-Manager#317]
Hi @sienori ,

I have just restarted Firefox and all sessions were gone. I have had issues before but TSM would show an error message (often IndexedDB error) and I would be able to restore the sessions following the steps indicated in the wiki.

This time TSM is simply blank. Number sessions is zero and no error message of any type. I tried to recover them using the recommended steps but nothing shows up no matter what I do.

I'm using Firefox 62.0.3 (x64) with TSM 4.1.0 in Ubuntu 16.04.

**Comment by sienori** [comment]
Sorry for the inconvenience...
Did the problem occur when updating Tab Session Manager?
In other words, did you use version 4.1.0 before restarting Firefox?
If the problem occurs when updating from version 2 or earlier to version 4.1.0, I may know the cause.

**Comment by xvazquezc** [comment]
Not that I'm aware, but I hadn't restarted Firefox for days (I think).
Definitely not updating from v2 or earlier

**Comment by xvazquezc** [comment]
Could it be that some of the files related to the db is corrupted?
I realised that after deleting `storage` and placing back a copy of the TMS' folder, it cannot save sessions any more. Is there any way to check which one is the responsible?

These are the contents of the folder:
```
moz-extension+++afbb73b5-65e3-42a9-9cf3-d7d73f379e1c
├── idb
│   ├── 1782160246ssensosi.files
│   │   ├── 5799
│   │   ├── 5926
│   │   ├── 5946
│   │   ├── 6462
│   │   ├── 6616
│   │   ├── 6847
│   │   ├── 7184
│   │   ├── 7237
│   │   ├── 7242
│   │   ├── 7261
│   │   ├── 7269
│   │   ├── 7291
│   │   ├── 7324
│   │   ├── 7343
│   │   ├── 7379
│   │   ├── 7395
│   │   ├── 7412
│   │   ├── 7416
│   │   ├── 7427
│   │   └── journals
│   └── 1782160246ssensosi.sqlite
├── .metadata
└── .metadata-v2
```

**Comment by sienori** [comment]
Here is a sample of IndexedDB.
http://www.tohoho-web.com/html5/indexed_db_api_sample.html
Please click `Create` and check whether an error is output.

**Comment by xvazquezc** [comment]
I get no error:

```
----------------------------------------------------
START: createSample()
END : createSample()
START: reqOpen.onupgradeneeded()
EXEC : createObjectStore()
END : reqOpen.onupgradeneeded()
START: reqOpen.onsuccess()
END : reqOpen.onsuccess()
```

**Comment by mrdc** [comment]
I have the same issue: FF 63.0.1, Tab Session Manager 4.2.2. A lot of URLs are gone...
Any way to restore them?

**Comment by mrdc** [comment]
It happened again on FF 66.0.3 32bit and TSM 4.5.2 :( Thanks to backup on each start only some tabs are lost.
For 1782160246ssensosi.sqlite I get "malformed database schema (unique_index_data) - near "WITHOUT":_syntax error" when I try to open it.
In the folder 1782160246ssensosi.files I see files without extensions with name xxxx where x is digit.

**Comment by sienori** [comment]
Sorry for the inconvenience.
Please see below for how to fix DB error:
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

I recommend using the **local backup option** or the **cloud sync function** in case the session is lost.
![backup](https://user-images.githubusercontent.com/29514424/78506378-07637a80-77b4-11ea-9908-a6bbe9a99c2d.png)
