### ISSUE TITLE
[HIGH PRIORITY]restoring session not working

### ISSUE THREAD

**Issue by boistordu** [sienori/Tab-Session-Manager#32]
Doesn't restore any tabs on firefox 56.0.0 fedora 25
If I configure to open in a new window, then it will open a new window, without again restoring the session ...

**Comment by boistordu** [comment]
the restoring function works in windows on new installation. 
Is it a problem with the fact that's an old version ?
Could it be a problem with a previous addon session manager which was obsolete for the 57 v ?

**Comment by sienori** [comment]
In FF56, it is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting.

**Comment by boistordu** [comment]
Okey let me try that in a few moments .

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
it worked athanks :0
