### ISSUE TITLE
Fold away windows in Session Manager view

### ISSUE THREAD

**Issue by lapineige** [sienori/Tab-Session-Manager#321]
Hello,

When I want to restore a session with many windows and/or many tabs in a window, I have to scroll a long time to restore a specific window (or each one, one by one, to reduce the load), because the tab list is long.

Would it be possible to fold away the windows, for instance with a drop-down arrow next to the window name, to (un)fold each window and save some space / readability ?

Thanks :)

**Comment by sienori** [comment]
In version 5, this issue is solved.
