### ISSUE TITLE
TSM doesn't open pinned tabs anymore

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#324]
As per title, it used to work fine but now it doesn't anymore. I don't know if it is related to the new FF (63) or to TSM..

    Platform (OS): Lubuntu 16.04
    Version of Firefox: 63
    Version of Tab Session Manager: 4.2.0

**Comment by sienori** [comment]
I fixed this issue. https://github.com/sienori/Tab-Session-Manager/commit/bbb564c2fb78e8dec93c0d014cea9ba81f2ef769
Thanks for the report!

**Comment by WPFilmmaker** [comment]
@WPFilmmaker Thanks for you for fixing it!
