### ISSUE TITLE
4.2.0 Update Crashes Firefox

### ISSUE THREAD

**Issue by maupassant2** [sienori/Tab-Session-Manager#326]
Automatic update to 4.2.0 crashed Firefox on the spot.
Now, Firefox starts and crashes immediately, unless I disable Tab Session Manager.

* Platform (OS): Windows 10
* Version of browser: Firefox Nightly 65.0a1
* Version of Tab Session Manager: 4.2.0

**Comment by kjetilsg** [comment]
4.2.0 won't open all tabs in a saved session, just some. Also some pinned tabs now opends as regular tabs.
- Platform: MacOS 10.14
- Browser: Firefox 63.0
- Tab Session Manager: Version 4.2.0

**Comment by kermus** [comment]
i also give a vote "Tab-Session-Manager 4.2.0" to crash Firefox 63.0 (64-bit) (win10 pro 1803)

**Comment by sienori** [comment]
Sorry for the inconvenience...

What does a *crash* mean?
* Crash reporter window is displayed
* All windows closes

Have you enabled the option "restore previous session at startup"?

**Comment by apaarfus** [comment]
[2018-10-29_10-03-18.zip](https://github.com/sienori/Tab-Session-Manager/files/2525535/2018-10-29_10-03-18.zip)

I've attached a short clip of the crashing we're probably all experiencing.  It's less of a "Firefox Crashed!", and more of a forced exit.  I can confirm this is occurring on both:

- Windows 10 Pro x64 v1803
- Windows 7 Professional x64 Buikd 7601

In both instances, I'm using some other extensions/mods for Firefox (currently FF 63.0 on both platforms):

Both:
- ShadowFox (basically userchrome.css and similar styles for FF, available here: [https://github.com/overdodactyl/ShadowFox](url)
- Disconnect 5.18.21
- Reddit Enhancement Suite 5.12.6
- uBlock Origin 1.17.2
- Tab Session Manager 4.2.0

Windows 7 Only:
- Humble New Tab Page 1.22

Windows 10 Only:
- HTTPS Everywhere 2018.9.19

---

Unfortunately I'm currently away from my Windows 10 box, though I can attempt to provide additional details from Windows 7.

**Comment by sienori** [comment]
I fixed this issue in ver 4.2.1. https://github.com/sienori/Tab-Session-Manager/commit/907cb094308d92fa13ecc3cd1cafd3a4de6a7a96 https://github.com/sienori/Tab-Session-Manager/commit/bbb564c2fb78e8dec93c0d014cea9ba81f2ef769
Thanks for the report!
