### ISSUE TITLE
Please update for Firefox 57 and migrate my existing saved sessions

### ISSUE THREAD

**Issue by weezer76** [sienori/Tab-Session-Manager#33]
Hello, could you please update for Firefox 57 and migrate my existing saved sessions to the updated extension? Thanks so much!

**Comment by kah0922** [comment]
Uh, this is already updated for Firefox 57. Are you thinking of [Session Manager](https://addons.mozilla.org/en-US/firefox/addon/session-manager/)?

**Comment by weezer76** [comment]
Yes, sorry about that.
