### ISSUE TITLE
Extension update closes most tabs

### ISSUE THREAD

**Issue by geekishly** [sienori/Tab-Session-Manager#330]
## Short description
Whenever this extension has updated in the last week-ish, I've had to reopen a previously saved session because four-fifths of my tabs close in the current session 

## Steps to reproduce

1. Start browser with clean profile
2. Install older version of Tab Session Manager
3. Wait for it to auto-update

## Expected result

A large number of open tabs are closed/disappear

## Actual result

I haven't done this, but since this has happened more than once now... 

## Platform information
* Platform (OS):  Windows 8.1
* Version of browser: 60.0.1
* Version of Tab Session Manager: 4.2.1

**Comment by sienori** [comment]
The option to use "discarded" property for lazy loading is available in firefox 63.
Enabling this option solves the problem of lazy loading tab closing on update. https://github.com/sienori/Tab-Session-Manager/issues/302
