### ISSUE TITLE
TSM Backup stopped working

### ISSUE THREAD

**Issue by 1RonRock** [sienori/Tab-Session-Manager#332]
## Short description
Backups have not been updated for 11 days. 

## Platform information
* Platform (OS): WIN 10
* Version of browser: 63.0.1 64bit
* Version of Tab Session Manager: 4.2.1

## Additional context
This may be related to my previous post. I have tried to find the TSM Backup folder and found that it had not been backed up since 10/28/18. It seems that something has broken. I have restarted the computer as well as FFox several times in attempts to repair the issue.

**Comment by sienori** [comment]
The cause of this problem is the same as  #331.
I think it's a firefox problem.
