### ISSUE TITLE
Imitation, exporting, importing

### ISSUE THREAD

**Issue by alandooz** [sienori/Tab-Session-Manager#34]
Consider something like this https://sessionbuddy.com/. But, in core, consider the option of importing and exporting the sessions to/from a txt, html, etc.

**Comment by sienori** [comment]
I will think about it.

**Comment by stronzo46** [comment]
Hey is it possible to import *.session Files fro Session Manager to Tab Session Manager?

**Comment by sienori** [comment]
I implemented it.
It is also possible to import .session file.
#40

**Comment by DedupOperator** [comment]
Hi thank you for the great work.
I got to this repo by an issue in thegreatsuspender extension, recommending your work as a replacement for SessionBuddy.

I would really like to see SessionBuddy backup import, as it didn't have any updates for a long time, and by reviewing it's google group, there are a lot of issues with users that have a large database.

I can submit a formatting sample if you like.
Thanks
