### ISSUE TITLE
Serious bug when TSM update happen

### ISSUE THREAD

**Issue by mikhoul** [sienori/Tab-Session-Manager#340]
Hi,

I finally found the cause of a strange behavior:, I use 3-4 windows and my main window have 50-60 tabs those days and from time to time for no apparent reason when I was back at my computer the main  window was missing most tabs  leaving me with only few tabs.

When it happened I had to reload my last full TSM backup from this window with all my tabs.

It happened this morning and right now but today I make the connection and understand when it happen and it is when you update TSM.

Moreover I can even tell you which tabs are lost when TSM update: I use [The Great Discarder](https://github.com/deanoemcke/thegreatdiscarder) to save my memory so all the tabs that are discarded when the update happen are the one that are closed/lost.

So when you update TSM you must look in some way to see which tabs are open to be able to restore them after the update but the Chrome API have a bug that prevent you to "read/see" the discarded tab.  So after the update only the tabs that were fully alive are restored.

It can bring to many users headache since Chrome is discarding arbitrary any tabs when he think the user don't have enough memory. So let's say on 75 tabs Chrome has discarded by itself 5 tabs to save memory and TSM update the user most of the time will not remark that 5 tabs were lost during the update unless he need them.

The reason I've see it it's because with TGD extension after 2 hours of non-use my tabs are automatically discarded exept the one on my white list, that's how I've found the relation between the lost tabs and the one that are lost when TSM update.

**NOTE**: It seem to happen only in the main windows where TSM open a tab to  say an update was done.
  
![image](https://user-images.githubusercontent.com/5678673/48677806-66393d00-eb48-11e8-80b8-deabd70ec50b.png)

Let me know if you need more information to fix it.

Regards :octocat:

**Comment by RobertAb1** [comment]
@mikhoul  _and others_

Vote on Bug 944918, Bug 1423917, Bug 1427928 _and other bugs_ on Bugzilla@Mozilla website to speed up solving this issue (with broken indexedDB) by Mozilla and removing this problem (_and other issues_) from TSM: #150

**Comment by Greek64** [comment]
I can confirm this bug. Like @mikhoul I had this bug happen to me at times, but could not figure out a pattern.
Finally I can confirm that this happens on TSM Updates.
I basically lose all Tabs that are not manually reloaded after a session restore, and have to manually restore a previous saved session that still contains all the tabs.

**Comment by Greek64** [comment]
Happened again today on update to 4.5.2

**Comment by kpedro88** [comment]
This is still happening when TSM updates. It's extremely harmful behavior for a tab management addon.

**Comment by r4m0n** [comment]
This problem happens on Chrome, I don't see why the Firefox bugs are going to do anything useful here. This has been happening for years now and TSM keep losing half my open tabs every time it updates.

If the issue is the inactive tabs associated with the extension getting deleted on the update process, maybe split the inactive handling to a mini-extension and leave it alone?

**Comment by sienori** [comment]
I fixed this problem. https://github.com/sienori/Tab-Session-Manager/commit/080f585b018809755b1c65f2e4853931f62e2923  https://github.com/sienori/Tab-Session-Manager/issues/457
It should take effect from the next update!
