### ISSUE TITLE
session save/load not working

### ISSUE THREAD

**Issue by chemag** [sienori/Tab-Session-Manager#343]
## Short description
I had a large list of stored sessions. They all disappeared after a reboot (the list is empty). Also, I cannot save new sessions.

## Steps to reproduce

1. Click on TSM Save Button

## Expected result
See a new session in the session list.

## Actual result
Session list keeps empty.

## Platform information
* Platform (OS): linux (4.15.0-38-generic)
* Version of browser: FF 63.0.3
* Version of Tab Session Manager: 4.3.2

Adding glitch.me results in normal mode ([1]) and incognito mode ([2]).

![1](https://user-images.githubusercontent.com/738720/49029218-f3881d00-f158-11e8-9caf-91efb88e8215.png)
![2](https://user-images.githubusercontent.com/738720/49029219-f3881d00-f158-11e8-8d1f-159ebd117fdf.png)

**Comment by sienori** [comment]
Please enable debug mode and show me the logs when clicking save button.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

**Comment by chemag** [comment]
![tab](https://user-images.githubusercontent.com/738720/49097351-6bba1580-f221-11e8-9526-8e258cbdcf8a.png)

**Comment by chemag** [comment]
![tab](https://user-images.githubusercontent.com/738720/49098935-f6e8da80-f224-11e8-95c8-22b596e17590.png)

**Comment by chemag** [comment]
There seems to be something broken in the indexeddb database tsm was using. I followed the "Restore Version 3.x.x data" instructions from https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error. Moved the `storage/` directory away, and restarted firefox, which created a new directory. I could save sessions. Then I copied the `default/moz-extension+++<uuid>` directory from the old directory to the new one. Now I cannot save any sessions, and none show up.

**Comment by chemag** [comment]
I poked around with the contents of the `default/moz-extension+++<uuid>` directory. The main file (`default/moz-extension+++<uuid>/idb/<id>.sqlite`) seems to have pointers to IDs found in `default/moz-extension+++<uuid>/idb/<id>.files/`. There, I found some [snappy](https://github.com/google/snappy) files, but I cannot even open them: 

```
$ python /usr/lib/python2.7/dist-packages/snappy.py -d <id>.files/2378
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 305, in <module>
    cmdline_main()
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 301, in cmdline_main
    method(src, dst)
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 263, in stream_decompress
    buf = decompressor.decompress(buf)
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 214, in decompress
    raise UncompressError("crc mismatch")
snappy.UncompressError: crc mismatch
```

**Comment by sienori** [comment]
> The main file (`default/moz-extension+++<uuid>/idb/<id>.sqlite`) seems to have pointers to IDs found in `default/moz-extension+++<uuid>/idb/<id>.files/`.

What is a pointer to IDs found in `default/moz-extension+++<uuid>/idb/<id>.files/`?
I have never seen it.

Also, `default/moz-extension+++<uuid>/idb/<id>.files/` directory is often empty.
What happens if you delete files in that directory?

### Ordinary directory structure:
```
default/moz-extension+++<uuid>/
  ├ idb/
  │  ├ <id>.files/
  │  │  └ (empty)
  │  └ <id>.sqlite
  ├ .metadata
  └ .metadata-v2
```

**Comment by chemag** [comment]
The sqlite file doesn't seem to contain any URLs itself. 

![tsm2](https://user-images.githubusercontent.com/738720/49121470-5ff04280-f265-11e8-8861-4641ddd7f0d3.png)

**Comment by chemag** [comment]
I deleted the `<id>.files/` dir, and restarted firefox. Now clicking on the tsm icon on Firefox only shows a small, empty box.

**Comment by chemag** [comment]
What I meant by "pointers" is the fact that, for example, the first two in the sqlite file has "2376" in the "file_ids" column. That's a file (snappy), but I cannot decode it:

```
$ python /usr/lib/python2.7/dist-packages/snappy.py -d /tmp/1782160246ssensosi.files/2376
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 305, in <module>
    cmdline_main()
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 301, in cmdline_main
    method(src, dst)
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 263, in stream_decompress
    buf = decompressor.decompress(buf)
  File "/usr/lib/python2.7/dist-packages/snappy.py", line 214, in decompress
    raise UncompressError("crc mismatch")
snappy.UncompressError: crc mismatch
```

**Comment by sienori** [comment]
It seems that the contents of the sqlite file are different from my environment.
In my environment, `file_ids` is `NULL` and `data` is `BLOB (binary data)`.

![object_data](https://user-images.githubusercontent.com/29514424/49124253-04729300-f2ff-11e8-8440-7afda72351f4.PNG)

The database seems to be corrupt. This is due to a firefox bug or other cause.

**Comment by chemag** [comment]
I agree this looks like an indexeddb issue. In my (corrupted?) database, the URLs are placed in files. For example, 
![this](https://user-images.githubusercontent.com/738720/49125643-90d87380-f275-11e8-9a59-e9f891cfba4e.png) is an example of an URL (you can see the "https://" part around column 0x1e0.

I wonder whether firefox decided to change the indexeddb format from "put the URLs in files, and link the files from the object_data `file_ids` fields" to "put the URLs in the `data` field". 

Anyway, I'll close the issue, as there's not much we can do here. Thanks *a lot* for the help.
