### ISSUE TITLE
Session Transfer

### ISSUE THREAD

**Issue by nollinvoyd** [sienori/Tab-Session-Manager#346]
Firefox 63.03, Windows 10 Pro

I have several profiles that I regularly modify and backup.  I have different sets of sessions for each.  

I transfer the following folders and files from one profiles to another:  

sessionstore-backups
storage
cookies.sqlite
cookies.sqlite.bak
places.sqlite
places.sqlite.corrupt
sessionCheckpoints.json
sessionstore.js
sessionstore.jsonlz4
storage.sqlite
storage-sync.sqlite

What else do I need to transfer so I still don't have to also import a stored backup session? Or is that not possible?

**Comment by sienori** [comment]
To move session data to another profile, please follow the following page.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

It is far easier to use session export and import functions.

**Comment by nollinvoyd** [comment]
"It is far easier to use session export and import functions."

I agree, but I'm usually moving session data to update several backup profiles.  That's why I'm including sessions, history, and cookies.  

If possible, I'd prefer just a quick and simple transfer of folders and files as opposed to mounting that profile each time I want to update sessions.  

I'm curious, why isn't moving/replacing the entire storage folder to the target profile not the same as just replacing 1782160246ssensosi.sqlite?

**Comment by sienori** [comment]
TSM uses a special storage called IndexedDB.
In order to move IndexedDB data to another profile, it is necessary to follow [Wiki's method](https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile).
Simply replacing the file will corrupt the data.
