### ISSUE TITLE
No visible way of changing the default directory or loading session from dialog

### ISSUE THREAD

**Issue by ognyandim** [sienori/Tab-Session-Manager#35]
Hi, I switched to this add-on but I can not find how to change the working directory. I want to save my sessions on Google Drive folder. This way I can have my sessions wherever I go.

Or if there is an option for loading old sessions from Session Manager with dialog will be useful.

I there a way to set it?

**Comment by sienori** [comment]
Sorry, there is no way to save a session in any folder.
This is due to web extension specifications.

Also, I do not have a method to migrate automatically from the Session Manager. #36

**Comment by ognyandim** [comment]
Then is there any way to migrate from old session manager to this one? I mean any way to migrate saved sessions and sync them across devices?

Because this is my current experience and it is really helpful - wherever I sit I have my working environment the same.

**Comment by sienori** [comment]
To migrate old sessions flom Session Manager, you must do it manually in firefox 56 or earlier.
It is only possible to activate SessionManager and TabSessionManager at the same time and restore and save sessions manually.

There is no way to sync with other devices at the moment.
I think I will consider a way to deal with google drives in the future.

**Comment by ruanomar** [comment]
If there is no way to save the sessions in any folder, how can I include my sessions in my automated scheduled backups in case TSM crashes/dies and my sessions are gone and I need a restore?

**Comment by ognyandim** [comment]
Probably with firefox sync? I will try it if it works.

**Comment by ruanomar** [comment]
I've never used that. I'd rather user file backup.

**Comment by sienori** [comment]
I implemented import/export function. #40
It is also possible to import .session file.

**Comment by sienori** [comment]
firefox sync is not possible.
Because the file's capacity has a limit of 100 KB.

**Comment by ruanomar** [comment]
Thank you!
