### ISSUE TITLE
file session page cannot be restored

### ISSUE THREAD

**Issue by lesar** [sienori/Tab-Session-Manager#353]
## Short description
To learn vue and laravel I have study some example.  

I use Tab session manager to save and restore example pages.  

The index.html file cannot be restored.  

The page show:  
`
Vuebnb
file:///home/leonardo/sviluppo/documentazione/manuali/laravel/FULLSTACK_VUEJS_2_AND_LARAVEL_5/esercitazioni/Full-Stack-Vue.js-2-and-Laravel-5/vuebnb-prototype/index.html
Questa pagina non può essere aperta da Tab Session Manager.
`

the url is this:  
`moz-extension://e32e5555-98a8-4fec-8fa9-94f25af4ee05/replaced/index.html?state=open_faild&title=Vuebnb&url=file%3A///home/leonardo/sviluppo/documentazione/manuali/laravel/FULLSTACK_VUEJS_2_AND_LARAVEL_5/esercitazioni/Full-Stack-Vue.js-2-and-Laravel-5/vuebnb-prototype/index.html&favIconUrl=undefined`  

the log is this:  
[log.log](https://github.com/sienori/Tab-Session-Manager/files/2649627/log.log)

## Platform information
* Platform (OS): Ubuntu 64 bit 16.04
* Version of browser:  firefox 63.0.3 (64 bit)
* Version of Tab Session Manager: Version 4.3.3

**Comment by sienori** [comment]
Due to limitations of webextensions, it is impossible to open local file. https://github.com/sienori/Tab-Session-Manager/issues/234

**Comment by lesar** [comment]
Ok thanks you
