### ISSUE TITLE
Sanity check

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [sienori/Tab-Session-Manager#355]
**Opening Rant about Mozilla and FireFox**
I, reluctantly, updated my good FireFox installation to a new version that only permits WebExtensions and does not allow use of unsigned addons.  From a technical perspective, I have no issues with either of these improvements except to say that I, as the owner of my machine, should have the ability to chose whether my instance of FireFox enforces, per addon, the signing policy or not (as this would enable me to easily tweak any addons I am using). From a product evolution perspective, I feel sorry for addon developers who are getting worn out trying to keep up with FireFox's rapid changes, and I don't think this is healthy for FireFox as a product in the long term.  I chose not to use FireFox ESR as I don't consider it a viable solution considering the time I would spend using/configuring my browser and it simply puts the problem off to another day.   So, having made the leap, I now have in my hands a browser shell that Mozilla claims is a performance race car when I actually want a Rolls Royce that compliments the performance with comfort and features that suit my taste.  The irony is that prior to 'upgrading', I actually had a Rolls Royce that I was very happy with.  So, to end my rant, I'm now faced with the prospect of either living without certain addons or learning how to use other addons that do similar things but differently and which may not have features I liked, hence this feature request post.

One addon that I consider important is the _Session Manager_ (by Michael Kraft) which I found most useful and easy to use.  Sadly it appears that Michael will not be maintaining his addon any longer so I (and others) must find an alternative.  I've already tried a number of Session Managers offered through the Mozilla Addon site and am drawn to this addon because it seems, from a functionality point of view, to be the closest to what I have achieved with my previous FireFox customisation.  I also like the UI and am please to see that it is _Tree Style Tabs_ aware.

My Use Case:  I use sessions to organise my browsing activities based on a projects I work on or subjects I research so that at a future point I am able to return and continue where I left off.  In my opinion, sessions have nothing to do with data retention for backup purposes, I have other tools for that which are very good at their job.

Features I would like to propose:

**Correlation between a browser window and a saved session.**
I used _Session Manager_ in conjunction with the _Fire Title_ addon. This allowed me to synchronise the names of sessions managed by _Session Manager_ with the title (prefix) shown in each browser window.  Without this synchronisation, saved sessions have very little meaning and I would have abandoned the whole idea.

**Allow the user to manually update the session record in _Tab Session Manager_**
I simply don't understand why anyone would want to make timed backups of sessions.  (I have already turned it off!) See my comment above concerning backups.  As far a version tracking, I use GIT.
The reason for the above critique stems from the following question: How does the user later distinguish between two auto-saved sessions that represent separate windows (and therefore groups of tabs) where the currently opened tab in each window happened to be the Google search page?
I would like therefore to propose the addition of a button in the _Tab Session Manager_ UI that allows the user to update the session with the current set of tabs in the selected window.  There is no need to add the title of the current web page to the session name.

**Creating New Sessions**
When creating a new session, the user should (ISO definition of should) be required to fill in the name at that point in time, with the save occurring afterwards.  Leaving it blank or filling it in later will only lead to a huge mess.

**Managing closed tabs or windows**
_Session Manager_ kept a record/list of recently visited pages and closed windows (the First Aid icon), and allowed me to recall them if needed.  On top of that, FireFox obviously has its own browser history.  Do I need to make another backup/version tracking comment here?

**Single window or groups of windows in a session**
Personally I avoided creating sessions from multiple windows because I would invariably end up with multiple copies of certain windows that were inconsistent with each other.  This confused me a lot at the start as I found it hard to decide which of the windows was my master record and to which session each belonged.  In the end, one window/session proved ideal for me.

**Comment by ric2b** [comment]
> I simply don't understand why anyone would want to make timed backups of sessions.

I can answer that: I've lost Firefox sessions enough times to not trust Firefox alone to re-open my last browsing session.

> When creating a new session, the user should (ISO definition of should) be required to fill in the name at that point in time

You can still do that, I don't want to because I just want my sessions to be backed up and the timestamp is enough information for me. I don't generally switch between multiple sessions, I have a single one.

**Comment by Napoleon-BlownApart** [comment]
At last someone noticed.  ;)  I understand what you mean.  I am, for various reasons primarily having to do with legacy addons, I'm using WaterFox now.  So I've got all my old addons working fine, where I'm using (and got accustomed to) `Session Manager`.
Cheers and good luck.
