### ISSUE TITLE
Tab-Session-Manager/SaveBackup_ExportSessions

### ISSUE THREAD

**Issue by daiveaux** [sienori/Tab-Session-Manager#356]
## Short description

The Save Backups is not saving any backups to the Downloads folder.  The Export Sessions does not allow to export current, active sessions.  Selecting "Export" does nothing.  Both issues appeared either on Version 4.2.x or 4.3.x prior to updating Firefox to Version 64.0.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. 
4. 

## Platform information
* Platform (OS): Windows 7 x64 SP1 V2.0
* Version of browser:  Firefox 64.0 64Bit
* Version of Tab Session Manager: 4.3.3

**Comment by pernicles** [comment]
Have you clicked the check mark and specified the folder you want to save the backups in? If not, create a folder and copy the folder path, then paste it into the folder location box, like so:
![image](https://user-images.githubusercontent.com/45774567/50187705-80e80880-02e4-11e9-88bc-09f93afe3d4b.png)
Make sure the check is there. Restart the browser and when you start it up again you will see Firefox downloaded a file as soon as you started it up. Hope this helps.

**Comment by sienori** [comment]
Please enable debug mode and show me the logs when clicking export button.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

**Comment by daiveaux** [comment]
Yes, this option was selected previously as well as setting up a folder underneath Downloads.  This stopped doing the Backup as of December 07.  I also have this Add-On in Chrome and this option works when the Chrome browser starts up.

**Comment by daiveaux** [comment]
Hi, thanks for following up.  Here is the log output when I run Export.  I have a lot of saved sessions that I have gzip'ed and now moving them off my computer to see if this help to free up space.  I am doing this since there is an error message:  "allocation size overflow."  It looks like a limit of 114.  Is that the session?  I have 15 Firefox windows opened currently with about ~1K tabs.  But this had no problem exporting previously.  Thanks for any help/suggestions that you may have.

[info] background/background: onMessageListener() Object { message: "exportSessions", id: null } background.js:1:67100[debug] background/export: exportSessions() null background.js:1:67100[debug] background/getSessions: getSessions() null null background.js:1:67100[debug] background/sessions: getAll() null background.js:1:67100[debug] background/sessions: =>getAll() Array(114) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ] background.js:1:67100allocation size overflow

**Comment by daiveaux** [comment]
Hi, I have been having a lot of issues with my Firefox running out of memory.  I use the FF built-in utility "about:memory" to clean up FF memory usage.  It takes 10-15 minutes of using FF before the computer memory is maxed out again.  I have to repeat this over and over again when I am using FF.

I decided to disable the Tab Session Manager add-in and quit all FF windows.  I only have about 5 add-ins for FF.  I reopened all my 14 FF windows and I no longer have any issues with running out of memory.  There is definitely an issue with Tab Session Manager interacting with my FF and I believe it is related to the recent updates to TSM which is causing the issue reported in the log that I attached below and the run away memory usage by FF.

Please let me know if you are able to fix these issues.  I am disabling TSM on my Chrome as well.  Thanks.

**Comment by sienori** [comment]
The problem of `allocation size overflow` was fixed in firefox 65.
Until firefox 64, there was a problem that export fails when session data is 256 MB or more.

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65#JavaScript
> Strings now have a maximum length of 2^30 - 2 (~1GB) instead of 2^28 - 1 (~256MB) (bug 1509542).
