### ISSUE TITLE
Allow for save location costumization outside of downloads folder

### ISSUE THREAD

**Issue by pernicles** [sienori/Tab-Session-Manager#357]
**Is your feature request related to a problem? Please describe.**
I don't like how the save location for the backup folder has to be within the downloads folder in my computer. Why can't it be anywhere else, like my Onedrive folder?

**Describe the solution you'd like**
I would like for changes to be made so that I could save the backups anywhere I'd like. Please make the user able to input the target folder location for saving the backups and have the option to create a new folder in that location.

**Describe alternatives you've considered**
I don't think there are any alternatives to this solution as it is very specific. Thanks for the help though!

**Additional context**

**Comment by sienori** [comment]
Due to limitations of webextensions, it is impossible to save it outside the download folder.

**Comment by pernicles** [comment]
That's weird... Another extension I use called "Clippings" allows it. They do require a helper app though, which I imagine isn't that much of a hassle. Anyways thank you for responding!

**Comment by pernicles** [comment]
Master Sienori, do you have any plans on making a helper application to save backups elsewhere? Pls do.

**Comment by irvinm** [comment]
@pernicles, just create a symbolic link in the download folder to the folder you really want to save to.  It just means you have to plan ahead a little, but isn't difficult to do it.  I, personally, created 4 symbolic links to folders outside of the download folder and then just configured the addon to be able to quick save to those 4 folders.
