### ISSUE TITLE
Tabs appear in reverse sequence

### ISSUE THREAD

**Issue by karlbu** [sienori/Tab-Session-Manager#359]
## Short description
Tabs are opening in reverse sequence.  For example, I save tab order as:  A, B, C, D, E.
The tabs load as: E, D, C, B, A.

I see that this was a prior issue (#87) that has been closed.  This has been occurring for several weeks.

## Steps to reproduce

1. Start browser
2. Load saved sessions.

## Expected result
Tabs should open in the sequence in which they are saved.

## Actual result
Screen shot a
<img width="886" alt="debug screen shot" src="https://user-images.githubusercontent.com/12497047/50486720-32fc9000-09c9-11e9-8f43-74f174849cc9.png">
ttached.

## Platform information
* Platform (OS): Windows 10, 64-bit
* Version of browser: Firefox 64.0
* Version of Tab Session Manager:  4.3.3

## Additional context
None

**Comment by RobertAb1** [comment]
https://github.com/sienori/Tab-Session-Manager/issues/369

**Comment by sienori** [comment]
We will discuss this issue in #369.
