### ISSUE TITLE
Option to Backup Sessions to the Cloud

### ISSUE THREAD

**Issue by Rcarballo2222** [sienori/Tab-Session-Manager#363]
**Is your feature request related to a problem? Please describe.**
I recently had an issue with my computer, and lost some files (including the session backups). It would be nice to automatically save the backups to the cloud on browser exit

**Describe the solution you'd like**
Backup sessions to a google drive or firefox sync account

**Comment by irvinm** [comment]
You could create a symbolic link to your google drive folder in your downloads directory and then use the "save backup" option and point it to that folder.

**Comment by Rcarballo2222** [comment]
Ok, that could work pretty well.  I wonder if some users would still find that too cumbersome, but those few users might not be worth the development of that whole feature

**Comment by harogaston** [comment]
Not everyone has or should have a google drive account. Also that can only work on your personal computer. Also is too hacky for most. Also that is not a solution.
The solution is to use the native WebExtenision API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by Rcarballo2222** [comment]
> 
> 
> Not everyone has or should have a google drive account. Also that can only work on your personal computer. Also is too hacky for most. Also that is not a solution.
> The solution is to use the native WebExtenision API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

Yeah that's why I was thinking maybe the Firefox Sync

**Comment by harogaston** [comment]
Unfortunately I just learned that the Web Extension API has a very limited storage size. It is aimed at synchronizing add-on configuration only. So this is not an alternative anymore.

**Comment by sienori** [comment]
In version 6.0.0, I implemented the cloud sync function!!
You can save sessions to Google Drive and sync with other devices. 
It can also be used for backup. #73
![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png)
![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)
