### ISSUE TITLE
Multi Account container addon?

### ISSUE THREAD

**Issue by 1RonRock** [sienori/Tab-Session-Manager#365]
**Is your feature request related to a problem? Please describe.**

Is Multi Account Container Addon compatible with TSM?

Or will it cause unexpected errors when used along with TSM? I would like to try Multi Account Container, but not at the risk of corrupting my sessions.

**Comment by sienori** [comment]
Yes, TSM supports Multi Account Container.

**Comment by RobertAb1** [comment]
@sienori 
Are APIs/changes in Firefox needed for TSM to better work with Multi Account Container?
There is Bug 1512802 (https://bugzilla.mozilla.org/show_bug.cgi?id=1512802) which was closed today (but it can be reopened), and any needed changes could be described there.
