### ISSUE TITLE
Directory where Session files are saved is not shown and not customizable.

### ISSUE THREAD

**Issue by ziwer1** [sienori/Tab-Session-Manager#37]

**Comment by sienori** [comment]
Session files are in the following places.
[profile folder]\browser-extension-data\Tab-Session-Manager@sienori\storage.js
(you can open profile folder from about:support)

There is no way to save a session in any folder.
This is due to web extension specifications. #35

**Comment by sienori** [comment]
I implemented import/export function. #40
