### ISSUE TITLE
Recover from old .mozilla folder

### ISSUE THREAD

**Issue by js-d-coder** [sienori/Tab-Session-Manager#371]
I have moved .mozilla folder to .mozilla.old folder to start fresh firefox setup and found out that my old sessions are gone. Is there a way to recover old saved sessions?  
Using KDE on arch linux, firefox 65.  
Thanks

**Comment by sienori** [comment]
Please see the following page for migration of session data to other profiles.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by js-d-coder** [comment]
Thanks, it worked!
