### ISSUE TITLE
Broken layout in Overflow Menu

### ISSUE THREAD

**Issue by danielleontiev** [sienori/Tab-Session-Manager#372]
## Short description
Layout of the extension looks broken when pinned to Overflow Menu.

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. Click on the extension's icon and select "Pin to Overflow Menu"
4. Open Overflow Menu and select the extension icon

## Expected result
It should fit the Overflow Menu horizontally

## Actual result
[Result](https://imgur.com/a/IEgAUHQ)

## Platform information
* Platform (OS): Ubuntu 16.04.5
* Version of browser: 64.0
* Version of Tab Session Manager: 4.4.0

## Additional context
Almost all extensions are suffer from this issue, maybe API restriction

**Comment by sienori** [comment]
Yes, It is due to API limitation.
Setting the width of the popup from the setting page will solve it.

**Comment by knoajp** [comment]
I managed to set the sidebar width to 200.
still not an ideal layout.
is it the correct way...?
