### ISSUE TITLE
TSM shows 0 sessions and will not save, but there is no IndexedDB error

### ISSUE THREAD

**Issue by zankai2** [sienori/Tab-Session-Manager#374]
Shows 0 sessions even though I have many (debug message seems because it returns null).

If I click save, it says session saved in green.

There is no IndexedDB Error message, (but I had that months ago and had to fix).

Latest auto-save would have been 2 windows having 994 tabs, which might be too many?

**Comment by irvinm** [comment]
It is definitely not a "too many tabs" issue.  I've run 800-1100 tabs with no problems.  FYI.

**Comment by zankai2** [comment]
Sometimes my firefox crashes and maybe this did it somehow?

My firefox just crashed now and wiped all my sessions from another session manager plugin but it's still working unlike TSM?

**Comment by llewlem888** [comment]
I've found that you can save hundreds of tabs per session with TSM just fine, but once you start getting around 1000 sessions saved, TSM becomes very slow to load and may actually fail to load at all. Try closing firefox, backing up your .mozilla (or whatever it is on Losedoze, I forgot) folder, and then restarting firefox and deleting all saved sessions in TSM settings. It looks like it won't be easy to reimport the sessions you want back, though.

What I did was:
1. Close Firefox
2. Back up my FF profile into ~/.mozilla/firefox/_________.Default User.bak-201902161036
(not actually underscores in that filename, just the UUID-ish characters of every auto-generated FF profile)
3. Restart Firefox
4. Open TSM settings, sessions section, and delete all sessions.
5. Click OK  in the confirmation box.
6. Open FreeFileSync and compare the backup profile folder to the live profile folder
7. Filter out all else but the files that only exist in the backup, and found 104 missing binary files, in what looks like the path TSM stores its sessions in, which was nearly cleared out after I deleted every session through the TSM settings. This was(mostly) it:
~/.mozilla/firefox/_________.Default User.bak-201902161036/storage/default/moz-extension+++f740c587-ab80-4b5f-ac52-595d09998e40/idb/
The session files seem to be in a folder named with 10 digits then "ssensosi.files", like so: __________ssensosi.files
Idk what ur digits will be, could be different with every FF profile. But copy that folder somewhere and you should have them saved. If you copy the whole profile folder it'll def work, but that might be a lot of space. My profile is over 1GB, but I use [btrfs reflinks](https://www.pixelbeat.org/docs/unix_links.html) to copy big folders like this.

Really though, idk what I'm doing. I fsking hate these monolithic browsers with their shitty APIs that try to recreate operating systems, poorly.

**Comment by onesolo** [comment]
I also have this problem!!!
My FF crashed but when I got it up again, it showed no session at all in TSM !!! I had many sessions saved!!! If I go to the save backup location, they are all of them!!!
How do I restore them to appear again on the TSM list?!? This must be some TSM bug...

**Comment by onesolo** [comment]
So, no news for this bug? I guess I have to move to another similar addon... :(

**Comment by 1RonRock** [comment]
Just happened to me. I can see that the most recent saved session is 5 days old in the TSM Backup folder. 5 days is a long time ago, I've been busy researching several projects. But 5 days ago would be better than nothing. How do I restore the sessions from the TSM Backup folder?

**Comment by sienori** [comment]
Sorry for the inconvenience.
Please see below for how to fix DB error:
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

I recommend using the **local backup option** or the **cloud sync function** in case the session is lost.
![backup](https://user-images.githubusercontent.com/29514424/78506378-07637a80-77b4-11ea-9908-a6bbe9a99c2d.png)
