### ISSUE TITLE
Add a Single Tab to a Saved Session!

### ISSUE THREAD

**Issue by Aezaeo** [sienori/Tab-Session-Manager#379]
**Is your feature request related to a problem? Please describe.**
It's annoying and highly inefficient, if I have a Window with a lot of tabs open and saving the Session(Window) to then have to go through and delete each individual tab that I do not wish to be part of my saved Session. It is also equally inefficient to have to open a new window and drag all the tabs I want saved, to a new Window to be saved as a Session.

**Describe the solution you'd like**
The simplest way to fix this is to add the option to add any single tab to any session they please.

**Describe alternatives you've considered**
Alternative things I've considered is using different Session Managers. Another issue with Tab Session Manager is the possibility have duplicate saves, it'd be nice to not save any duplicate tabs.

**Additional context**
https://i.imgur.com/XJ3LLkR.png
In this screenshot you'll notice a context menu made for One Tab, it has the ability to save a single tab. Something like this would be extremely useful. Also if you get the chance, I'd take a look at Session Sync @sienori  to get a few more ideas of some things you can add to Tab Session Manager to make it the best Session Manager around. I currently use multiple Session Managers because some do more than others. I find this to be inefficient so a single Manager that could do it all what would be worth it.

**Comment by rupeshk** [comment]
Ability to save a single tab to a session is a must have feature

**Comment by rddim** [comment]
+1

**Comment by futagoza** [comment]
@sienori Would it be possible to add this?

**Comment by sienori** [comment]
I will implement this feature in the future.

**Comment by serovar** [comment]
Any news on this? :)

**Comment by Dimoks** [comment]
And also need to move tabs, at least in the saved window, between windows in a session, or even between the saved sessions.

**Comment by xHurricanex** [comment]
Moving tabs between windows will be great!

**Comment by sienori** [comment]
The ability to add current tab was added in version 6.9.0! https://github.com/sienori/Tab-Session-Manager/issues/458
