### ISSUE TITLE
Tab Session Manager Restore

### ISSUE THREAD

**Issue by sbensley** [sienori/Tab-Session-Manager#38]
Hi, I would like to find out I recently installed this addon in firefox 57, but when the addon restores my tabs ( around 63 Tabs) it reopens all of them. Is it possible to just restore the tabs, but let me choose what to open and what to leave for now?

**Comment by naoliv** [comment]
I usually have ~400 tabs in my browser (yes, I have problems with tabs)
And it just gets unusable when it tries to load all of them.

**Comment by FSMaxB** [comment]
I significantly reduced my number of tabs by using [Browse Later](https://addons.mozilla.org/en-US/firefox/addon/browselater/) and [resumeLater](https://addons.mozilla.org/en-US/firefox/addon/resumelater/). This should work for everybody who uses Tabs as temporary bookmarks (like I did).

**Comment by sbensley** [comment]
Thanks I'll try it. I brought mine down to 48 from 63 tabs.

**Comment by ertyz** [comment]
Sienori-san may implement this feature in next versions with native Firefox API (tabs.discard() will be available since Firefox 58). After that you don't need to use third-party addons https://github.com/sienori/Tab-Session-Manager/issues/18#issuecomment-338952293

**Comment by grahamperrin** [comment]
> … restore the tabs, … open … leave …

To clarify: you want all tabs to be present, with just one per window loaded, and load another restored tab only after you click on it – true?

(The title – _Tab Session Manager Restore_ – is ambiguous.)

**Comment by sbensley** [comment]
Let's say you have 50 Tabs you want to restore, but you only want certain tabs to be active. So out of 50 tabs you might only want to activate 25 of them with the other 25 tabs to be there but no active. Just because you have 50 tabs present you might not need all 50 to be active right off the bat.

**Comment by PenaPP** [comment]
That's exactly what I need as well. Some tabs belong to the same site and requires login and I don't want to be redirected to login page on each of them. Additionally it consumes more memory and takes longer to load.

**Comment by sienori** [comment]
I add lazy loading function.
This greatly reduces memory usage.
https://github.com/sienori/Tab-Session-Manager/commit/501461d4ffd69fec7320b8c2da815f99970aa9b1

**Comment by sbensley** [comment]
Here is what I found out as a another way to do tabs. On your browser you have the ability to login to firefox and sync stuff like Open Tabs / Bookmarks / Logins / History / Add-ons and so on. Once you do that it will start sync all that stuff. Then let's say you Logoff and shutdown your PC. The next morning after you start your PC back up and login. Start your Firefox browser and then click on History and then scroll down to "Restore Previous Session" this will then restore all the tabs you last used the previous night(Even the tabs not fully loaded). Then all you need to do is click on the tabs you want to start using and it will load. The others tabs will remain visible, but not loaded. Give that a try and let us know.

**Comment by RobertAb1** [comment]
Vote on new bugs on Bugzilla@Mozilla website to speed up preparation of other session manager-related APIs by Mozilla:  https://github.com/sienori/Tab-Session-Manager/issues/150
