### ISSUE TITLE
Folders/Categories like Session Manager

### ISSUE THREAD

**Issue by skalfate** [sienori/Tab-Session-Manager#389]
**Is your feature request related to a problem? Please describe.**

I save a lot of sessions and its frustrating to go through the list. Yes the search bar is there but I think there is a better solution. A little more organizing power.

**Describe the solution you'd like**

I'd like it if Custom Folders/Categories/Groups can be created just like in Session Manager where you group multiple sessions based on what they are related to. 

For example, lets say I have 20 sessions related to [ random youtube videos], so I would group them all under one single entry in the list under ["Youtube Videos"] which would lead to another list menu which will list all the sessions I have grouped under it.

Just like the way there are folders in the bookmark menu.

**Describe alternatives you've considered**
I don't know.

**Additional context**

![image](https://user-images.githubusercontent.com/20464880/54954213-b9186c00-4f0f-11e9-8dd6-6f5419025e1f.png)

![image](https://addons.cdn.mozilla.net/user-media/previews/thumbs/199/199981.png?modified=1543520390)

![image](https://www.maketecheasier.com/assets/uploads/2016/08/save-browser-session-firefox-6.jpg)

![image](https://www.maketecheasier.com/assets/uploads/2016/08/save-browser-session-firefox-7.png)

**Comment by sienori** [comment]
You can use the tag function.

![list](https://user-images.githubusercontent.com/29514424/54985579-62d12900-4ff4-11e9-90ae-a1928bfdc00f.PNG)
![filter](https://user-images.githubusercontent.com/29514424/54985580-62d12900-4ff4-11e9-9c61-b7ebc394c312.PNG)

**Comment by skalfate** [comment]
Ah I see, thanks. Its something for now. 

Hopefully in the future we get more options for interface for example; this popup model + perhaps full tab window

and an easier to navigate ui for folders/session-name like the one for session buddy for chrome.

![image](https://2.bp.blogspot.com/-7d4gYHOxo8Y/V35oFNFgJEI/AAAAAAAAq0A/fXSv_gFgYCEFJaBWbX79PNdUJ2q-3678QCLcB/s1600/Session%2BBuddy%2Bestensione%2BGoogle%2BChrome.PNG)

**Comment by RobertAb1** [comment]
Related topics: 
https://github.com/sienori/Tab-Session-Manager/issues/375
https://github.com/sienori/Tab-Session-Manager/issues/387
https://github.com/sienori/Tab-Session-Manager/issues/394
https://github.com/sienori/Tab-Session-Manager/issues/150
