### ISSUE TITLE
Open and Delete button colors

### ISSUE THREAD

**Issue by dfordham** [sienori/Tab-Session-Manager#392]
**Describe the solution you'd like**
Just from an ease of use issue, I would like to see the Open button text be green and the Delete button text be red.  

<img width="264" alt="TabSessionMgr" src="https://user-images.githubusercontent.com/6720298/55288225-7b816c00-5371-11e9-8b0b-3b01055e25c9.png">

**Comment by sienori** [comment]
In version 5, the open / delete buttons have icons and usability has been improved.
