### ISSUE TITLE
how to synchronize tabs using Google Chrome or cloud?

### ISSUE THREAD

**Issue by candrapersada** [sienori/Tab-Session-Manager#395]
how to synchronize tabs using Google Chrome and Firefox or cloud?

**Comment by RobertAb1** [comment]
For Firefox: probably you could synchronize profile folder in Dropbox between computers. Make sure to have only one instance of  Firefox working at the time.

**Comment by candrapersada** [comment]
add Ekspor URL list for google chrome? and synchronize via online without saving to computer.

**Comment by sienori** [comment]
In version 6.0.0, I finally implemented the cloud sync function!!
You can save sessions to Google Drive and sync with other devices. #73
![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png)
![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)

**Comment by candrapersada** [comment]
why button Sign in with Google not working
![78505793-c027ba80-77b0-11ea-80ed-de25f8e67552](https://user-images.githubusercontent.com/36833664/78520968-9f805480-77f2-11ea-8792-8e9a88ab0cac.png)
for Edge is based on the Chromium?

**Comment by sienori** [comment]
Cloud sync also available in Edge!

**Comment by candrapersada** [comment]
is it possible to sync the settings "Tab Session Manager"
