### ISSUE TITLE
Open the list of saved sessions in new tab in Firefox

### ISSUE THREAD

**Issue by RobertAb1** [sienori/Tab-Session-Manager#396]
The list of saved sessions can be viewed now in popup window which opens after clicking TSM toolbar button. However, the usage of popup window is not ideal solution:
1) since this window is limited by size (800 x 600 pixels) ([link1](https://github.com/sienori/Tab-Session-Manager/issues/245), [link2](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups), [link3](https://bugzilla.mozilla.org/show_bug.cgi?id=1404626)), and 
2) for some actions involving opening single pages from saved sessions (it is impossible to set where tabs with these pages are added to tab strip, and the scroll position of popup window is difficult to control).

These problems could be avoided by adding option to open the list of saved sessions in new tab; this tab can take the size of entire screen and it can be moved freely inside tab strip. 
Please, check extension Session Buddy available for Chrome to see how it was solved there.

**Comment by sienori** [comment]
In version 5, the session list has a two-column UI and can be displayed in full screen.
