### ISSUE TITLE
Import of .json Session file is not working

### ISSUE THREAD

**Issue by olaims** [sienori/Tab-Session-Manager#397]
## Short description
I exported the session into a .json file before formating my PC. Now, after a clean Windows 10 install I tried to import that .json file, but no Tabs are restored. The .json file contains all information of the around 50 Tabs (I opened it with Notepad++ to check the content)

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Import session (select file)
4. Import session (click on "import" button)

## Expected result
Tabs should be imported

## Actual result
Nothing happens

## Platform information
Windows 10
Firefox Developer 67.0b14
Version of Tab Session Manager: Version 4.5.2

**Comment by sienori** [comment]
The imported sessions are displayed in the toolbar popup.
![popup](https://user-images.githubusercontent.com/29514424/58497032-06d27e80-81b6-11e9-9c32-ad37dbf2a69b.PNG)

**Comment by mirh** [comment]
It doesn't work for me either. 
I import the .json backup I made, "1 session" is detected and I get the nice and dandy "Sessions imported." popup. 
None appears anywhere.

**Comment by uberkael** [comment]
I can confirm it also in Chrome 77.0.3865.75.

**Comment by kamidev** [comment]
I have a similar problem after a browser crash. I have the old profile and also session backups in JSON format. But when I try to import them, I get this: 

<img width="663" alt="Skärmavbild 2019-09-20 kl  18 00 08" src="https://user-images.githubusercontent.com/1655/65341392-928e7180-dbd0-11e9-9b11-62853f0d7ed5.png">

**Comment by kamidev** [comment]
When I turn on debugging, I can see this when it fails to read the file:

<img width="1459" alt="Skärmavbild 2019-09-20 kl  19 24 51" src="https://user-images.githubusercontent.com/1655/65346272-a17b2100-dbdc-11e9-9683-0c87b8ae5dec.png

**Comment by kamidev** [comment]
Since I had a fresh backup of my profile, I finally get my sessions back using @sienori:s helpful instructions here: https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error.

**Comment by sienori** [comment]
I confirmed the problem where importing huge sessions failed. https://github.com/sienori/Tab-Session-Manager/issues/461
I fixed it in version 5.1.1. Thanks!

**Comment by itamar-dw** [comment]
I still see this problem on v 6.11.1, firefox version 94.0.2
I solved it in a brute-force way - a one line bash command to extract all url's from the json, then I copy-pasted it to the tab session manager "import from url list".

**Comment by luannbertaud** [comment]
I had the same issue, resolving by editing the JSON:
- I set all the Windows isFocused to false
- Change the uuid of the session

**Comment by mihaitodor** [comment]
I believe the import also fails if you go to settings and configure "Save device name to session". I did this before exporting my current session and it refused to import it until I edited the JSON manually and set `"tag": []` (it's a sibling of the session `name` element).

**Comment by Ynjxsjmh** [comment]
The imported session won't be placed on the top of existing sessions, it is sorted based on the `date` value in the json file. You need to scroll down a bit to find the exact imported session.

```
{
    "tabsNumber": 45,
    "name": "xxxx",
    "date": 1679990437097,
    "lastEditedTime": 1679990419723,
    "tag": [
      "winClose"
    ],
}
```

**Comment by ron23456** [comment]
luannbertaud's workaround was successful for me (thank you!).  In the JSON I changed:

**"focused": true,**

to:

**"focused": false,**

and I changed **"id"** near the bottom of the file.  Then I was able to find the session after I imported it.

**Comment by Dobypeti** [comment]
Sorry for the ping but this is still an issue @sienori.

In my case I had to both set `"tag": []`, `"focused": false,` and change the ID (Firefox extension)
