### ISSUE TITLE
TSM does not list, save, or export any sessions at all.

### ISSUE THREAD

**Issue by angeltek** [sienori/Tab-Session-Manager#398]
## Short description
Tab Session Manager does not list any previously saved sessions (ie the dropdown TSM window shows zero saved sessions), will not save any new sessions, and pressing the export sessions does nothing at all.  This is not an IndexedDB problem - that error is not shown and I have in any case followed https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error just to be sure.

Deleting the just the two TSM folders in my profile's storage folder when Firefox is closed, then starting Firefox seems to clear the problem in that TSM will then save new sessions (but obviously I loose all previously saved sessions). After restoring the original TSM storage folders I enabled debugging and restarted Firefox.  

The debug log is shown below... the second DataCloneError occurred when I selected the TSM dropdown window from the toolbar but did nothing else... the third DataCloneError after I selected the dropdown and pressed the save button.

## Platform information
* Platform (OS): Windows 10 Pro
* Version of browser: Firefox 66.0.3 (64bit)
* Version of Tab Session Manager: 4.5.2

## Additional context - Firefox debug log

Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
Successfully compiled asm.js code (total compilation time 1ms) adblockplus.js
[info] background/background: init() background.js:1:67100
[debug] background/sessions: init() background.js:1:67100
[debug] background/sessions: =>init() 
success { target: IDBOpenDBRequest, isTrusted: true, srcElement: IDBOpenDBRequest, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 3378, … }
background.js:1:67100
[info] background/updateOldSessions: updateOldSessions() background.js:1:67100
[debug] background/updateOldSessions: migrateSessionsFromStorage() background.js:1:67100
[debug] background/updateOldSessions: addNewValues() background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[info] background/autoSave: setAutoSave() undefined undefined background.js:1:67100
[debug] background/autoSave: startAutoSave() background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
DataCloneError: The object could not be cloned. background.js:1
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Debugging with Firefox Developer Tools 
Array [ "temp" ]
 default background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
DataCloneError: The object could not be cloned. background.js:1
    onsuccess moz-extension://4a156804-fda4-4b3a-9a8f-d2f9f0a8106e/background/background.js:1
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More] ExtensionContent.jsm:490:18
[info] popup/components/PopupPage: init() popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getInitState" }
background.js:1:67100
[debug] popup/actions/controlSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getSessions", id: null, needKeys: (6) […] }
background.js:1:67100
[debug] background/getSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: getAll() 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
DataCloneError: The object could not be cloned. background.js:1
[info] popup/components/PopupPage: init() popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getInitState" }
background.js:1:67100
[debug] popup/actions/controlSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getSessions", id: null, needKeys: (6) […] }
background.js:1:67100
[debug] background/getSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: getAll() 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
DataCloneError: The object could not be cloned. background.js:1
[info] popup/components/PopupPage: saveSession() Debugging with Firefox Developer Tools saveAllWindows popup.js:1:72442
[info] popup/actions/controlSessions: sendSessionSaveMessage() Debugging with Firefox Developer Tools saveAllWindows popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "saveCurrentSession", name: "Debugging with Firefox Developer Tools", property: "saveAllWindows" }
background.js:1:67100
[debug] background/save: saveCurrentSession() Debugging with Firefox Developer Tools 
Array []
 saveAllWindows background.js:1:67100
[debug] background/save: loadCurrentSession() Debugging with Firefox Developer Tools 
Array []
 saveAllWindows background.js:1:67100
[debug] background/save: saveSession() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 1, name: "Debugging with Firefox Developer Tools", date: 1556887836843, tag: [], sessionStartTime: 1556887693798, id: "08ea144f-fc4c-41cd-92cf-2bf7969ee54e" }
 true background.js:1:67100
[debug] background/sessions: put() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 1, name: "Debugging with Firefox Developer Tools", date: 1556887836843, tag: [], sessionStartTime: 1556887693798, id: "08ea144f-fc4c-41cd-92cf-2bf7969ee54e" }
background.js:1:67100
[debug] background/sessions: =>put() success background.js:1:67100
[info] popup/components/PopupPage: openNotification() 
Object { message: "Session saved.", type: "success", duration: 2000 }
popup.js:1:72442

**Comment by sienori** [comment]
I think that the database of TSM is corrupted.
The solution is to delete the TSM folder in profile's storage folder (Previous sessions will be lost).
Thank you for your understainding.

**Comment by WolfganP** [comment]
Same issue here. None of the wiki troubleshooting procedures helped, had to start saving sessions from scratch (previous windows/tab arrangements lost).
Is there any manual procedure where a session can be recovered from the storage/default/addon-folder files previously backed up?

**Comment by angeltek** [comment]
@WolfganP:  I deleted the TSM folder as advised above and was able to revert to an earlier set from a backup of my system that at least had some of my open sessions.  I now have a second session manager installed in Firefox which I use as a form of backup in between full system backups.  To be fair I haven't had any other problems with Sienori's Tab-Session-Manager before or since.

**Comment by WolfganP** [comment]
Thx @angeltek 
I tried to import some sessions from profile\sessionstore-backups folder but it seems TSM doesn't like any of the jsonlz4 files saved by the extension (even trying with uncompressed versions).

**Comment by sienori** [comment]
Sorry for the inconvenience.
I recommend using the **local backup option** or the **cloud sync function** in case the session is lost.
![backup](https://user-images.githubusercontent.com/29514424/78506378-07637a80-77b4-11ea-9908-a6bbe9a99c2d.png)
