### ISSUE TITLE
TSM lost my saved sessions + can not save sessions anymore

### ISSUE THREAD

**Issue by Kinofaya** [sienori/Tab-Session-Manager#399]
Hi,

I have no saved sessions left in TSM, and it wont let me save sessions anymore.
In TSM folder I have a storage.js.migrated file that I can not import.
I opened some with notepad and it seems some of my tabs appears in it.

I tried to reinstall TSM already, but no changes.

Can you help to recover my sessions, or at least help me so I can save sessions ?

**Comment by Andrzej-Andrzej** [comment]
This happened to me as well. After Firefox add-ons were disabled my TSM are gone. Where are they stored ? Is it a way to recover it ?

**Comment by sienori** [comment]
@Kinofaya 
It is probably an IndexDB error.
See https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

@Andrzej-Andrzej 
It is not a bug of TSM. #400
See https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox

**Comment by Kinofaya** [comment]
It worked !
Thx a lot !
