### ISSUE TITLE
Import .session Files from Session Manager

### ISSUE THREAD

**Issue by Domysee** [sienori/Tab-Session-Manager#40]
Hi, thanks for replacing Session Manager! Awesome work!

Is there any possibility to import sessions from Session Manager? 
If not, would it be possible to add it?
That would be a huge relieve, as I have many many sessions, and transferring them manually is not feasible.

**Comment by ceribik** [comment]
The addon MySessions claims to be able to do it, so presumable it's possible.

**Comment by Domysee** [comment]
Are there any plans to implement that?

**Comment by AndrewThompson1** [comment]
Seconding the request for this ability, as Firefox now no longer supports Session Manager and I too have many save sessions that I can't access. Firefox recommends Tab Session Manager as the replacement for Session Manager, so I wouldn't be surprised if you get more requests for this. Thank you.

**Comment by ITriptych** [comment]
Thank you so much for creating a replacement for this invaluable tool!

Please add my voice to the chorus asking for an import function.  I have been relying heavily on Session Manager for some time to organize my online research.  It could take me months to recover all the sessions I've generated by crawling through the individual session files for the urls.  I'm in the middle of several projects for which I now cannot access several actively needed SM session files, so I will try the "My Sessions" tool.  Failing that, I'll have to start digging into the session files, so I (and I imagine many others) would greatly appreciate a native means to import those sessions into your app.  

Thanks again!

**Comment by sienori** [comment]
I implemented it. https://github.com/sienori/Tab-Session-Manager/commit/3b68b5a7bb8b4c3ee9f71ff6b9e54bcf3153c483
Please wait a little more until the update

**Comment by Domysee** [comment]
Awesome, that was quick!
Thank you so much!

**Comment by ITriptych** [comment]
Hat’s off to you sir…and many thanks!  It means a lot that you took the time to address our need so quickly.

**Comment by ffreeman21** [comment]
Thank you so much for replacing Session Manager - and now for providing the ability to import previous sessions.  

Could you clarify whether "wait a little more until the update" means a few days, or weeks, or what?

Personally I rely on Session Manager a huge amount for managing mutiple projects etc.  I have literally several hundred sessions saved (Yes - I need to purge the old ones!) within about 30 different categories.  I note that another user has asked for the inclusion of "groups"/categories for classifying the saved sessions, and hope that you will also be able to implement that feature.

**Comment by kymharper** [comment]
Please add me to the list of those eagerly awaiting the update and thanks also :-)

**Comment by Domysee** [comment]
Well, since this is implemented now, I think the issue can be closed.

Thanks again @sienori

**Comment by Maggy11** [comment]
@sienori , rnc is correct to reference to my message #50 . I am still not able to open my .session sessions, but after a reboot I didn't get my last session back either.

**Comment by ziwer1** [comment]
Thanks to you sir, I am moving back to FF.
