### ISSUE TITLE
Restore windows in accordance to Windows 10 virtual desktops

### ISSUE THREAD

**Issue by RIS2000** [sienori/Tab-Session-Manager#401]
On Windows 10 is it possible to make Tab session manager to restore Firefox windows in accordance with the virtual desktop on which they were ?

It could be a great feature!

**Comment by sienori** [comment]
Perhaps the WebExtensions API can not control the state of Windows virtual desktops.
Thank you for your understanding.

**Comment by allanlaal** [comment]
continued in #913
