### ISSUE TITLE
All sessions are gone after reset

### ISSUE THREAD

**Issue by AndyDeNike** [sienori/Tab-Session-Manager#402]
After resetting firefox, loading my profile, all my session data was gone.  I attempted to import "storage.json.migrated" file but it but it was greyed out and could not select.  This may be the wrong file entirely, and if thats the case if anyone could please tell me where I could find the proper file (or location of my previous  session data).  Any help/advice as to what might be going wrong would be truly appreciated, thank you for your time!

<img width="809" alt="Screen Shot 2019-05-04 at 3 08 55 PM" src="https://user-images.githubusercontent.com/15356537/57185367-d3365a00-6e7e-11e9-9925-2d32555271ec.png">

**Comment by sienori** [comment]
This page may help you.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by AndyDeNike** [comment]
@sienori thank you so much for responding, in this case, I want to bring back all the sessions I lost, would it be possible to do so from my current profile (rather than migrating to another profile).  

Based on this picture I am seeing 13 or so moz-extension+++ directories.  Would you have any tips on how to get my original sessions back ?  

<img width="1050" alt="Screen Shot 2019-05-06 at 11 33 56 AM" src="https://user-images.githubusercontent.com/15356537/57246810-0863b900-6ff3-11e9-870b-6efa8eebaa08.png">

**Comment by sienori** [comment]
Unfortunately, I think that session data was deleted by the reset of Firefox.
To restore old sessions, you need to have a backup of the old profile or old sessions.

**Comment by AndyDeNike** [comment]
thank you, I will be careful of this going forward!
