### ISSUE TITLE
Can't open Tab Session Manager to view my session

### ISSUE THREAD

**Issue by Infernoflower** [sienori/Tab-Session-Manager#405]
Hello, when I try and open Tab Session Manager, it opens up for a few seconds, then closes and doesn't show my sessions. Note that this doesn't happen in a different profile, and I'm using the same version in both profiles. What should I do?

**Comment by sienori** [comment]
Please show me the debug log when you open the toolbar popup.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

Perhaps the cause is an IndexedDB error.
See https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

**Comment by Infernoflower** [comment]
Here's the debug log on Console: 

Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
TypeError: content is null ext-browser-content.js:234:15
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
Error: Could not establish connection. Receiving end does not exist. background.js:35:297950
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
Error: Could not establish connection. Receiving end does not exist. background.js:35:298003
TypeError: a is undefined background.js:1:261051
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Q&A How to use debug mode · sienori/Tab-Session-Manager Wiki 
Array [ "temp" ]
 default background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[error] background/sessions: getAll() 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, eventPhase: 0, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 18452913, … }
background.js:1:67100
TypeError: a is undefined background.js:1:261051

Do you think these errors have something to do with it not opening?

**Comment by Infernoflower** [comment]
Deleting the 'storage' file in my profile appears to have fixed the problem. Thanks so much for your help.
