### ISSUE TITLE
I can't import session buddy session

### ISSUE THREAD

**Issue by kotenok2000** [sienori/Tab-Session-Manager#408]
## Short description

I can't import session buddy session
## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. 
4. 

## Platform information
* Platform (OS): 
* Version of browser: 
* Version of Tab Session Manager: 

## Additional context

[session_buddy_export_2019_05_29_13_13_37.json.txt](https://github.com/sienori/Tab-Session-Manager/files/3231947/session_buddy_export_2019_05_29_13_13_37.json.txt)

**Comment by alexckwok** [comment]
I know that this is several months old, but I am also having the same issue now. I am trying to import a json file from Session Buddy (Chrome) into Tab Session Manager (Firefox) and keep getting a "read failed" error - to which clicking "import" then does nothing. 

Steps to Reproduce:
1. Download both Chrome & Firefox Browsers (I am running beta on both, but stable works too!)
2. Install Session Buddy on Chrome and Tab Session Manager on Firefox
3. Open windows that you want to save to a session on Chrome
4. Save the session using Session Buddy on Chrome
5. Within the Session Buddy interface, click the gear icon in the upper right-hand corner, then "Export".
6. Ensuring that "Sessions" and "Windows" are both selected, and that "Saved" is selected under the drop down menu next to Sessions, export the session as a json file to your desktop.

7. Close Chrome and Open Firefox. 
8. Navigate to the Tab Session Manager Settings, by right clicking on the Tab Sessions icon in the addons bar. Click "Sessions" in the left hand menu, then click "Browse" next to Import Sessions.
9. Select the json file that you saved using Session Buddy, and click "Open".
10. The error message "Read Failed" will display underneath the filename of the Session Buddy session. Clicking "Import" will then exit you out of that view, but opening Tab Session Manager after will show that none of the sessions imported successfully.

Expected Result: Importing a json file from the Session Buddy extension in Chrome to Tab Session Manager will import the correct number and details of sessions from Session Buddy to Tab Session Manager. It is assumed that the text under the filename in Tab Sessions Manager settings would change to read "Read Successful".

Actual Result: Importing a json file from the Session Buddy extension in Chrome to Tab Session Manager ends in a "Read Failed" error message. Further checking the Sessions in Tab Sessions Manager will reveal that nothing has imported successfully. 

Platform (OS): Microsoft Windows 10 Home 1903
Version of Browser: Firefox 70.0b8 (64-bit); Google Chrome 76.0.3809.132 (64-bit)
Version of Session Buddy: 3.6.3
Version of Tab Session Manager: 5.1.0

**Comment by narfanar** [comment]
This's currently my biggest hurdle in trying to migrate from Chrome to Firefox. Without the ability to migrate my dozen (too big) sessions, I'll just have to stay on Chrome for now.

And a big part of the reason I started migration was to make use of the Simple Tab Groups extension to mitigate this big session issue, but alas.

**Comment by sienori** [comment]
Version 6.10.0 now supports importing Session Buddy sessions! https://github.com/sienori/Tab-Session-Manager/commit/c0ece0a9aeb38c7314e84edca86a3bba11dce0fc
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-How-to-import-sessions-from-other-extensions
![image](https://user-images.githubusercontent.com/29514424/129353314-cacfcef2-8af0-4d3c-a47f-eb4e5995f276.png)

**Comment by Darthagnon** [comment]
Thank you so much for this! (Wish I'd had this option back in the day when I transferred everything over manually).

**Comment by bhuvidya** [comment]
This fix might need to be updated. I have exported from Session Buddy v3.6.4, macOS 10.15.7, and the js function which checks for a valid Session Buddy file is looking for some keys that don't exist - "created", "modified", "id" and "gid". Once I added these keys with dummy values the importer was happy. Cheers.

**Comment by MJJoyce** [comment]
For anyone else running into an issue here, note that the Session Buddy export instructions show that you should pick the "Saved" sessions. If you pick "All" and the current session is included you will run into read failures. The current session lacks some of the required keys like above indicates. For me it was missing `created`, `id`, and `gid`. Could just save the current session and then export as well to address this (I imagine).

**Comment by BeVarLurton** [comment]
> For anyone else running into an issue here, note that the Session Buddy export instructions show that you should pick the "Saved" sessions. If you pick "All" and the current session is included you will run into read failures. The current session lacks some of the required keys like above indicates. For me it was missing `created`, `id`, and `gid`. Could just save the current session and then export as well to address this (I imagine).

came here for this, was not dissapointed, written from my now completly ported allnew firefox return :-)

**Comment by akohlsmith** [comment]
This bug still exists with Session Buddy 4.0.5 and Tab Session Manager 7.1.1. The exported collections only have `url`, `favIconUrl` and `title` keys no matter if I select "all" or "selected".
