### ISSUE TITLE
firefox - restores saved private browsing windows as normal windows

### ISSUE THREAD

**Issue by LJMP** [sienori/Tab-Session-Manager#410]
## Short description
firefox version now restores saved private browsing windows as normal windows!

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. enable Save private window, Startup: Restore previous session at startup
4. open a new **private browsing window** and some tabs
4. close firefox
5. reopen firefox: the once private browsing window tabs get restored in **normal window**

## Expected result
private browsing window tabs get restored in **private browsing window**
(it worked like this before mozilla made this extension _allowed in private windows_ shenanigans)

## Actual result
once private browsing window tabs get restored in **normal window**

## Platform information
* Platform (OS): ubuntu
* Version of browser: 67.0.1 (64-bit)
* Version of Tab Session Manager: Version 4.5.2

## Additional context
it worked fine restoring private browsing windows before this extension _allowed in private windows_ thingy

**Comment by auralarch** [comment]
It actually does seem to consistently restore private window tabs to a private window in Windows 7 Ultimate x64.

**Comment by LJMP** [comment]
somehow magically works again🤷✨ 
closing this
