### ISSUE TITLE
Tabs with a local file system address can not be restored

### ISSUE THREAD

**Issue by megies** [sienori/Tab-Session-Manager#412]
## Short description

Tabs with a local filesystem address (e.g. to some png file, in the example a local file `file:///tmp/some_image.png`) are not restored properly (e.g. when exiting browser and restarting it).

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Navigate to a local file, e.g. put `file:///tmp/some_image.png` in address bar to show a locally stored image
4. Close browser session/window
5. Reload browser session/window through Tab Session Manager
6. Instead of navigating to the `file://...` address, a failure page is shown (see below screenshot)

## Expected result

The tab showing a local file should be properly restored, with a `file://...` address in the address bar.

## Actual result

A failure notification page is shown above with the actual local file address and a note that `"This page can not be opened by Tab Session Manager."`

![Screenshot from 2019-06-12 15-11-49](https://user-images.githubusercontent.com/1842780/59354078-a2bac900-8d24-11e9-9124-439abf262ab7.png)

## Platform information
* Platform (OS): Linux, Debian 9 stretch
* Version of browser: 67.0.1 (64-bit)
* Version of Tab Session Manager: Version 4.5.2

**Comment by sienori** [comment]
Local files can not be opened due to limitation of WebExtensions. #234
