### ISSUE TITLE
unable to read text due to font colour

### ISSUE THREAD

**Issue by zayd62** [sienori/Tab-Session-Manager#418]
## Short description

the options menu (the three dots) for a session is difficult to read due to font colour

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. have a session saved 
4. click on three dots in upper right for the session
5. notice that the text is grey on white

## Actual result

![2019-07-07 at 17:15](https://user-images.githubusercontent.com/26032382/60771112-dcd87a00-a0da-11e9-8a0c-31dd225f36b2.png)
the red arrow is the problem, blue arrow is the menu buttons pressed to get to the problem

## Platform information
* Platform (OS): from ```cat /etc/os-release```:
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Version of browser: 67.0.4
* Version of Tab Session Manager: 4.5.2

## Additional context

seems to only happen when i am using a dark theme, specifically pop-OS dark [`GitHub page here`](https://github.com/pop-os/gtk-theme) as my application theme. in pop-OS light it has the font color as black so it seems to be looking at the OS theme and coloring the font accordingly (light theme --> dark text, dark theme --> light text).

**Comment by sienori** [comment]
This problem has already been solved.
