### ISSUE TITLE
Did a Firefox refresh all sessions lost?

### ISSUE THREAD

**Issue by Strogano** [sienori/Tab-Session-Manager#419]
Apparently I made a huge mistake. I refreshed Firefox from "about:support", and of course lost all my sessions and now can't find my backed up sessions which I am sure I have made (I must have deleted them by accident when deleting old Firefox bookmark files, very untypical of me since I'm neurotic about my backups and usually have them in two places at least).

So is there anything I can do? 

Looking inside sessionstore-backups in my Firefox profile, there are 4 files but the two bigger ones are created after the refresh: upgrade.jsonlz4-..., previous.jsonlz4, recovery.baklz4  and recovery.jsonlz4.

**Comment by Strogano** [comment]
Ok apparently Firefox has created a back up of the old profile on the desktop! What should I move from there to the new profile to get my old sessions back? Tried moving the folder sessionstore-backups but that didn't work. I don't want to replace the whole new profile with the old one if possible because refreshing Firefox actually solved a problem I've been having with Firefox.

**Comment by sienori** [comment]
This page may help you.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by Strogano** [comment]
Thanks, I didn't try that but ended up restoring my old profile from the backup Firefox created & got my sessions back yippee!
