### ISSUE TITLE
Autosave does not work

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#420]
TSM 4.5.2 on FF 67.0.4 (64-bit) Linux, does not save sessions automatically anymore.

I have autosave enable every 20 minutes, and 'save the session regularly' is toggled. However when I click on the floppy disk icon to check whether the session has been saved or not, It shows no current session saved.

I wanted to enable debug mode but I didn't understand where the output was..
If I can provide more info please let me know.

ps: I don't know if it matters but I previously imported,sessions i have (and which are not the one that should b saved automatically) from an older ff profile.

**Comment by sienori** [comment]
See this page for how to use the debug mode.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

Does session save work?

**Comment by WPFilmmaker** [comment]
Thanks I will give it a look!
TSM does regularly backup as instructed
And if I click 'save a session' button it does save.
I also noticed that 'Restore previous session at startup' restores the last session when I imported the sessions from another profile. It ignores that a new session (saved manually because autosave does not work) is available.

**Comment by WPFilmmaker** [comment]
I was able to enable debug and I tried changing settings a bit and then reverting to the one i mentioned in the first post to see if debug showed something. I got:
.....................
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
undefined is not a valid URL. background.js:321
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
undefined is not a valid URL. background.js:321
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:490:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
Security Error: Content at moz-extension://f12c3156-2432-4c46-904f-4e4f4ce58a58/ may not load data from blob:null/983331fa-a91f-4987-9991-6ab76e8f154b.
Loading failed for the <script> with source “blob:null/983331fa-a91f-4987-9991-6ab76e8f154b”. blank:1:1
Promise resolved after context unloaded
polyfill.js:241
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
Security Error: Content at moz-extension://f12c3156-2432-4c46-904f-4e4f4ce58a58/ may not load data from blob:null/ee9c0692-1d83-4484-b4a9-3426cf0e3127.
Loading failed for the <script> with source “blob:null/ee9c0692-1d83-4484-b4a9-3426cf0e3127”. blank:1:1
Promise resolved after context unloaded
polyfill.js:241
undefined is not a valid URL. background.js:321
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
Security Error: Content at moz-extension://f12c3156-2432-4c46-904f-4e4f4ce58a58/ may not load data from blob:null/b1784667-69db-4461-ad60-eb4c57e0d7bb.
Loading failed for the <script> with source “blob:null/b1784667-69db-4461-ad60-eb4c57e0d7bb”. blank:1:1
Promise resolved after context unloaded
polyfill.js:241
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:490:25
TypeError: can't access dead object
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
Error: Invalid tab ID: 1610 ExtensionUtils.jsm
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Debugging with Firefox Developer Tools 
Array [ "temp" ]
 default background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[debug] background/sessions: =>getAll() 
Array(48) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
background.js:1:67100
[debug] background/save: saveSession() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 783, name: "Debugging with Firefox Developer Tools", date: 1562932044159, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
 false background.js:1:67100
[debug] background/sessions: put() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 783, name: "Debugging with Firefox Developer Tools", date: 1562932044159, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
background.js:1:67100
[error] background/sessions: put() 
IDBRequest { error: DOMException, source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", onsuccess: onsuccess(), onerror: onerror() }
background.js:1:67100
[error] background/save: saveSession() 
IDBRequest { error: DOMException, source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", onsuccess: onsuccess(), onerror: onerror() }
background.js:1:67100
[info] background/background: onMessageListener() 
Object { message: "getInitState" }
background.js:1:67100
[info] background/background: onMessageListener() 
Object { message: "getSessions", id: null, needKeys: (6) […] }
background.js:1:67100
[debug] background/getSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: getAll() 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: =>getAll() 
Array(48) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Tab Session Manager 
Array [ "temp" ]
 default background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[debug] background/sessions: =>getAll() 
Array(48) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
background.js:1:67100
[debug] background/save: saveSession() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Tab Session Manager", date: 1562932149571, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
 false background.js:1:67100
[debug] background/sessions: put() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Tab Session Manager", date: 1562932149571, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
background.js:1:67100
[info] settings/settings: setSettings() ifAutoSave false options.js:1:80119
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. ExtensionUtils.jsm
[error] background/sessions: put() 
IDBRequest { error: DOMException, source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", onsuccess: onsuccess(), onerror: onerror() }
background.js:1:67100
[error] background/save: saveSession() 
IDBRequest { error: DOMException, source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", onsuccess: onsuccess(), onerror: onerror() }
background.js:1:67100
[info] settings/settings: setSettings() ifAutoSave true options.js:1:80119
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. ExtensionUtils.jsm
[info] popup/components/PopupPage: init() popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getInitState" }
background.js:1:67100
[debug] popup/actions/controlSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "getSessions", id: null, needKeys: (6) […] }
background.js:1:67100
[debug] background/getSessions: getSessions() null 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: getAll() 
Array(6) [ "id", "name", "date", "tag", "tabsNumber", "windowsNumber" ]
background.js:1:67100
[debug] background/sessions: =>getAll() 
Array(48) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
background.js:1:67100
[info] popup/components/PopupPage: saveSession() Debugging with Firefox Developer Tools saveAllWindows popup.js:1:72442
[info] popup/actions/controlSessions: sendSessionSaveMessage() Debugging with Firefox Developer Tools saveAllWindows popup.js:1:72442
[info] background/background: onMessageListener() 
Object { message: "saveCurrentSession", name: "Debugging with Firefox Developer Tools", property: "saveAllWindows" }
background.js:1:67100
[debug] background/save: saveCurrentSession() Debugging with Firefox Developer Tools 
Array []
 saveAllWindows background.js:1:67100
[debug] background/save: loadCurrentSession() Debugging with Firefox Developer Tools 
Array []
 saveAllWindows background.js:1:67100
[debug] background/save: saveSession() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Debugging with Firefox Developer Tools", date: 1562932216055, tag: [], sessionStartTime: 1562922337998, id: "47154ee9-dee0-4d87-b474-7779ff647132" }
 true background.js:1:67100
[debug] background/sessions: put() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Debugging with Firefox Developer Tools", date: 1562932216055, tag: [], sessionStartTime: 1562922337998, id: "47154ee9-dee0-4d87-b474-7779ff647132" }
background.js:1:67100
[debug] background/sessions: =>put() success background.js:1:67100
[info] popup/components/PopupPage: changeSessions() 
Object { message: "saveSession", session: {…} }
popup.js:1:72442
[info] popup/components/PopupPage: openNotification() 
{…}
​
duration: 2000
​
message: "Session saved."
​
type: "success"
​
<prototype>: Object { … }
popup.js:1:72442
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. ExtensionUtils.jsm
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Tab Session Manager 
Array [ "temp" ]
 default background.js:1:67100
[info] background/autoSave: handleTabUpdated() background.js:1:67100
[info] background/autoSave: setUpdateTempTimer() background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
[debug] background/sessions: =>getAll() 
Array(49) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
background.js:1:67100
[debug] background/save: saveSession() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Tab Session Manager", date: 1562932255611, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
 false background.js:1:67100
[debug] background/sessions: put() 
Object { windows: {…}, windowsNumber: 3, windowsInfo: {…}, tabsNumber: 784, name: "Tab Session Manager", date: 1562932255611, tag: (1) […], sessionStartTime: 1562922337998, id: "af6a7256-de2a-471b-900e-30434deded95" }
background.js:1:67100
[debug] background/autoSave: updateTemp() background.js:1:67100
[debug] background/save: loadCurrentSession() Tab Session Manager 
Array [ "temp" ]
 default background.js:1:67100
[debug] background/tag: getSessionsByTag() temp null background.js:1:67100
[debug] background/sessions: getAll() null background.js:1:67100
.....................
I noticed an error was shown as well, I think when TSM was supposed to autosave. I couldn't copy and paste so I screenshooted it:
https://imgur.com/4BYCrhzhttps://imgur.com/4BYCrhz

**Comment by WPFilmmaker** [comment]
issues were probably caused by a corrupted file or something, in a new installation everything works, closing.
