### ISSUE TITLE
[Feature Request] Named window support - FireTitle

### ISSUE THREAD

**Issue by choman** [sienori/Tab-Session-Manager#423]
I've been playing with [crappy-firetitle](https://addons.mozilla.org/en-US/firefox/addon/crappy-firetitle/) and like it right up until I need to restart firefox

Then I thought it would be good if Tab-Session-Manager just supported the same functionality

Just a thought, Cheers
Keep up the great work

**Comment by sienori** [comment]
I've implemented window title restoration! 8c36c38 https://github.com/sienori/Tab-Session-Manager/issues/690
