### ISSUE TITLE
All sessions lost on update

### ISSUE THREAD

**Issue by wbt** [sienori/Tab-Session-Manager#424]
## Short description
On updating the extension (trying to get the UI elements shown [here](https://github.com/sienori/Tab-Session-Manager/issues/350) for import/export, which were not showing), ALL session data was immediately lost without warning, including the backup copy of the database also stored in the extension's storage directory.  This was a very negative experience.   Some warning would be much appreciated!

**Comment by sienori** [comment]
Sorry for the inconvenience.
Please see below for how to fix DB error:
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

I recommend using the **local backup option** or the **cloud sync function** in case the session is lost.
![backup](https://user-images.githubusercontent.com/29514424/78506378-07637a80-77b4-11ea-9908-a6bbe9a99c2d.png)
