### ISSUE TITLE
FF68 blinks on startup

### ISSUE THREAD

**Issue by jniggemann** [sienori/Tab-Session-Manager#425]
## Short description
FF68.0.1 with TSM 4.5.2 on Win10
When starting FF, it opens (with all tabs as expected), immediately closes and opens again - then it's ready to use. This started after installing TSM.

**Comment by sienori** [comment]
You seem to have enabled the option to restore the previous session on startup in both TSM and Firefox.
Disable the option to restore the previous session at startup in TSM.
![image](https://user-images.githubusercontent.com/29514424/64519793-d14e3d00-d32f-11e9-925d-ed742fc1787d.png)
![image(1)](https://user-images.githubusercontent.com/29514424/64519796-d27f6a00-d32f-11e9-954b-dffb84740cf0.png)

**Comment by jniggemann** [comment]
Exactly, thank you for pointing this out
