### ISSUE TITLE
[Version 5.0] UI bug when opening from overflow menu

### ISSUE THREAD

**Issue by harogaston** [sienori/Tab-Session-Manager#436]
If you place the add-on in Firefox's overflow menu section, opening it renders the UI all wrong. The window is not big enough.

**Comment by IT-Sumpfling** [comment]
This is how this looks:
![image](https://user-images.githubusercontent.com/13335853/64438098-c2fde800-d0c7-11e9-9e51-7b4da9fab0a7.png)

Workaround for now: use the new "Open session list in new tab" option.

**Comment by kgoutsos** [comment]
I'm getting the same issue (Firefox 69 on Ubuntu). Increasing the width in the preferences (e.g. #372) does not seem to work in this mode.

Note: the same issue was present in TSM versions <5.0

**Comment by sienori** [comment]
This is due to a bug in Firefox. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1373490
Many other extensions are also affected by this bug.

**Comment by sienori** [comment]
I added an option to adjust the size to fit the overflow menu.

![image](https://user-images.githubusercontent.com/29514424/64638693-3e052c80-d441-11e9-9d53-a3a24b16f0ee.png)
![image](https://user-images.githubusercontent.com/29514424/64638563-faaabe00-d440-11e9-884a-706fdcbd20b3.png)

**Comment by kgoutsos** [comment]
Works very well for me, thanks. 

Maybe it's my screen size but I'm getting this tiny issue with the "No sessions selected." label being too close to the border with the default sidebar width. It looks much better with a 280 sidebar width.

![image](https://user-images.githubusercontent.com/1337633/64732894-9426ae00-d4db-11e9-9731-2d4e0bfd4b9a.png)

**Comment by ThisIsABug** [comment]
Someone on bugzilla proposed to solve this issue like chrome did:
When the button is clicked, being inside the overflow menu, it gets temporarily moved into the toolbar to show the full-sized window.
Wouldn't this be a good workaround for such an extensive bug on mozillas side?
I mean this will not be fixed soon, it will take (and took already) a looong time.

**Comment by hackel** [comment]
The solution is to change the entire popup to only show the selected session, with a back button to return to the session list.  It should not try to show both side-by-side, and adjusting the widths to squeeze them both in produces an extremely poor experience.
