### ISSUE TITLE
5.0.0 and slow-downs on the right-column

### ISSUE THREAD

**Issue by TinyTrbl** [sienori/Tab-Session-Manager#437]
**Is your feature request related to a problem? Please describe.**
Before 5.0.0 i was able to navigate and manage sessions list without slowdowns, but with 5.0.0 you made that session content is always populated in the right-column, and really large sessions just hang my Firefox for a while.

i.e. with 5.0.0 you cannot use three-dot-menu or delete-button without showing session's content, and addon hangs on big session for a while... which is bad.

**Describe the solution you'd like**
1) put delete command into three-dot-menu
2) now add three-dot-menu back to the left-column items, but in a special area that will not open these items right away (i.e. three-dot-button will open menu but not select the session)

**Describe alternatives you've considered**
Or add an option that prevents right-column item's lists from being populated until clinking on arrow-button (**>** this one), like it was worked before 5.0.0.

Thank you! Hehe!

**Comment by sienori** [comment]
I will implement an option that will not expand the tab list if the selected session is huge.
Also, I plan to add open and delete buttons to the session list. #447

**Comment by sienori** [comment]
In version 6.2.0, the loading of the session when the pop-up is opened has been greatly accelerated.
Thanks!
