### ISSUE TITLE
Buttons for simple regular actions.

### ISSUE THREAD

**Issue by alexdali** [sienori/Tab-Session-Manager#440]
**Is your feature request related to the problem? Please describe.**
In connection with 2-column layouts require more unnecessary movements for simple standing action.

** Describe the solution you want**
Is it possible to add quick buttons ("open" and "delete") under the name of each session. In the left column (where sessions are listed)

** Describe the alternatives you have considered**
Better in the form of icons without text.
You can implement them as a drop-down menu, as it was before. But it is each session that has its own and in the left column.

** Additional context**
Anyway, thanks for the nice extension.

**Comment by sienori** [comment]
I plan to add open and delete buttons to the session list.
Discuss in #447
