### ISSUE TITLE
A way to restore old single column layout functionality.

### ISSUE THREAD

**Issue by L0stLink** [sienori/Tab-Session-Manager#441]
The old column layout allowed the deletion of sessions by hovering over the list and clicking on delete. This was a smooth, fast one click solution. The new layout requires a click to select the list and then to move across the UI to the other side to click delete. This quickly becomes tedious when a lot of entries have to be deleted.

It would be great if there was a way to toggle the old UI from the setting.

An alternative solution could be to automatically select the top most element form the list of sessions. This will still enable fast deletion of elements.

**Comment by MichaelMFeldman** [comment]
Yes @sienori - thank you for your hard work on this extension. I use it every day. Unfortunately this UI looks pretty but kind of sucks. If I'm opening the extension, 99% of the time I want to open or delete a session, and I already know which one it is based on the number of windows or tabs and the timestamp. What was once a one-click action is now two.

Why not keep the two column layout while still showing an Open button inline?

Thank you!

**Comment by sienori** [comment]
I plan to add open and delete buttons to the session list.
Discuss in #447

There is no plan to restore old single column layout.
This is because it will be difficult to maintain compatibility when the tab editing function is implemented in the future.

**Comment by L0stLink** [comment]
That is okay, I just wanted the old workflow back, having a single column layout would be ideal but is not a priority. The most used feature for me is deleting unwanted, auto-saved sessions. I have the same concirns as nollinvoyd when it comes to being able to deleting sessions quickly:
> I second the motion, but I have a question.
> 
> It's not uncommon for me to collect 50+ sessions in the list. With the old setup, I could just repeatedly click-click-click on delete, leaving my mouse in the same position as the next session would move up to take the place of the deleted one, and in a matter of seconds, remove as many older session as I pleased.
> 
> But now, deleting just one session is painfully slow. You click on a given session, have to wait until it's list loads, then reach over to the right button to delete, and then you have the deletion delay before continuing.
> 
> Will bringing the open & deleted buttons back to their original position return the previous speed efficiency. If not, maybe have an option to close that new side panel, if that would help speed things up?
> 
> thanks

Thanks for all your work.

**Comment by L0stLink** [comment]
Closing in favor of #447.
