### ISSUE TITLE
Forced to use the new tab view because the regular "old" window is now too small to display anything

### ISSUE THREAD

**Issue by BitGrub** [sienori/Tab-Session-Manager#446]
As the subject line says. Can no longer view/open/delete sessions because the window is too small. Forced to use the "open in new tab" option nobody asked for.

How can I roll back to the previous version?

**Comment by mcashm** [comment]
+1 I am seeing this too
![image](https://user-images.githubusercontent.com/42278717/64543240-de007000-d2f2-11e9-8586-b7bccc504269.png)
