### ISSUE TITLE
Saved sessions in groups

### ISSUE THREAD

**Issue by Jbowman57** [sienori/Tab-Session-Manager#45]
The old sessions manager allowed sessions to be saved in groups (not sure what it was called) so that I could have several sessions saved under a project name.  Is there any way to implement this?  Hopefully this makes sense.  I've used this old feature all the time but don't remember what they called it.

**Comment by ffreeman21** [comment]
I'd like to strongly endorse this request - I have so many sessions saved (altho' they do need to be purged somewhat) that I couldn't manage or find the relevant sessions with the use of Groups.

I've just checked - the old Session Manager does call them 'Groups', altho' I think of them as 'Categories'. 

I'm currently staying with FF v.56 for a bit until I can transfer my (several hundred!) saved sessions across to FF57.

**Comment by sienori** [comment]
Interesting.
It will be implemented in the future.
(After adding the function to manage sessions with the list.)

**Comment by ffreeman21** [comment]
Any idea of timescale for this, please?  The absence of both this facility & the ability to save current window only (as distinct from whole browser session) are show-stoppers for me.  I'm wondering whether I should be considering an alternative browser that has an extension providing these options?

**Comment by sienori** [comment]
I implemented the function to manage sessions with tags.
https://github.com/sienori/Tab-Session-Manager/commit/aec6ee4cc1694979844cf85ca99996f94a64e9b8
https://github.com/sienori/Tab-Session-Manager/commit/d62a3f07cae678c06a9af3418a6c7f2dd4759ece

@ffreeman21 Also, I implemented the function to save only the current window.
 https://github.com/sienori/Tab-Session-Manager/commit/5ede5f3797fa013ccd6515253c7e3e78448c093e
