### ISSUE TITLE
Save backup interrupts Firefox's restore previous session feature

### ISSUE THREAD

**Issue by futagoza** [sienori/Tab-Session-Manager#450]
## Short description

It seems that when I restart Firefox with TSM's "Save Backup" feature enabled, it generates and then downloads the backup of sessions it has saved. This is expected, but after saving 8+ sessions (with only 1 containing multiple windows), I figured out that this seems to be interrupting Firefox's session restore functionality, specifically, the active tab on the main window does not load correctly most of the time (most of the time it doesn't load, sometimes it loads after the backup is generated), while the active tab on other windows don't load until the backup is generated.

## Steps to reproduce

1. Start browser with a clean profile
2. Install Tab Session Manager, enabling the "Save Backups" feature
3. Open multiple windows with multiple tabs
4. Save multiple sessions
5. Restart Firefox

## Expected result

1. Normal behaviour from Firefox's restore previous session feature
2. Background generation of the backup and download

## Actual result

TSM's "Save Backup" feature seems to take priority, interrupting/altering the behaviour of Firefox's restore previous session feature.

## Platform information

* Platform (OS): Windows 10 x64 (Up to date)
* Version of browser: 69.0 _(problem was first observed on 68.x)_
* Version of Tab Session Manager: 5.0.0

## Additional context

Like I said above, I only noticed the problem after I had 8+ sessions saved, but because I usually turn on my browser and then go do something else for a few minutes (like make tea), there's a possibility this has nothing to do with the problem.

**Comment by sienori** [comment]
In the current version, the backup starts 30 seconds after the browser is launched.
