### ISSUE TITLE
Session context menu gets positioned off screen

### ISSUE THREAD

**Issue by kmelvn** [sienori/Tab-Session-Manager#451]
Select any session, and try to open the context menu for that session (by clicking the three vertical dots). The menu is positioned completely to the right, barely visible on the right edge. This happens when opening the Session Manager both in popup mode or as a separate tab.

![tabsession](https://user-images.githubusercontent.com/6759115/64702701-4d20c480-d4ab-11e9-9744-7bb3540a5ead.png)

When inspecting the popup context menu (`div#menu`) there's a CSS property `left: 1300px` (pixel amount depends on the screen size, of course) that positions the popup off the screen.

Platform info: latest Arch Linux, Firefox 69.0 using the Wayland back-end, plugin version 5.0, (same behavior on a fresh Firefox session with just Tab Session Manager).

**Comment by sienori** [comment]
I fixed this bug. https://github.com/sienori/Tab-Session-Manager/commit/ee64825ff1e5c333b8480eb2d1299070d3034e8a
Thanks!
