### ISSUE TITLE
Restoring session windows separately.

### ISSUE THREAD

**Issue by kotenok2000** [sienori/Tab-Session-Manager#456]
**Is your feature request related to a problem? Please describe.**
I have lots of tabs in several windows, and when TSM tries to restore them all at once the memory usage becomes too much.
I was able to mitigate it by restoring one window, killing and reloading extension to reclaim memory and restore next window. Since 5.0 there is no option to restore windows separately.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Снимок экрана (55)](https://user-images.githubusercontent.com/8822292/64756303-1d1f0300-d537-11e9-8d65-93108682c98e.png)

**Comment by sienori** [comment]
I fixed the issue where windows without titles could not be opened individually. https://github.com/sienori/Tab-Session-Manager/commit/cbb2d78afbea8446424f8aa6d25b18178edaf986
Thanks!
