### ISSUE TITLE
Automatic upgrade silently closes many tabs

### ISSUE THREAD

**Issue by Thryduulf** [sienori/Tab-Session-Manager#457]
The last two automatic updates to Tab-Session-Manager (4.5.2 → 5.0.0; 5.0.0 → 5.1.0) have silently closed most of my open tabs. This time before the upgrade I had 161 tabs open, after the upgrade only 54 (including the one session manager opened in the background to tell me about the upgrade). 

Fortunately I could restore from a ~20 minute old backup (this time)/~2 hour old backup (previous time) but this is still _very_ bad and had I been away for an extended period I may not have been so fortunate. 

There should be exactly no circumstances when tabs are closed silently without confirmation.

**Comment by Thryduulf** [comment]
This has happened again -  136 tabs silently closed. Fortunately I was able to restore from an 8-minute old backup but had the upgrade happened tomorrow I would likely have not been so lucky and may have all but the 12 most recently visited tabs. 

There are absolutely no circumstances under which it should even be possible for this extension to silently close tabs, let alone desirable for it to do so. What have you done in the last two months to address this fundamental flaw?

**Comment by sienori** [comment]
This happens when `Tab lazy loding` is **enabled** and `Use the "discarded" property for lazy loading` is **disabled**.
![image](https://user-images.githubusercontent.com/29514424/68122308-64c97600-ff4d-11e9-9fa1-13bd86a51d61.png)

In Firefox, I recommend enabling `Use the "discarded" property for lazy loading` option.
In Chrome, this option is not available (due to WebExtensions API limitations). Disable `Tab lazy loding` option or turn off automatic extension updates.

**Comment by Thryduulf** [comment]
Thank you for that workaround for a problem that should not exist (and which has just happened _again_. 
However, I need to use lazy loading to avoid using up all my memory and rely on the favicons to navigate around my tabs quickly, even if they haven't yet been loaded this session so it's not really a viable option.  Turning off automatic extension updates is an alternative, but why should I have to degrade the performance of all my other extensions because a critical bug in this one extension has not been fixed?

**Comment by Thryduulf** [comment]
This is just to remind the developers that this is _still_ happening over a year after it was first raised as a serious issue.

**Comment by Thryduulf** [comment]
And it has just happened again. Is there truly no appetite to fix this serious bug?

**Comment by Thryduulf** [comment]
And yet again. If I was paying for this I'd have demanded a refund by now.

**Comment by sienori** [comment]
Sorry for the inconvenience. I will fix this problem.
Memo: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onUpdateAvailable

**Comment by sienori** [comment]
I fixed this problem. https://github.com/sienori/Tab-Session-Manager/commit/080f585b018809755b1c65f2e4853931f62e2923
Skip auto-updating when a lazy loading page is open.
It will be enabled in the next next update.

**Comment by r4m0n** [comment]
I feel this "fix" is a little too brittle... At best, this will silently disable upgrades on the extension for as long as people have 1 remaining unloaded tab, and only the people following this bug will be aware of that. And that's assuming the update bypass works on all supported browsers.

It might be a decent stopgap measure, but this doesn't looks like a proper final fix for the issue.
