### ISSUE TITLE
Add current tab to selected session

### ISSUE THREAD

**Issue by futagoza** [sienori/Tab-Session-Manager#458]
**Is your feature request related to a problem? Please describe.**

Currently, to add tabs to an existing session I have to either add the current window to it then remove the tabs I don't want, or move the tabs I want to a new window and then add that window to the desired session.

**Describe the solution you'd like**

1. Add an option called `Add current tab` to the `Edit a session menu`
2. All new tabs added this way would be added to an unnamed window entry in that session
3. This unnamed window entry would only be created on the first tab added via this method

**Describe alternatives you've considered**

1. Adding an option called `Add the current tab to an existing session` to page actions (the three dots at the end of the address bar). This would open up a new single-column popup that allows us to select which session we want to add it to. The rest would be as points 2 & 3 from the above solution.

2. Instead of the current tab, multiple tabs could be selected to add to an existing session using [this comment I made on #14](https://github.com/sienori/Tab-Session-Manager/issues/14#issuecomment-531610532)

**Comment by ronso0** [comment]
This would be awesome!
As a first step it would already be quite nice being able to add a single tab.

**Comment by pidgeon777** [comment]
It would be nice to also add an option so that the current tab is added to the active session only if not already there (duplicates prevention).

**Comment by sienori** [comment]
I implemented the ability to add current tab in version 6.9.0!
Right-click on the window title or click on the Edit button to display the menu.
![image](https://user-images.githubusercontent.com/29514424/127774371-924d4ad5-b1f5-4871-9541-dbe42f65ac5c.png)

**Comment by ronso0** [comment]
great, thank you!
