### ISSUE TITLE
Add favicons to tabs saved

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#460]
**Is your feature request related to a problem? Please describe.**
Right now only pinned tabs show their favicon, other tabs they are just square boxes, which, if you have many, makes it hard to find in case you want to remove some of them.

**Describe the solution you'd like**
Add favicons for tabs saved

**Describe alternatives you've considered**
No alternatives afaik

**Additional context**
TSM Version 5.1.0  on FF 69.0 (64-bit) Linux.

**Comment by VTiTux** [comment]
To keep your favicon, uncheck "Use the "discarded" property for lazy loading"
But this is considerably degrading the loading time and loading behavior of Firefox.

A great improvement is to have this option checked + Favicon.
A vote for that!

**Comment by VTiTux** [comment]
The default firefox's behavior is great.
So, why not using it when Firefox is started, to restore the last session, and use the specific TabSessionManager's behavior only when the session have to be replaced by an other one?
