### ISSUE TITLE
Unable to restore sessions

### ISSUE THREAD

**Issue by tg-x** [sienori/Tab-Session-Manager#463]
## Short description
When trying to open a saved session, a new window opens with an empty tab, but none of the saved tabs.

## Steps to reproduce
1. Start browser with clean profile
2. Import saved sessions
3. click 'Open' next to a saved session

Also tried with existing profile and disabling all other addons -- same result.

## Expected result
session is restored

## Actual result
a few sessions can be restored, but most of them can not, in which case a new window opens with an empty tab instead of the saved tabs

## Platform information
* Platform (OS): Linux
* Version of browser: Firefox 66.0.2
* Version of Tab Session Manager:  5.1.0

**Comment by sienori** [comment]
Can't restore only imported sessions?
Please share session files that cannot be restored.
And please show me the debug log when restore faild. https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode

**Comment by tg-x** [comment]
The debug console says:
`[error] background/open: openTab() tryOpen() create Error: "No cookie store exists with ID firefox-container-313"`

This was likely a container created and then removed by the [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) addon.

The best course of action in this case would be to open in it in the default container in a way that would trigger Temporary Containers to create a nem tmp container for the tab.

**Comment by sienori** [comment]
I fixed the broblem where the tab of deleted container not opening. https://github.com/sienori/Tab-Session-Manager/commit/5c49da81dd554bf9b1b51cf98c0f0acfc8998a64
Thank you!
