### ISSUE TITLE
You deleted all sessions, again

### ISSUE THREAD

**Issue by ANrd3243** [sienori/Tab-Session-Manager#468]
Ok dudes, this is not funny anymore. The second time I write here and the second time on the same problem. Your add-on removes all tabs. What do you recommend there? Install a clean version FF? OK. Install a new add-on? OK. Use instructions from [here](https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error)?  OK.
Nothing works anyway.

I'm honestly amazed, why do you think we keep tabs? Because we need to keep it! If the add-on does not fulfill its main function, it is not needed. Just help me get the old tabs, given that your instructions do not work, even on clean versions (Did you even check them before writing?)

Windows 7
Latest version FF
Latest version addon
![изображение](https://user-images.githubusercontent.com/37775327/66958007-9abebd00-f067-11e9-806a-336345b99f87.png)

**Comment by soredake** [comment]
I have the same problem, addon brokes itself after some amount of time, usually week or two, it happened already 14 times

**Comment by sienori** [comment]
Sorry for the inconvinient.
Do you have backups of old profiles or sessions?
If you don't have a backup, unfortunately you won't be able to restore your previous session...

Installing a clean version does not help restore previous sessions. 
It only initializes the corrupted database and makes the add-on work properly. Data will be lost.

I recommend enabling the backup sessions option.
![image](https://user-images.githubusercontent.com/29514424/68146624-c274b700-ff7b-11e9-94b1-0d899d72ba1a.png)

I'm investigating the problem of session disappearance.
For reference, please let me know the storage capacity and free space where Firefox is installed.

**Comment by johnnyr1977** [comment]
Same here.

Doesn´t even save the current sessions anymore.

Any ideas?

Best regards
