### ISSUE TITLE
Restore tab icons on the lazy loaded tabs

### ISSUE THREAD

**Issue by konste** [sienori/Tab-Session-Manager#469]
When tabs are lazily restored in Chrome they show correct text, but unfortunately only generic Tab-Session-Manager icon which makes them hard to distinguish. One workaround is to turn off lazy tabs loading, but it has obvious drawbacks. It would be really helpful to restore tab icons in addition to tab text when tabs are lazy loaded.

**Comment by irvinm** [comment]
This is a limitation of Firefox.  Tabs that are created as "discarded" do not fill in the favicon until loaded.  

https://bugzilla.mozilla.org/show_bug.cgi?id=1475240

**Comment by konste** [comment]
@irvinm What a pity! Does Chrome have the same limitation?

**Comment by irvinm** [comment]
It doesn't look like Chrome even supports creating tabs in a discarded state.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
https://developer.chrome.com/extensions/tabs#method-create

![2019-10-20_17-22-07](https://user-images.githubusercontent.com/979729/67166534-61839700-f35e-11e9-91b4-478cbe5c3d41.jpg)

**Comment by konste** [comment]
Interesting! But how tab lazy loading is implemented for Chrome then? It definitely works with the exception of tab icons.

**Comment by sienori** [comment]
@konste 
In Chrome, It displays its own replacement page with title, URL and favicon and redirects to the original page.

Replacement page example:
> moz-extension://dfa9c5a6-966e-4907-9101-4eeaa1bb5266/**replaced/index.html**?state=redirect&**title**=Google&**url**=https%3A%2F%2Fwww.google.com&**favIconUrl**=https%3A%2F%2Fwww.google.com%2Ffavicon.ico
