### ISSUE TITLE
Enhancement: Default Session View option

### ISSUE THREAD

**Issue by itsonlycomputers** [sienori/Tab-Session-Manager#47]
Please add an option to set the default view (1) User Saved Sessions (2) or All.  I personally prefer to only see User Saved Sessions

**Comment by ffreeman21** [comment]
I agree.  To me the autosaved sessions are merely there as back-up - important & useful, but not the main purpose of the function of the extension.

**Comment by sienori** [comment]
I plan to add a function to save the state of the sort and view last seen by the user.

**Comment by sienori** [comment]
I implemented it in ver1.7.0.

**Comment by itsonlycomputers** [comment]
Perfect!  thank you!
