### ISSUE TITLE
treestyletab data structure preservation

### ISSUE THREAD

**Issue by bijang** [sienori/Tab-Session-Manager#478]
is there anyway to preserve the treestyletab data structure after saving and reopening a session?

**Comment by sienori** [comment]
Please enable the option `Supports Tree Style Tab`.
![image](https://user-images.githubusercontent.com/29514424/68089405-d7821500-feab-11e9-8b86-f12e126faeb9.png)

**Comment by bijang** [comment]
Thank you! I spent the last 2 days browsing the many many different tab session managers, and now I've found the best. I will definitely be supporting this project.
One request, is it possible to increase the search options, it would be useful to have an option to do a full session search, [perhaps fuzzy search], and search for not just by session name but by text inside the session(s)
