### ISSUE TITLE
Search options

### ISSUE THREAD

**Issue by bijang** [sienori/Tab-Session-Manager#480]
Is it possible to increase the search options?
It would be useful to have an option to do a full session search, [?perhaps fuzzy search], and search not just by session name, but by text inside the session(s)

**Comment by kikecalpe** [comment]
I also think search bar should be improved.
It now searches by session name only as @bijang said.
Search in pages titles and tags is minimum desirable, intuitive too.
Search bar could have key tags that improve search, as «tag» that show tags used, «date» that shows results from a day, «include»,«exclude», and something like that.
It would be great improvement when TSM is intensively used.

**Comment by kikecalpe** [comment]
Duplicated:
[Search feature for saved session access. #142](#142 )
[Add search function for saved tabs #228](#228 )
[Search sessions by tags #368](#368 )

**Comment by mrdc** [comment]
Very useful feature to have!

**Comment by jimmcclintock** [comment]
Hope search is improved. Would make it an even more valuable add-on, one for which I would pay $.

**Comment by sienori** [comment]
Version 6.2.0 supports search by tab name and AND search!
![4d5b0d7b5a66b638cd84b79113e0c6ed](https://user-images.githubusercontent.com/29514424/90147214-eb549300-ddbc-11ea-8375-07eca72620b4.gif)
Thanks!

**Comment by hmijail** [comment]
Wow, I came here looking for a search option because I couldn't find it in the add-on. So great that it's there! Certainly worth paying for, as @jimmcclintock said ;).
 
I'd suggest to make it more conspicuous!

**Comment by jimmcclintock** [comment]
$10 Donation sent via Paypal.

Great work! Makes finding things SO much easier.
