### ISSUE TITLE
Saved session metadata 

### ISSUE THREAD

**Issue by bijang** [sienori/Tab-Session-Manager#481]
Current saved session visible metadata includes name of tab open on save, number of windows and number of tabs and time and date stamp. I am running tab session manager on firefox but on different laptops, currently 3, and synchronising the saved sessions in a shared repository, so potentially I could open the session of a different computer. So my request is, could the name or and indentifier of the computer on which the sesssion was saved be included in this visible metadata, to sort the different sessions. This is basically the way firefox tab sync works, maybe there's a smarter way of doing this but I can't think...

**Comment by sienori** [comment]
When adding the cloud sync feature in the future, I implement an option to identify computers using tags.

**Comment by bijang** [comment]
That;s great to hear you plan to have a cloud sync, 
can this include self hosted clouds? or just dropbox etc? 
One idea, is there any way to integrate with xbrowsersync? This synchronises bookmarks, encrypted, with the option to self host the service. 
They have the aspiration to sync tab also. 
I raised this issue already https://github.com/xbrowsersync/app/issues/128

**Comment by Jacobknew** [comment]
@sienori if you are working on this feature, I have interest in helping. I am a developer (I'm not active on github, but it is my job) and I'd be open to handling the chrome implementation, depending on how you want this to work. Please let me know!

**Comment by sienori** [comment]
In version 6.0.0, I finally implemented the cloud sync function!!
You can save sessions to Google Drive and sync with other devices.
![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png)
![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)

Using the save device name option, you can distinguish between sessions on different devices.
![image](https://user-images.githubusercontent.com/29514424/78505979-ccf8de00-77b1-11ea-8738-ad0d282f60dc.png)
