### ISSUE TITLE
tabs (pinned ?) with url to local file not opened by Tab Session Manager.

### ISSUE THREAD

**Issue by f-abel** [sienori/Tab-Session-Manager#483]
my session includes a local url "file:///c:/somewhere/"

When i open the session this pinned tab show :

/C:/path/frame_monitor.html
file:///C:/path/frame_monitor.html
This page can not be opened by Tab Session Manager.

I didn't check is not pinned do the same, i would expect it does.

**Comment by sienori** [comment]
Local files can not be opened due to limitation of WebExtensions. https://github.com/sienori/Tab-Session-Manager/issues/234
