### ISSUE TITLE
lost session, firefox session restore vs extension session restore

### ISSUE THREAD

**Issue by wtfiwinomgs** [sienori/Tab-Session-Manager#486]
session is lost if firefox is restarted (either via exit, reopen the program, or through menu -> file -> restart).

Steps to reproduce:
1. open up tab session settings, make sure "Tab lazy loading" box is checked - (When opening a session, the contents of each page are not loaded until you select the tab. If unchecked, memory usage greatly increases when session is restored).
2. Close firefox, re-open firefox
3. restore session not via "menu -> history -> restore previous session", instead restore it via tab session manager extension.
4. with tab lazy loading, tabs that are not loaded will show links such as 
https://i.imgur.com/cFopb62.png (which firefox can't seem to recognize it as a normal url thus discard them)
5. with the 100 tabs, only have few pages loaded, while rest tab remain what shows in step 4.
6. restart firefox, proceed to restore session not via extension but through "menu -> history -> restore previous session".

expected result that firefox should be able to read the url info same as what extension reads and able to restore it but it is not the case.

actual result, firefox couldn't restore and loses session  looks like extension restore become the only method. the only way to have session restore from firefox work again is to load every tab (time consuming and use up CPU/memory), then close firefox again.

## Platform information
OS windows 8.1
latest Firefox 69
5.1.0

**Comment by sienori** [comment]
You can use the `discarded` option.
![image](https://user-images.githubusercontent.com/29514424/71641236-b5561900-2cdb-11ea-9680-9db085d2fc09.png)
