### ISSUE TITLE
Display open / delete buttons in session list, fade in/out animation speedup

### ISSUE THREAD

**Issue by wtfiwinomgs** [sienori/Tab-Session-Manager#487]
**Is your feature request related to a problem? Please describe.**
it is a neat feature, but only when you have few sessions. when with 50-100 sessions (need to save regularly every 1 min due to high workload), to delete through is ver much a pain.  each time mouse hovers over a session in session list, the buttons then appear 150-200ms later, for over 100 sessions that is 15-20 seconds lost and do this several times a day..

**Describe the solution you'd like**
I want the buttons of open/delete show up right away soon as mouse hover over sessions in session list. better yet, have an option to always show open/delete button on all session at all time. Give options to user to choose removal of fade in/hover transformation and show buttons at all time, and also give user option to adjust fade in/out/hover animation time to instant.

**Describe alternatives you've considered**
I understand theres risk of opening or deleting multiple session by having buttons show at all time, hence the option of letting user choose.

**Additional context**
n/a

**Comment by sienori** [comment]
I speeded up the animaion. https://github.com/sienori/Tab-Session-Manager/commit/5cbbef1d3f56e8e56a092a21b6c10a869173be86
Thanks!
