### ISSUE TITLE
How do I import Sessions to Tab Session Manager in Windows 10?

### ISSUE THREAD

**Issue by RJ-1** [sienori/Tab-Session-Manager#488]
I want to import my sessions from a W7 machine to a W10 machine but Tab Session Manager doesn't have a 'browse' option to the files on my jump drive, and I can't find where to place them in Windows 10.  Can anyone give me any suggestions?

**Comment by sienori** [comment]
1. Export session on W7 machine
2. Place exported file on W10 machine (Using USB memory or cloud storage)
3. Import the file
