### ISSUE TITLE
Add tag dialog box should have last used list of earlier used tags

### ISSUE THREAD

**Issue by klorinczi** [sienori/Tab-Session-Manager#494]
Add tag dialog box should have last used list of earlier used tags.

**Comment by sienori** [comment]
I've implemented tag suggestions! https://github.com/sienori/Tab-Session-Manager/commit/e074a4801ff8cf05cbae56b8294f4ca811e226ac
![image](https://user-images.githubusercontent.com/29514424/114170911-90386780-996e-11eb-9668-4cc13e054eae.png)
