### ISSUE TITLE
popup size settings not effective & not saved

### ISSUE THREAD

**Issue by noyannus** [sienori/Tab-Session-Manager#495]
The popup size settings are not effective, i.e. no change in width or height. The numbers are not saved. 

Sidebar setting works as expected, it resizes up to the popup width, then just displays the red frame around the sidebar width setting.

Apparently, you have set a hard-coded upper limit. For the sidebar it makes sense to not be wider than the popup itself, but for the whole popup it's not necessary, IMO. 

Please allow larger popups.

![Screenshot](https://user-images.githubusercontent.com/6339921/70865290-0637e480-1f5c-11ea-9de5-437077faa637.png)

macOS 10.14.6 (18G1012)
FF 71.0 (64-Bit)
Tab Session Manager 5.1.1

===========
EDITED TO ADD:
Found it: in `defaultSettings.js` remove lines 273, 283, and 293.

**Comment by sienori** [comment]
This is due to a limitation of webExtensions. https://github.com/sienori/Tab-Session-Manager/issues/245
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups
>It will grow to a size of **800x600** pixels at most if that fits on the user's screen.

**Comment by noyannus** [comment]
Thanks for explaining. 
The limit is unfortunate, though. Maybe they will change it in the future.
