### ISSUE TITLE
Lost session and cannot access backups, Most likely corrupted "1782160246ssensosi.sqlite"

### ISSUE THREAD

**Issue by tsukitsukiaki** [sienori/Tab-Session-Manager#497]
## Short description

On Firefox 71.0, Windows 10, the extension window closes instantly so I cannot access backups. I cannot import or export the backups using the extension's options window. And Firefox did not do its built-in session backup within the profile folder.

It happened after I had to do a force restart to my PC, because my screen blacked-out and I couldn't see anything.

I have attempted both the guides in the wiki to fix or migrate my backups.
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

It fixes the extension, but it could not save my session backups.
**How can I reclaim my lost session's URLs?**

## Steps to reproduce the problem

1. Open Mozilla Firefox with many tabs opened
2. (Optional??) Your monitor blacks-out
3. Force restart your PC
4. Open Mozilla Firefox again
5. The session with all the tabs are gone
6. Attempt to open the Tab Session Manager extension window, but cannot access the backups

## Platform information
* Platform (OS): Windows 10
* Version of browser: Mozilla Firefox 71.0 (64-bit)
* Version of Tab Session Manager: 5.1.1

## Additional context

I tested the folder "storage" within the profile with only the "Tab Session Manager" folder in it.
It seems the extension is fixed when the file "1782160246ssensosi.sqlite" is deleted and automatically recreated, but it could not save my sessions.

So I assume the "1782160246ssensosi.sqlite" file is corrupted.

I tested the "1782160246ssensosi.sqlite" with DB Browser for SQLite.exe.
If I remove enough data within "index_data," "object_data," or "object_store," at least 1-entry within "object_data," and restart Firefox, the entire file seems to be reset as if it was newly created.

I still have a folder "1782160246ssensosi.files" which seems to contain numerically named files. When put into a text editor, I can see they contain URLs of my tabs, but they are encrypted.

**Is there any way to reclaim the URLs encrypted within the "1782160246ssensosi.files" folder?**

**Even if it has to be done slowly over many days, or manually rebuild a new "1782160246ssensosi.sqlite" using data from the old version.
I lost a lot of tabs...**

**Comment by sienori** [comment]
I don't know how to restore URL list from sqlite file... #421
I recommend enabling the backup option to prevent data loss.
