### ISSUE TITLE
dotsession restore doesn't work here

### ISSUE THREAD

**Issue by Maggy11** [sienori/Tab-Session-Manager#50]
LS,
Yesterday my Firefox started to upgrade to v57 after a reboot, without my concent.  Normally Firefox does ask my permission before starting an upgrade installation, allowing me to backup my profile (weird that firefox never built in an automated backup...) BTW in other forums I've seen a lot of complaints about this auto start of the v57 upgrade and its consequences...
At first I was just shocked by the behavior of v57. When it started up, I was surprised by the ugly black single row of tabs, but it looked like all of my session was restored, probably several hundreds of tabs.
But sh#t never comes alone, Windows installed updates as well and asked for another reboot. Then I noticed that it first closed my active Firefox session, and another one, and another one. To my surprise Firefox no longer functioned in my normal single window mode. The result was that after the reboot Firefox started with the session of the last closed window, with nothing but three automatically generated tabs.
I started searching for a way to restore my older session, found out that both TabMixPlus and SessionManager were gone, then found your TabSessionManager as the only possible solution. I installed it, went to options>sessions>import>reference, browsed to backup.session > import. Then it tells me "session imported", but all I see are the already open tabs. I tried to find another button to click in order to open the imported session but can't find it. There's tons of work in all these tabs. You'd be my hero if you could help me.

**Comment by ffreeman21** [comment]
As another user of the old Session Manager, I sympathise with you - but was careful not to let FF auto upgrade, and am still user FF56!  My understanding is that the old Session Manager (SM) & the new Tab Session Manager (TSM) do not necessarily store their sessions in the same place. - and they are certainly stored in different formats.  I'm guessing, but I image that you would have to point TSM to the old directory used by SM.  If you were just telling it to import a backup, it would be importing its own backup from the previous session (if any).

Personally, in your circumstances, I might try to go back to v.56 or earlier (I know you can download a special pre-57 version), and then try to recover from there.  But I'm no expert.

**Comment by rnc** [comment]
Tab-Session-Manager can now import `*.session` files from SessionManager as @sienori  implemented it in #40

**Comment by sienori** [comment]
@Maggy11 Just to be sure I will ask, do you know the toolbar button?
The list of sessions is displayed by clicking the toolbar button.

**Comment by Maggy11** [comment]
@sienori Thanks a lot, I found the toolbar button. The first attempt to restore all my old tabs crashed both FF57 and Win7, after reboot FF restored most tabs, leaving about:blank tabs in place of the few tabs that probably caused the crash. You now officially are my hero.
