### ISSUE TITLE
Disable auto-saving sessions by default

### ISSUE THREAD

**Issue by TotalCaesar659** [sienori/Tab-Session-Manager#502]
When you install Tab Session Manager the first time, it automatically saves all your session ("Save the session regularly", "Save the session when window was closed" and "Save the session when exiting browser" are turned on by default). If you forgot to disable them at once, somebody may see your sessions (they also are written to hard drive and may be restored).
I think this features need to be disabled by default for giving user more privacy.

**Comment by almereyda** [comment]
I'm also always baffled by the frequent and unasked appearance of TabSessionManager backup files in my Downloads directory.

Additionally they are cryptically named, with datetime stamp and amount of sessions, which is not easily understandable for a common user.

Whyfore I can support the suggested changes in #572.

Evantually TSM could suggest to create a backup every now and then, but not enforce it this way?

**Comment by sienori** [comment]
To make new users aware of the existence of autosave, I think the default setting should be turned on. 
If you set the category filter to `User Save`, the autosave sessions will be hidden.
