### ISSUE TITLE
[Feature] Session renaming

### ISSUE THREAD

**Issue by pidgeon777** [sienori/Tab-Session-Manager#505]
Please add a function to rename existing sessions.

For example, one might single click to the title of a session, and then it could become editable.

Or, select a session and press a hotkey (e.g. F2 for renaming as implemented in Windows).

Or, select a session and then rename it through an option of the session context menu.

**Comment by dojo90** [comment]
Actual you can solve it by tagging the session.

Anyway 1+ because I also want this feature 👍

**Comment by x-ProgrammEd-x** [comment]
+1.
how do I tag a session?

**Comment by logvinata** [comment]
Great! But If I save several windows as separate sessions it is quite uncomfortable to rename them _after_ saving.  Please add an opportunity to rename session during manual saving.

**Comment by sienori** [comment]
@logvinata You can save the session by specifying the title.
![rename](https://i.gyazo.com/964d876c27a66593d6381a10df7edb2b.gif)

**Comment by j-hui** [comment]
@sienori  is there any way to do this from the keyboard only? and is it possible to easily update an old session with the new state (e.g. use a session as a workspace)?

**Comment by JeffRockatansky** [comment]
Shouldn't this be closed now?
