### ISSUE TITLE
[Feature] Place sessions into custom subfolders

### ISSUE THREAD

**Issue by pidgeon777** [sienori/Tab-Session-Manager#506]
Actually once sessions are saved, those are accessible through a simple filterable list.

It would be cool for a user to create some folders (e.g.: *Home*, *Work*...) where to place those sessions.

The filter box should be able to display only the sessions searched by the user even if inside some certain folders (maybe by still showing them inside their parent folder).

It should be possible for the user to create subfolders.

It should be possible to rename the folders.

It would be also good to add some *Expand All/Collapse All* buttons, to expand or collapse the folder tree.

**Comment by sienori** [comment]
You cau use a tag.
