### ISSUE TITLE
[Bug] When re-opening the Tab Session Manager window, the session display listbox is reset to 'All'

### ISSUE THREAD

**Issue by pidgeon777** [sienori/Tab-Session-Manager#507]
This is what happens:

1) I open the Tab Session Manager panel in a new window (thus not as a popup). It starts showing all sessions (listbox set to 'All') by default.

2) I set the sessions filter listbox to 'Saved by user' so only the sessions I saved are shown, and not the automatically saved ones.

3) I close the Tab Session Manager panel.

4) I re-open the Tab Session Manager panel.

5) The session filter listbox is still set back to 'All', showing all of the saved sessions (automatic and user).

I would expect the filter listbox not to change when closing and re-opening the Tab Session Manager window. In my case, I would like to visualize only the sessions saved by the user whenever I open the Tab Session Manager panel and not the automatically saved ones.

**Comment by sienori** [comment]
Now this problem is fixed.
