### ISSUE TITLE
 Detect "Supports Tree Style Tab" checkbox default value by firefox version

### ISSUE THREAD

**Issue by jabacrack** [sienori/Tab-Session-Manager#51]
Detect "Supports Tree Style Tab" checkbox default value by firefox version. I try this extension in firefox 56 and it take time to understand why my tabs doesn't restore. After I uncheck this checkbox it start working.

**Comment by sienori** [comment]
For now, we turned off the default.
https://github.com/sienori/Tab-Session-Manager/commit/a9d8bb0b19431c748e3d43fa207ee2f3e4d6a7a3

**Comment by sienori** [comment]
I changed it to ignore TST setting if FF 57 or earlier. https://github.com/sienori/Tab-Session-Manager/commit/9c11a2244fd14be886c1adc5609f42758242778b
