### ISSUE TITLE
Tabs no longer seem to load on startup

### ISSUE THREAD

**Issue by forestranger29** [sienori/Tab-Session-Manager#510]
Opening Firefox 72.0.1 using version 5.2.0 of tab session mgr & tabs no longer auto restore.  Works fine manually loading the tab session.

**Comment by sienori** [comment]
Check your startup settings.
![image](https://user-images.githubusercontent.com/29514424/72673795-6ddcd480-3ab2-11ea-96fe-39cfb1f01a06.png)

**Comment by forestranger29** [comment]
That was it...Thank you!  I scanned through the settings quickly before messaging, but obviously I wasn't looking very hard.  I love this addon. Thanks again!
