### ISSUE TITLE
[NOT A BUG REPORT] Where to find session files from a crashed OS disk?

### ISSUE THREAD

**Issue by cheesecracker** [sienori/Tab-Session-Manager#512]
Hi,

This is not a bug report but a call for help.

A computer of mine has crashed so hard that it can no longer boot.  But I can still read all its files in the hard disk via USB.

Please tell me where to find previous session files inside the HD.  Supposedly starting from
C:\Users\<username>\AppData

Thanks in advanced

**Comment by sienori** [comment]
See this page.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

Example session file path: `C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\v3xlq8r5.default\storage\default\moz-extension+++de50ed3a-7f77-40bc-af2e-c5953d30edbb\idb\1782160246ssensosi.sqlite`

**Comment by cheesecracker** [comment]
Thanks
