### ISSUE TITLE
dom.indexedDB.enabled not present in Firefox 72

### ISSUE THREAD

**Issue by grahamperrin** [sienori/Tab-Session-Manager#513]
https://github.com/sienori/Tab-Session-Manager/issues/210#issuecomment-375123651 #222 and https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error#user-content-indexeddb-is-not-enabled-in-aboutconfig describe: 

`dom.indexedDB.enabled`

That's not present in Firefox 72.

**Comment by CaptainFrosty** [comment]
Yes I have 76.0b6 and it is not an option

**Comment by sienori** [comment]
Thanks! I updated the wiki.
