### ISSUE TITLE
URL ignore list not working when saving session

### ISSUE THREAD

**Issue by mattiaswerner** [sienori/Tab-Session-Manager#516]
## Short description
Added https://www.youtube.com & https://www.reddit.com on a line each in the "URL list to ignore when saving session" field under settings. All tabs that match those urls are still saved and restored.

## Steps to reproduce

1. Save session.
2. Add URLs to ignore list.
3. Overwrite previously saved session.
4. See that the number of tabs saved does not change.

## Expected result
Expecting the tabs in the session saved that matches the ignore list to not be saved and restored.

## Actual result
Full set of open tabs is saved and restored.

## Platform information
* Platform (OS): Ubuntu 18.04.4
* Version of browser: Firefox 73.0 (64-bit)
* Version of Tab Session Manager: 5.2.0

## Additional context
First time trying to use this feature. Not working as expected. Quite possible that I'm doing something wrong and/or misunderstanding. Please advise if so.

Thank you for your time.

**Comment by sienori** [comment]
You must specify all paths using wildcards.
```
https://www.youtube.com/*
https://www.reddit.com/*
```

**Comment by mattiaswerner** [comment]
I do not wish to close all Reddit or YouTube tabs, just the ones that are explicitly on the main site.

**Comment by sienori** [comment]
@mattiaswerner You need a slash for that.
```
https://www.youtube.com/
https://www.reddit.com/
```

**Comment by mattiaswerner** [comment]
Tried it and it doesn't make a difference.

**Comment by sienori** [comment]
Ignore URLs list only applies to newly saved sessions. It does not apply to already saved sessions.

**Comment by mattiaswerner** [comment]
Ah, as you say it worked when saving as a new entry. I would suggest adding that detail as flavour text in the settings to avoid confusion.
