### ISSUE TITLE
Open all tabs simultaneously

### ISSUE THREAD

**Issue by jabacrack** [sienori/Tab-Session-Manager#52]
When i restore all my 300+ tabs I see that tabs open one by one. Old Session Manager open all tabs in same time. Is possible do same things?

**Comment by grahamperrin** [comment]
> … Old Session Manager open all tabs in same time. …

To clarify: that's not the case where tabs are spread across multiple windows. Firefox may spend some time on one window before proceeding to restore the next.

**Comment by sienori** [comment]
Tabs are opened one by one in order, it is a specification to correspond to Tree Style Tab.
(It was fast until ver1.1.0)
I am planning to add a function to speed up when TST option is turned off.
However adding it will be done after fixing some bugs when opening session.

**Comment by ognyandim** [comment]
I have the same issue. I have a session with 120 tabs and when I restore it all of them are opened one by one and the sorting is not preserved.

**Comment by sienori** [comment]
For now, I implemented lazy loading.
This greatly reduces memory usage and make session restore faster.
501461d

**Comment by ognyandim** [comment]
Great! My colleague has 250 tabs session and he had problems too. In R&D scenario 100+ tabs are not rare situation.

**Comment by ooofest** [comment]
@sienori Hi, I was curious if you were considering an update (could even be a beta release) of your latest code enhancements related to lazy loading, session import, etc. so that we might help to test, perhaps?  If we can build a version on our own from your code in Github, that would be cool, too - I don't have a dev environment setup at this time, admittedly.

Just wondering :)

**Comment by sienori** [comment]
@ooofest To use the latest development version, you need to download the repository from git hub and read manifest.json from the about:debugging page.
I plan to upload the latest version to AMO within a few days.

**Comment by sienori** [comment]
In [ver 3.2.0](https://github.com/sienori/Tab-Session-Manager/releases/tag/3.2.0), I speeded up session restoration!
When the TST support option is disabled, all tabs open at once.
Also, multiple windows are restored simultaneously.
