### ISSUE TITLE
feature request: dark mode and customization options

### ISSUE THREAD

**Issue by Bamajon1974** [sienori/Tab-Session-Manager#520]
Feature requests:

Are you planning on adding a dark mode as well as any font size, color and/or style customization capabilities in the extension? 

Thanks in advance

**Comment by absorber** [comment]
Related issue: https://github.com/sienori/Tab-Session-Manager/issues/211

**Comment by sienori** [comment]
I implemented the dark mode!
![dark mode](https://user-images.githubusercontent.com/29514424/101980998-d88b9580-3cac-11eb-9c84-e8f64a4c0d9c.png)

**Comment by Bamajon1974** [comment]
Awesome! Thank you! 

How do you turn on the dark mode?  I don't immediately notice any feature in the session list box or settings. 

Also, the Edge version of TSM is stuck at v6.2. Can it be updated to v6.4 as well?

Thanks!

**Comment by sienori** [comment]
To enable the dark mode, you need to set the OS to dark mode.
https://www.pcmag.com/how-to/how-to-enable-dark-mode-in-windows-10

The Edge version is under review. It should be available in a few days.

**Comment by absorber** [comment]
Thanks for this! But what if I'm using Linux?

**Comment by Bamajon1974** [comment]
Understood. Thank you for your help!

**Comment by killerzula** [comment]
> Thanks for this! But what if I'm using Linux?

Im using linux as well and cant figure out how to apply the dark mode.
