### ISSUE TITLE
IndexedDB Error for Chrome

### ISSUE THREAD

**Issue by eanea** [sienori/Tab-Session-Manager#534]
## Short description

Got "IndexedDB Error". how fix it?

## Platform information
* Platform (OS): Ubuntu
* Version of browser: Chromium 81.0.40
* Version of Tab Session Manager: 6

**Comment by boistordu** [comment]
me too.

- platform: windows 10
- browser: edge dev (chromium version)
- version of tab manager: 6

**Comment by justjoed** [comment]
me too.

platform: windows 10
browser: Google Chrome Ver.: 81.0.4044.138 (Official) (64 bit)
version of tab manager: 6

**Comment by CaptainFrosty** [comment]
I get it randomly on Firefox. Seems it doesn't matter which platform.

**Comment by mikhoul** [comment]
It's a bug introduced in latest 6.0 version  
  
Until the bug is fixed just install the previous 5.2 version in dev mode and everything will be fine like before.  
  
Regards ! :oc

**Comment by eanea** [comment]
v6.2.0 doesn't cause this problem
