### ISSUE TITLE
How to get the credentials file

### ISSUE THREAD

**Issue by aunpyz** [sienori/Tab-Session-Manager#535]
## Short description
I'm trying to contribute to this project but kinda lost with no information about the credentials.js file. I only see it's being ignored in .gitignore file

## Steps to reproduce
1. Clone the project and follow the instruction from README (run `npm install` and `npm run watch-dev`)
2. Load the extension from `dev/firefox/manifest.json` file 
3. Inspect the addon

## Actual result
![image](https://user-images.githubusercontent.com/14342782/79687720-7db3b280-8273-11ea-9670-e9c1bb9cf5fc.png)

## Platform information
* Platform (OS): Opensuse Leap 15.1 
* Version of browser: Firefox 75.0

**Comment by sienori** [comment]
Please add `src/credentials.js` like below.
``` credentials.js
export const clientId = "xxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com";
```

**Comment by aunpyz** [comment]
Again, is there a missing plugin for translating filename from camelCase to PascalCase?
Because these 4 files below have the PascalCase name but being referred in their corresponding js file as camelCase name
https://github.com/sienori/Tab-Session-Manager/blob/16fd3f5db4e3bcfdccea5e3dd4ef4602f529abb2/src/popup/components/DonationMessage.js#L4
https://github.com/sienori/Tab-Session-Manager/blob/16fd3f5db4e3bcfdccea5e3dd4ef4602f529abb2/src/popup/components/Modal.js#L5
https://github.com/sienori/Tab-Session-Manager/blob/16fd3f5db4e3bcfdccea5e3dd4ef4602f529abb2/src/popup/components/SessionDetailsArea.js#L15
https://github.com/sienori/Tab-Session-Manager/blob/16fd3f5db4e3bcfdccea5e3dd4ef4602f529abb2/src/popup/components/TextInputModalContent.js#L3
![image](https://user-images.githubusercontent.com/14342782/79689824-71365680-8281-11ea-845b-de56b4da4660.png)

**Comment by sienori** [comment]
Sorry, that's my mistake, I don't get the error on Windows.
Can you rewrite camelCace to PascalCase and create a pull request for me?

**Comment by ovgolovin** [comment]
I'm new to `React` and `Web-pack`, trying to make a small change to the project.

I faced  the same problem. 
Adding `src/credentials.js` helped build `npm run build`.

But still I see this errors during runtime:
![image](https://user-images.githubusercontent.com/1408822/85616844-26371780-b613-11ea-8193-6ffe6e160fbc.png)

It might be something trivial. But I couldn't resolve it fast as I'm new to this technology stack.
