### ISSUE TITLE
Support for other Chromium-based browsers

### ISSUE THREAD

**Issue by adrianleong98** [sienori/Tab-Session-Manager#537]
Would it be possible to introduce support for other Chromium-based browsers, such as Opera or the new version of Microsoft Edge? I tried installing the extension onto these browsers but get an error message saying that the IndexedDB is not available in these browsers. I know in the past, it has been said that Edge was incompatible, but due to it now being Chromium-based, would it not be possible to support it and Opera, like Chrome is?

**Comment by sienori** [comment]
The Edge version is now available!
https://microsoftedge.microsoft.com/addons/detail/tab-session-manager/jkjjclfiflhpjangefhgfjhgfbhajadk
