### ISSUE TITLE
Session import failure

### ISSUE THREAD

**Issue by rnc** [sienori/Tab-Session-Manager#54]
By accident I tried to import an encrypted session. Obviously it failed. _However_ it failed silently - should it not output some failure message?

Would it be useful to be able to activate some form of debug logging ?

**Comment by grahamperrin** [comment]
Please: encrypted in what way; encrypted by what?

**Comment by rnc** [comment]
@grahamperrin  In SessionManager its possible to encrypt the saved session. I have since disabled that and imported successfully - the issue is regarding silent failure.

**Comment by sienori** [comment]
I did not know that the Session Manager has an encryption option.
I want to make it detectable.

**Comment by lapineige** [comment]
> I did not know that the Session Manager has an encryption option.

I think it was working using Firefox's Master Password.
That would be a great addition :)

**Comment by sienori** [comment]
In the past version, I fixed to show "Read failed" message if it is encrypted.
