### ISSUE TITLE
Skip favicons when exporting

### ISSUE THREAD

**Issue by ertyz** [sienori/Tab-Session-Manager#549]
### Short description
TSM Backup and Export json files take too much space because of keeping favicons.

In case of regular backups and autosaves TSM created 500 MB json file every time. And all thanks to favicons.
I have 18 GB TSM Backups folder size only for 65 sessions. Isn't it too much?

### Describe the solution you'd like
Option to pass to save a favicons inside of json files.

### Additional information
Windows 10 x64, Firefox 76 x64

**Comment by sienori** [comment]
I'm considering replacing too long favicon URLs... https://github.com/sienori/Tab-Session-Manager/issues/471

**Comment by sienori** [comment]
I've implemented the ability to compress the favicon url when saving the session! 1c6ac8a #471 
This update saves memory usage and storage space by compressing the favicon URL.

I have also implemented incremental backups. https://github.com/sienori/Tab-Session-Manager/issues/710
This saves storage space for backups.
