### ISSUE TITLE
replace-session button

### ISSUE THREAD

**Issue by richard-delorenzi** [sienori/Tab-Session-Manager#551]
# Is your feature request related to a problem? Please describe.
I wish to update sessions, and have one session per window. I found a setting to make "only save the current window" be the default, then found the option to replace a session with the current window. I also found in the issue tracker a request for add current tab to session.

**The replace with current window, in the menu, is dangerously close to other options.**

# Describe the solution you'd like
Therefore **add a convenience button. So I can easily click "replace-session".**

# Describe alternatives you've considered
Add a way to add a convenience button, linked to any menu button.

# Additional context
N/A

**Comment by sienori** [comment]
> The replace with current window, in the menu, is dangerously close to other options.

In version 6.3.0, the redo function was implemented. You can use `replace with current window` button.
