### ISSUE TITLE
sync dont work

### ISSUE THREAD

**Issue by JD99** [sienori/Tab-Session-Manager#552]
I apologize in advance for bad English. 
I start synchronization. 
Half the synchronization freezes. 
restarts only after browser reboot.
no files in google drive
firefox 76.0.1

![Скриншот 04-06-2020 230905](https://user-images.githubusercontent.com/8160891/83805395-7bd56f80-a6b8-11ea-9b7a-fdc80e31267c.png)
![Скриншот 04-06-2020 230838](https://user-images.githubusercontent.com/8160891/83805397-7c6e0600-a6b8-11ea-94b8-2f014cf32357.png)

**Comment by sienori** [comment]
If the error persists, try deleting the data.
Open your Google Drive settings and delete the TSM data.

![image](https://user-images.githubusercontent.com/29514424/85859580-5986cb80-b7f8-11ea-958c-022dd9f3eccf.png)
![image](https://user-images.githubusercontent.com/29514424/85859478-39efa300-b7f8-11ea-9082-017461d1197e.png)

**Comment by JD99** [comment]
thank. works
