### ISSUE TITLE
Store cookies for sessions

### ISSUE THREAD

**Issue by Deckweiss** [sienori/Tab-Session-Manager#555]
I often have multiple accounts for certain websites, one for work and one for personal use. Currently, I have Firefox set to not store any cookies. That way, when I open for example the work session I can log in with my work accounts and when I open my personal session, I can log in with my personal accounts.
Now I have about 10 tabs in those two sessions each, 8 of which are the same site that I use with multiple accounts, and every time I start to work, I need to go through every one of those and log in (and often accept the same popups for site settings). Then when I start to work on my projects in the evening I have to do the same again. It takes about a minute, but besides the time, it is mostly very annoying to do multiple times every day.

I would like a way to store cookies in the tab session manager, so that when I open the work related session, all the websites are logged in to my work account, when I open the personal session all the tabs are logged into my personal account. When I open a new browser window without opening any session, I should be logged out everywhere because no cookies should be stored.

I don't really care how advanced of a feature that is from the usability side. Burrow it in the deepest settings, or make me extract the cookies manually and put them in the session somehow. Also I wouldn't mind if it didn't work properly when opening sessions with colliding cookies, I only have either one of those open at the same time. If it is possible in any way to add this feature, it would greatly help me with my daily workflows.

If there is any compromise, workaround or better way to do this, please let me know.

Thank you!

**Comment by sienori** [comment]
The containers will be useful.
https://support.mozilla.org/en-US/kb/containers

You can open the tabs in a personal/work container.
TSM saves and restores the container state of a tab.
