### ISSUE TITLE
Import previous session only opens one tab

### ISSUE THREAD

**Issue by jlcenter** [sienori/Tab-Session-Manager#56]
I imported a previous session from Session Manager.  TSM says 2 windows with 85 tabs were imported, but when I try to restore the session, only one window opens with one tab.  Is this a known issue with import? 

Thanks.

    -John

**Comment by ranran1** [comment]
Same problem - exported a Session Manager session (39 tabs) in FF56.  Then closed FF56, opened FF57 and tried to import with Tab Session Manager - it is recognized as 39 tabs, but when I click on the little link stating '1 Window 39 tabs' it only lists 13 tabs and that is all that is opened.

**Comment by sienori** [comment]
>only one window opens with one tab.

@jlcenter Are you using FF 56?
It is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting.
 #52

**Comment by sienori** [comment]
I am not familiar with the .session file, it will be appreciated if you upload problematic files. (Be careful about privacy)

**Comment by ranran1** [comment]
Thank you for responding, sienori.  To address your comments above:

1) I am trying Firefox 57.  I am using Tree Style Tab from Piro.

2) The Firefox Add-on page states: `Version1.5.0
Added Sessions import / export function.
**It also supports SessionManager's session file (.session)**.
Revamped options page.`

I assumed that meant it could import a .session file exported from Michael Kraft's 'Session Manager' add-on that only works through FF56.  Is this untrue?

**Comment by sienori** [comment]
@ranran1 Sorry for the confusion.
Session import is possible with FF 57.

The following my comment are for jlcenter.
jlcenter’s  problem often happens in #32 (52 is a mistake).
>@jlcenter Are you using FF 56?
>It is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting.
>#52


Probably ranran1's problem is different from this.
>it is recognized as 39 tabs, but when I click on the little link stating '1 Window 39 tabs' it only lists 13 tabs and that is all that is opened.

There is a high possibility that there is a bug in the import function.

**Comment by ranran1** [comment]
Thank you again for responding, sienori.

Do you have another suggestion for how I can get all of my tabs safely from FF56 to FF57?

**Comment by geeveebee** [comment]
In my case I want to open a session saved a few minutes earlier.

57 tabs according to session manager.

but when I click Open it only adds the first 10 of them.

I'm using FF57 and the save and load (open) is done with the same version.

**Comment by geeveebee** [comment]
I did some digging into my problem here's what I've found...

I exported the sessions
looked at the sessions data
noticed that it stopped on a local file url/tab
looking closer I noticed that the "lastAccessed" value is double quoted unlike the others tabs timestamp

when removing the double quotes it continues till the next local file that probably also have this double quotes problem.

the tab recreating is also very slow as it does reload the page from the specific site and it seems to wait on previous tabs load completions before it goes on.

**Comment by jlcenter** [comment]
Sorry I didn’t see this earlier. I’m running 57 & I didn’t uncheck the Tree Tabs setting. I’ll give that a try tonight.  

Thanks. 

    -John

**Comment by jlcenter** [comment]
I just unchecked the setting & all of my tabs appeared.  I didn't do that before because it said it only had to be done for version 56.  I checked it again & the tabs are still there!  Now I'm confused...  -John

**Comment by sienori** [comment]
@ranran1 
I need to fix the import function of the .session file.
If possible, please upload problematic files
It will be helpful for debugging.

**Comment by sienori** [comment]
@geeveebee 
Processing stops when opening a local file.
I am planning to fix it soon.
#15 #6

**Comment by sienori** [comment]
@jlcenter 
If you checked TST option, Processing stops if there is an inconsistency in the parent-child relationship of the tab on Tree Style Tab.
I will fix this problem.

**Comment by ranran1** [comment]
jlcenter, 

Thanks for the reply - so if using FF57, unchecking the TST setting actually worked for you?  I'll have to give that a try...

**Comment by sienori** [comment]
@geeveebee 
I added a function to replace a page that can not be restored.
#16

**Comment by sienori** [comment]
@jlcenter 
I fix it.
https://github.com/sienori/Tab-Session-Manager/commit/fecc84996188b552b92b00683c3ebbb9873a0f76

**Comment by ranran1** [comment]
thank you for fixing that, sienori.  What version contains this fixed code?  I still see v.1.5.0 on the add ons website - is there an updated version we should be looking for to test?

**Comment by sienori** [comment]
To use the latest development version, you need to download the repository from git hub and read manifest.json from the about:debugging page.
I plan to upload the latest version to AMO within a few days.
