### ISSUE TITLE
Autosave for user sessions

### ISSUE THREAD

**Issue by dsvi** [sienori/Tab-Session-Manager#57]
Hi!

In the old session manager it was possible to tick "autosave this session"  checkbox for user created sessions. Is it possible to add such option to the TabSessionManager?
So when you manually save a session with the checkbox "on", it becomes _current_ and autosaved periodically.

**Comment by boistordu** [comment]
totally up for that. Because it's a bit a pain in the ass to delete all the auto save regularly session and the session in use to re-save it afterwards with the new content

**Comment by sienori** [comment]
The concept of Tab Session Manager is different from Session Manager.
That function is not compatible with TSM.
Thanks for your understanding.
