### ISSUE TITLE
Losing tab grouping when restoring last tab session 

### ISSUE THREAD

**Issue by cherian** [sienori/Tab-Session-Manager#571]
Chrome came up with support for grouping: https://blog.google/products/chrome/manage-tabs-with-google-chrome/

When restoring from a crash or machine restart, I lose the groups created previously.

**Comment by sienori** [comment]
`chrome.tabs.group` API does not seem to be available yet in Chrome.
https://developer.chrome.com/docs/extensions/reference/tabs/#method-group
I will support the tab group when the API becomes available.

https://github.com/sienori/Tab-Session-Manager/issues/652

**Comment by sienori** [comment]
In version 6.6.0, I implemented support for tab groups! https://github.com/sienori/Tab-Session-Manager/commit/f3e14f7d30ec9e46a58d6a84848f6a4b677a7591 #652 
To save tab groups, you need to install [an additional extension](https://github.com/sienori/Save-Tab-Groups-for-Tab-Session-Manager).

**Comment by cherian** [comment]
Can you point me to where this is in the chrome store? I couldn’t find it: https://d.pr/i/e1ZqKg 
Couldn’t find it in the options either: https://d.pr/i/tpPfgY

**Comment by sienori** [comment]
Version 6.6.0 will be available within a few days. Please wait for a while.
https://chrome.google.com/webstore/detail/aghdiknflpelpkepifoplhodcnfildao
