### ISSUE TITLE
Add an option to export/import settings

### ISSUE THREAD

**Issue by brol** [sienori/Tab-Session-Manager#573]
Hello,
It could be pleasant and useful, during deployments, to have an import/export option in order to simplify this type of operation. It would also be useful when you need to reset a Firefox profile that is corrupt.
Thank you

**Comment by sienori** [comment]
I'd like to implement this in the future.

**Comment by sienori** [comment]
I have implemented a settings import/export function. https://github.com/sienori/Tab-Session-Manager/commit/be537832b650148a54b193488e4afe598d139159 #350 
Thanks for your patience!
![image](https://user-images.githubusercontent.com/29514424/129328269-9c69ba91-a8e4-4f48-9e2c-970d7bbf6471.png)

**Comment by candrapersada** [comment]
will there be an option to import and export settings to the cloud like google drive?
