### ISSUE TITLE
Tab Session Manager with big number of sessions slows down Firefox

### ISSUE THREAD

**Issue by cosuwi** [sienori/Tab-Session-Manager#578]
## Short description
Tab Session Manager with big number of sessions causes slow (sometimes _very_ slow) browser work: longer loading of pages (up to 2 times longer for me), low responsiveness (delays, hangs) of the user interface, higher memory consumption. This is not experienced when Tab Session Manager has few sessions.

## Steps to reproduce
1. Start Firefox with a clean profile, install Tab Session Manager, configure it as in the screenshot: https://user-images.githubusercontent.com/67523720/86544635-33b4a180-bf31-11ea-92db-c59e060344c8.png
2. Disable disk cache in Firefox, so it won’t affect page loading time.
3. Make a few sessions in Tab Session Manager.
4. Start Firefox with a session of two-three dozen tabs. In the tab context menu, choose “Select all tabs” and then “Reload tabs”, and measure pages’ loading time. Experience browser performance in general after that.
5. Make Tab Session Manager have several hundred sessions, each of several hundred tabs.
6. Do the same as in step 4, with the same session.

## Platform information
* Platform (OS): Windows 10
* Version of browser: latest Firefox (64-bit)
* Version of Tab Session Manager: latest

**Comment by cosuwi** [comment]
Please reply. Will it be fixed?

**Comment by sienori** [comment]
I plan to resolve the memory issue. https://github.com/sienori/Tab-Session-Manager/issues/471

**Comment by mikhoul** [comment]
> I plan to resolve the memory issue. #471

Do you have an ETA ?  


Regards ! :octocat:

**Comment by sienori** [comment]
I've implemented the ability to compress the favicon url when saving the session! 1c6ac8a #471
This update saves memory usage and storage space by compressing the favicon URL.
