### ISSUE TITLE
Session on Startup

### ISSUE THREAD

**Issue by Natsulus** [sienori/Tab-Session-Manager#58]
I have multiple pinned tabs I want opening on startup and startup options for FF57 don't work well for that. "Show your windows and tabs from last time" won't work since but I typically close my session with other tabs open and the other two options open the home/blank page along with the pinned tabs.

Session Manager had a [Startup & Shutdown option](http://sessionmanager.mozdev.org/options.html#startup). I don't really need the Shutdown options, but would it be possible to have an open session on startup option?

**Comment by rnc** [comment]
Could an option like this be configurable (like in SessionManager) ? :-)

**Comment by ooofest** [comment]
If Tab Session Manager was able to add a choice in "When Firefox starts" that might also have the side-effect of making the window-closing prompt from Firefox appear, as it seems disabled when "Show your windows and tabs from last time" is selected.

**Comment by Croydon** [comment]
I need to exact same thing: opening pinned(!) tabs at startup, don't restore anything else

**Comment by storyjesse** [comment]
I need this too. I don't save my browsing history. Saving the tabs which are open when I close FF is NOT the same as saving my entire history. Firefox 57 broke this. Tab-Session-Manager has given me a work around because I can now click to restore the last autosaved session. It would be awesome if there was an option to make this happen automatically when FF starts.
Cheers :-)

**Comment by sienori** [comment]
I added the option restore previous session at startup in version 1.8.0.
https://github.com/sienori/Tab-Session-Manager/commit/4fd6aa64e7d691ae7c625075fa559ffdfefaa83f

**Comment by TChilderhose** [comment]
Awesome. Thanks for adding that. Would it be possible to add the ability to restore a specific session on startup? I have a session labeled "Startup" that I would like to have loaded when I startup.

**Comment by Natsulus** [comment]
What Tchilderhose said was more what I was requesting. If I wanted a restore previous session on startup, I could have just used Firefox's "When Firefox Starts: "Show your windows and tabs from last time" option.

**Comment by fbohorquez** [comment]
I needed same thing. I followed this steps:  

1.- Get code:

`$ git clone https://github.com/sienori/Tab-Session-Manager.git`

2 .- Search and edit the algorithm in this point.

File: **Tab-Session-Manager/background.js**
Line: [189](https://github.com/sienori/Tab-Session-Manager/blob/e4bcd01e9e9f7c3328e2985072f56e54d283aaec/Tab-Session-Manager/background.js#L189) 
Change to:  `return (element.name == "default");`

3 .- Create un zip file of directory _Tab-Session-Manager/_. The file _manifest.json_ must be in root of file zip.

4- In firefox Developer Edition or Nightly make sure that option _xpinstall.signatures.required_ is _false_ in about:config.   IMPORTANT: This is easy in firefox version Developer Edition or Nightly. If you want use Standar version of firefox you must signed the addon. 

5 .- Drag and drop the file in addons tab of firefox for install modified addon.

6 .- Save one session and use the name _default_. Active the option _Restore previous session at startup_ of installed complement. 

Now firefox  will load _default_ session in each start .

Carefull, this modify one feature original.  You need revise this repository for new updates. Also firefox will be less fortified.

I hope this help you.

**Comment by sienori** [comment]
I will add that option in the future.

**Comment by davidhedlund** [comment]
@sienori I think "Restore previous session at startup" should be enabled by default because this is what most users want. I don't like to enable this option every time I install the add-on.

What do you think?

**Comment by davidhedlund** [comment]
@sienori Ok fair. You can ask a Yes/No dialog popup to enable this setting directly when the add-on has been installed.

**Comment by chrnoe** [comment]
Every Update I look for that feature ... but it is not implemented so far, unfortunately. I also would appreciate this feature ... every time I start ff I have to open my startup session manually. :-(

**Comment by chrnoe** [comment]
oh, great, a new version ... but, a pitty, without this feature ...

**Comment by sienori** [comment]
Thank you for waiting so very very long time.
In version 5.2.0, I implemented the startup session! https://github.com/sienori/Tab-Session-Manager/commit/5a1a604276eacfe367e712635fade031e561f82b
![image](https://user-images.githubusercontent.com/29514424/71642801-a465d180-2cf4-11ea-87da-79a64d06ccd0.png)
![image](https://user-images.githubusercontent.com/29514424/71642813-c8c1ae00-2cf4-11ea-8cb2-508658c7d4a9.png)
