### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by ertyz** [sienori/Tab-Session-Manager#59]
Just an advice.

Imho the current donation method (Amazon-jp gift card ) is inconvenient for many of westerners. They don't understand how much is ¥10'000.
PayPal [donation button](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/) look more familiar and simple for many people.

With best regards.

**Comment by sienori** [comment]
Thanks for your advice.
I am in the process of upgrading my PayPal account.

**Comment by sienori** [comment]
I added PayPal button in ver 1.6.0.
Thanks.
