### ISSUE TITLE
Save backup periodically

### ISSUE THREAD

**Issue by brain8891** [sienori/Tab-Session-Manager#591]
**Is your feature request related to a problem? Please describe.**
Currently, backup are ran every single time FF starts, which creates too many large files, which the user have to delete manually. 

**Describe the solution you'd like**
1- an option to download the backup periodically, for me once a day is perfect. 

**Describe alternatives you've considered**
2-  I assume Add-ons can have unlimited storage access, so why not backup there and have an option to delete backups older than X days. 

**Additional context**
-

**Comment by mikhoul** [comment]
I agree it's the same in Chromium, deleting backups older than X days would be very useful for saving space.

**Comment by StoopidoMan** [comment]
8GB of backup! WHY? The old one should be deleted, didn't know about it till I saw my download folder

**Comment by sienori** [comment]
Because the WebExtensions API cannot access local files, local backups are always increasing. I wish there was a better way...
https://github.com/sienori/Tab-Session-Manager/issues/641

**Comment by brain8891** [comment]
Whe

> 
> 
> I have implemented incremental backup! [72da718](https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545)
> This allows you to manage backup sessions individually.
> Only updated sessions are saved, saving storage. #710
> 
>     * One session is saved in one json file.
> 
>     * When a session is updated, the json file is overwritten.
> 
>     * Autosave sessions are saved in a separate folder.
> 
>     * The file name is `date - session_name #tags [session_id].json`.
> 
> 
> ![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
> ![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)

-When will this be implemented?

-will Bookmarks backup will be supported?

 -Lastly, Does this mean that older backup will be replaced in download folder?

**Comment by sienori** [comment]
@brain8891 
This will be enabled in the next update.

With the improvement of local backup, it is no longer necessary to implement bookmark backup.  https://github.com/sienori/Tab-Session-Manager/issues/678
Bookmark backups are incomplete because they can' t store the complete session information.


The folder structure will look like this:

- Tab Session Manager - Backup
  -  old backup.json (huge)
  -  old backup.json (huge)
  - ...
  - User Save
    - session 1.json
    - session 2.json
    - ...
  - Auto Save - Browser exited
    - session 1.json
    - session 2.json
    - ...
  - Auto Save - Regularly
    - session 1.json
    - session 2.json
    - ...
  - Auto Save - Window closed
    - session 1.json
    - session 2.json
    - ...

**Comment by brain8891** [comment]
First, reply here when there is an update so I test it. 

you said it is incremental, so that would save space, however does it replace the old files? Because now we have more folders to go through to delete very old backups. 

The main problem with backups is that old backup are not replaced as TSM don't have access to download folder,  and it should be deleted manually by the user. 

Also, about bookmark backup, you know better, but I was hopping it would  be possible to add complete session information within each bookmark name and address field. Sorry if that was not a smart suggestion.  


At the end, I really hope you consider using web extension unlimited storage permission.  Most user would trust TSM anyway since it is recommended by Mozilla.

**Comment by sienori** [comment]
If the user updates a session, the corresponding backup file will be overwritten.
Automatic deletion of backups can be implemented by developing an external native application that works with TSM. If there are enough requests, I may try it...

The backup using `storage.local` is unreliable because it cannot be accessed when the TSM is broken or reinstalled. I think local backup is the best solution.

**Comment by brain8891** [comment]
> Automatic deletion of backups can be implemented by developing an external native application that works with TSM. If there are enough requests, I may try it...

What about a batch file or a portable application that the user keep in backup folder, and run it periodically, to  delete older backups or keep the recent X back ups, for example. 

Having said that, if the files are overwritten then there might not be a need to delete older backups. The important is not to have 10GB+ of backup which is what happened in my case. 

> The backup using storage.local is unreliable because it cannot be accessed when the TSM is broken or reinstalled. I think local backup is the best solution.
I agree. This information is for other users who came here, I presume `storage.local ` is the file used to store add-ons data when `unlimited storage permission` is used. and that why I agree with Sienori. 

thank you very much

**Comment by brain8891** [comment]
I used the new backup system for five days:

1-  I am not sure how TSM incremental backup work, it doesn't look incremental, I checked the settings and there is no mention of incremental backup so I presume it is the default behavior.  would you explain in detail how the new system works? (my backup reached 900MB and it has been only 5 days and I didn't notice any .json file being overwritten) 

2- Also, is there way to switch back to the old system (single backup file) , it was easier to delete manually, and  now I have 4 folders to manage :) Having said that, the idea of organizing different type of backups in 4 folders is amazing if old backup files were overwritten.

Feature request: Adding number of windows, and total tabs to the .json file name. 

Thank you very much for this amazing add-on.

**Comment by sienori** [comment]
Incremental backups mean:
Only sessions that have been saved or updated since the last backup will be backed up. If the session is updated, it will be overwritten.

 I will add an option to select the backup behavior in the next version. #762
![image](https://user-images.githubusercontent.com/29514424/117452939-51063200-af7f-11eb-8fec-b6d465111001.png)

**Comment by brain8891** [comment]
I think we have a bug here, the .json files of the same session is not being overwritten. To elaborate if the file would be overwritten then my backup should not exceed 1gb (it was 900 MB on May 3rd ) but now on May 5th it is 1950MB, and that is only 5 days! 


just a feedback: I think the individual backup is amazing, my only concern is storage management, and how much time consuming it is.

**Comment by sienori** [comment]
When you say "not overwritten" do you mean that multiple files with the same name will be created?
If the autosave limit is large, the number of backups will increase.

I have also added an option to compress the session. This will reduce the size of the backup. #471 
![image](https://user-images.githubusercontent.com/29514424/117530444-359b3580-b018-11eb-8bbf-a86e023d945d.png)

**Comment by brain8891** [comment]
> When you say "not overwritten" do you mean that multiple files with the same name will be created?

If you mean multiple file with similar name appended by a number, then No. 

I still don't understand what you mean by overwriting the .json file. for me as a user I just want old backup to be deleted, so that I would not have to go to four folders and delete backups manually. 

The (Auto Save regularly) is set to backup every 30 minute, and yes it does contribute to the majority of the storage. 

What does (Maximum number Saved) means?
![image](https://user-images.githubusercontent.com/7104190/117539266-f3272800-b01a-11eb-9968-1482c56e4d42.png)
 

Are you planning to have backup older than x days deleted automatically, or overwritten by newer backup or just keep the latest x backups?

**Comment by candrapersada** [comment]
and how to move the save location from download to another location?
![gambar](https://user-images.githubusercontent.com/36833664/117591463-d562db80-b15e-11eb-9c32-0bc0982ca0e5.png)
