### ISSUE TITLE
[Feature Request] Session Buddy data import

### ISSUE THREAD

**Issue by Darthagnon** [sienori/Tab-Session-Manager#594]
**Is your feature request related to a problem? Please describe.**
[Session Buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko?hl=en) is another popular (900,000 users Chrome) session manager browser plugin, that I've used until now. It exports data in JSON format (and multiple text formats), but Tab Session Manager cannot import this session data, though it can import data from the far less popular [Session Manager](https://chrome.google.com/webstore/detail/session-manager/mghenlmbmjcpehccoangkdpagbcbkdpc) (60,000 users Chrome).

**Describe the solution you'd like**
Could Tab Session Manager implement Session Buddy data import?

**Describe alternatives you've considered**
I want to move over from Session buddy to Tab Session Manager, but I can't, as I have a lot of sessions saved, and need to import them :'( It would also probably increase the popularity of Tab Session Manager (30,000 users Chrome, 86,000 users Firefox)

**Comment by JohnAnderson** [comment]
I also would like to import Session Buddy data into Tab Session Manager so that I can potentially switch from Edge to Firefox.  @Darthagnon's feature request is nearly a year old.  It would be really nice to be able to import the Session Buddy JSON export into Tab Session Manager.  I'm sure @Darthagnon and I are not the only ones who #would appreciate it?  How about it?

**Comment by sienori** [comment]
Version 6.10.0 now supports importing Session Buddy sessions! https://github.com/sienori/Tab-Session-Manager/commit/c0ece0a9aeb38c7314e84edca86a3bba11dce0fc #408 
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-How-to-import-sessions-from-other-extensions
![image](https://user-images.githubusercontent.com/29514424/129353314-cacfcef2-8af0-4d3c-a47f-eb4e5995f276.png)

**Comment by Darthagnon** [comment]
Thank you so much!!!!! ❤

**Comment by JohnAnderson** [comment]
Auto-updated to 6.10.0 yesterday, and works like a charm to import Session Buddy sessions.  Thanks very much, and sorry for being a bit impatient...
