### ISSUE TITLE
about:xxx not restored properly

### ISSUE THREAD

**Issue by irvinm** [sienori/Tab-Session-Manager#6]
about:config, about:addons, etc. are not being restored properly when restoring a session.  The tabs are restored as blank new tabs.  When I look at the session they are stored in, I do see the tabs and when I hoover over the link it looks correct.

**Comment by sienori** [comment]
Because of the Firefox specification, those pages can not be opened.
Therefore, it is replaced with a new tab.

**Comment by irvinm** [comment]
Just a thought ... would there be a way to restore (or create) a blank page with a single link in it to the original Firefox URL -- about:config, about:performance, etc.?  That way you at least know what you had open and could just click on it to load the original page or close the tab.  ("New Tab" pages usually worry me as I wonder if there was something valid not restored properly)

**Comment by sienori** [comment]
I'll think about it. Thanks!

**Comment by rnc** [comment]
Even if those 'special tabs' can't be restored, rather than replacing with blank empty tabs - which, as @irvinm says, implies something has gone wrong - can they just be ignored?

**Comment by sienori** [comment]
Sorry I made you wait.
I added a function to replace a page that can not be restored. https://github.com/sienori/Tab-Session-Manager/commit/789c4d4b4a8d91c950137eafe8ffecbefe356870
This change also resolves the problem at session restoration. #16
