### ISSUE TITLE
[question] ¿is possible use a custom session as a auto-save session?

### ISSUE THREAD

**Issue by sanslash332** [sienori/Tab-Session-Manager#605]
I explain. On the old  session manager, when you create (or load) a session, you can mark it as an auto-save session. So, if you add / remove tabs during your navigation, these changes will be reflected on the session and you dont have to update it manualli.

Currentli the extension saves a backup of your current session every X minutes, but if you want to reflect these new changes on your saved session, you habe to replase the active window on the session manualli.

Currentli exist this option? or is a feature request?

Thanks!

**Comment by sienori** [comment]
In version 6.12.0, I implemented Tracking Session feature! #890

You can set a session as a tracking session from the session menu. When you open a tracking session, changes in the window are automatically reflected in the session. This allows for efficient workspace switching!

![session menu](https://user-images.githubusercontent.com/29514424/166821091-8ff657bd-dbfc-49e1-ac23-974c6d313e54.png)
![tracking session](https://user-images.githubusercontent.com/29514424/166821237-f4e1eece-0bda-4c50-bb63-db6280ba9329.png)

https://github.com/sienori/Tab-Session-Manager/releases
