### ISSUE TITLE
Add current tab

### ISSUE THREAD

**Issue by aiolos01** [sienori/Tab-Session-Manager#606]
It would be very useful if you could add the currently active tab to a saved session. Currently the only option is to add current window which means you have to close all the tabs you don't want to be added before adding it. And then you end up with a session with 2 windows. It would be much easier to just add the current tab to the already saved window.

**Comment by sienori** [comment]
I implemented the ability to add current tab in version 6.9.0! #458 
Right-click on the window title or click on the Edit button to display the menu.
![image](https://user-images.githubusercontent.com/29514424/127774371-924d4ad5-b1f5-4871-9541-dbe42f65ac5c.png)

**Comment by aiolos01** [comment]
That is great news. Thank you.
