### ISSUE TITLE
[Feature request] Allow opening tabs in background with a click (middle click preferably)

### ISSUE THREAD

**Issue by hblaise** [sienori/Tab-Session-Manager#607]
**Describe the solution you'd like**
I prefer using Tab session manager in a tab instead of the popup and not being able to open tabs in the background from saved sessions is uncomfortable. Please allow opening individual tabs in saved sessions with the mouse middle button in a background tab.

**Describe alternatives you've considered**
Alternatively, consider adding a shortcut to open tabs in background tabs (without losing focus of the Tab session manager tab).

**Comment by sienori** [comment]
In version 6.3.0, I implemented middle click function! Middle click to open the tab in the background.
Thanks!
