### ISSUE TITLE
[Feature request] Display account name in Settings, if sync connected to Google Drive.

### ISSUE THREAD

**Issue by klorinczi** [sienori/Tab-Session-Manager#611]
Feature request: Display account name in Settings, if sync connected to Google Drive.

**Comment by sienori** [comment]
I've improved it to show the account name! Thanks! https://github.com/sienori/Tab-Session-Manager/commit/cd58cf1718d892effdde13345dd7481c3b9fbe67
![image](https://user-images.githubusercontent.com/29514424/114171875-de019f80-996f-11eb-9ce7-2b6bd7db5b20.png)

**Comment by klorinczi** [comment]
Great! Thanks!
