### ISSUE TITLE
[Feature request] Language change option

### ISSUE THREAD

**Issue by klorinczi** [sienori/Tab-Session-Manager#612]
Please allow language change option in Settings.

I would like to change the language to English.
It makes bug reporting easier.

**Comment by sienori** [comment]
To change the language, please set the value of intl.locale.requested in about:config. https://github.com/sienori/Tab-Session-Manager/discussions/370
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Testing_out_your_extension

**Comment by klorinczi** [comment]
Invalid? 
Why? 

I would like to change language of this app separately from my browser settings.
