### ISSUE TITLE
Search bar auto display

### ISSUE THREAD

**Issue by GHNewbiee** [sienori/Tab-Session-Manager#625]
**Is your feature request related to a problem? Please describe.**
When the number of sessions is practically big, scrolling down to select a session is not the solution. Searching is the only way since `pg-up`, `pg-dn`, `home` and `end` operations are not available, isn't it?

**Describe the solution you'd like**
After a predefined number of saved sessions is reached, the search bar should be automatically displayed and focused, ready for typing. IMHO, this is the fastest way.

**Describe alternatives you've considered**
`pg-up`, `pg-dn`, `home` and `end` operations should also be available.

**Additional context**
For the time being, I have to move the pointer from the TSM icon to the small search icon, click on it and wait for the bar to get displayed/opened. This takes 1-2 seconds which is a waste of time! -:)

**Comment by sienori** [comment]
The search bar opens automatically when you open the session list and type in the text. No need to click the search button!

**Comment by GHNewbiee** [comment]
My only concern is if this feature is easy discoverable from a "conservative" user.
