### ISSUE TITLE
Extension uses gigabytes of memory in FF with many tabs

### ISSUE THREAD

**Issue by JanKanis** [sienori/Tab-Session-Manager#628]
## Short description
I've been using this extension in firefox for a long time, but as my session grows, this extension starts to consume many gigabytes of memory. Without this extension enabled my firefox uses about 7 GB. With this extension enabled the browser peaks at over 20 GB during startup, after which it backs down again. 

## Steps to reproduce

1. Install Tab Session Manager in Firefox with a large session open (around 6000 tabs in my case)
2. Set Firefox's native settings to 'restore previous session' on startup, set Tab Session Manager's startup setting to 'do nothing'.
3. Restart the browser
4. Notice that during startup the memory usage goes over 20 GB
5. After some time memory usage drops down again. Or, if you don't have enough memory, something gets killed by the system.

## Expected result
The browsers memory usage increases with at most a few percent

## Actual result
The browsers memory usage during startup more than triples compared to not having the extension installed.

## Platform information
* Platform (OS): Linux
* Version of browser: 80.0.1 and earlier
* Version of Tab Session Manager: 6.2.1 and earlier

## Additional context
It looks like TSM does some processing on all the tabs when the browser starts up, which consumes a lot of memory. It should reduce the memory it uses.

**Comment by gisforgirard** [comment]
6000 tabs? i actually have nothing to contribute to this at all, i thought i opened a lot with 200 open, i am just genuinely wondering what do you need 6000 tabs open for?

**Comment by andreasabel** [comment]
I usually have 1000 tabs, can grow to a lot more.  TSM handles this well in general, but see #638 where TSM's memory consumption becomes pathological.

**Comment by JanKanis** [comment]
> 6000 tabs? i actually have nothing to contribute to this at all, i thought i opened a lot with 200 open, i am just genuinely wondering what do you need 6000 tabs open for?

I open tabs while looking up stuff I'm working on or investigating or whatever. Then there are always some tabs (often articles) I don't get to. Over time they pile up, and going through all of them playing garbage collector takes too much work. But we don't live in the 1990s anymore, I don't need to clean up my mailbox or my documents folder, why should I need to clean up my tabs 😎

**Comment by sienori** [comment]
I've implemented the ability to compress the favicon url when saving the session! 1c6ac8a #471
This update saves memory usage and storage space by compressing the favicon URL.
