### ISSUE TITLE
Search: unsure how to use boolean AND operator

### ISSUE THREAD

**Issue by ngirard** [sienori/Tab-Session-Manager#633]
Hi,

unless I missed something, the search functionalities are documented nowhere, which makes it hard to use.
In particular, the changelog for v6.2.0 mentions *supported AND search*, but when I tried the `AND` wasn't treated as an operator but as a simple search term.

Cheers, and thanks for your work and dedication !

**Comment by sienori** [comment]
If you search for words separated by a space, it's an AND search!
