### ISSUE TITLE
Name the session

### ISSUE THREAD

**Issue by maddhin** [sienori/Tab-Session-Manager#635]
**Is your feature request related to a problem? Please describe.**
TSM always automatically saves sessions with "random" names based on tab that is just open. So it is hard to find the latest session if one switches regularly between different sessions (or tab groups if you want). 

**Describe the solution you'd like**
I would like to save a session and give this session a name. Then TSM should auto-update that session so it can be easily found again.

**Comment by makkanx** [comment]
This is already possible. At the bottom left you can change whatever text is there to whatever you would like to call the session.
