### ISSUE TITLE
Cannot load a session from JSON file

### ISSUE THREAD

**Issue by elvisef** [sienori/Tab-Session-Manager#637]
## Short description
As in the topic: I cannot load my session saved in a JSON file.

## Steps to reproduce
1. Open Firefox
2. Open extension options and choose load a session (from file)
3. I chose a file, and clicked - extension showed the file loaded into this extension
4. Then I need to click "import" to import a session (that I chose from a file in 3rd point)
5. After clicking "import" a popup appears that it was successfully imported.

## Expected result
It should be loaded, I had three windows and many tabs opened, when I saved to JSON file.

## Actual result
The problem is, there is no session loaded at all. It is not visible on the list at all.
I have no other sessions saved at all, so the screenshot is useless.
There is just no session after being loaded from the file.

## Platform information
* Platform (OS): LINUX (debian 10.x)
* Version of browser: 78.4.0esr (64 bity) but it was saved in other version, probably also 78.x because was the latest one
* Version of Tab Session Manager: 6.2.1

## Additional context
Where to search for it ? Do I need to restart my Firefox to load it ?
But it didn't help, I tried it already.

**Comment by mwichmann** [comment]
I seem to have run into some variant of this. Firefox is 82.02, Fedora 32.  Suddenly, there are no sessions. The backup folder (`~/Downloads/TabSessionManager - Backup`) is full of backups dating back a ways, so something didn't go corrupt all of them, but while loading one "seems to work" still no sessions appear.  Are there more advanced recovery methods?

**Comment by boistordu** [comment]
same problem here under fedora 33 after upgrade from fedora 32. The files are still there where it got saved and when I'm trying to import them again, nothing appeared.
It's the same under whonix distribution.
And it happened on my fedora 32 hosts too with i guess the new update of firefox for fedora.

**Comment by mwichmann** [comment]
So it's not just the old saved setup, even freshly saved sessions with a couple of tabs won't open. On quit, it leaves a `sessionstore.jsonlz4` file. On startup it thinks for a moment as if it were going to open, then gives up (no messages), and discards that file (assuming that's the one that matters?)

**Comment by baermb** [comment]
I also see this problem with a recent upgrade to Firefox 82.0.2 on a Fedora 32 system.  All the sessions were lost, automatic saving (timed or at firefox quit) don't seem to work.  Manual saving does seem to work.

**Comment by boistordu** [comment]
Seems to have been solved with the Firefox update of today number version -3

**Comment by baermb** [comment]
It looks to be fixed for me as well.  I upgraded to Firefox to 82.0.2-3 (I assume I had -2 before, but not sure) on a Fedora 32 system.  Both the missing old sessions and the several new manually created sessions are available again. The automatic saving (e.g. timed and window closing) is also working.

**Comment by mwichmann** [comment]
Now I've updated, same result - magically all the tabs came back.  So looks like this was a Fedora-Firefox-specific thing.

**Comment by boistordu** [comment]
Doesn't work in windows now with version 6.3.0 and the new version of Firefox 82.0.3

**Comment by donw146** [comment]
I having the same problem as boistordu - a session had disappeared. I tried to load it from a .json file - the import said it worked but there is no sign of the session.

**Comment by donw146** [comment]
More recent testing results:
1. There seems to be a limit of 89 saved sessions.
2. Importing old .session files works

**Comment by sienori** [comment]
The import function does not allow duplicate sessions. If the same session already exists, it will not be imported.

If you don't see any of your saved sessions in the session list, it is a problem with the IndexedDB, not the import. Please try reinstalling TSM or [repairing IndexedDB](https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error).

**Comment by elvisef** [comment]
Alright, for me seems to be working now. Thanks !
