### ISSUE TITLE
[FireFox] Need adaptation for hamburger menu

### ISSUE THREAD

**Issue by Makishima** [sienori/Tab-Session-Manager#639]
If addon is hidden in the hamburger menu it's can not display properly

<details>
<summary>screenshot</summary>

![изображение](https://user-images.githubusercontent.com/5548003/97314433-c5e20c00-1878-11eb-889f-5fdbde43636e.png)

</details>

**Comment by sienori** [comment]
This is a Firefox problem. https://github.com/sienori/Tab-Session-Manager/issues/436
