### ISSUE TITLE
Backup files are saving in Downloads on Mac and waste space

### ISSUE THREAD

**Issue by abcdenis** [sienori/Tab-Session-Manager#641]
## Short description
I experienced free space leakage on my macbook and found a folder with backup files:
/Users/USER/Downloads/TabSessionManager - Backup

```
➜  TabSessionManager - Backup ls -l *.json  |wc -l
      40
➜  TabSessionManager - Backup du -sh .
2.6G	.
```

## Steps to reproduce

Using addon for 3-4 month I suppose.

## Expected result
To have determined folder on macos to save settings.
Option for controlling number of backup files or maximal occupied space.

## Actual result
Wasted SSD space.

## Platform information
* Platform (OS): macos 10.14.6
* Version of browser: Firefox 78.4.0 ESR
* Version of Tab Session Manager: 6.2.1

## Additional context
-

**Comment by sienori** [comment]
Because the WebExtensions API cannot access local files, local backups are always increasing. I wish there was a better way...

**Comment by brain8891** [comment]
@sienori  What about storing Backup within Tab Session Manager sandbox, WebExtension allow unlimited storage:
[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage)
[https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_store-unlimited-amount-of-client-side-data](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_store-unlimited-amount-of-client-side-data)

Why not going that route? 

Also, add a tool tip of where that folder would be stored in the users device.

Lastly, would you please answer this: when I checked [browser-extension-data\Tab-Session-Manager@sienori] there was only one File storage.js.migrated where is the Sessions data stored?

**Comment by sienori** [comment]
It is a good idea to store the backups in `storage.local`.
However, the extension needs to add permissions to use unlimited storage.
Adding the permissions reduces the utilization of the new version because the user has to grant them manually when updating. Therefore, I do not want to add new permissions...

`browser-extension-data\Tab-Session-Manager@sienori\storage.js.migrated` is a settings file from before the firefox storage was converted to IndexedDB. It is not in use now.
Sessions data stored in `storage\default\moz-extension+++[Extension ID]\idb\1782160246ssensosi.sqlite`.
Also, settings data sotored in `storage\default\moz-extension+++[Extension ID]^userContextId=4294967295\idb\3647222921wleabcEoxlt-eengsairo.sqlite`

**Comment by brain8891** [comment]
@sienori 
maybe this will help you decide:
1- On next update ask the users to vote on it  I think most who users of  Tab Session Manager are technical enough to understand the reason of unlimited storage, and I personally get wary when asked for unlimited storage but not when it makes sens like backup of sessions which is large.  Also, in the add-on's description explain why each permission is requested that always give me peace of mind. 

2- Also, I think I saw add-ons that ask for certain permission when that particular setting is enabled which is solve the whole problem.

3-  Make another add-on with that ask for that permission and see how many users move from TSM to TSM2

Tab session Manager is basically to backup the session so it make sense to have more control over it.

**Comment by sienori** [comment]
Using bookmarks is a good idea!
The `bookmark` permission is an optional permission, so no user permission is required when updating. Bookmarks are an effective backup option because they are easily accessible even when TSM storage is broken. I will implement bookmark backup.

**Comment by sienori** [comment]
Discuss bookmark backup: #678

**Comment by sienori** [comment]
I have implemented incremental backup! https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545 #710
This allows you to manage backup sessions individually.
Only updated sessions are saved, saving storage.

* One session is saved in one json file.
* When a session is updated, the json file is overwritten.
* Autosave sessions are saved in a separate folder.
* The file name is `date - session_name #tags [session_id].json`.

![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)
