### ISSUE TITLE
two session backups created instead of one

### ISSUE THREAD

**Issue by nollinvoyd** [sienori/Tab-Session-Manager#645]
Windows 10, FF82.02, 

Has anyone else experienced two backups created and saved to the TabSessionManager - Backup folder instead of the the expected one backup when Firefox is launched/restarted? It doesn't happen all the time, but occurs randomly.  I don't see a pattern.

I just upgraded to TSM 6.3.0, but this has been happening for a while now.

I have enabled debug mode, so i will post the log when I have it, I still would appreciated feedback.

**Comment by sienori** [comment]
This problem may have been resolved since the startup process was changed in version 6.4.0.
