### ISSUE TITLE
The Feedbro extension feed reader tab is not restored

### ISSUE THREAD

**Issue by alexolog** [sienori/Tab-Session-Manager#646]
## Short description
The [Feedbro](https://nodetics.com/feedbro/) extension feed reader tab is not restored on browser restart

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. Install [Feedbro](https://addons.mozilla.org/en-CA/firefox/addon/feedbroreader/)
4. Click on the Feedbro icon and select "Open Feed Reader"
5. Navigate to `about:profiles` and click on "Restart Normally..."

## Expected result
All tabs restored, including the feed reader.

## Actual result
All tabs restored, EXCEPT the feed reader.

## Platform information
* Platform (OS): Windows 10 v.1903
* Version of browser: FF dev edition 83.0b9 (64-bit)
* Version of Tab Session Manager: 6.3.0

## Additional context
Debug log on restart:
```
Unknown category for SetEventRecordingEnabled: fxmonitor
debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:196:11
XHRGEThttps://snippets.cdn.mozilla.net/us-west/bundles-pregen/Firefox/aurora/en-us/default.json
[HTTP/1.1 200 OK 0ms]

No messages returned from https://snippets.cdn.mozilla.net/6/Firefox/83.0/20201105203649/WINNT_x86_64-msvc/en-US/aurora/Windows_NT%2010.0/default/default/. ASRouter.jsm:122
XHRGEThttps://firefox.settings.services.mozilla.com/v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US
[HTTP/1.1 200 OK 0ms]

XHRGEThttps://location.services.mozilla.com/v1/country?key=[redacted]
[HTTP/1.1 200 OK 649ms]

GETwss://push.services.mozilla.com/
[HTTP/1.1 101 Switching Protocols 348ms]

can't access property "createInstance", Cc['@mozilla.org/toolkit/glean;1'] is undefined BrowserGlue.jsm:2632
POSThttp://ocsp.digicert.com/
[HTTP/1.1 200 OK 99ms]

POSThttp://ocsp.digicert.com/
[HTTP/1.1 200 OK 28ms]

XHRPOSThttps://incoming.telemetry.mozilla.org/submit/activity-stream/spoc-fills/1/[redacted]
[HTTP/1.1 200 OK 692ms]

Error: Can't find profile directory. 6 XULStore.jsm:66:15
```

**Comment by sienori** [comment]
To restore a previous session using TSM, please enable the `Open previous session` option. It will restore the Feedbro page.
![image](https://user-images.githubusercontent.com/29514424/102609932-a6c47400-416f-11eb-8e17-0ceb70f5066b.png)

**Comment by alexolog** [comment]
Weird.  All the other tabs were reloaded even with the "incorrect" setting.
Thanks.

**Comment by sienori** [comment]
If you restart from `about:profiles`, Firefox's tab restore function will work.
Also, you may have Firefox's tab restore setting enabled.
https://support.mozilla.org/en-US/kb/how-do-i-restore-my-tabs-last-time

**Comment by alexolog** [comment]
I do have it enabled.  Should I turn it off when using TSM?

**Comment by alexolog** [comment]
Hmmm...  When I turn the TSM restore on, tab with local files fail to load,
