### ISSUE TITLE
clicking on export doesn't do anything

### ISSUE THREAD

**Issue by naobug** [sienori/Tab-Session-Manager#647]
When clicking the three-dot menu on a saved session, clkicking on export doesn't show the save file prompt/window. Nothing happens.
So I can't locally save my sessions any more.
I'm using Version 6.3.0 with Firefox 82.0.2

**Comment by naobug** [comment]
I don't know why.
But now the export works again.
The only thing that has changed is Firefox got updated from 82.0.2 to 82.0.3 in the meantime.
The tab session manager still is on 6.3.0

**Comment by sienori** [comment]
I think it's just a temporary problem with Firefox.
