### ISSUE TITLE
Overwrite an existing saved session if the new session has the same name

### ISSUE THREAD

**Issue by buithehoa** [sienori/Tab-Session-Manager#648]
**Is your feature request related to a problem? Please describe.**
My daily process is to open a saved session which includes tabs that relate to a specific project, for example: Project X. When I'm done with Project X, I will save all the open tabs with the name "Project X". Now I have 2 sessions named "Project X". I will have to delete the old session and keep the new session.

**Describe the solution you'd like**
I think it makes sense to overwrite an existing saved session with a new one if the new one has the same name.

**Describe alternatives you've considered**
This can be an option cause not overwriting might be what other users prefer.

**Additional context**

Thank you for your work. This is always my favourite plugin.

**Comment by ElhemEnohpi** [comment]
@buithehoa you can already overwrite a session, even more easily. In TSM's window, right-click the "Project X" session you want to replace, and choose "Replace with current session". Or you can click on the sesson and use the three-dots menu in the upper right of the window.

Personally, I think that two sessions with the same name probably shouldn't be allowed, but it's not really a big problem.

**Comment by buithehoa** [comment]
@ElhemEnohpi Thank you. I can overwrite existing sessions as instructed.

**Comment by jacko116** [comment]
Hello!
Excellent add-on! 
However, I would like to ask if its possible to automatically overwrite existing session when closing a window or closing Firefox while keeping the same session name. Tab Session Manager as I understands it autosaves the session with the name: Auto Save - Window Closed (or action taken) or it names the saved session with the name of the tab opened in the session. It would be useful that the addon either overwrites the session with the same name, or create a new session while keeping at the begining the session name given by the user, for example: Session Name # [Date]. Like this user can easily find session by name given and also have backups of the same session numbered with the date.

Thank you
G.
