### ISSUE TITLE
When  i kill and restart extension to conserve memory after session restoring i get message stating that indexeddb is not supported

### ISSUE THREAD

**Issue by kotenok2000** [sienori/Tab-Session-Manager#650]
## Short description

When  i kill and restart extension to conserve memory after session restoring i get message stating that indexeddb is not supported
## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. 
4. 

## Platform information
* Platform (OS): 10.0.19042.610
* Version of browser: 86.0.4240.111
* Version of Tab Session Manager: 6.3.0

**Comment by sienori** [comment]
The problem has probably been fixed by this commit https://github.com/sienori/Tab-Session-Manager/commit/a73981594b2bb742d8a11b0a070b292ff290fbad
