### ISSUE TITLE
Save groups in Chrome

### ISSUE THREAD

**Issue by aviv926** [sienori/Tab-Session-Manager#652]
Hi, thanks for this extension

Can you please add an option that keeps all the groups of cards in Chrome?
(Google added a new option on this)
I'm talking about it:
https://blog.google/products/chrome/manage-tabs-with-google-chrome/

Can you make the extension save that as well?

**Comment by bbd-service-git** [comment]
+1 

I would pay serious cash for tab groups to be preserved.

**Comment by sienori** [comment]
I plan to support Chrome's tab groups.

**Comment by aviv926** [comment]
> I plan to support Chrome's tab groups.

thank you for that!

**Comment by sienori** [comment]
`chrome.tabs.group` API does not seem to be available yet in Chrome.
https://developer.chrome.com/docs/extensions/reference/tabs/#method-group
I will support the tab group when the API becomes available.

**Comment by rpg-roleplay-fan** [comment]
I copied after closing chrome the 3 session folders (Session, Session Worker, Session Storage) in chrome user profile to a named saved folder.
For later Restoring I copied form my named folder the 3 folders back to  the Orginal Profile Path (before that i deleted the folders or its cont) .
Starting the chrome profile and the state of the tab is restored.
I am not sure if it worked direct, i activate all Tab Groups Options in about:flags.

why you could not build such a functionality for group tabs in a beta version, till there is no api for doing this an a better way?

**Comment by rpg-roleplay-fan** [comment]
there is an API in development in review phase.
https://docs.google.com/document/d/1WgNtyBSuSmmHIuENU8IKLZmSK3tAVPpnjwjfD3clxqI/edit

**Comment by aviv926** [comment]
Is there any news regarding this issue?

**Comment by aviv926** [comment]
> I plan to support Chrome's tab groups.

Is there any news regarding this issue?

**Comment by sienori** [comment]
The [`chrome.tabGroups` API](https://developer.chrome.com/docs/extensions/reference/tabGroups/) has been released, but it seems to be available in Manifest V3. It may be difficult to support it immediately...

**Comment by aviv926** [comment]
> The [`chrome.tabGroups` API](https://developer.chrome.com/docs/extensions/reference/tabGroups/) has been released, but it seems to be available in Manifest V3. It may be difficult to support it immediately...

I saw [this extension](https://chrome.google.com/webstore/detail/tab-group-saver-save-and/ghbdjeckopemkoomopmpgjifafpcjhga) in the Google Chrome store I think it works according to the cache method or API ...it saves the name + the cards that are in each group

Maybe this will give you direction for your extension

**Comment by Pictor13** [comment]
Despite its name, in the description reports that:

>**Tab Group Saver does not (yet) auto-save your tab groups**

@sienori do you know how much of the codebase needs to be changed to upgrade the extension to V3?
Or you are maybe already aware of what will be the pain point in adapting the code?

Just to know, in case we can contribute.

**Comment by sienori** [comment]
In version 6, I implemented support for tab groups!
To save tab groups, you need to install [an additional extension](https://github.com/sienori/Save-Tab-Groups-for-Tab-Session-Manager).
TSM accesses `chrome.tabGroups` via the "Save Tab Group" extension.
