### ISSUE TITLE
Adding tab(s) to an existing session

### ISSUE THREAD

**Issue by GHNewbiee** [sienori/Tab-Session-Manager#654]
**Is your feature request related to a problem? Please describe.**
I would like to add a new tab to an existing session. For the time being, the only option I have is to use the "add current window" menu option, getting a session with an additional window.

**Describe the solution you'd like**
An additional option would be added, like "add current tab", under "add current window". 

**Additional context**
The only drawback I see is in case that more than one windows exist in a session. In that case, the question is in which window the tab will be added.

**Comment by sienori** [comment]
I implemented the ability to add current tab in version 6.9.0! #458 
Right-click on the window title or click on the Edit button to display the menu.
![image](https://user-images.githubusercontent.com/29514424/127774371-924d4ad5-b1f5-4871-9541-dbe42f65ac5c.png)
