### ISSUE TITLE
Enhanced lazy load functionality

### ISSUE THREAD

**Issue by owenshaupt** [sienori/Tab-Session-Manager#655]
To be frank, I'm a former Great Suspender user and I, like many others, have left following the sale of the extension by the original dev. Now, I use two separate extensions to fulfill the needs left by GS: Auto Tab Discard (for putting tabs to sleep) and Tab Session Manager (for, duh, session management).

I really love the lazy loading for restored tabs/windows and it seems to be halfway to actually fulfilling the first half of what I lost after axe-ing GS. Here are where my requests come in.

1. Create an option _to not_ (lazy) load a restored tab until the body of that tab is clicked on, _i.e._, click once on a tab to change your view to that tab, then click again somewhere in the browser window to load the tab. Thus, the user is given more control of when a tab loads.

2. Create a function to force a tab into the yet-to-be-loaded, "asleep" state.

Thanks for making such a robust and functional extension I can use on FF and Chrome :)

**Comment by sienori** [comment]
Such a feature is not in the scope of TSM.
TSM's lazy loading is a feature to reduce the load of opening many tabs at once.
[The Great Suspender](https://github.com/greatsuspender/thegreatsuspender) is open source, so you can build and install it by yourself.

**Comment by candrapersada** [comment]
> The Great Suspender is open source, so you can build and install it by yourself.

but The Great Suspender can only be used for Chromium based browsers and there is still no development for Firefox and the tabs in Great Suspender from Chromium cannot be opened in Firefox
