### ISSUE TITLE
Dark background for unloaded tab placeholder page

### ISSUE THREAD

**Issue by ElhemEnohpi** [sienori/Tab-Session-Manager#656]
**Is your feature request related to a problem? Please describe.**
I use Dark Reader so all web pages have a dark background. When I use "Tab lazy loading", but not "Use the "discarded" property", there is a white placeholder page used, with the tab name etc. When I click on an unloaded tab, for a second there is a blast of bright white light that is physically painful to my eyes.

![screenshot_346](https://user-images.githubusercontent.com/23618559/100163430-f3d96100-2eb5-11eb-8a80-57c473a8ce0f.png)

**Describe the solution you'd like**
TSM would detect using a dark browser/OS theme and automatically give a dark background. Or it could have an option to manually set a dark background in the settings, or some other way to customize the placeholder page.

This feature would go along with a complete "dark mode" requested in #211. However, I would like it to be implemented sooner, since it is a much bigger problem because it happens very often, and because it should be much simpler to fix than a full dark theme.

**Comment by sienori** [comment]
I implemented the dark mode!
![image](https://user-images.githubusercontent.com/29514424/101981064-8a2ac680-3cad-11eb-933b-883fc5405a71.png)
