### ISSUE TITLE
Sessions are gone, is there a backup somewhere?

### ISSUE THREAD

**Issue by geeveebee** [sienori/Tab-Session-Manager#66]
Hello,

the memory hungry new firefow crashed a few minutes ago.

for some reason the session list is now empty and the restore of firefox doesn't recover all tabs.

is the data of auto saves & window closes written to disk somewhere?

and is it in a format that can be imported again?

**Comment by geeveebee** [comment]
the sessions appear to be in

c:\Users\username\AppData\Roaming\Mozilla\Firefox\Profiles\profile_id\browser-extension-data\Tab-Session-Manager@sienori\storage.js

but only those I can see now : /

**Comment by rnc** [comment]
@sienori @geeveebee It does appear that looking at my current storage.js via
```cat Tab-Session-Manager@sienori/storage.js | jq -C 'reduce path(.[]?[]?[]?[]?) as $path (.; setpath($path; {}))' ```
that all the sessions are saved in a single file. Here I think SessionManager had an advantage ; as it used separate files, if a file was corrupted on crash it was possible to revert to a prior saved session file. 

Would it be better to split the session saves out to separate files or in the short term create a backup file? (although of course, a potential issue with that is that you don't want to overwrite the backup with a corrupted file - limited timestamped backups would be better).

**Comment by geeveebee** [comment]
indeed. I was using SessionManager aswell but noticed that it was disabled and there's no update for FF57 ready.

Just save each auto backup to it's own filename auto-timestamp and the manuals like user-timestamp or so.

rotate them to keep the latest 20 or so.

**Comment by sienori** [comment]
Automatic backup can not be implement due to Web Extension specifications.

Currently, there are only measures to export frequently to prevent loss of sessions.
Session import can specify multiple files.
Duplicate sessions are ignored, so you do not have to worry about duplication

Also, I plan to implement a function to select session and export.
(I'm sorry if I misunderstood the intentions of the question)

**Comment by irvinm** [comment]
It is a shame to hear that automatic backup can not happen.  I just lost all of my sessions when Firefox crashed and when I checked the storage.js it was empty.  I lost everything (700+ tabs) and obviously many regular and customer backups.  I will certainly learn to export and save them off moving forward if that is the only way with webextensions.

I did find one "storage.js.corrupt" which does look to have a lot of information (albeit it is from November 26th, so not current) but when I tried to copy it to storage.js and restart Firefox it merely renamed it "corrupt" again and started a new session.

Is there any way to extract the info from the corrupt storage.js? (Or as much of it as possible)

**Comment by alterechtschreibung** [comment]
@sienori Can you use a separate file for each saved session by default? This would significantly reduce the risk to lose everything.

**Comment by irvinm** [comment]
In the meantime, I wrote a batch file that is kicked off from task scheduler that makes a copy of the storage.js and appends the date\time to the filename.  It then deletes files older than (X) days as long as there is (Y) remaining copies.  It might be a little overboard, but I have had 2 instances already where Firefox would crash and leave me with a corrupted storage.js for session manager.  I don't mind losing a few hours or a half days worth of changes, but to possibly lose everything is scary to me.

PS. I was lucky enough the first time it happened that I had used session manager to load at startup and hence everything was stored in history.  I merely selected EVERYTHING from the day in the history and restored it all then deleted all the tabs I had closed.  [Painful, but I didn't lose anything]

**Comment by alterechtschreibung** [comment]
@sienori MySessions seems to save the tabs as bookmarks. This should also solve the corruption problem, I guess. Would this be a way to go for Tab Session Manager?

**Comment by sienori** [comment]
I implemented the function to save the backup.
I thought that I could not save the file without user interaction, but it was a misunderstanding.
The save destination is only Firefox default download directory.
https://github.com/sienori/Tab-Session-Manager/commit/96e76b0d8c79ed0fe08af974e03fcdf0a72bfcfa

**Comment by Das-Sams** [comment]
The stuff is definitely not stored in my default download directory. I renamed it and made a new one. Then I saved my session again, but the download directory stayed empty. I also cannot find it anywhere in the ~/.mozilla/ directory
Where is it?
