### ISSUE TITLE
make session page expandable...left and right

### ISSUE THREAD

**Issue by dduran1210** [sienori/Tab-Session-Manager#661]
just a suggestion.  cannot expand the session block, or the whole page , so i can see the complete session name as it was saved.

should be able to expand it ....left and right.

thanks
Dave

**Comment by sienori** [comment]
Does that mean the entire session name is invisible?
![image](https://user-images.githubusercontent.com/29514424/101620971-85210980-3a58-11eb-87af-d97897ffd23e.png)

If the `Display session name within one line` option is unchecked, the entire session name will be displayed.
![image](https://user-images.githubusercontent.com/29514424/101621011-91a56200-3a58-11eb-85e8-b1d8eb151273.png)
![image](https://user-images.githubusercontent.com/29514424/101621058-9e29ba80-3a58-11eb-8e96-e6ef01c3968f.png)
