### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by CodeBoy9090** [sienori/Tab-Session-Manager#664]
**Dark Mode** 
Please Consider adding dark mode as soon as you can , as it is more comfortable to eyes and more lovely.

**Comment by evelikov** [comment]
There's been a [MR open](https://github.com/sienori/Tab-Session-Manager/pull/539) for half an year

**Comment by sienori** [comment]
I implemented the dark mode!
![dark mode](https://user-images.githubusercontent.com/29514424/101980998-d88b9580-3cac-11eb-9c84-e8f64a4c0d9c.png)

**Comment by CodeBoy9090** [comment]
It is an appreciated effort, thank you

**Comment by killerzula** [comment]
> It is an appreciated effort, thank you

Hello, how do I apply this dark theme?

**Comment by jmona789** [comment]
I think it auto applies if you have your OS set to dark theme

**Comment by jmona789** [comment]
> > It is an appreciated effort, thank you
> 
> Hello, how do I apply this dark theme?

I think it auto applies if you have your OS set to dark theme
