### ISSUE TITLE
Regular Saving Default Setting

### ISSUE THREAD

**Issue by CodeBoy9090** [sienori/Tab-Session-Manager#666]
## Short description
Setting the auto save feature by default will lead some new users who are not yet familiar with the extension to be annoyed from the number of sessions saved without their order.
## Steps to reproduce
1. just install the extension as new user.

## Expected result
the sessions added regularly with a huge number
## Actual result
I think it is more suitable to have regular saving to be enabled manually

## Platform information
* Platform (OS): Windows
* Version of browser: Chrome , Edge and Firefox
* Version of Tab Session Manager: 6.2

**Comment by sienori** [comment]
To make new users aware of the existence of autosave, I think the default setting should be turned on.
If you set the category filter to `User Save`, the autosave sessions will be hidden.
