### ISSUE TITLE
Pinned tabs do not follow lazy loading setting

### ISSUE THREAD

**Issue by wcatlan** [sienori/Tab-Session-Manager#667]
Hi,

When loading a window with Tabbed Session Manager, it does do lazy loading on regular tabs (ie, does delay loading until selected), but TSM does not do so for pinned tabs.  TSM should provide a specific setting for pinned tabs, or, use the existing setting for all tabs.

I do have the native Firefox (Version 83.0 Windows) setting set to load pinned tabs on demand, and that works when opening a window session without TSM, however, when TSM opens the windows, it loads pinned tabs automatically.

![image](https://user-images.githubusercontent.com/42011807/101245326-0d5e8200-36da-11eb-9d81-aa007c11f7c5.png)

![image](https://user-images.githubusercontent.com/42011807/101245338-223b1580-36da-11eb-823d-160f12e2f64d.png)

![image](https://user-images.githubusercontent.com/42011807/101245390-88c03380-36da-11eb-87bd-06cd684e8bee.png)

Thanks for a great plugin!

Bill

**Comment by sienori** [comment]
Due to the specification of Firefox, pinned tabs cannot be opened as "discarded".
If you enable the `Tab lazy loading` option and disable the `Use the "discarded" property for lazy loading` option, the pinned tabs will be opened for lazy loading.
