### ISSUE TITLE
restore currentTime for video/audio HTML elements

### ISSUE THREAD

**Issue by gliptak** [sienori/Tab-Session-Manager#675]
**Is your feature request related to a problem? Please describe.**
Unless logged in, Youtube videos (and other video/audio elements on other sites) don't seem to keep their last played position when restored by Tab-Session-Manager.

**Describe the solution you'd like**
Restore last played position/currentTime for video/audio HTML elements

**Comment by sienori** [comment]
It will be difficult to support this due to the specification of the WebExtensionsAPI.
