### ISSUE TITLE
Bookmark backup option

### ISSUE THREAD

**Issue by sienori** [sienori/Tab-Session-Manager#678]
Use bookmarks to back up sessions.

> 4-Why not use Bookmark as a backup option, you can add extra data to the URL/Location or name entry of the bookmark to add extra metadata that TSM might need enable to restore the tabs.
_Originally posted by @brain8891 in https://github.com/sienori/Tab-Session-Manager/issues/641#issuecomment-741831819_

>Using bookmarks is a good idea!
>The `bookmark` permission is an optional permission, so no user permission is required when updating. Bookmarks are an effective backup option because they are easily accessible even when TSM storage is broken. I will implement bookmark backup.
_Originally posted by @sienori in https://github.com/sienori/Tab-Session-Manager/issues/641#issuecomment-748029572_

**Comment by brain8891** [comment]
Further suggestions:

1- Ability for users to choose backup folder, for example:  [Bookmarks Menu/Random Folder/Add-ons backup/TSM/] 

2- customizable bakup naming scheme with variables like, **date format**, **number of tabs** and **device name**, for example: 
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/**backup of main device/ yyyy-mm-dd 990 tabs**]

And on other devices:
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/**backup of my other device/ yyyy-mm-dd@tt-mm**]

reasons: the device name will help avoid conclusions when  syncing between devices, and appending the total number of all windows tabs helps with troubleshooting and for date format there is  need no for an explanation. 

3- customizable backup intervals in three categories:
          A- when browser starts up
          B- when browser terminate/exit/shutdown
          C- on time intervals 
Additionally each of these three backup type would be saved in a different folder for example: 
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/backup of main device/ **Time interval**/yyyy-mm-dd]
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/backup of main device/ **on shutdown**/yyyy-mm-dd]
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/backup of main device/ **on startup**/yyyy-mm-dd]

Also , the option to turn off all  or some of these three type of backup.

4- To be more organized Each window would be in a separate folder with the **Window ID**, **title** and **number of tabs**
for example:
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/backup of main device/**on startup/yyyy-mm-dd@tt-mm 2000 tabs/ window ID= 9; title=school project; Tabs=900** ]

5- Also to be more organized, whether you use the [Name"] or the [location:] filed for the data needed by STG make the information there more easily understandable, and I think using the name field is the best choice. 
![image](https://user-images.githubusercontent.com/7104190/102618680-a5d21900-4154-11eb-9ff0-b6c68a21d008.png)

I am not sure what kind of data/metadata you will add for each tab/bookmark, for sure the back button history of tabs is not possible yet,  but let say the order of a tab in the tab bar would be added to each bookmark then make it easily understandable by the user for example:
[Bookmarks Menu/Random Folder/Add-ons backup/TSG/backup of main device/**on startup/yyyy-mm-dd@tt-mm 2000 tabs/ window ID= 9; title=school project; Tabs=900/ GitHub, TabbarLocation:1**]
![image](https://user-images.githubusercontent.com/7104190/102619251-97d0c800-4155-11eb-9a6b-56aa2b4a6109.png)
which means it is the first tab in that window

And for the title, I mean the Fireifox window title which can be modified by addons such as [Window Titler](https://addons.mozilla.org/en-US/firefox/addon/window-titler/) or by add-ons that manages tabs such as [Simple Tab Group ](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/)


Thank you for this amazing add-on and I hope this helps :)

**Comment by sienori** [comment]
I have implemented incremental backup! https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545 #710
This makes local backups very convenient and bookmark backups unnecessary.

This allows you to manage backup sessions individually.
Only updated sessions are saved, saving storage.

* One session is saved in one json file.
* When a session is updated, the json file is overwritten.
* Autosave sessions are saved in a separate folder.
* The file name is `date - session_name #tags [session_id].json`.

![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)
