### ISSUE TITLE
Unable to open saved session

### ISSUE THREAD

**Issue by hklene** [sienori/Tab-Session-Manager#68]
Hi!

I have a saved session of about 100 tabs. This morning, I had to restart my computer because of updates. After that firefox came up and showed only two tabs, one empty the other with some add-on nagscreen. Now I wanted to retried the last saved session, but I can't. A second window opens, but it only has one empty tab.

I moved file:///home/holger/.mozilla/firefox/logr1js5.default/browser-extension-data/Tab-Session-Manager@sienori/storage.js to backup and restarted firefox, opend some tabs. Restore after Firefox starts worked like a charm, but I cannot open a specific session. Everytime I try, only a new Window with one empty tab, no matter how many tabs the session has. It simply does not restore anything other than the default on startup.

Questions:
- How to edit the storage.js, to make my desired session the one, to restore on startup?
- How to debug, why it won't allow to restore an arbitrary session?

Thanx
Holger

PS: This is FF56 on Kubuntu with TSM 1.3.3

**Comment by rnc** [comment]
session.js is in json format. You could edit it (or filter it using [jq](https://stedolan.github.io/jq/) ) to narrow down the offending problem. Perhaps its a about:* tab which @sienori  has already fixed? This is where an option to enable debug logging would be helpful!

**Comment by hklene** [comment]
First I updated to TSM 1.5.0 but that didn't bring back my tabs.

Then I edited the storage.js, replacing all about:* for some real URL. At first, it didn't show those changes in the GUI. I had to manually save a session, to make it show the desired backup.

But trying to resurrect it, I still have the window with a single empty tab.

**Comment by sienori** [comment]
In FF56, it is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting. https://github.com/sienori/Tab-Session-Manager/issues/32

Also, there is no function to restore on startup yet. (I am sorry if I misunderstood the intention of the question)

To use the latest development version, you need to download the repository from git hub and read manifest.json from the about:debugging page.
I plan to upload the latest version to AMO within a few days.

**Comment by hklene** [comment]
Thanx, this did the trick. Now I have three ways :-)
- at first, I extracted the URLs by hand
- second, I learned a neat jq command, to get the URLs programmatically
- third, your extension also succeded

Sadly the tree-style structure is lost by all three methods, but hey, I should have read/closed some of those tabs long time ago. So I'm closing here ...
