### ISSUE TITLE
Overwriting Existing Session and Session Name

### ISSUE THREAD

**Issue by jacko116** [sienori/Tab-Session-Manager#684]
Hello!
Excellent add-on!
However, I would like to ask if its possible to automatically overwrite existing session when closing a window or closing Firefox while keeping the same session name. Tab Session Manager as I understands it autosaves the session with the name: Auto Save - Window Closed (or action taken) or it names the saved session with the name of the tab opened in the session. It would be useful that the addon either automatically overwrites the session (when quiting or closing window) with the same name given by the user, or create a new session while keeping at the beginning the session name given by the user, for example: Session Name # [Date]. Like this user can easily find session by name given and also have backups of the same session numbered with the date.

Thank you
G.

**Comment by duendwang** [comment]
I would like this too. Helps in using the addon as project workspaces.

**Comment by ein-bandit** [comment]
Really good suggestion! For me personally I need to replace a saved session with the current sessions always, since the plugin does not override the existing session.
There is also not shortcut for manually saving current window to override the existing session.
+1 for the above suggestions :)

**Comment by sienori** [comment]
In version 6.12.0, I implemented Tracking Session feature! #890

You can set a session as a tracking session from the session menu. When you open a tracking session, changes in the window are automatically reflected in the session. This allows for efficient workspace switching!

![session menu](https://user-images.githubusercontent.com/29514424/166821091-8ff657bd-dbfc-49e1-ac23-974c6d313e54.png)
![tracking session](https://user-images.githubusercontent.com/29514424/166821237-f4e1eece-0bda-4c50-bb63-db6280ba9329.png)

https://github.com/sienori/Tab-Session-Manager/releases
