### ISSUE TITLE
save windows position?

### ISSUE THREAD

**Issue by gabri25ele** [sienori/Tab-Session-Manager#69]
is possible to save also the windows position of the session?

**Comment by hejops** [comment]
Would like to know this as well. Session Manager was able to do so.

**Comment by tbertels** [comment]
This needs an API change, see for example [bug 1413525](https://bugzilla.mozilla.org/show_bug.cgi?id=1413525).

**Comment by ElhemEnohpi** [comment]
@tbertels, are you sure? Why couldn't it use the Window API to get and set window positions?
https://developer.mozilla.org/en-US/docs/Web/API/Window

**Comment by RobertAb1** [comment]
Issue 69 is also discussed few times here: https://github.com/sienori/Tab-Session-Manager/issues/131

**Comment by tbertels** [comment]
@ElhemEnohpi: indeed, it looks like it already exists, my bad.
And this API may make it possible to fix #144!

**Comment by RobertAb1** [comment]
@tbertels 
Is also window size covered by this Windows API?

**Comment by tbertels** [comment]
@RobertAb1: from
https://developer.mozilla.org/en-US/docs/Web/API/Window/outerHeight
https://developer.mozilla.org/en-US/docs/Web/API/Window/outerWidth
https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo
it looks like it does.

**Comment by RobertAb1** [comment]
@tbertels 
Great!

Also the order of windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1235231

**Comment by RobertAb1** [comment]
Related #144

**Comment by ElhemEnohpi** [comment]
> Also the order of Firefox windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1235231

@RobertAb1, that is a bug in the built-in Session Restore component. Tab Session Manager doesn't have that bug, it's not a problem. Please understand that Web Extensions like Tab Session Manager are completely unrelated to anything to do with built-in Session Restore! There's no API for them to access it, they don't use it in any way.

**Comment by sienori** [comment]
I will implement this function in the future.
