### ISSUE TITLE
Custom window titles saved but not restored

### ISSUE THREAD

**Issue by ghost** [sienori/Tab-Session-Manager#690]
## Short description
Custom window titles are saved in Firefox but not restored. Custom window titles appear in the Tab Session Manager main panel, however after restarting the browser and restoring all the tabs from TSM, custom window titles are lost.

## Steps to reproduce
1. Start Firefox
2. Set custom window titles on each window with an extension such as Window Titler
2. Click on "Save all windows" on TSM
3. Observe that custom window titles appear on the first tab of each window between square parenthesis in the TSM main panel
4. Quit Firefox
5. Restart Firefox
6. Restore all tabs by clicking on "Open in new window" in TSM
7. Click on "Save all windows" on TSM
8. Observe that custom window titles no longer appear on the first tab of each window between square parenthesis on the TSM main panel

## Expected result
Custom window titles should appear on the first tab of each window between square parenthesis on the TSM main panel

## Actual result
Custom window titles no longer appear on the first tab of each window between square parenthesis on the TSM main panel

## Platform information
* Platform (OS): Mac OS Catalina
* Version of browser: Firefox 84.0.1
* Version of Tab Session Manager: 6.4.0

## Additional context
N/A

**Comment by astraetech** [comment]
Surprisingly a major issue here as well for someone coming from an older FF with Firetitle where it worked perfectly. Would love to see that addressed.

**Comment by astraetech** [comment]
Seriously considering going for the Patreon if this increases the chances this could get implemented :) I really like the addon!

**Comment by sienori** [comment]
I've implemented window title restoration! https://github.com/sienori/Tab-Session-Manager/commit/8c36c380e8ac64699127611e35b5dc560111e237
Thanks!

**Comment by PolarBruski** [comment]
Should this be fixed and working?  I've had issues with it for the past year, which makes me very sad since the combination off Window Titler + Tab Session Manager is the best way for my brain to manage work and research for teaching.  Let me know if there's a setting I should enable or a test I can do.  I try keeping my computers running for as long as possible, but when they need to update and restart, I lose all my window names. :(
