### ISSUE TITLE
openerTabId is not restored for tabs with special URLs (like about:config)

### ISSUE THREAD

**Issue by piroor** [sienori/Tab-Session-Manager#692]
## Short description

TSM sets `openerTabId` for restored tabs when the compatibility option for Tree Style Tab is activated. But it looks to fail for tabs with special URLs impossible to be opened with `tabs.create()`, like `about:config`.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager.
3. Go to TSM's options page.
4. Activate the compatibility option for Tree Style Tab.
5. Import the session data: [tabs-with-dangerous-URL.zip](https://github.com/sienori/Tab-Session-Manager/files/5780724/tabs-with-dangerous-URL.zip)
6. Restore the imported session "tabs with dangerous URL" with a new window.

## Expected result

Tabs are opened with `openerTabId` except the first tab, like:

```
1. about:addons (no `openerTabId`)
2. about:debugging (`openerTabId` = 1)
3. about:support  (`openerTabId` = 2)
4. about:networking  (`openerTabId` = 3)
5. about:config  (`openerTabId` = 4)
```

## Actual result

All tabs are opened without `openerTabId`.

## Platform information
* Platform (OS): Windows 10
* Version of browser: Firefox 84.0.2
* Version of Tab Session Manager: 6.4.0

## Additional context

Here is the original issue reported to TST: https://github.com/piroor/treestyletab/issues/2774

**Comment by piroor** [comment]
TSM replaces the URL of an opening tab, from a dangerous URL to its safe version like `moz-extension://xxxx-xxxx-xxxx-xxxx/replaced/index.html?state=open_faild&title=%E9%AB%98%E5%BA%A6%E3%81%AA%E8%A8%AD%E5%AE%9A&url=about%3Aconfig&favIconUrl=undefined` . The replacing logic looks to break the restoration logic of `openerTabId` - sorry this is just a assumption.

**Comment by sienori** [comment]
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/b5f066c9307d241005be2703892f3281ebed4c55
Thank you for the detailed report!

**Comment by piroor** [comment]
Oh, thank you for the quick fix!
