### ISSUE TITLE
Import from crashed PC

### ISSUE THREAD

**Issue by andreapx** [sienori/Tab-Session-Manager#696]
My Windows PC just decided that it didn't wanted to boot...
I've installed a new disk and I've done a fresh Windows 10 installation.
Now...how can I import the sessions that I had saved in the old Windows installation?
I've tried to move the old 1782160246ssensosi.files folder in the new PC, but when I start FF TSM says that there is no IndexDB.
Thanks!!!

**Comment by sienori** [comment]
This page may help you: https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by andreapx** [comment]
Thanks, thanks, thanks!!!
I've had also to import the folder "1782160246ssensosi.files".
