### ISSUE TITLE
tabs' lazy loading never ends unless the “discarded” property is used

### ISSUE THREAD

**Issue by Mithgol** [sienori/Tab-Session-Manager#697]
## Short description
If the setting “Use the `discarded` property for lazy loading” is not set, then tabs' lazy loading does not seem to end.

## Steps to reproduce
1. Install Mozilla Firefox 85.0 (64-bit).
2. Visit the “about:profiles” page.
3. Create a new profile “Tab Manager test”.
4. Hit “Launch profile in new browser”, continue in that browser.
5. Open https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager and add “Tab Session Manager” to Firefox.
6. In the settings of “Tab Session Manager”, uncheck “Use the `discarded` property for lazy loading”.
7. Unpack [this ZIP archive](https://github.com/sienori/Tab-Session-Manager/files/5884085/tabs_exported.zip) to get the file `tabs_exported.json`
8. Enter the section “Sessions” in the settings of “Tab Session Manager”, use the “Import sessions” tool to import from `tabs_exported.json`
9. Click in the icon of “Tab Session Manager” on the toolbar, confirm that the imported session has 903 tabs.
10. Click the imported session, then right-click on it, choose the “Open in current window” option.

## Expected result
Every imported tab is loaded eventually, albeit lazy (i.e. only the icon and the JavaScript that loads the actual page on focus).

## Actual result
Tabs' lazy loading does not seem to end.

## Platform information
* Platform (OS): Windows 7 Professional Service Pack 1.
* Version of browser: Mozilla Firefox 85.0 (64-bit).
* Version of Tab Session Manager: 6.4.0.

## Additional context
Tabs load fine if the “discarded” property is used.

**Comment by sienori** [comment]
Opening 900 tabs without the `discarded` property is not recommended as it causes performance problems. In my environment(Windows10, AMD 3700X, RAM 32GB), it took a few minutes to open.
