### ISSUE TITLE
Location of sessions in chrome under Linux

### ISSUE THREAD

**Issue by Jezhi** [sienori/Tab-Session-Manager#698]
I need to know the location of sessions' file(s) in google chrome under Linux (Debian). Please, help.

**Comment by Jezhi** [comment]
Just say if there's no chance to restore a session file that was deleted accidentally.

**Comment by sienori** [comment]
Sorry my late reply.
In Windows Chrome, it was found in the following file: 
`C:\Users\USER\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_apckmmkkalmmljfdlejfiaafhkkhbaeg_0.indexeddb.leveldb`

If there are no files or backups left from before the deletion, unfortunately, you will not be able to recover the data...

**Comment by Jezhi** [comment]
Thanks for your reply. Indeed, even though I've managed to recover some files of this folder, it didn't help me in restoring the lost URLs.
