### ISSUE TITLE
Tree Style Tab - Vertical tab tree support?

### ISSUE THREAD

**Issue by irvinm** [sienori/Tab-Session-Manager#7]
Using the vertical tab solution "Tree Style Tab", I am able to manage my tabs vertically and even put them into topic trees.  Tab Session Manager is able to store all of the tabs and restore them (minus about:xxx), but isn't able to maintain the relationships.

I am not sure if this request is even possible as I can see that when I am also running "Tree Tabs", that add-on does not see the changes I make using Tree Style Tab.

Test Session:
![tree](https://user-images.githubusercontent.com/979729/31142423-3ec6fa4e-a848-11e7-9624-06757a7b8665.PNG)

Restored Session:
![non-tree](https://user-images.githubusercontent.com/979729/31142422-3ebd27f8-a848-11e7-8a2c-1e42c6bd3c0a.PNG)

**Comment by gogoengie** [comment]
I would also appreciate this functionality. If I understand correctly, it should be a simple case of setting `openerTabId` when recreating the tab.

References (search for `openerTabId`):
 * https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create
 * http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-10-03_migration-we-en.htm#topic2017-10-03_migration-we-en

At a glance, it looks like `Tab-Session-Manager::saveSession` saves the entire `Tab`, but restores only a few properties when recreating the session. If `Tab-Session-Manager::makeTab` would include the `property.openerTabId` of the saved tab, that might be enough. (Disclaimer: I am neither an extensions developer nor even a JavaScritp dev, just an interested user.)

**Comment by sienori** [comment]
That is probably possible.
I will support it in the next version.

**Comment by sienori** [comment]
Supported in 1.3.1

If you replaced the parent-child relationship of tabs, It is impossible to restore completely.
This is because TST does not update the openerTabId when replacing tabs.

**Comment by irvinm** [comment]
@sienori I just wanted to say thanks.  I passed your feedback to piroor (TreeStyleTabs) and he has already made the change to update openerTabId.  With these 2 changes, it should provide a pretty nice use case with vertical tabs with a session manager.
