### ISSUE TITLE
Enable dark mode button.

### ISSUE THREAD

**Issue by Darkwolf1515** [sienori/Tab-Session-Manager#702]
**Is your feature request related to a problem? Please describe.**
Since I use a custom theme, it wont report as dark to the extension, making it inaccessible.

**Describe the solution you'd like**
Just a button to enable dark mode.

**Comment by gsirvine** [comment]
I don't no longer see in option for dark mode or themes inside the settings page of the extension.  So I can't switch into dark mode on one of my computers.  My laptop is already in dark mode but I can't locate the option?  It is like it disappeared.

Version 6.4.0

**Comment by sienori** [comment]
I plan to add a dark mode option in the next update.

**Comment by sienori** [comment]
Dark mode option was added in version 6.4.1.
