### ISSUE TITLE
Feature request: push cloud sync

### ISSUE THREAD

**Issue by duendwang** [sienori/Tab-Session-Manager#703]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Push cloud sync instead of timed or manual only. So far I've noticed that it just tells me when it's out of date but I need to push to sync with cloud.

**Comment by sienori** [comment]
I added the auto sync option! https://github.com/sienori/Tab-Session-Manager/commit/31346439f654654789574ef5c0044eac50d13cc2 #602
![image](https://user-images.githubusercontent.com/29514424/114171875-de019f80-996f-11eb-9ce7-2b6bd7db5b20.png)

**Comment by petko10** [comment]
Btw I noticed auto-saves don't trigger the auto-cloud-sync, is that intended? And btw, just as a side question - are there any quotas when using the GDrive API (for max requests per user or app)? I couldn't find any in the docs, but I would've guessed there are some.
