### ISSUE TITLE
[Feature] Session Menu - "Add current tab" option

### ISSUE THREAD

**Issue by Bruno2049** [sienori/Tab-Session-Manager#707]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In the session menu, you already have the option "Add current window", but will be awesome to have the "Add current tab" option too.

**Describe alternatives you've considered**
Add the "Add current tab" option to the session menu.

**Additional context**
![image](https://user-images.githubusercontent.com/6771565/107863932-cc0fee80-6e4f-11eb-92ae-79ac02ab6b67.png)

**Comment by kocjs** [comment]
Yes, I am looking for this too. See #554. 

> I would love to just right click a tab and an option appears "TSM safe to existing session", that should then allow me to choose one of my saved sessions. Nest time I open that session it should be appended to the end.

**Comment by kocjs** [comment]
One more user too #654 

> Describe the solution you'd like
An additional option would be added, like "add current tab", under "add current window".

**Comment by kocjs** [comment]
similar #587 

> Please add the ability to move tabs between sessions. Right now, the only option to merge sessions (or move one tab) is to load the session and tab and save them manually. Very tiring. The ideal option, of course, is drag and drop, but the context menu will also be useful ...

**Comment by galfonso99** [comment]
I really hope this is implemented at some point. This extension is perfect except for this missing feature. I hate having to add a new window for just one tab. Also it could be like save selected tabs and ofc by default it just saves the current tab.

**Comment by adamwinn** [comment]
I'd love to see this enhancement too

**Comment by geonyoro** [comment]
I'll be attempting to add this myself.

**Comment by sienori** [comment]
I implemented the ability to add current tab in version 6.9.0! #458 
Right-click on the window title or click on the Edit button to display the menu.
![image](https://user-images.githubusercontent.com/29514424/127774371-924d4ad5-b1f5-4871-9541-dbe42f65ac5c.png)
