### ISSUE TITLE
[backups]  splitted JSON instead of big JSON

### ISSUE THREAD

**Issue by jlmxyz** [sienori/Tab-Session-Manager#710]
As a user, I use tab session manager on several devices, at home, at work, on chrome, firefox, chromium... backups are shared on sshfs
in order to manage all saved sessions, I would like instead of a big archive "2021-02-18 22-27-02 (35 sessions).json" I would like to have 35 Json files with a name of session_name.tags.json since I tag all my sessions with "Save device name to session" feature

**Comment by perXautomatik** [comment]
i like the idea of some sort of alternative system to the "large" jsonfile, (my files are in the size of a 1000+) and was looking into ways to use etl to migrate the sessions into a sql db,

**Comment by sienori** [comment]
I have implemented incremental backup! https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545
* One session is saved in one json file.
* When a session is updated, the json file is overwritten.
* Autosave sessions are saved in a separate folder.
* The file name is `date - session_name #tags [session_id].json`.

This allows you to manage backup sessions individually.
Only updated sessions are saved, saving storage.

![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)

**Comment by candrapersada** [comment]
why when checked, backup can't ignore to choose where to save files manually?
![gambar](https://user-images.githubusercontent.com/36833664/117342875-e943de80-aecd-11eb-8d9d-b715836e240f.png)
![gambar](https://user-images.githubusercontent.com/36833664/117344542-aedb4100-aecf-11eb-80b2-d361dc5b26f5.png)

**Comment by candrapersada** [comment]
> I have implemented incremental backup! [72da718](https://github.com/sienori/Tab-Session-Manager/commit/72da718c019899906e7de7994195ab18f0e4c545)
> 
> * One session is saved in one json file.
> * When a session is updated, the json file is overwritten.
> * Autosave sessions are saved in a separate folder.
> * The file name is `date - session_name #tags [session_id].json`.
> 
> This allows you to manage backup sessions individually.
> Only updated sessions are saved, saving storage.
> 
> ![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
> ![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)

is there a feature to automatically import from `One session is saved in one json file`?
