### ISSUE TITLE
[popup size] allow height to be more than 600

### ISSUE THREAD

**Issue by jlmxyz** [sienori/Tab-Session-Manager#711]
**Is your feature request related to a problem? Please describe.**
the poppup is by far too small, only 7 sessions are visible and on today displays it could be 1000 of height without issue

**Describe the solution you'd like**
don't limit height and width, let the user choose.

**Describe alternatives you've considered**
....

**Additional context**

**Comment by bandaid** [comment]
There is a discussion about these types of requests. It is not a _bug_ issue.

**Comment by sienori** [comment]
Popup size is limited to 800x600 according to WebExtensions specifications.

You can open the session list in a tab to get a larger view.
![image](https://user-images.githubusercontent.com/29514424/116043448-a2264400-a6aa-11eb-859d-e0a9ecf39202.png)
