### ISSUE TITLE
Auto save fails to work in Firefox 86

### ISSUE THREAD

**Issue by desbest** [sienori/Tab-Session-Manager#714]
## Short description
Auto save fails to work in Firefox 86

## Steps to reproduce
1. Use Firefox 86
2. Wait X minutes
3. No auto saved sessions

## Expected result
A new auto save session should be saved

## Actual result
No new auto save session is saved in the new release of Firefox 86.
```
Uncaught (in promise) TypeError: e is undefined
    te moz-extension://0e54994e-993a-463f-99a1-084da100ccf7/background/background.js:29
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://a270d310-67ff-4a6a-9cb5-c7ebdc8a4ff7/background/background.js:4
background.js:4:8704
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onWebNavigationCompletedHandler moz-extension://c643f582-af6e-4146-a607-c00f2d512cbb/background.js:355
background.js:355:45
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    <anonymous> moz-extension://a270d310-67ff-4a6a-9cb5-c7ebdc8a4ff7/background/background.js:4
```

## Platform information
* Platform (OS): Windows 10
* Version of browser: 86
* Version of Tab Session Manager: 6.4.0 and 6.4.1

**Comment by j-beaver** [comment]
same problem for me
even worse, I'm not able to save sessions manually

**Comment by desbest** [comment]
It looks like Firefox upgrading from version 85 to 86 in March 2021 broke the extension.
You'll have to backup your sessions, uninstall the extension, restart firefox so it loads with it gone, then install it again.
Once installed again it will start to work again as normal.
