### ISSUE TITLE
Support Chrome Tab Group

### ISSUE THREAD

**Issue by LeanLL** [sienori/Tab-Session-Manager#717]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When we save/restore the sessions, be able to maintain the tabs groups from the Chrome

**Describe alternatives you've considered**
None

**Additional context**
Example of the Tab Groups
![image](https://user-images.githubusercontent.com/10226034/110163174-80a58c00-7dce-11eb-86e8-fdf8a78cf162.png)

**Comment by sienori** [comment]
Thanks! I'd like to support Chrome tab groups in the future. More research is needed. 
Memo: https://developer.chrome.com/docs/extensions/reference/tabGroups/

**Comment by LeanLL** [comment]
> Thanks! I'd like to support Chrome tab groups in the future. More research is needed.
> Memo: https://developer.chrome.com/docs/extensions/reference/tabGroups/

Sienori, if u can guide me to where, in the code, use the chrome Session API to get the current session, I may try to code this case of the tab.

**Comment by sienori** [comment]
The `chrome.tabGroups` API seems to be available in Manifest V3. It may be difficult to support it immediately... https://github.com/sienori/Tab-Session-Manager/issues/652

**Comment by sienori** [comment]
In version 6.6.0, I implemented support for tab groups! https://github.com/sienori/Tab-Session-Manager/commit/f3e14f7d30ec9e46a58d6a84848f6a4b677a7591 #652 
To save tab groups, you need to install [an additional extension](https://github.com/sienori/Save-Tab-Groups-for-Tab-Session-Manager).
