### ISSUE TITLE
Create Backup at Startup

### ISSUE THREAD

**Issue by anishmittal2020** [sienori/Tab-Session-Manager#718]
# Current Behavior

When enabled, creates Backup at Startup.

# Suggested Behavior

Let us select a delay in time after which the backup should start.
When enabled, creates Backup at Startup, after the predefined delay.

# Purpose

To not slow the browser startup.

**Comment by sienori** [comment]
I added a 30 second delay on startup. https://github.com/sienori/Tab-Session-Manager/commit/98752964f1d859f8387d0cae122fbbbdaee087ab
