### ISSUE TITLE
Bug: Auto-save with session manager imported session

### ISSUE THREAD

**Issue by kunal999** [sienori/Tab-Session-Manager#72]
After a session manager session is imported, if it is auto-saved without saving manually, it saves with all the URLs as "about:newtab".

Please note, if the session is saved manually once after importing, then auto-save works fine.

**Comment by sienori** [comment]
Does the same problem occur in version 1.8.0?

>Please note, ~~

Also, I fixed it.
https://github.com/sienori/Tab-Session-Manager/commit/2b11271af128e09305a9541b1d030118002f6796
