### ISSUE TITLE
Offline webpage viewing

### ISSUE THREAD

**Issue by tab328** [sienori/Tab-Session-Manager#729]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm looking for a way to save and view session webpages offline.

**Describe alternatives you've considered**
Firefox's Offline mode only works for a small number, for a short time, and does not persist after a computer restart. I would prefer the cached pages be stored indefinitely, like the sessions. I'm open to any other suggestions that fit the criteria, but I haven't found anything. I want all open tabs to be saved locally (automatically) and for the local saved pages to be reloaded in place of fetching from the web to save on data usage. Saving 200+ pages individually as pdf is not feasible. Thank you in advance!

**Comment by sienori** [comment]
This function is outside the scope of TSM. Try to find other extensions. 
For example: https://addons.mozilla.org/en-US/firefox/addon/save-page-we/
