### ISSUE TITLE
Save to cloud, sync settings with firefox sync

### ISSUE THREAD

**Issue by natrius** [sienori/Tab-Session-Manager#73]
**Version:**
1.5.0

**Issue:**
When saving a session and accessing another computer, the session is not available.

**Possible solution:**
Addons like uMatrix and uBlock Origin provide the possibility to sync with firefox sync. Add this possibility.

That would be actually incredible. Thanks for the Addon, i like it so far :)

**Comment by sienori** [comment]
I will think about it.

**Comment by natrius** [comment]
Just to give an example, when working at school or at work with the laptop and when getting home it would be nice to reopen with all the tabs. Right now i have to get some bookmarks and delete them afterwards :/

**Comment by maximloginov** [comment]
If the ["foder to save"](https://github.com/sienori/Tab-Session-Manager/issues/189) option will be implemented, one can point to Dropbox or Goodle drive folder to store the sessions as suggested at https://stackoverflow.com/questions/31430906/how-to-sync-session-manager-sessions-accross-devices-in-firefox

**Comment by sienori** [comment]
@maximloginov It is impossible to save a session as a file anywhere like the old Session Manager.
With WebExtensions, you can only save copies of sessions as backups.

**Comment by josetta** [comment]
I would like to ask for cloud saving option too, it is really annoying everyday saving sessions to json and importing on second machine. After moving to IDB, sharing addon parts between machines not working either, so export import is now only possibility... THX

**Comment by timoc** [comment]
I would suggest this feature be used for the automatic 'backup' feature. 
In my use case, it is not often i want to transfer sessions between systems, but when i do, using bookmarks and firefox sync, would make it seamless.
Duplicate #376, #181

**Comment by adamshand** [comment]
I've been using Tab Session Manager for the last couple months and it's been great, many thanks!

The one thing I'd really love is if my saved sessions moved between computers with Firefox Sync.  Would make the process of switching computers between work and home a little better.

Thanks again.

**Comment by sienori** [comment]
Thank you for waiting so long.
I finally implemented the cloud sync function!!
You can save sessions to Google Drive and sync with other devices.
![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png)
![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)

**Comment by natrius** [comment]
Amazing! Thank you for you hard work. 

I don't want to jangle on your nerves, but do plan to implement others as well? I'm using FF because i try not to use Google or Microsoft at all. As it seems not possible with Firefox Sync, i'm thinking about Nextcloud, for example. 

Best regards.

**Comment by josetta** [comment]
great, thx :D

**Comment by timoc** [comment]
Thanks!

**Comment by sienori** [comment]
Currently, there are no plans to support cloud storage other than Google Drive. Thank you for your understanding.

**Comment by natrius** [comment]
Well, with the implementation of https://github.com/sienori/Tab-Session-Manager/issues/189 its at least somewhat possible with Nextcloud. Thanks for your work :)

**Comment by aviv926** [comment]
How do I download tab backups from Google Drive's cloud?

**Comment by sfederici** [comment]
> Thank you for waiting so long. In version 6.0.0, I finally implemented the cloud sync function!! You can save sessions to Google Drive and sync with other devices. ![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png) ![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)

I see an orange exclamation mark on my green cloud button. When I click it, a "syncronizing..." text shows up and the exclamation mark disappears. But then, after 5 minutes the exclamation mark is back, and the text keeps saying "syncronizing". Is there something that I'm missing?
