### ISSUE TITLE
extension locked up machine for several minutes

### ISSUE THREAD

**Issue by MartinThomas9** [sienori/Tab-Session-Manager#733]
## Short description
I disabled this extension for about 7 weeks.
When I re-enabled it my machine at once locked up for several minutes. When I got a bit of control I checked with the KDE System Monitor and found that the WebExtensions process was using 3.5GB and rising. 

## Platform information
Firefox 87.0 (64-bit)
Debian  Linux 9.13
Tab Session Manager  Version 6.4.2

**Comment by StoopidoMan** [comment]
I have the same problem on Windows, and on Firefox 87

**Comment by sienori** [comment]
It seems to have been improved. https://github.com/sienori/Tab-Session-Manager/issues/718

**Comment by MartinThomas9** [comment]
Yes, it has improved a lot.
