### ISSUE TITLE
High CPU, RAM usage after updating to FFV87

### ISSUE THREAD

**Issue by StoopidoMan** [sienori/Tab-Session-Manager#735]
## Short description
After updating to FF V87, Firefox started to take time to run, and the ram usage sometimes reached over 4-10GB and CPU usage would raise significantly. After disabling  TSM the issue was resolved. 

Also after restarting FF without TSM, and then enable TSM raise the ram to 4GB in total. 

I have the same problem on a different profile, however, I didn't try it on a fresh new profile. 

## Steps to reproduce
-

## Expected result
-

## Actual result
Sorry I can't provide any logs.

## Platform information
* Platform (OS): Windows 7
* Version of browser: FF v87
* Version of Tab Session Manager: V6.4.2

## Additional context
-

## Additional Feedback:

Having backup is great but every time I run FF, TSM downloads a 350MB file, and I have to delete the periodically, that is another reason why I disabled it. I will be enabling it on weekly basis to take a backup. Please fix this. it should be seamless.

**Comment by StoopidoMan** [comment]
update: Solved, after updating to V87 FF started to to hang on startup and get memory leak, at first after disabling TSM the issue was resolved, but it came back after some time, so I disabled all the add-ons and eventually after deleting all the history the issue was resolved, not sure what caused it. 

My apologies. 

Having said that, based on `About:Performance ` TSM does consume a lot of resources when it should not be active for example it should save my sessions every hour, but I often saw it active on "A bout:Performance" when it should not be.  And the backup are not zipped and each back in my case is 400MB if it was zipped that would be reduced to 50MB
![image](https://user-images.githubusercontent.com/71223069/115883142-83cc0880-a45e-11eb-8b0c-da05c949c044.png)

And I think saving these backup within the Addon sandbox is more intuitive, I understand it is another permission to ask, and I am always weary of those but not for a session backup add-on.

**Comment by sienori** [comment]
Automatic deletion of local backups cannot be implemented due to WebExtensions limitations.
I've considered compressing and decompressing backups in the past, but decided against it because of performance issues.
Using cloud sync, you can back up sessions to Google Drive.

If auto-save when window is closed or browser is closed is enabled, the TSM will be activated each time a tab is opened.
