### ISSUE TITLE
Upon opening a session, all webpages (and subsequently contained media) are loaded

### ISSUE THREAD

**Issue by d0peman** [sienori/Tab-Session-Manager#74]
Is it possible to prevent all opened tabs from loading and only load upon selecting the tab as SessionManager did previously? I understand that they're opened one by one though and that this might be a bit of a stretch to implement at this stage.

This easily becomes irritating when the session contains multiple tabs containing media that will begin playing immediately as soon as the page is loaded (YouTube, for example)

Great job on the addon so far though!

**Comment by sienori** [comment]
Lazy loading option was added in ver1.6.0.

**Comment by d0peman** [comment]
You're my hero. Thank you so much mate!
