### ISSUE TITLE
Cant export on brave.

### ISSUE THREAD

**Issue by Darkwolf1515** [sienori/Tab-Session-Manager#746]
I am unable to export from brave, as it appears like this.  
![image](https://user-images.githubusercontent.com/65789901/114611482-f3b7e300-9c55-11eb-8ecd-d4b9408a88da.png)

## Platform information
* Platform (OS): Windows 10
* Version of browser: Brave 1.22.71
* Version of Tab Session Manager: 6.5.0

**Comment by sienori** [comment]
I installed Brave and tested it, and it seems to work fine. 
![image](https://user-images.githubusercontent.com/29514424/116057871-3350e700-a6ba-11eb-8ce6-d6b16ebce391.png)

Add `.json` to the file name and try downloading it. #640

**Comment by Darkwolf1515** [comment]
Yeah, that worked fine, thanks.
