### ISSUE TITLE
Reserve session copy on PC is not saving

### ISSUE THREAD

**Issue by xHurricanex** [sienori/Tab-Session-Manager#751]
Reserve session copy on local PC is not working.
Tried making folder in Downloads folder for this copy - the extension is not saving local copies...

![2021-04-21_115827](https://user-images.githubusercontent.com/62963044/115527135-73b6fc00-a299-11eb-8a1c-ea41ebdc2bd0.jpg)

**Comment by sienori** [comment]
To back up, use the Save Backup option.
![image](https://user-images.githubusercontent.com/29514424/115969936-6d1ad400-a57a-11eb-8664-5073a72d6302.png)
