### ISSUE TITLE
Extension is broken in Firefox 89 (current beta)

### ISSUE THREAD

**Issue by levifig** [sienori/Tab-Session-Manager#754]
## Short description
Not working at all: no sessions saved, can't import/export sessions

## Steps to reproduce
1. Upgrade to Firefox 89.x
2. No workerino.

## Expected result
Sessions should be saved according to preferences, imported session should appear in the sessions list, should be able to export sessions

## Actual result
No sessions are being saved.
Export sessions button does nothing.
Import says it imported but it doesn't show them anywhere.
No errors on console or debugger.

## Platform information
* Platform (OS): macOS
* Version of browser: 89.0b3
* Version of Tab Session Manager: 6.6.0

**Comment by levifig** [comment]
Managed to find some info on the debugger:

```
[debug] background/sessions: getAll() null background.js:1:71494
[error] background/sessions: getAll() 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
​
bubbles: true
​
cancelBubble: false
​
cancelable: true
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​
isTrusted: true
​
originalTarget: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​
returnValue: true
​
srcElement: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​
target: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​
timeStamp: 76494119
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
background.js:1:71494
    methodFactory moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:1
    onerror moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    (Async: EventHandlerNonNull)
    getAll moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    getAll moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    $ moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    Ye moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    ke moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
    be moz-extension://85860304-f26f-b04f-bab5-3d1ff713ffc6/background/background.js:31
```

Hopefully that does give you some pointers… 😬

**Comment by sienori** [comment]
Beta versions of Firefox may cause temporary problems. Please check with the release version.
Restarting the browser or reinstalling the extension may fix the problem.

If this does not fix the problem, the IndexedDB is probably corrupted.
Please refer to this page: https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

**Comment by mrdc** [comment]
@sienori Is it safe to reinstall the extension? I mean that no session data will be lost? Because sessions export stopped working I can make the backup.

Using release version of FF 89.0.1 and the same issue.
