### ISSUE TITLE
Cannot open/import last session

### ISSUE THREAD

**Issue by ThisIsToXiN** [sienori/Tab-Session-Manager#755]
I updated my firefox (to 88.0) which required restart of the browser. After that I could only see sessions from ~ a week ago (2021.04.19) in the extension. I got the latest JSON files in the "TabSessionManager - Backup" folder but the extension in the browser does not show them. I tried importing those files, but that does not work.

## Platform information
* Platform (OS): Windows
* Version of browser: Firefox 88.0
* Version of Tab Session Manager: 6.6.0

**Comment by sienori** [comment]
Please try reinstalling the extension. If the problem persists, please refer here:
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
