### ISSUE TITLE
Unsure about the new local backup option

### ISSUE THREAD

**Issue by ngirard** [sienori/Tab-Session-Manager#756]
Heya,

the "local backup option" from the new [release 6.7.0](https://github.com/sienori/Tab-Session-Manager/releases/tag/6.7.0) seems potentially interesting to me, but I couldn't find any details about it.

Would you giving some details ?

Cheers, and as always, thanks for your efforts !

**Comment by sienori** [comment]
See https://github.com/sienori/Tab-Session-Manager/issues/710#issuecomment-826905945
Version 6.7.0 will be available in the store in a few days, so please give it a try!

**Comment by ngirard** [comment]
Aha! Seems juicy... can't wait to give it a try !

That indeed solved the question for me, but you might want to add it to the project documentation.

Cheers, and thanks for your quick reply !
