### ISSUE TITLE
Google sync still not works 100% correctly

### ISSUE THREAD

**Issue by xHurricanex** [sienori/Tab-Session-Manager#759]
3 problems were mentioned in the last weeks with Google sync in TSM:

1) Sign off from Google after PC restart.
2) Sign off from Google after Chrome restart (without PC restart).
3) Sign off from Google after don't-know-what-happens in some time of regular work in Chrome.

The latest update (version 6.7.0) fixed problems 1 and 2.
But problem 3 is still not solved.
I updated TSM today and after successful sign-in (maybe 30-40 minutes or so) I got a floating screen with the request to sign in to Google. I signed in - and that was OK for another 30-40 minutes.

**Comment by sienori** [comment]
Are you using Chrome on only one device?
If so, signing out and signing in again in the settings page should solve the problem.

If you are using Chrome on two or more devices, the first Chrome you sign in to will fix the problem.
The second Chrome you sign in with will still have the problem.

**Comment by xHurricanex** [comment]
I use Chrome on 1 PC (and don't use TSM in other Chrome-based browsers on this PC, only in Chrome) and Android smartphone.
Do you mean that I have not to use Chrome on smartphone so TSM in Chrome PC should work?

Right now I manually signed off and signed in to Google again - let's wait till evening to see how TSM will work.

**Comment by xHurricanex** [comment]
This is evening - everything is fine.
Showed a small gratitude.
Thank you - now TSM is awesome)
