### ISSUE TITLE
mutiple files downloads at backup instead of only one

### ISSUE THREAD

**Issue by sanslash332** [sienori/Tab-Session-Manager#762]
## Short description

On the previous versions (6.6.0 and before) if you turn on the backup at startup option, when you browser starts, the extension downloads one big json file containing all your sessions to backup it. In my case that download is manual, because I preffer with every download choose the destination so the classic "save to" popup appear (chrome / edge) to ask the destination folder.

But, in the new update (6.7.0) instead to create one download with the json file, the extension created one download for each session that I have, so in total, I have more than 150 promts of save...

Is possible restore the previous behabior? to download one big file with all your sessions?

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager version 6.7.0 in chrome or edge.
3. browse in the web, open various windows, closing tabs, etc. To have a few sessions in your extenssion. with 10 or 20 is OK
4. go to tab session manager settings, and turn on the backup function
5. close the browser and re open it
6. see how appear one download for each session you've created.

## Expected result

When you open the browser, only one download appear with one json file containing all your sessions. In previows versions that was the behavior, and if you go to settings / sessions  and push export sessions, you have only one big file. not multiple small files.

## Actual result

After open the broser, you have one download per session.

## Platform information
* Platform (OS): Windows10 64bits 
* Version of browser: chrome Versión 90.0.4430.93 
* Version of Tab Session Manager: 6.7.0

alternative testing environment:
* browser: edge enterprice v88
* tab session manager version: 6.6.0 (with the correct behabior

Thanks!

**Comment by innesst** [comment]
I agree. Same with Chrome 90
The current behavior is very bad and I would much prefer to be able to revert.

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/117261915-e966be80-ae7a-11eb-8bc4-7437c3920866.png)

**Comment by innesst** [comment]
Yes. That box isn't checked. So it's not asking where to save. But it is still downloading hundreds of files at every launch. It used to download only 1 file.

**Comment by Ergobyt** [comment]
PLEASE

Make 

> Renewed local backup option #710
> Supports incremental backups.
> Only sessions that have changed will be saved separately, saving storage.
> https://github.com/sienori/Tab-Session-Manager/issues/710

an OPTIONAL feature.

**Comment by sienori** [comment]
I'll add the individual backup option in the next version. Thanks for the feedback!
![image](https://user-images.githubusercontent.com/29514424/117452939-51063200-af7f-11eb-8fec-b6d465111001.png)
