### ISSUE TITLE
BackUp fails since update to 6.7.0

### ISSUE THREAD

**Issue by SudoNoNo** [sienori/Tab-Session-Manager#764]
## Short description
TSM's backup functions fail since update from 6.6.0 to 6.7.0

## Steps to reproduce
1. 6.6.0 made last backup on April 20th
2. updated to 6.7.0 on April 30th
3. 4 sessions since update to 6.7.0

## Expected result
Saved backups on May 1st, 4th & 5th in folder "TabSessionManager - Backup"

## Actual result
1. Backups May 1st, 4th & 5th missing 
2. Restarting FF does not force 6.7.0 to backup
3. Restarting FF with deactivated / later re-activated extension does not force backup
4. Restarting FF with deactivated / later re-activated backup preference does not force backup
5. Restarting FF with changed / later re-changed location name for backup does not force backup

## Platform information
* Platform (OS): macOS 10.15
* Version of browser: Firefox 88
* Version of Tab Session Manager: 6.7.0

## Additional context
Display of sessions is sometimes wrong. Currently there are 54 to 59 sessions saved while sometimes exactly 30 sessions are displayed when opening window/tab. Once or twice re-opening window/tab does show correct list & number of sessions. But error re-occurs often when opening window/tab at a later moment.

**Comment by sienori** [comment]
In version 6.7.0, backups are saved individually in folders. Are there any files in the "User save" folder?

![image](https://user-images.githubusercontent.com/29514424/116102215-7c6c5f80-a6e9-11eb-9e51-dd4cc4122c31.png)
![image](https://user-images.githubusercontent.com/29514424/116101851-28617b00-a6e9-11eb-9ead-1d032d5c7723.png)


Also, I will add an option to select the backup behavior in the next version. https://github.com/sienori/Tab-Session-Manager/issues/762
![image](https://user-images.githubusercontent.com/29514424/117452939-51063200-af7f-11eb-8fec-b6d465111001.png)


> Display of sessions is sometimes wrong

This will also be fixed in the next version. https://github.com/sienori/Tab-Session-Manager/commit/83a7736959f5873709b4ff8930ef05b5069c48bf

**Comment by SudoNoNo** [comment]
Thanks for your reply. Looking forward to the update.

Your screenshots are from Windows (and Chrome?) – I cannot find these folders in macOS and Firefox.

**Comment by sienori** [comment]
> Your screenshots are from Windows (and Chrome?) – I cannot find these folders in macOS and Firefox.

Backups are saved in `[Download folder]/Tab Session Manager - Backup`.
The download folder can be found in the Firefox settings.
![image](https://user-images.githubusercontent.com/29514424/120099961-3b98b800-c179-11eb-9605-5dda4ec32d2e.png)

**Comment by SudoNoNo** [comment]
> > Your screenshots are from Windows (and Chrome?) – I cannot find these folders in macOS and Firefox.
> 
> Backups are saved in `[Download folder]/Tab Session Manager - Backup`.
> The download folder can be found in the Firefox settings.

Thanks, I know. I just mentioned that because you referred especially to the folder "user save" which is not on macOS/firefox.

BackUp works again. Thanks a lot!

Two small remarks (should I open a new issue for these?):

1. The backup file does not show up in "download history" of Firefox anymore. (I don't use the individual backup. The download history was my kind of control panel to check if backup worked after restart.)

2. The numbers of sessions who are displayed are not mixing up anymore. But the name of the backup file adds one more session than I have displayed. E.g. I have 59 saved sessions displayed after restarting Firefox but the name of the backup file is beginning with "60 sessions".
Q1: Do I miss a session in display?
Q2: Or is the current session after restart added to the 59 already saved sessions when backing up?
Q3: Or is that a issue in indexing?
