### ISSUE TITLE
[warn] background/export: exportSessions() Error: filename must not contain illegal characters (aka "no startup backup")

### ISSUE THREAD

**Issue by CircleCode** [sienori/Tab-Session-Manager#771]
## Short description
until version 6.7.0, startup backup were working as expected
starting from version 6.7.0, startup backup are no more saved.

## (perhaps) useful logs
I get the following logs after startup:
```
[debug] background/backup: backupAllSessions
[debug] background/export: exportSessions() null TSM true
[debug] background/getSessions: getSessions() null null
[debug] background/sessions: getAll() null
[debug] background/sessions: =>getAll() 
Array(31) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
[warn] background/export: exportSessions() Error: filename must not contain illegal characters
```
But since download path is not logged, I am not able to check further.

I could eventually try to run a local version of the extension to use the debugger and see if I can find more clues.

## Platform information
* Platform (OS): arch linux
* Version of browser: firefox nightly 90.0a1 (2021-05-10) (64-bit)
* Version of Tab Session Manager: 6.8.0

**Comment by sienori** [comment]
What is the language of Firefox?

**Comment by CircleCode** [comment]
firefox is in english, but the OS is in french

**Comment by CircleCode** [comment]
> I could eventually try to run a local version of the extension to use the debugger and see if I can find more clues.

I was trying to load TSM as temporary addon, but since this is triggered at startup, I do not know how to reproduce the issue in a temporary addon…

**Comment by sienori** [comment]
What is the date format in TSM settings?
![image](https://user-images.githubusercontent.com/29514424/117673223-9035bc80-b1e5-11eb-89fd-ea2f4aaf83b4.png)

Also, does the session export work?
![image](https://user-images.githubusercontent.com/29514424/117673591-e276dd80-b1e5-11eb-8b4f-dbd464b66076.png)

> I was trying to load TSM as temporary addon, but since this is triggered at startup, I do not know how to reproduce the issue in a temporary addon…

To install it as a persistent add-on:
1. Run `npm run build`
2. Rename `dist/tab_session_manager-for-firefox-6.8.0.zip` to `dist/tab_session_manager-for-firefox-6.8.0.xpi`
3. Drag and drop it into firefox

**Comment by CircleCode** [comment]
> What is the date format in TSM settings?

date format is `YYYY.MM.DD HH:mm:ss`

> Also, does the session export work?

it works both in `/tmp` and in `/home/me/Téléchargements/TabSessionManager - Backup`

> To install it as a persistent add-on…

Will try this

**Comment by CircleCode** [comment]
> To install it as a persistent add-on…

Is there a way to build the extension not minified?

**Comment by sienori** [comment]
Thanks for the research! I've fixed it. https://github.com/sienori/Tab-Session-Manager/commit/267b9998dc7316a5f10274fe9a555af38a45dc51

**Comment by CircleCode** [comment]
Thanks for the quick fix!
