### ISSUE TITLE
Tab restore load problem ( replaced.js replaced.css )

### ISSUE THREAD

**Issue by uberkael** [sienori/Tab-Session-Manager#784]
## Short description
After restoring a session most of the tabs (but not all)  show an intermediate page but does not load the original page.
Reloading the page does not help.
Reinstall the extension and restore the sessions does not fix the problem.
Also, an error is shown in the console.
![image](https://user-images.githubusercontent.com/1783926/119357385-cbd18b80-bca7-11eb-88b2-db7f4a2aca79.png)
ERR_FILE _NOT_FOUND
chrome-extension://iaiomicjabeggjcfkbimgmglanimpnae/replaced/replaced.css

## Steps to reproduce
restore a normal session

## Expected result
Restored tab load normally

## Actual result
An intermediate page in most of the tabs showing "Copy URL" and the original URL.
![image](https://user-images.githubusercontent.com/1783926/119357060-6da4a880-bca7-11eb-84f7-9b32828bbdaf.png)
Reload the page does not fix it, copying the link and load the URL does (obviously).

## Platform information
* Platform (OS): Windows 10
* Version of browser: Chrome 91.0.4472.69
* Version of Tab Session Manager: 6.8.1

## Additional context
Looking at the code there is not replaced.css and line 2 of /src/replaced/replaced.js shows 
`import "./replaced.scss";`
I think it was moved to replaced.scss on 908a08c8705be60478093ba3950ddf3f20e9d9a9

**Comment by Sife-ops** [comment]
Same exact problem on arch with vanilla chrome.

**Comment by TUstudents** [comment]
Exact same problem. Tabs are not restored, as the intermediate page has a problem to load "replaced.css". No way to rollback extension to a previous version in Chrome webstore, no way of adding a dummy css file to the extension folder as Chrome protection will disable it immediately.

CSS file is loaded in replaced.html at line 6 `    <link rel="stylesheet" type="text/css" href="replaced.css">`

Platform information
Platform (OS): Windows 10
Version of browser: Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
Version of Tab Session Manager: 6.8.1

**Comment by sienori** [comment]
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/03357e4d3763d045575d8ab4cadbd5f4b58c62d7
This was due to a specification change in Chrome 91.  Thank you for the report!

**Comment by Sife-ops** [comment]
Awesome and thank you!!!

**Comment by uberkael** [comment]
Great, Good Work!
