### ISSUE TITLE
Russian version have broken UI buttons positions

### ISSUE THREAD

**Issue by Oplkill** [sienori/Tab-Session-Manager#79]
Russian version have broken buttons positions, like button "Open"(Открыть on Russian) moved down or button "Save" at the right down position of window moved down too
![fnpntwi 1](https://user-images.githubusercontent.com/7405630/33388804-f875e5b0-d541-11e7-851e-8ff78c27e591.png)

**Comment by sienori** [comment]
I will fix it.

**Comment by sienori** [comment]
I fixed it in version 1.7.0.
