### ISSUE TITLE
Support Window Naming feature

### ISSUE THREAD

**Issue by chungr** [sienori/Tab-Session-Manager#794]
**Is your feature request related to a problem? Please describe.**
Both Chrome and Edge support a feature called "Name Window" which allows you to assign a titlebar name to a group of tabs.  This name is not saved by Chrome or Edge if a crash occurs, it would be great if Tab Session Manager saved them.

**Describe the solution you'd like**
Add an option that for all saved sessions, window names are saved and restored.

**Describe alternatives you've considered**
Currently, I have to manually rename all of the windows anytime Edge or Chrome crash, which takes a considerable amount of time.

**Additional context**

**Comment by sienori** [comment]
The WebExtensions API does not yet support window naming in Chrome. I will support it when the API is released. #770
