### ISSUE TITLE
No reply in discussions? Possible bug and feature requests

### ISSUE THREAD

**Issue by rebop** [sienori/Tab-Session-Manager#796]
Issue: When opening a tab group (session) the focus is on the last tab of the group. I would like it to be on the first tab. Can that be changed? I am a bit of a geek so happy to open the hood and tweak if that can be done.

Question: Where are these stored? Simply cannot find them. I keep multiple computers in sync by copying the "Session Manager" Session folder so I always am in sync now, but cannot find where these are stored. Nothing at all in browser-extension data.

Suggestion: Would be nice to change the highlight color. Not the theme, just the blue to my choice to better match my overall themes. Small stuff.

Bigger stuff suggestion: I REALLY miss having a popup open when opening the browser that asks which Session to open or none. So handy in Session Manager.

Thanks!

~Bob

**Comment by sienori** [comment]
Sorry for the late reply. I replied to the discussion. https://github.com/sienori/Tab-Session-Manager/discussions/782
