### ISSUE TITLE
Session not saved to old session

### ISSUE THREAD

**Issue by Terrijoo** [sienori/Tab-Session-Manager#798]
## Short description

Don't know if this is a bug or if it's intended, but if you open new tabs in an existing and opened session, it won't save to the existing session but instead creates a new "auto saved" session, when you close the window or Chrome.
Just asking, because "Smart Sessions" for example does it, but it lacks a few things I really like about TSM.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Save a window with e.g. 1 tab as session
4. Open the newly saved session
5. Add a new tab to it
6. Close the window/Chrome

## Expected result

The session to be saved on the existing one, so adding the new tab onto the old session.

## Actual result

It creates another auto saved session and won't save onto the existing one.
Here's the output from the debug logs if I close the existing session with a new tab:
![image](https://user-images.githubusercontent.com/5391946/120309791-ef16bf00-c2d5-11eb-97ec-ae25b4203355.png)
What seems strange there is the log for "getSessionsByTag" that always states "temp" as a tag, even though I gave it my own tag?

## Platform information
* Platform (OS): Windows 10
* Version of browser: Chrome 91.0.4472.77
* Version of Tab Session Manager: 6.8.2

## Additional context

If it's actually intended, it'd be nice to have an option for that to be possible.

**Comment by VilleSuominen** [comment]
I would also like to hear if this is intended. I would love to have an option to "update session" instead of always creating new ones.

**Comment by trevor87** [comment]
> I would love to have an option to "update session" instead of always creating new ones.

I am looking for the same option. All I could find is that currently you seem to be able to do this manually using "Replace with current session".

**Comment by EricHedden** [comment]
Confirmed, 
Auto save is broken as described on

Windows 7
Firefox 89.0 (64bit)
Tab Session Manager 6.9.0


However, 
Auto save DOES work on

Windows 7
Chrome 92.0.4515.131 (official build) (64-bit)
Tab Session Manager 6.9.0

**Comment by sienori** [comment]
In version 6.12.0, I implemented Tracking Session feature! #890

You can set a session as a tracking session from the session menu. When you open a tracking session, changes in the window are automatically reflected in the session. This allows for efficient workspace switching!

![session menu](https://user-images.githubusercontent.com/29514424/166821091-8ff657bd-dbfc-49e1-ac23-974c6d313e54.png)
![tracking session](https://user-images.githubusercontent.com/29514424/166821237-f4e1eece-0bda-4c50-bb63-db6280ba9329.png)

https://github.com/sienori/Tab-Session-Manager/releases
