### ISSUE TITLE
How do I restore sessions from an IndexDB backup?

### ISSUE THREAD

**Issue by anga83** [sienori/Tab-Session-Manager#799]
Hi there!

Today, Chrome forced me to reinstall the extension by saying the extension was damaged. After reinstalling all saved sessions are gone.

I was able to recover the IndexDB folder of the extension containing the *.log and *.ldb files from my TimeMachine backup. However, unfortunately, the extension window remains empty. 

Is there a way to reimport those sessions?

Best regards!

PS: I do have a manual backup json file, but that's a bit dated. So, I'd prefer to somehow "link" the storage files rather than my exported file.

**Comment by freemedom** [comment]
C:\Users\ \AppData\Local\Google\Chrome\User Data\Profile 1\IndexedDB\chrome-extension_iaiomicjabeggjcfkbimgmglanimpnae_0.indexeddb.leveldb
The URL data is here

is a leveldb database

**Comment by sienori** [comment]
Unfortunately, we have not found a way to recover the session from the DB file.  https://github.com/sienori/Tab-Session-Manager/issues/421
I highly recommend enabling local / cloud backup.
