### ISSUE TITLE
Filter of sessions does not work properly with user saved sessions

### ISSUE THREAD

**Issue by ghmv** [sienori/Tab-Session-Manager#8]
After selecting "user saved" filter above the session list, all auto saved sessions stay listed below the user saved ones. When no user saved session exists, the list looks the same as all or auto saved lists, only scroll bar is missing and no session can be selected (edited, deleted etc.).

**Comment by sienori** [comment]
I think it is due to a bug in Firefox (ver.57?).
It often happens when it is stored in other tool in the toolbar.
