### ISSUE TITLE
"Replace with current window" bug

### ISSUE THREAD

**Issue by TahsinTariq** [sienori/Tab-Session-Manager#800]
## Short description

On an existing save, If replace with current window is selected, the TSM tab is also included in the newly saved session.
I've tried adding the TSM address to the "URL list to ignore when saving session" but that doesn't work.
## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Open a few websites and save session
4. Go to saved session and click "Menu" then "Replace with current window"

## Expected result

![image](https://user-images.githubusercontent.com/62146852/120709200-5d2dd280-c4de-11eb-9511-dbb4bdc1ae14.png)

## Actual result

![image](https://user-images.githubusercontent.com/62146852/120709155-51daa700-c4de-11eb-8f7c-87718510f480.png)

## Platform information
* Platform (OS): Windows, several Linux distros
* Version of browser: Firefox Latest
* Version of Tab Session Manager: 6.8.2

## Additional context

 - mild annoyance every time I save a session

**Comment by sienori** [comment]
Ignoring URLs was not reflected in "Replace with current window" and "Replace with current session".
I fix it in version 6.9.0. https://github.com/sienori/Tab-Session-Manager/commit/b86ee86217f3a6eab026d21fe23007f14e9a5683
Thanks!
