### ISSUE TITLE
Lost all my saved sessions 

### ISSUE THREAD

**Issue by gaveer** [sienori/Tab-Session-Manager#804]
## Short description

closed browser and boof
## Platform information
* Platform (OS):  Windows, 10
* Version of browser: Chrome Latest
* Version of Tab Session Manager: 6.8.2

**Comment by gaveer** [comment]
I had long list of sessions saved into my extension , and everything gon , how i can recover them

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/120940513-509bbb00-c726-11eb-9f2d-e34cde66b75d.png)

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/120941421-5c3db080-c72b-11eb-9d18-4168f33cdd0a.png)

**Comment by gaveer** [comment]
[000017.zip](https://github.com/sienori/Tab-Session-Manager/files/6605077/000017.zip)

**Comment by mYnDstrEAm** [comment]
Do you have any backups of the folder? I think on Windows you can sometimes right-click the file or folder and click Restore previous versions to restore prior versions. Make sure to copy the whole Chrome folder elsewhere before doing/restoring anything.

**Comment by freemedom** [comment]
C:\Users\  \AppData\Local\Google\Chrome\User Data\Profile 1\Local Extension Settings\iaiomicjabeggjcfkbimgmglanimpnae
This folder should not actually have the required URL data

C:\Users\  \AppData\Local\Google\Chrome\User Data\Profile 1\IndexedDB\chrome-extension_iaiomicjabeggjcfkbimgmglanimpnae_0.indexeddb.leveldb
The URL data is here，But you can see that the data here has disappeared...

I finded the results for hours of search (since I foolishly backtracked on the Chrome version)

**Comment by freemedom** [comment]
C:\Users\ \AppData\Local\Google\Chrome\User Data\Profile 1\Local Extension Settings\iaiomicjabeggjcfkbimgmglanimpnae
You can open these files directly with a text editor, and you'll find that most of them are RemovedQueue (which I guess is the key of levelDB).

removedQueue":["cf994135-c4a1-4acb-abda-3b25dbf5bd84","df61a578-eaa6-44e9-9af6-f4d8b37de4fe","7a19c204-f040-4673-b19e-a823c61d8a74","2d427b7f-5ab6-4648-8402-aede8f3480e9","debc09aa-8f00-499a-a9d1-27dac05ef8ca","b56a561e-4fb6-44cc-ae5f-

**Comment by freemedom** [comment]
In addition, these LevelDB folders seem to be impossible to decrypt (I use Plyvel to decrypt, Complains https://stackoverflow.com/questions/41587347/can-you-read-leveldb-data-without-the-proper-comparator), you can directly use a text editor to open, Some English words and numbers are normal, but most of them are garbled

**Comment by freemedom** [comment]
The removedQueue should be the key that holds all manually deleted sessions that can be recovered
