### ISSUE TITLE
"Tab Lazy loading" option no longer works in Edge

### ISSUE THREAD

**Issue by gskoczylas** [sienori/Tab-Session-Manager#805]
# Description

I've been using Tab Session Manager with Microsoft Edge, and it's worked fine for months, but recently I've been having a strange problem when opening a saved session. Basically, when I now click "Open" to restore a previously saved session, it loads the active tab correctly, but all other tabs don't load fully and show the tab title plus its URL and copy button in the main window. The URL itself shows up as _extension://jkjclfiflhpjangefhgfjhgfbhajadk/replaced/index.html?state=redirect&title=...._ (partial URL).

I've tried disabling all other extensions, but that doesn't help. I had to disable this option - hopefully temporarily as it is very useful.

## Platform information

* Platform (OS): Microsoft Windows 10 Ent. ver. 20H2
* Version of browser: Edge
* Version of Tab Session Manager: 6.8.1

**Comment by sienori** [comment]
This problem has been fixed in version 6.8.2. https://github.com/sienori/Tab-Session-Manager/issues/784
It will be available in the Edge Store within a week.
