### ISSUE TITLE
All Sessions are lost. Again

### ISSUE THREAD

**Issue by mrdc** [sienori/Tab-Session-Manager#814]
Hi,

It happened again: all sessions are lost.

Firefox 89.0.1, TSM 6.8.3.

Today I've noticed that there are only 170 sessions of ~350 are shown in TSM, I was able to save new windows - at least they showed in TSM. Auto-save stopped working.
I've tried `Session -> Export sessions`, but after clicking the export button nothing has happened. Have tried advice from this issue: https://github.com/sienori/Tab-Session-Manager/issues/754#issuecomment-826577695:
```
Restarting the browser or reinstalling the extension may fix the problem.
If this does not fix the problem, the IndexedDB is probably corrupted.
```
Enabled debug in TSM (see errors below). After browser restart the same 170 sessions, no more no less.
So, I've decided to reinstall the TSM (made the backup of 1782160246ssensosi.sqlite). After TSM reinstall and FF close/open I've received: `Error - IndexedDB is not available in your browser.`
Used 1782160246ssensosi.sqlite backup, changed the `origin` value.
Checked 1782160246ssensosi.sqlite integrity - DB is in perfect condition according to official sqlite3 tool...
Again opened FF - no more `Error - IndexedDB is not available in your browser.`, but now I see only some random 30 sessions (not the last 30, not the first 30, not the middle 30).
 
The question is: how is that possible that sqlite fails so often for saving sessions, while it's being widely used for huge amount of apps without issues? If it fails so often, then, maybe, it's a good idea to change a data structure in DB, so it's more robust and not dies by a small error. 

We need info about data structure that TSM uses to store sessions - I see data blobs without any extra info which can be used for recovery.
Based on that info I can try to recover some data. The 1782160246ssensosi.sqlite DB itself is not corrupted and passes all checks made by sqlite3.

```
[error] background/sessions: getAll() 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
​
bubbles: true
​cancelBubble: false
​cancelable: true
​composed: false
​currentTarget: null
​defaultPrevented: false
​eventPhase: 0
​explicitOriginalTarget: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​isTrusted: true
​originalTarget: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​returnValue: true
​srcElement: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​target: IDBRequest { error: DOMException, source: IDBObjectStore, readyState: "done", … }
​timeStamp: 305027
​type: "error"
​<get isTrusted()>: function isTrusted()
​<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }

```

**Comment by mrdc** [comment]
Some update concerning this: `Again opened FF - no more Error - IndexedDB is not available in your browser., but now I see only some random 30 sessions (not the last 30, not the first 30, not the middle 30).`
In console I see this: 
```
[error] background/autoSave: updateTemp() TypeError: n is undefined
    $ moz-extension://a65d2b16-26ab-ac41-87de-06015e5cc1b3/background/background.js:31
    De moz-extension://a65d2b16-26ab-ac41-87de-06015e5cc1b3/background/background.js:31
    Se moz-extension://a65d2b16-26ab-ac41-87de-06015e5cc1b3/background/background.js:31
    Ae moz-extension://a65d2b16-26ab-ac41-87de-06015e5cc1b3/background/background.js:31
```

**Comment by mrdc** [comment]
I was able to recover my sessions from the extension's db. Actually, corruption happens not on db level, but higher - the extension or browser. When a "few bytes" are corrupted the whole db with sessions become invalid for the extension (browser), because it expects no errors in saved data as data is binary representation of an object which is then used to restore sessions. So, simple saying - yes, it's possible to make sessions protected from corruption, but it requires changes to the extension.

**Comment by mrdc** [comment]
@sienori 
Any ideas?

**Comment by sienori** [comment]
Following the wiki and deleting the `storage` folder may solve.
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
If even one of the files in the storage is corrupted, it will affect the TSM.

I highly recommend enabling local / cloud backup.
