### ISSUE TITLE
Losing sessions, import does not work

### ISSUE THREAD

**Issue by c-holtermann** [sienori/Tab-Session-Manager#829]
## Short description
All sessions get lost regularly. They stay for some minutes. Then get lost. Going back in history in a running session brings them back. Closing firefox leads to permanent loss. Exporting works. Importing does not add sessions.

## Platform information
* Platform (OS): Windows 7
* Version of browser: firefox 90.0.2 (64bit)
* Version of Tab Session Manager: 6.8.3

**Comment by c-holtermann** [comment]
Like this the extension is unusable and while I like the idea and need the extension for my intended workflow I cannot find a workaround at the moment.

**Comment by sienori** [comment]
The Indexed DB may be corrupted. Please refer to the following solutions.
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error

**Comment by c-holtermann** [comment]
Thank you for your reply. I tried that. It did not solve my case. After [refreshing firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and reinstalling this extension it started working again. Unfortunately refreshing also destroyed the backup folder which I put in the same directory by just changing the name. Firefox was more thorough cleaning up then I had expected.
