### ISSUE TITLE
Feature: Visually separate user and auto-saved sessions

### ISSUE THREAD

**Issue by martixy** [sienori/Tab-Session-Manager#830]
**Is your feature request related to a problem? Please describe.**
It's really hard to tell user sessions from auto-saved.

**Describe the solution you'd like**
Put user sessions and auto-saves in a separate location in the UI.

**Describe alternatives you've considered**
n/a  (Yes I am aware of the existing dropdown, it is not a viable alternative.)

**Additional context**
I got this extension because it can save tab groups (my favourite new feature), but the UI is very... obstructing.
(I am using the extension in Chrome.)

**Comment by skalfate** [comment]
I second this request. :heart:
