### ISSUE TITLE
Tab with local File tab is not restored

### ISSUE THREAD

**Issue by KlausiD** [sienori/Tab-Session-Manager#836]
## Short description
A local file that is open in a tab is not restored, when i start the browser again.

## Steps to reproduce
1. Start browser 
2. open File like d:\log.html
3. close browser
4. start browser again

## Expected result
the tab with d:\log.html is not restored!
result:
log.html
file:///D:/Vhdl_projekte/fd_mastercpu_f1/debug_kompatible/report/log.html
URL kopieren
Diese Seite kann von Tab Session Manager nicht geöffnet werden.

## Platform information
* Platform (OS): win10
* Version of browser:  FF 90.0.2
* Version of Tab Session Manager:  6.9.0

**Comment by sienori** [comment]
Due to the limitation of WebExtensionsAPI, the extension cannot open local pages. #234
