### ISSUE TITLE
Option to open session in tabs in the current window without overwriting the window

### ISSUE THREAD

**Issue by VampiroNocturno** [sienori/Tab-Session-Manager#84]
I think it can be useful.

**Comment by sienori** [comment]
I will think about it.

**Comment by Jbowman57** [comment]
The old sessions manager gave the ability to append the current session (open tabs in the current window), open a session in a new window, leaving the current session open, or replace the current session.  This can be helpful when comparing and possible merging sessions.

**Comment by sienori** [comment]
I added three menu options In ver1.9.0.
- Open in new window
- Open in current window
- Add to current window
