### ISSUE TITLE
On Chrome reopen, JSON files repeatedly try to download, file explorer opens and must be closed.

### ISSUE THREAD

**Issue by charlesdaigle** [sienori/Tab-Session-Manager#840]
## Short description

Reopening chrome causes a JSON file with some of the following below titles to repeatedly and automatically download:

```
2021-08-11_` 21-26-20 - The Connectivity Standards Alliance Unveils Matter, Formerly Known as Project CHIP - Business Wire #winClose [*INSERT MY PC NAME HERE*]- [265cdfff-

2021-08-11 21-25-50 - Fwd- Mask Mandate and Vaccine Verification - [INSERT MY EMAIL ADDRESS HERE] - Gmail #browserExit #CND-PC - [8352169c-1b2d-4bd5-819d-d89f9cb
```

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Close 2 windows of Chrome
4. Reopen chrome (opens 2 windows)
5. Bug should occur now.

## Expected result

Normal browser usage.

## Actual result

JSON file dialog (Windows default)

## Platform information
* Platform (OS): Windows 10
* Version of browser: 92.0.4515.131
* Version of Tab Session Manager: 6.9.0

## Additional context

None for now. Please let me know if you need any other information/log files or anything.

**Comment by sienori** [comment]
If the `Save backup` option is enabled, json files will be downloaded when the browser is started.
![image](https://user-images.githubusercontent.com/29514424/129383429-ca960e23-979e-4141-8ad2-c8c026e275e6.png)

**Comment by charlesdaigle** [comment]
Thanks -- I had this option enabled without setting a default save location.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
