### ISSUE TITLE
TSM causes (huge) CPU usage whenever a new tabs opens with many tabs open

### ISSUE THREAD

**Issue by ganego** [sienori/Tab-Session-Manager#844]
## Short description
TSM causes CPU usage whenever a new tabs opens. Since I have many tabs open this uses 25% CPU (1 full core!) for ~7 seconds.  
So maybe give me an option to not write the session file every time I open a new tab, since I guess this is what you do.

## Steps to reproduce
1. Start browser with clean profile
2. Install Tab Session Manager
3. Open session with many tabs
4. Open about:performance
5. Open new tab
6. Observe CPU uses in about:performance as well as TaskManager

## Expected result
Don't clog my CPU.

## Actual result
Each Spike is a new empty opened tab.

![image](https://user-images.githubusercontent.com/4750881/129382034-e56a0544-e314-4bb9-b858-b36d876445a8.png)

## Platform information
* Platform (OS): Windows
* Version of browser: FF90
* Version of Tab Session Manager: 6.9.0

**Comment by sienori** [comment]
If the following options are enabled, TSM will save the session in the background every time a tab is opened.
- `Save the session when window was closed`
- `Save the session when exiting browser`

Disabling these options will reduce the CPU usage.

**Comment by ganego** [comment]
> If the following options are enabled, TSM will save the session in the background every time a tab is opened.
> 
>     * `Save the session when window was closed`
> 
>     * `Save the session when exiting browser`
> 
> 
> Disabling these options will reduce the CPU usage.

But I don't want to disable these. Of course I want to save the session when I exit the browser or close a window, it makes no sense to disable them to not save the whole session every time I open a tab.
I just don't want it to save whenever I open a new tab.
Those two things have nothing to do with each other.
