### ISSUE TITLE
Press Enter to Open First Suggested Tab Session  

### ISSUE THREAD

**Issue by guy-who-googles** [sienori/Tab-Session-Manager#849]
**Is your feature request related to a problem? Please describe.**
After opening Tab Session Manager, I start typing to search to for the session I need. Intuitively, I press `Enter` to open the first suggested session. Currently, this selects the first suggested session, but doesn't open it, so I have to reach for my mouse.

**Describe the solution you'd like**
To be able to press `Enter` to open the first suggested session. It could also make sense to add `Tab` and `Shift+Tab` to move to the next/previous suggestion.

**Describe alternatives you've considered**
No alternatives that I can think of outside the default and suggested behavior.

**Comment by sienori** [comment]
This is already implemented.
Input search words and press `Enter` to focus on the first session.
Use the `up`/`down` keys to move the focus, and `Shift+Enter` to open a session.

**Comment by guy-who-googles** [comment]
Related questions:   
* Do you have thoughts on exposing these (focus on next session, move focus up, move focus down, and open session) in the Keyboard Shortcuts section?
* If not, can the default be documented somewhere, i.e. wiki?
