### ISSUE TITLE
No list of current saved sessions since April, 2021

### ISSUE THREAD

**Issue by karbonbee** [sienori/Tab-Session-Manager#851]
Can't find an answer to this anywhere. Running latest Firefox on a Mac OS 10.13.x - the last couple of Firefox updates have erased my old profile, creating a new one, so I have had to constantly start from scratch over the last couple of months. Syncing FF restores previous add-ons, etc, but not the previous settings for them. Tab Session Manager asks in it's settings for a designated save folder in the Downloads folder - which I've done, repeatedly - however since April 2021 no new sessions are being saved in that folder - or any other place on my computer that I have been able to find. So once again with the Firefox update to 91.0.1 (64-bit) today, I've once again lost all of my sessions from yesterday. Days and days of research and organization that I now have to try to track down... once again. No option I can find to import anything current. Very frustrating!! Is there another place where previous sessions might be stored? If there is anymore information you need me to provide, please let me know. Thanks.

**Comment by sparc** [comment]
same problem after FF upgrade

**Comment by sienori** [comment]
Sorry for the inconvenience. 🙇 🙇 
In previous versions, there was a possibility of session loss when the storage capacity was low. This will be fixed in the next update. #860 
It is recommended to enable local backup and Cloud Sync to prevent session loss.
