### ISSUE TITLE
Sessions are not deleting after reaching the maximum (same as bug 233)

### ISSUE THREAD

**Issue by Hub-O-Gits** [sienori/Tab-Session-Manager#853]
Addon = v6.10.0
Firefox = v91.0.1 x64 Release
OS = Windows 7 SP1 x64

Issue: Old sessions are not being pruned/deleted.
Same or similar to previous closed bug report: #233

Current stats (note that I have it configured to save the last 10 sessions for each type.):
- \"Auto Save - Browser exited" --> `160 files (103 MB)`
- \"Auto Save - Regularly" --> `1,465 files (989 MB)`
- \"Auto Save - Window closed" --> `100 files (57.1 MB)`
- \"User Save" --> (_contains imported sessions that were deleted within the app, but are still present_)

**Comment by anishmittal2020** [comment]
@sienori I am facing the same issue on Ubuntu

**Comment by sienori** [comment]
You seem to be talking about files that are backed up. 
The `Maximum number saved` option controls the number of sessions on the extension. It has no relation to backups.

Due to API limitations, it is not possible to control the number of backup files. If necessary, you can manually delete past backups.

**Comment by Hub-O-Gits** [comment]
Okay, I changed the wording above to indicate that these are session **backups** rather than sessions... That distinction doesn't really address my point though, does it - which is about uncontrolled data output. And your "invalid" label is rudely false as well. "Invalid" would imply that there isn't an actual issue, when clearly there is. And you acknowledge that there is...

So you're saying there's no way that an extension can delete files it creates itself? Either in or outside of the API?
