### ISSUE TITLE
Can't import large Session Buddy export

### ISSUE THREAD

**Issue by miyakoj** [sienori/Tab-Session-Manager#861]
## Short description
I exported one session from Session Buddy that has 68 tabs. When I attempt to import it into Tab Session Manager, I always get a "Read failed" error. I checked both Sessions and Windows in the show bar.

## Steps to reproduce

1. Open Tab Session Manager settings.
2. Click "Sessions".
2. Browse for a Session Buddy export file.

## Expected result
The import will be successful.

## Actual result
![image](https://user-images.githubusercontent.com/19511435/132082394-f19b932a-0698-4f51-ac8c-0885cd65ab85.png)
![image](https://user-images.githubusercontent.com/19511435/132082398-373d2dd0-b44d-47d7-9a4e-424660a2ec8b.png)

## Platform information
* Platform (OS): Windows 10
* Version of browser: Firefox 91.0.1
* Version of Tab Session Manager: 6.10.0

**Comment by sienori** [comment]
Did you export as described in this article? Don't forget to check `**Sessions** and **Windows**.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-How-to-import-sessions-from-other-extensions

**Comment by andrey-gpe** [comment]
> 
> 
> Did you export as described in this article? Don't forget to check `**Sessions** and **Windows**.
> https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-How-to-import-sessions-from-other-extensions

Hi, I did export EXACTLY as described in this article and I have the same issue.  Windows 10 Pro, Firefox 91.0.2 (64-bit)

I tried both selected and all sessions:

![SessionBuddy1](https://user-images.githubusercontent.com/56980952/132738785-0028c66c-fc8a-437b-978e-e0bb8b4c3457.jpg)

![SessionBuddy2](https://user-images.githubusercontent.com/56980952/132738798-0957d727-4ac8-4a59-9655-ebed1f49cb76.jpg)


Thanks.

**Comment by sienori** [comment]
Can you share your session buddy's file?
Please send it to my email. sienori.firefox@gmail.com
(Of course, I will be very careful with your privacy)

**Comment by andrey-gpe** [comment]
OK, done.  Thanks.

**Comment by sienori** [comment]
Thanks! This will be fixed in the next update. https://github.com/sienori/Tab-Session-Manager/commit/e3179ca3c1aecea625918314673bd19baaa7743b
