### ISSUE TITLE
Can't save sessions

### ISSUE THREAD

**Issue by martixy** [sienori/Tab-Session-Manager#866]
## Short description
Clicking save button does nothing.

## Steps to reproduce
1. Click save button
2. ...

## Expected result
Sessions saved

## Actual result
Literally nothing

## Platform information
* Platform (OS): Win10 v2004
* Version of browser: Google Chrome	93.0.4577.63 (Official Build) (64-bit) (cohort: Stable)
* Version of Tab Session Manager: Version 6.10.1

## Additional context
Not sure what other information I can give. Extensions simply fails to work for me.
Installed it once because of tab group support and managed to save 1 session a couple months ago. Now it just fails to work.

**Comment by sienori** [comment]
Are you working in an incognito window? You need to disable the Save private window option.
![image](https://user-images.githubusercontent.com/29514424/135763176-e2a616fd-2e69-4966-b1c5-7b64d27d4ef4.png)

If this is not the case, try reinstalling the extension.

**Comment by martixy** [comment]
* Not incognito.
* Reinstalling did not help.
* Disabling Save tab groups extension did help.

**Comment by bezdeneg** [comment]
Very often, every other time, sessions are not saved. I always open a lot of tabs and windows (from 10 windows and from 200 tabs). There is always enough memory, I check.
Automatically saves, including when there are many windows and tabs.
And on request, in manual mode - every other time!
windows 10/32Gb RAM.

**Comment by jmcd040** [comment]
2021-11-24 I have exactly the same problem as martixy. Reinstalling seems to have worked. If it fails again I'll add a note.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
2022-2-21 same problem again on chrome

**Comment by merlinpimpim** [comment]
Hi,
Without  "save tab group" checked everything is ok.
With "save tab group" checked the session can't be saved (Save Tab Groups for Tab Session Manager is installed and activated):
![p2NtumQmZY](https://user-images.githubusercontent.com/113300765/189537098-3d54177f-e85e-4bbd-81e5-755551b561ce.png)

**Comment by sienori** [comment]
@merlinpimpim Perhaps this issue has been resolved. #981
