### ISSUE TITLE
Tabs are opened in reverse order due to other add-ons

### ISSUE THREAD

**Issue by Urhixidur** [sienori/Tab-Session-Manager#87]
Tab Session Manager chokes upon trying to reload a session that includes tabs open to something else than http:// or https:// pages, such as a file:/// or about:config tab. I haven't even tried ftp:// tabs. It will load the tabs up to the first "incorrect" one and stop then and there.

**Comment by sienori** [comment]
Are you using version 1.6.1?
In this version, pages that can not be opened are replaced.
Processing should not stop.

**Comment by Urhixidur** [comment]
Yes, 1.6.1 is the current version. If this was upgraded very recently, the problem could have occurred under 1.6.0 and TSM upgraded meanwhile. I'll do a test.

**Comment by Urhixidur** [comment]
Indeed, 1.6.1 now loads the tabs with a "This page can not be opened by Tab Session Manager" message (moz-extension:// loads correctly). Better than before by far.

However, my tabs are re-opened in reverse order! This is most probably because of another extension, "Open Tabs Next to Current". Maybe TSM should detect it and work around it by either temporarily desactivating it or by opening the tabs in reverse order.

It's tricky: my session has two windows, and the first window did not have its tabs reversed. Pinned tabs (on the first window) are also safe. Let me run some more tests.

**Comment by Urhixidur** [comment]
All right, here's how it seems to go when "Open Tabs Next to Current" is also present:

a) Pinned tabs open in the correct order.
b) If there are just one or two non-pinned tabs, they open in the correct order.
c) If there are three or more non-pinned tabs, they open in reverse order.

Until this is fixed, I'll have to remember to turn "Open Tabs Next to Current" off before shutting Firefox down. Ugh.

**Comment by ooofest** [comment]
@Urhixidur Are you possibly thinking of the All Tabs Helper add-on?  That has "Open Tabs Next to Current," not this add-on (i.e., Tab Session Manager).  It also has the tab list, pinned tabs concept, etc. that you mentioned.

**Comment by Urhixidur** [comment]
@ooofest No, I did not have All Tabs Helper added. It's a nice add-on for navigating one's tabs, but it has nothing to do with where a new tab gets added. Pinned tabs are built-in, it's not something added by an add-on.

**Comment by ooofest** [comment]
Actually All Tabs Helper for WebExtensions includes an option to open new tabs next to the current one (at least, in its latest form) - outside of an about:config option, I was not aware of that being exposed in the v57 UI (hence, my question).

**Comment by sienori** [comment]
I fixed that tab opens in reverse order. https://github.com/sienori/Tab-Session-Manager/commit/1b68e8753f08e74691844e4935d9a6d59e70ff6c
I think that this problem is solved in the latest version.

**Comment by Urhixidur** [comment]
Yes, I can confirm that the "Open Tabs Next to Current" add-on no longer screws up tab order upon session restoration. Great work!
