### ISSUE TITLE
Importing sessions from old Firefox installation

### ISSUE THREAD

**Issue by SummerShades** [sienori/Tab-Session-Manager#874]
Hello, Yesterday, my Firefox (FF) installation refused to play any audio.  After over an hour of trying numerous attempts to fix this, I ended up having to uninstall then install a new copy of FF.  I checked to ensure that TSM had backed up sessions to both the computer and Google Drive before I uninstalled.  I installed the new copy of FF, with the add-ons that were previously installed (add-ons automatically installed as I signed in to FF).  I went to import the previous session of TSM but the back ups are nowhere to be found, including on Google Drive or the Downloads folder of FF.  I have read through your Issues forum.  There is nothing in the getAll lines of Console tab of the Debugging pages of the previous profile, and only the new sessions in the getAll lines of the current Console tab.  The only backups in FF's Downloads folder are for the new profile.  When I look inside the "Old Firefox Data" folder (the folder which FF automatically created when I uninstalled it), and look under the Storage > Default folder, I see that there is a ssensosi.sqlite file under one of the UUID folders.  I presume that this contains the previous FF installation's sessions' data that TSM uses.  If I am correct, how can I transfer this to the new profile's storage folder for TSM.  I read [https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error](url) but this is only for re-indexing, and not replacing the sessions data.  If I am incorrect, then please could you advise how I can import the sessions data from the old installation?  Note that the Previous sessions backup from FF doesn't help as it only saves the last session, so this is simply the last few tabs from when I was trying to fix the audio loss.
Thank you.

**Comment by RafaelLinux** [comment]
Curiously, I just asked the same  yesterday in https://github.com/sienori/Tab-Session-Manager/discussions/876
Despite I copied "sessionstore-backups" folder from older profile to the new one and then launched Firefox, older sessions did not appear in TSM backup sessions.

**Comment by RafaelLinux** [comment]
It seems no one is reading this thread and unfortunately I need to recover my sessions ASAP .... time to search alternatives to TSM.

**Comment by sienori** [comment]
How to migrate sessions to another profile:
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by RafaelLinux** [comment]
Perfect and detailed explanation. I searched about this issue only in Issues and Discussions so my fault. Anyway, there is no comparable addon for Firefox, I must say it, so thanks for your excellent work.

**Comment by SummerShades** [comment]
Thank you, @sienori. I have successfully migrated the sessions' data from the old FF installation by following your explanation at the link you have provided. This is a great relief; thank you. 😄 

The only outstanding problem is that there is no sign of the TSM backups in Google Drive. I have checked all of TSM's settings and made a manual back up to Google by pressing TSM's "Cloud sync" button.  TSM implies that the back up has synced to the cloud but I cannot find it anywhere.  TSM is now downloading backups to FF's downloads folder, which I in turn back up online, so it is not a major problem, but it seems that TSM Google back up is not working as expected.

**Comment by sienori** [comment]
@SummerShades 
Sessions will be saved as hidden app data in Google Drive. You can check it from Google Drive Settings>Manage Apps.
![](https://user-images.githubusercontent.com/29514424/85859580-5986cb80-b7f8-11ea-958c-022dd9f3eccf.png)
![](https://user-images.githubusercontent.com/29514424/85859478-39efa300-b7f8-11ea-9082-017461d1197e.png)

**Comment by SummerShades** [comment]
I can now see TSM in Google Drive.  Thank you.
