### ISSUE TITLE
Tab order not respected when opening session in current window and the current window's first tabs are pinned

### ISSUE THREAD

**Issue by DiegoBM** [sienori/Tab-Session-Manager#885]
## Short description
When you try "Open in current window" a new session, when the first current window's tabs are pinned, then the tabs of the new session won't open in the right order, instead the first tab of the new session will be open last (If the first tab is part of a group, it will be opened the last one on that group).

## Steps to reproduce
1. Open a session where the first tab/s are pinned tab/s
2. Click on Tab session manager extension, right click on another session of your choice
3. Choose "Open in current window"

## Expected result
The tabs of the new session should open in the right order, as they appear in the list of tabs in Tab Session Manager for the new session

## Actual result
Once the new session opens, you'll notice that the first tab in the tabs list is not the first tab saved Tab Session Manager's list. The first tab in the list is moved to the last position of the browser's open tabs.

## Platform information
* Platform (OS): Windows 10
* Version of browser: Chrome 94.0.4606.71
* Version of Tab Session Manager: 6.10.1

**Comment by sienori** [comment]
I merged the PR. Thank you!
