### ISSUE TITLE
Sporadic session autosave

### ISSUE THREAD

**Issue by medmaca** [sienori/Tab-Session-Manager#89]
Regardless of the interval I set the session autosave times seem to be intermittent.  A shorter interval results in more autosaves but not at the interval set.

Also, it would be ideal to only autosave if the state has actually changed, i.e. if the open tabs have changed, else ignore.

**Comment by sienori** [comment]
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/fdf331f3d8fb49ada529d37c980cf4cceba0cc38
The function to ignore if open tabs haven't change has already been implemented.
