### ISSUE TITLE
Auto save session when closing or restarting firefox

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#9]
Would be possible to auto save session when closing or restarting firefox?

**Comment by sienori** [comment]
I would like to respond in the future.

**Comment by sienori** [comment]
Supported in ver1.3.1

**Comment by rayman89** [comment]
I tried to open a session saved this way but a new window appeared with nothing on it.

**Comment by sienori** [comment]
Are you using firefox 56?
It is necessary to turn off "Supports Tree Style Tab(Firefox57++)" setting.

**Comment by rayman89** [comment]
Yes that fixed it thanks. Might be good idea to disable it by default and add a warning or something.
