### ISSUE TITLE
Have Open and Delete Buttons in different locations

### ISSUE THREAD

**Issue by roecla** [sienori/Tab-Session-Manager#90]
I think it's a little dangerous to have the open and delete buttons very close to each other as they are now. Especially as there is no confirmation dialog for deleting a saved session. 

One solution could be to move the "Delete" button next to the date and time and have the "Open" button in the bottom left corner where "Delete" is now. That would put separation between the two and reduce the risk of accidentally deleting a session one was meaning to open.

**Comment by sienori** [comment]
I implemented the function that confirm when delete was clicked in version 1.7.0.
