### ISSUE TITLE
Optionally save incognito tabs

### ISSUE THREAD

**Issue by rqu1** [sienori/Tab-Session-Manager#91]
Being able to save incognito tabs is useful in case of (for example) the browser crashing. As mentioned in #23 , this should not be enabled by default, but the fix removed the ability to save incognito tabs entirely, which in my opinion removes useful functionality. I think a reasonable solution would be to make this configurable. 
Thanks!

**Comment by gitbjo** [comment]
I'm voting for it to be configurable, I like to browse in incognito mode, but I would like to be able to save the tabs in use to be able to continue my session after a browser/computer restart.
Thanks for providing this add-on !

**Comment by sienori** [comment]
Ok, I will add that feature.

**Comment by sienori** [comment]
I added the option.
https://github.com/sienori/Tab-Session-Manager/commit/264a012deb2cca82e83cd6e6e141449e25c43639

**Comment by gitbjo** [comment]
Thank you ! Wonderful Christmas gift :-)
