### ISSUE TITLE
Most recent session (from window close) does not appear

### ISSUE THREAD

**Issue by hejops** [sienori/Tab-Session-Manager#92]
When I quit Firefox and restart it, the most recent session does not appear initially. It only appears after loading the 2nd most recent session.

**Comment by Anke** [comment]
Same here - Windows 10, Firefox Quantum Developer Edition - the last session does not appear in the list by default. I have to resort the list first.

**Comment by sienori** [comment]
I fixed it in version 1.8.0.
https://github.com/sienori/Tab-Session-Manager/commit/2b11271af128e09305a9541b1d030118002f6796
