### ISSUE TITLE
[Request]: Counter badge on the toolbar icon. 

### ISSUE THREAD

**Issue by tnilzon** [sienori/Tab-Session-Manager#922]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A counter badge on the toolbar icon showing the number of saved sessions.

**Describe alternatives you've considered**
N/A

**Additional context**
Example icon from another extension of how it could look like.

![image](https://user-images.githubusercontent.com/6920015/145705074-5598d667-756f-453e-98d6-2e8e807e2246.png)

**Comment by claudio-salvio** [comment]
Hello,

FYI @sienori has another extension for that purpose called **Count Tabs** [@github.com](https://github.com/sienori/Count-Tabs) [@mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/count-tabs/)

Best regards,
Claudio Salvio

**Comment by sienori** [comment]
Yes, I consider the display of the number of tabs to be outside the scope of the TSM.
