### ISSUE TITLE
Save Tab Groups option disable manual saving

### ISSUE THREAD

**Issue by www-wagner** [sienori/Tab-Session-Manager#926]
## Short description
When the option **Save tab groups** in enabled, I can't manually save session. The required **Save Tab Groups for Tab Session Manager** extension is properly installed.

## Steps to reproduce
1. In TSM settings, enable the option **Save tab groups**
![image](https://user-images.githubusercontent.com/18124316/146394320-890c8448-aedf-48b2-81c2-6bc55e472029.png)
2. Try to save all windows or current window as TSM session

## Expected result
All windows or current window should be saved as new TSM session

## Actual result
Nothing happens; console log shows no message

## Platform information
* Platform (OS): Kubuntu 20.04
* Version of browser: Vivaldi 5.0.2497.28 stable (64-bit)
* Version of Tab Session Manager: 6.11.1 + Save Tab Groups for Tab Session Manager: 1.0.2

## Additional context
When the option **Save tab groups** is disabled, saving sessions automatically works!

**Comment by Droyk** [comment]
the same thing happens to me I'm using Windows 10 (21H1) Edge Version 97.0.1072.76 (Official Build) (64-bit) 
The moment I enable the install & enable the save tab group extension & select the save tab groups in the setting page. it stops the automatic save intervals & doesn't even let the user save the tabs manually. I've also tried making a new profile same issue! please fix @sienori

**Comment by sienori** [comment]
This may be related to a issue with the PWA. https://github.com/sienori/Tab-Session-Manager/issues/981
This has been fixed.
