### ISSUE TITLE
Empty tabs randomly replace tabs with data when sessions are restored.

### ISSUE THREAD

**Issue by rfajman** [sienori/Tab-Session-Manager#930]
## Short description
For a long time now I've been noticing empty tabs appearing in my recovered windows.  Until today I wasn't certain if they were replacing good tabs, or just being added.  Now I am certain that, at least in some cases, good tabs are being replaced by empty tabs.  

## Steps to reproduce
I don't know how to reproduce the problem. 

## Expected result
The expected result is, obviously, to not have empty tabs replacing tabs with useful information.

I've attached a copy of a session that has an empty tab in nearly every window.

## Actual result
I saved a session that has an empty tab having replaced one with good data in nearly every window.  I tried changing the extension from json to txt so I could upload the file, but I couldn't do it no matter which method I tried.  I was going to append the file to the end of this message, but then I saw the size of the file and thought better of that.  Sorry about that.

## Platform information
* Platform (OS): Windows 10
* Version of browser: Firefox 95.0.2
* Version of Tab Session Manager: 6.11.0

**Comment by YousufSSyed** [comment]
I have the exact same issue where tabs would get replace by empty about:newtab pages, on Firefox for Mac.

**Comment by sienori** [comment]
Please share the json file that reproduces the problem.
