### ISSUE TITLE
Tab groups are not saved correctly

### ISSUE THREAD

**Issue by daxliniere** [sienori/Tab-Session-Manager#933]
When you restore a window with tab groups, all tabs are restored, but only one grouped tab will be inside each tab group. The remaining tabs will be immediately before the tab group that they should belong to.

I have looked at the JSON file saved by TSM when exporting and can confirm that the error seems to be in the save step, as opposed to the restore step.

Incorrectly restored tabs have the property **"groupId": -1** instead of something like **"id": 906712642**.

* Platform (OS): Windows 10 Pro 21H2
* Version of browser: 97.0.4692.71 (Official Build) (64-bit)
* Version of Tab Session Manager: 6.11.1

Let me know if you need any extra information or if you would like someone to beta test a fixed version.

Thank you for providing this extension and all the best!

Dax Liniere.

**Comment by daxliniere** [comment]
I manually corrected the **"groupId": -1** entries and can confirm that tabs are restored correctly, so it seems to be a bug with just the save routine, rather than the restore routine.

Hope that helps to track down the bug!

**Comment by sienori** [comment]
To save tab groups, you should install [Save Tab Groups for Tab Session Manager](https://chrome.google.com/webstore/detail/aghdiknflpelpkepifoplhodcnfildao).
