### ISSUE TITLE
[FR] Configure the naming of backups

### ISSUE THREAD

**Issue by claudio-salvio** [sienori/Tab-Session-Manager#936]
**Is your feature request related to a problem? Please describe.**

I use **Tab Session Manager** on **different computers** (pc1, pc2, ...) with **different users** (usr1, usr2, ...) logging into **various browsers** (chrome, edge, firefox) with **different browser profiles** (x1@gmail.com, y2@mozilla.org, ...).
Currently the backups are generated with names like `10 Sessions - 2022-01-10-22-33-44.json`.

**Describe the solution you'd like**

I would find it very useful **to be able to configure the naming of both single and multiple session backups**.
I'm thinking of something like a **template** where you can use **variables** that are replaced by their values when **TSM** performs the backup.

Using a template like for example: 
`brw=%Browser%_dc=%YYYYYYYMMDDhhmmss%_dvc=%ComputerName%_prf=%BrowserProfile%_usr=%UserName%.backup.tabsessionmanager.json`
resulting in a name like:
`brw=firefox_dc=20220110223344_dvc=pc1_prf=y2@mozilla.org_usr=user2.backup.tabsessionmanager.json`

Greetings,
Claudio

**Comment by sienori** [comment]
Renaming save folders may be helpful.
![image](https://user-images.githubusercontent.com/29514424/190421075-ba90eff0-11f3-4a6b-ba30-d0595d433f6e.png)
