### ISSUE TITLE
Storage location of TSM saved sessions

### ISSUE THREAD

**Issue by VLM-TechEd** [sienori/Tab-Session-Manager#940]
I apologize for posting this here; I am not very familiar with GitHub and don't know where else to post it.

I had to reinstall Firefox (clean reinstall), and I would like to find my saved sessions from my previous installation. I have a complete c drive backup from before the reinstall. Where can I find the TSM saved sessions so that I can import them into my new Firefox installation?

Thank you.

PS: I did not, unfortunately, think to export my sessions before taking down the previous installation. That, of course, would have solved the problem easily. Oops.

**Comment by sienori** [comment]
See: https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by VLM-TechEd** [comment]
Thank you!
