### ISSUE TITLE
[FR] Pin Saved Tab Session

### ISSUE THREAD

**Issue by heywolf15** [sienori/Tab-Session-Manager#944]
I want to pin one or more tab session, so it would be easy when you have a lot of saved tab session or just want to organize

**Describe the solution you'd like**
Make a pin tab session possible for one or more session

**Describe alternatives you've considered**
Make something easy to organize, like tags, group that can be naming and maybe can be check in pull down menu

**Comment by sienori** [comment]
You can tag the session. ![image](https://user-images.githubusercontent.com/29514424/190418858-e66cd06a-9e28-4ee3-af53-0147e1e84642.png)

**Comment by heywolf15** [comment]
Thank you
