### ISSUE TITLE
Redirect instead of popup on drive sign in 

### ISSUE THREAD

**Issue by Melcha2237** [sienori/Tab-Session-Manager#945]
When signing up for sync on mobile browsers that support chrome extensions (Kiwi browser), there is no way to sign in.

I suspect that the issue is that the sign-in button creates a popup, which mobile can't support. An easy fix should be to have that button be a redirect to a sign-up page instead of a popup. 

Hope you fix this, otherwise great extension

**Comment by Melcha2237** [comment]
I also want to mention that I don't need to sync tabs FROM the Kiwi browser, only from the computer browser, and only see them on the Kiwi browser.

**Comment by RufusVulpecula** [comment]
I'm also unable to get this feature working on Kiwi. I even imported the settings but it seems that setting requires a separate authentication as it should. I'm really looking forward to this feature as it would really enable tab and session syncing across all platforms and browsers I use.

**Comment by sienori** [comment]
Sorry, support for the kiwi browser is not planned.

**Comment by rokejulianlockhart** [comment]
@sienori, why?
