### ISSUE TITLE
Feature request: Save Youtube Queue lists!

### ISSUE THREAD

**Issue by Droyk** [sienori/Tab-Session-Manager#950]
**Describe the solution you'd like**
I make lot's of queue lists 
![image](https://user-images.githubusercontent.com/15848350/152432322-b5d52d2e-12d9-45e9-85ca-9a6cf0cf00e4.png)
I forgot to watch most of them as the day progresses 
and since these queue lists are temporary 
(https://www.youtube.com/watch?v=A5YxwFgRRCI&list=TLPQMDMwMjIwMjKtvD5ruYu6RA&index=2) 
so even if the session manager saves the URL it doesn't save the queue list. & I constantly get irritated by the fact that the extension can't save the queue lists.  

**Describe alternatives you've considered**
if you can't save the queue list automatically because it isn't possible technically then make your own queue lister 
![image](https://user-images.githubusercontent.com/15848350/152434734-b88511df-185d-4f75-96f1-2580ca6f5de7.png)
make it so the moment the user presses the queue list button the video starts to save in your extension queue rather than make a native youtube queue list!
if the above doesn't sound like a good solution then forgive me I'm really bad with words.

**Comment by sienori** [comment]
It is out of scope of the TSM. Look for other extensions to solve the problem.

**Comment by Droyk** [comment]
> It is out of scope of the TSM. Look for other extensions to solve the problem.

I've been searching for it but nothing is available on the chrome store that provides this functionality!
Please I beg you just try to make it possible! this feature would be a great addition to the extension!
