### ISSUE TITLE
Cloud sync is stuck

### ISSUE THREAD

**Issue by 108anup** [sienori/Tab-Session-Manager#951]
I get an error similar to this: https://github.com/sienori/Tab-Session-Manager/issues/680

The sync gets stuck after downloading 31 sessions, the status message says "Downloading... (32/104)". I have tried deleting data from google drive, signing out/in, restarting browser. None of these helped. I use Firefox and Brave. Issue started occurring when I first starting syncing on Brave (earlier used only Firefox and things were fine). I do give read/write permissions to the extension for google drive (on Brave you need to explicitly check a box for this).

I don't know if the issue is with the 32nd session or with the some corner case with number 32, or some other sync error.

**Comment by 108anup** [comment]
I think its one particular troublesome session, that is not being downloaded properly...

**Comment by 108anup** [comment]
I have around 104 sessions.

**Comment by 108anup** [comment]
Can I access some sync logs. Where could I see these?

**Comment by 108anup** [comment]
Yeah actually, I am also facing this issue where old deleted sessions from one machine from delete on another machine.

#952

**Comment by 108anup** [comment]
Basically, in the debug mode log, I see that there is a file for which drive gives 403 forbidden (malware content). After this error, the sync gets stuck. I am not sure which of my sessions might be causing this.

**Comment by 108anup** [comment]
I added logging to cloudSync.js to log what file it is trying to download. I exported sessions and was about to find the blocking sessions based on timestamp from downloadFile. After removing this session, sync works.

Can perhaps add this debugging by default. It was a pain to get the google API permissions setup just for running local clone of the extension...

**Comment by 108anup** [comment]
Keeping open: debugging could be added or if download fails, sync shouldn't remain stuck...

**Comment by sienori** [comment]
Try remove session in Google Drive: https://github.com/sienori/Tab-Session-Manager/issues/1023#issuecomment-1166365555
