### ISSUE TITLE
Not accurately syncing across multiple devices with Google on Chrome Browser?

### ISSUE THREAD

**Issue by kissingfrogs2003** [sienori/Tab-Session-Manager#952]
## Short description

I have TSM installed on all my devices. For some reason for the past week or so, I cannot get the devices to sync and all show the same information. For example, if I update sessions (deleting, adding) on my laptop the changes will not show up on my desktop. In fact many old deleted sessions are still showing on my laptop. I have tried logging in/out of google on both machines. I have made sure to "force sync" on both browsers....still nothing. 

Here are pictures of the TSM sessions showing in the Chrome browsers at the same time (using remote desktop connection):
![image](https://user-images.githubusercontent.com/98179211/152613095-799a1c59-d436-4914-b606-9af95a808e7d.png)

(p.s. I am not sure how to get an error log, especially because there is technically no error. Both machines/browsers BELIEVE they have updated their syncing info)

## Platform information
* Platform (OS): Windows 10
* Version of browser: Laptop: Chrome Version 98.0.4758.81 (Official Build) (64-bit); Desktop: Chrome Version 98.0.4758.82 (Official Build) (64-bit)
* Version of Tab Session Manager: both running Version 6.11.1

**Comment by kissingfrogs2003** [comment]
Since posting starting to write up this post I now seem to be having issues similar to this one. Only on ONE device (Desktop). Also- I can't delete any saved drive data because my settings are not currently set to use Google Drive with TSM

#951

**Comment by sienori** [comment]
Session deletions cannot be reflected on other devices.
See to reset Google Drive: https://github.com/sienori/Tab-Session-Manager/issues/1023#issuecomment-1166365555
