### ISSUE TITLE
Allow only 1 window each

### ISSUE THREAD

**Issue by txsastre** [sienori/Tab-Session-Manager#953]
I really like this plugin, it's only a few weeks with it, but I always wanted something like this. Congratulations.

Well my feature request is related to window groups, sometimes I open twice or more the same groups of windows, could be possible to allow configuring how many times a group can be opened ?

Thank you very much

**Comment by sienori** [comment]
You can add multiple identical windows to a single session.
Try `Add current window`.
![image](https://user-images.githubusercontent.com/29514424/190413915-4b59038c-31fd-4929-a51b-be7397833a37.png)
