### ISSUE TITLE
Add a way to playlists the tabs & sessions!

### ISSUE THREAD

**Issue by Droyk** [sienori/Tab-Session-Manager#959]
I'm a huge right-click open in the background person. and I think many of us are but hoarding tabs consumes memory and processing power. so I was thinking of a better way to do this instead of opening the tab in the background make a **tab playlist/queue list**. whenever a user hits right-click open in the background your extension doesn't open the link. it just adds that link into a list and that list will work as a playlist. just like a **Youtube Playlist or Queue list** does. Users can make multiple playlists that will work like different groups. let's say you made one single playlist now you want to open not only one tab but 3 to 4 tabs together from a single playlist that will work as one group, not like multiple playlists! when you close one tab different tab pops up from the playlists to get the work done. make it a user-specific choice what kind of functionality they want. do they want an automatic behavior like an autoplay function or no autoplay like only users can choose what tabs need to come up front!

& for this feature, it would be better if you can provide us with a sidebar that has all the saved links, and users can open it either by clicking your extension or hitting a hotkey! a bit like the below screenshot!
 
![image](https://user-images.githubusercontent.com/15848350/154953497-58e2aab6-433b-47b6-87b0-1d03eb8a1ee2.png)

This feature would be a huge one for functionality please do think about it! @sienori 

P.S. I'm not a native English speaker so forgive my grammatical mistakes!

**Comment by sienori** [comment]
This is outside the scope of the TSM.

**Comment by Droyk** [comment]
> This is outside the scope of the TSM.

Hmm, I see while I'm not a dev. but isn't this an excuse for a challenging problem?

**Comment by elig0n** [comment]
@Droyk Look for extensions that will open background tabs in unloaded mode i.e. "UnloadTabs", "Tab Unloader" "LoadTabOnSelect" etc...

**Comment by Droyk** [comment]
> @Droyk Look for extensions that will open background tabs in unloaded mode i.e. "UnloadTabs", "Tab Unloader" "LoadTabOnSelect" etc...

I'm aware about it & that's not what I want! it's a bit d/f approach! & seems like in chrome most of the extensions I have used that does this functionality usually only unloads the tab after loading the tab which still consumes memory & processing power.
