### ISSUE TITLE
[feature request] Allow subfolders for session backups.

### ISSUE THREAD

**Issue by cocoonkid** [sienori/Tab-Session-Manager#963]
[feature request] Allow subfolders for session backups.

I tried but I cannot use 

0-browsersessions/FF-Backup
0-browsersessions/Chrome-Backup
0-browsersessions/FFD-Backup
0-browsersessions/Brave-Backup

If this could be supported it would be highly appreciated.

With multiple browsers the Downloads folder becomes kinda clogged.

Thank you for your consideration.

**Comment by sienori** [comment]
This should work!
![image](https://user-images.githubusercontent.com/29514424/190407245-41a80fe5-0a31-47fa-9b44-2ddfabef066b.png)
