### ISSUE TITLE
Tab Sessions not being created

### ISSUE THREAD

**Issue by w9ran** [sienori/Tab-Session-Manager#964]
I typically leave many tabs open for long periods of time, and yet occasionally I either shut Firefox down for some reason or Windows does so to update.    When I first started using TSM the restoration process worked flawlessly but now for some reason it's stopped working at all.   Even though I have all the "Auto Save" setting set correctly as I understand it, the fact is when Firefox closed unexpectedly there was only one session shown - from over a month ago.   That is one I created manually the last time this happened.

Here are my settings:
![image](https://user-images.githubusercontent.com/3194542/159140018-7c25f264-f4ab-426a-8d1d-a2afbb10f243.png)

One new factor with this most recent anomaly is that I had two Firefox windows open at the time - one with many tabs (which I want to restore) and a second window with only one tab open.    When I restarted Firefox, it only would restore the window with the single tab open, which of course was frustrating.   I'm afraid I messed around enough that it overwrote the sessionstore file.

The poor performance of Firefox Session Restore is what prompted me to seek out an alternative but now it seems that Tab Session Manager isn't working either.    I'd appreciate any suggestions, thanks!

Bob

**Comment by sienori** [comment]
I cannot reproduce the problem. Does manual saving of sessions work?
