### ISSUE TITLE
The copies of the sessions disappear.

### ISSUE THREAD

**Issue by Cixert** [sienori/Tab-Session-Manager#966]
## Short description

I have Tab Session Manager installed in the Chrome based browser "360 Extreme Explorer" as an extension to recover tabs in case of system failure, although I often use the combination "control+shift+T" to restore tabs when they are closed randomly.
However, every few months when I get a blue screen or crash, "control+shift+T" stops working, so that's when I start working with Tab Session Manager. But when I open the extension there are no saved browsing sessions, they are all gone. This has always happened to me when I have the problem, so the extension does not work for me.
I would like to know how to recover these lost sessions, both the copies saved in Chrome folders and the copies saved by Tab Session Manager.

## Platform information
* Platform (OS): Windows XP
* Version of browser: Chromium 87 (360 Extreme Explorer 13)
* Version of Tab Session Manager: 6.11.1

**Comment by afterdelight** [comment]
bad luck, try restart browser worked for me
