### ISSUE TITLE
The option that sync with Dropbox

### ISSUE THREAD

**Issue by pmoris** [sienori/Tab-Session-Manager#97]
Would it be possible to implement an option where the user can specify a custom location to store the session files? See [http://sessionmanager.mozdev.org/options.html#advanced](http://sessionmanager.mozdev.org/options.html#advanced). 

Session manager had this option and it allowed users to continue where they left of on dual boot systems or on different machines entirely when the session folder was shared via a sync tool like dropbox.

Also, a big thanks for providing a nice successor for all of us who need a new session management add-on now.

**Comment by kah0922** [comment]
WebExtensions don't have free access to the file system, so I don't think that's possible.

**Comment by rnc** [comment]
Very similar to discussion in #66 ? Given VioletMonkey can backup to e.g. Dropbox via https://github.com/violentmonkey/violentmonkey/blob/master/src/background/sync/dropbox.js could this be an option?

**Comment by sienori** [comment]
The option that sync with Dropbox is interesting.
I will think about it.

**Comment by sienori** [comment]
Also, even if you use symbolic links with Dropbox it is possible to synchronize. (I do not recommend it)

**Comment by alterechtschreibung** [comment]
If the price for that is the inclusion of unfree code and/or a privacy harm, please don't do this. Moreover Webdav is a free protocol.

**Comment by sienori** [comment]
In version 6.0.0, I implemented the cloud sync function.
You can save sessions to Google Drive and sync with other devices. #73
![cloudsync](https://user-images.githubusercontent.com/29514424/78505793-c027ba80-77b0-11ea-80ed-de25f8e67552.png)
![cloudsync2](https://user-images.githubusercontent.com/29514424/78505794-c322ab00-77b0-11ea-8347-2744ea0f6494.png)
