### ISSUE TITLE
Session windows not being restored in the same order listed in the Session

### ISSUE THREAD

**Issue by ericmschmidt** [sienori/Tab-Session-Manager#978]
## Short description
My session is no longer opening in the same window order. If my system reboots, I have to manually re-open each window from the session window-by-window instead of being able to restore the entire session.
## Steps to reproduce

1. Start Firefox with Tab Session Manager already installed
2. Click Tab Session Manager extension icon
3. Find and highlight session to restore
4. Click Restore button/link to restore session

## Expected result
Both windows and tabs should open in the order that they are listed in the selected Session
![image](https://user-images.githubusercontent.com/8714769/163850862-b2adc2b0-3bd2-4379-852d-fd995c48a23b.png)
![image](https://user-images.githubusercontent.com/8714769/163850904-f25917a7-18d2-4990-ae48-2f781d00ea4b.png)

## Actual result
![image](https://user-images.githubusercontent.com/8714769/163850959-e0d424bb-7274-48ab-863e-852c73047ec1.png)
[console-export-2022-4-18_11-53-10.txt](https://github.com/sienori/Tab-Session-Manager/files/8507203/console-export-2022-4-18_11-53-10.txt)

## Platform information
* Platform (OS): Windows 10 Pro 21H2 OS Build 19044.1586
* Version of browser: Firefox 99.0.1
* Version of Tab Session Manager: [Version 6.11.1]

## Additional context
I've tried deleting all prior sessions and re-creating new sessions, resetting the Tab Session Manager settings, and even clearing the browser's temporary files but nothing seems to get the windows to restore in the same order as they did last time.

**Comment by d4k0** [comment]
Same problem here.

**Comment by sienori** [comment]
TSM do not support the order in which windows are opened. This is because it is not possible to get the order of the windows when saving the session.
