### ISSUE TITLE
Support restore_pinned_tabs_on_demand

### ISSUE THREAD

**Issue by TobiaszCudnik** [sienori/Tab-Session-Manager#979]
## Short description
When saving a session with discarded (suspended) tabs, which are also pinned, the extension should store that information and then apply when restoring. [Related issue on auto-tab-discard](https://github.com/rNeomy/auto-tab-discard/issues/151).

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Install [auto-tab-discard](https://github.com/rNeomy/auto-tab-discard)
4. Set `browser.sessionstore.restore_pinned_tabs_on_demand` to `true` in `about:config`
5. Pin some tabs
6. Discard them
7. Save the session
8. Restore the session in an empty window

## Expected result
Tabs are loaded in the same state as before (discarded).

## Actual result
All the tabs are being fully loaded.

## Platform information
* Platform (OS): Mac
* Version of browser: 99.0.1
* Version of Tab Session Manager: 6.11.1

Thanks!

**Comment by sienori** [comment]
Firefox does not seem to support opening pinned tabs with discarded.
