### ISSUE TITLE
Option to view stored sessions alphabetically

### ISSUE THREAD

**Issue by WebSkater** [sienori/Tab-Session-Manager#98]
for quick access and a far better readability when searching a certain saved session an option for viewing the stored sessions in alphabetical order (beside viewing newest or oldest first) would be a great improvement.

option could look like "A-Z" or "Z-A"

**Comment by sienori** [comment]
I plan to add this feature.

**Comment by WebSkater** [comment]
Glad to hear that! TSM seems to get a real replacemet for the old Session Manager

**Comment by sienori** [comment]
I implemented it.
https://github.com/sienori/Tab-Session-Manager/commit/f4400fb473533919c1a48dc1b264251663a0f3ec
