### ISSUE TITLE
Migrate Profile And Sessions

### ISSUE THREAD

**Issue by AndyNumber1** [sienori/Tab-Session-Manager#980]
Hi, Andy here, 😊

My problem is my session is cannot read anymore, and why you dont reply my email ? show some responsibility, because here i see many issue and problem that you dont responses too.

And i found some tips here, after reinstall, in 1782160246ssensosi.sqlite folder, if you migrate from old firefox, you can rename some session file from your backup tsm folder, example :

![osdd](https://user-images.githubusercontent.com/29286500/164147347-6fa5bcfc-7c74-4d98-b129-158e6dcc55c0.jpg)

From this new installation of tsm, take file 1613, and delete it, make sure you dont need this anymore, or have backup or copy this session, or save url list, then from your old firefox tsm backup, say 8888, copy that and put in this new tsm ssensosisqlite folder, and rename that file to 1613, next, load it, if you have problem, just export session to json, then import from that file and see if you can see this 1613 session, load it, and save in this new tsm folder, dont forget from the start to check backup option to on, because that is the most important option from this extension, good luck, 

and there is some mistake from your tutorial, in idb folder that the tutorial point is dont just have just 1 file, instead 2, and that is : 
- 1782160246ssensosi.sqlite folder, and
- 1782160246ssensosi.sqlite file

and i see my session in 1782160246ssensosi.sqlite folder, and i make backup of this, but there is some misguide tutorial that i think you must update because every little mistake is fatal, here is step from your tutorial :

- How to migrate sessions data to another profile

(In this case: [distination root directory]\storage\default\moz-extension+++ae28caf2-9857-4b99-bee9-9e2cfdd3b28c)
Exit Firefox and replace idb\1782160246ssensosi.sqlite with the previous sqlite file.
Open the replaced sqlite file with editing software.

Here, use [DB Browser for SQLite](http://sqlitebrowser.org/).

![image](https://user-images.githubusercontent.com/29286500/164144297-3bb822a0-29f3-4507-845a-4887fab33473.png)

Open Browse Data tab.
edit sqlite The value of origin is the TSM directory name of the previous profile.
(In this case: moz-extension+++de50ed3a-7f77-40bc-af2e-c5953d30edbb)
Change this value to the TSM directory name of the current profile. 
(In this case: moz-extension+++ae28caf2-9857-4b99-bee9-9e2cfdd3b28c)

From this, tutorial, the origin is: 
moz-extension+++ae28caf2-9857-4b99-bee9-9e2cfdd3b28c, but in case, in my session.sqlite file origin name is different, it is:
moz-extension//:ae28caf2-9857-4b99-bee9-9e2cfdd3b28c,
why that different ? this is mistake, you must update this.

At last, the most important is the safety of the session files, you dont have to add another extra unnecessary feature, just make it fast, light, minimum resources, and most important, safe from any sudden accident, so make sure the session file is safe, because computer problem cant be predicted, so make sure the session url tab list is placed to the most safest place, and can be access, or read anytime, why the save backup option is not checked by default ? this is most important option setting from this extension, and place it in top of the option page for easy to recognizes.

## Platform
* Platform (OS): Microsoft 10
* Version of browser: Mozilla Firefox 98
* Version of Tab Session Manager: 6.11.1

## Additional Tutorial

Some useful extension :
Copy/Paste and Save Tabs List. (Firefox Addons)

From safest step before you reinstall, but, that depend on your condition or problem too :

https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-How-to-import-sessions-from-other-extensions
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A-How-to-use-debug-mode
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error-for-Chrome
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile

**Comment by sienori** [comment]
See this wiki for more information on profile migration.
https://github.com/sienori/Tab-Session-Manager/wiki/Q&A:-Sessions-data-storage-location;-How-to-migrate-sessions-data-to-another-profile
Sorry, I cannot provide support for problems in individual cases.
