### ISSUE TITLE
Failed to save session while using PWA and enabled save tab groups

### ISSUE THREAD

**Issue by DannyDeLoach** [sienori/Tab-Session-Manager#981]
## Steps to reproduce

1. Set TSM to automatically save sessions (e.g. every 30 minutes, when a window is closed, etc.)
2. or
3. Click 'Save' 

## Expected result

1. Sessions will be automatically saved as set in settings
2. or
3. The current session will be saved when the 'Save' button is clicked

## Actual result
1. No sessions are being automatically saved
2. Clicking the 'Save' button gives the error, "Failed to save session".

Here is a screenshot of the error I receive, when I click the 'Save' button:

![2022-04-22 01-43-57](https://user-images.githubusercontent.com/24360823/164612133-27fd0088-9cd4-49b3-be94-867e2bd07de8.jpg)

I have enabled debug mode, but I do not know how to access and share the logs

## Platform information
* Platform (OS): Windows 10
* Version of browser:  Chrome Version 100.0.4896.88
* Version of Tab Session Manager: 2.0

## Additional context
I removed the TSM extension from Chrome and deleted any of the TSM folders in the Chrome directory. I restarted my computer and re-installed TSM. The problem persists.

**Comment by bezdeneg** [comment]
+1
Platform (OS): Windows 10
Version of browser:  Yandex Browser (Chrome engine) Version 22.3.2.644 (64-bit)
Version of Tab Session Manager: 6.11.1

**Comment by 1024mb** [comment]
With Firefox the addon is nor saving manually nor automatically. It doesn't show any error either, it's been like that for some time now I just noticed.

**Comment by mindwarp42** [comment]
Confirmed on Kiwi 101.0.4951.40 on fully updated stock Android 11 on both a Samsung Galaxy Tab A8, a Samsung Galaxy Tab A 10.4" 2020, and a Moto G Power (8th gen). I noticed it when I had to replace my old Samsung tablet and was backing up settings. The last saved sessions were from 2021. Supposedly, I exported 23 sessions from my old tablet, but only 22 show up after importing them. I lost about 6 months of data. I did try to enable cloud save, but nothing happens. Manual saves give the error OP listed. When I just thought to look at my Moto, the sessions listed when I first switched from Firefox to Kiwi are missing as well - no sessions appear, even though autobackups are enabled on both devices.

**Comment by DannyDeLoach** [comment]
I did some more troubleshooting and discovered a pivotal piece of information.

If no 'web apps' are open, TSM works as expected. What I mean by 'web app', is when I open a web page, select 'More tools', 'Create shortcut', 'Open as window' and create a desktop shortcut for opening the web page as a 'web app'. If I open any of the 'web apps' I have created, then TSM exhibits the behavior described in my original post (i.e. it no longer automatically saves sessions and I can no longer manually save a session). If I close the 'web app', then TSM saves sessions as expected.

I would like to continue using 'web apps'. I would also like to use TSM. TSM is a great extension. I hope the author of the extension or someone with knowledge of how it works can help me figure out how to use TSM while I am also using 'web apps'.

**Comment by Anutrix** [comment]
@DannyDeLoach Please change issue title to reflect that it only happens when 'web apps'(PWAs?) are open.

Also just a note, it works fine for me on current latest Firefox 104.0.1 and has always been fine(past few 4-5 years). I have over 1700 saved sessions, with each with tabs ranging from 20-80 tabs with huge variety and regularly use it. Not sure if I use any Web Apps.

**Comment by sienori** [comment]
Thanks for the report and research! @mohemohe fixed this problem!

**Comment by 1024mb** [comment]
Oops, forgot to update here, I don't know what the problem was on my end but uninstalling and reinstalling the addon fixed everything.
