### ISSUE TITLE
LOST ALL TAB SESSION MANAGER SESSIONS

### ISSUE THREAD

**Issue by cheese1218** [sienori/Tab-Session-Manager#983]
hey there, hope you are doing well. Recently I noticed that all my sessions on my windows 10 laptop seem to have disappeared. Nothing is wrong with my laptop or SSD. No idea what caused this either. The extension has now begun saving new sessions and I can't seem to find anything before a few days ago show up. I never had a backup either very sadly.
Is there anyway for me to go into my Google Chrome user data profile and restore those missing sessions or find out anything about what was lost?
I'm not sure where tab session manager stores sessions for chrome, This is an extremely important issue and crucial life saving matter for me please, I am begging you if you or anyone here could help me out it would mean the world to me please please.

**Comment by sienori** [comment]
Sorry for any inconvenience this may cause.
I recommend using backup or cloud sync options in case of session loss.
