### ISSUE TITLE
Norwegian translation not used.

### ISSUE THREAD

**Issue by filtys00** [sienori/Tab-Session-Manager#993]
## Short description
Tab Session Manager UI is displayed in English when browser UI language is set to Norwegian, despite there being a Norwegian translation.

## Platform information
* Browser: Mozilla Firefox
* Version of browser: 100.0
* Version of Tab Session Manager: 6.12.0

## Additional context
Written Norwegian is split into two slightly different versions of each other:
- Norwegian Bokmål (`nb`)
- Norwegian Nynorsk (`nn`)

Tab Session Manager stores the Norwegian translation under `no`, which is unsupported.

**Comment by sienori** [comment]
To change the extensions language, set the value of `intl.locale.requested` to `no` in `about:config`.
https://superuser.com/questions/488141/how-do-i-change-user-interface-language-in-firefox-to-avoid-so-called-localizati

**Comment by filtys00** [comment]
Sorry if I were unclear.
This does not solve the problem.
The problem is that Tab Session Manager stores the Norwegian language file under `_locale/no`, while it should be stored under both `_locale/nb` and `_locale/nn`.
This is due to there being two different varieties of Norwegian.
